"use client";

import { useEffect, useMemo, useState } from "react";
import { getSupabaseBrowserClient } from "@/lib/supabase";

type Profile={role:string;organisation_id:string|null};
type Org={name:string;support_email:string|null;brand_name:string|null;logo_url:string|null};
type Subscription={status:string;seat_limit:number|null;current_period_end:string|null;grace_until:string|null};
type Check={key:string;title:string;detail:string;href:string;done:boolean;critical:boolean;count?:number;note?:string};

export default function LaunchReadinessPage(){
  const [profile,setProfile]=useState<Profile|null>(null);const [org,setOrg]=useState<Org|null>(null);const [subscription,setSubscription]=useState<Subscription|null>(null);const [counts,setCounts]=useState<Record<string,number>>({});const [loading,setLoading]=useState(true);const [message,setMessage]=useState("");
  useEffect(()=>{let live=true;(async()=>{const c=getSupabaseBrowserClient();const {data:auth}=await c.auth.getUser();if(!auth.user){window.location.href="/auth?next=/launch-readiness";return;}const {data:p,error:pError}=await c.from("staff_profiles").select("role,organisation_id").eq("id",auth.user.id).single();if(!live)return;if(pError||!p){setMessage(pError?.message||"Unable to load profile.");setLoading(false);return;}setProfile(p as Profile);if(!["CPD Lead","Admin"].includes(p.role)){setLoading(false);return;}if(!p.organisation_id){setLoading(false);return;}const orgId=p.organisation_id;const results=await Promise.all([
    c.from("organisations").select("name,support_email,brand_name,logo_url").eq("id",orgId).single(),
    c.from("school_subscriptions").select("status,seat_limit,current_period_end,grace_until").eq("organisation_id",orgId).maybeSingle(),
    c.from("organisation_domains").select("id",{count:"exact",head:true}).eq("organisation_id",orgId).eq("status","verified"),
    c.from("organisation_staff_directory").select("id",{count:"exact",head:true}).eq("organisation_id",orgId).eq("active",true),
    c.from("staff_profiles").select("id",{count:"exact",head:true}).eq("organisation_id",orgId),
    c.from("school_policies").select("id",{count:"exact",head:true}).eq("organisation_id",orgId).eq("active",true),
    c.from("training_requirements").select("id",{count:"exact",head:true}).eq("organisation_id",orgId).eq("active",true).eq("mandatory",true),
    c.from("onboarding_programmes").select("id",{count:"exact",head:true}).eq("organisation_id",orgId).eq("active",true),
    c.from("inset_days").select("id",{count:"exact",head:true}).eq("organisation_id",orgId),
    c.from("cpd_budgets").select("id",{count:"exact",head:true}).eq("organisation_id",orgId),
    c.from("school_resource_library").select("id",{count:"exact",head:true}).eq("organisation_id",orgId).eq("active",true),
  ]);if(!live)return;const errors=results.map(r=>r.error?.message).filter(Boolean);if(errors.length)setMessage(errors.join(" · "));if(results[0].data)setOrg(results[0].data as Org);if(results[1].data)setSubscription(results[1].data as Subscription);setCounts({domains:results[2].count||0,directory:results[3].count||0,members:results[4].count||0,policies:results[5].count||0,training:results[6].count||0,onboarding:results[7].count||0,inset:results[8].count||0,budgets:results[9].count||0,resources:results[10].count||0});setLoading(false);})();return()=>{live=false};},[]);
  const checks=useMemo<Check[]>(()=>[
    {key:"licence",title:"Active school licence",detail:"A trial, active subscription or valid grace period is needed for normal staff access.",href:"/school-access",done:subscriptionAllowsAccess(subscription),critical:true,note:subscription?`Status: ${subscription.status}`:"No subscription record"},
    {key:"domain",title:"Verified school email domain",detail:"At least one verified domain is required for automatic school-account matching.",href:"/school-access",done:counts.domains>0,critical:true,count:counts.domains},
    {key:"members",title:"Staff accounts connected",detail:"At least one live staff account should be connected before launch testing is signed off.",href:"/organisation",done:counts.members>0,critical:true,count:counts.members},
    {key:"directory",title:"Staff directory prepared",detail:"Recommended for accurate departments, roles and sites on first sign-in. Staff can still join without pre-import.",href:"/staff-sync",done:counts.directory>0,critical:false,count:counts.directory},
    {key:"policies",title:"Required policies published",detail:"Publish the policies staff should read and acknowledge, with versions and review dates.",href:"/school-hub",done:counts.policies>0,critical:true,count:counts.policies},
    {key:"training",title:"Mandatory training configured",detail:"Create at least one active mandatory requirement with the correct audience and renewal cycle.",href:"/training",done:counts.training>0,critical:true,count:counts.training},
    {key:"onboarding",title:"Onboarding pathways available",detail:"New Staff, ECT and Teaching Assistant programmes can be assigned as staff join.",href:"/school-hub",done:counts.onboarding>0,critical:false,count:counts.onboarding},
    {key:"inset",title:"INSET / CPD calendar started",detail:"Add the first INSET day or scheduled CPD event so staff can see upcoming development activity.",href:"/school-hub",done:counts.inset>0,critical:false,count:counts.inset},
    {key:"branding",title:"School support identity configured",detail:"Set a school display name/support contact; a logo is optional.",href:"/school-hub",done:Boolean(org?.support_email&&(org?.brand_name||org?.name)),critical:false,note:org?.support_email||"No support email"},
    {key:"budget",title:"CPD budget created",detail:"Optional but useful for tracking external CPD, cover and programme spend.",href:"/school-hub",done:counts.budgets>0,critical:false,count:counts.budgets},
    {key:"resources",title:"School resource library started",detail:"Add local guidance, templates or CPD resources staff should be able to find quickly.",href:"/school-hub",done:counts.resources>0,critical:false,count:counts.resources},
  ],[subscription,counts,org]);
  const required=checks.filter(c=>c.critical);const requiredDone=required.filter(c=>c.done).length;const allDone=checks.filter(c=>c.done).length;const readiness=Math.round((allDone/checks.length)*100);
  if(loading)return <main className="stagePage"><div className="stageCard">Checking school launch readiness…</div></main>;
  if(!profile||!["CPD Lead","Admin"].includes(profile.role))return <main className="stagePage"><section className="stageHero"><span className="eyebrow">LAUNCH READINESS</span><h1>CPD Lead or Admin access required.</h1><p>This page contains school-level setup information.</p></section></main>;
  if(!profile.organisation_id)return <main className="stagePage"><section className="stageHero"><span className="eyebrow">LAUNCH READINESS</span><h1>Connect an organisation first.</h1><p>Create or join the school organisation before running launch checks.</p><div className="stageHeroActions"><a className="primary phaseLinkButton" href="/organisation">Organisation setup</a></div></section></main>;
  return <main className="stagePage readinessPage"><section className="stageHero readinessHero"><span className="eyebrow">SCHOOL LAUNCH READINESS</span><h1>{org?.name||"Your school"}: launch checklist</h1><p>One place to see whether the school-access and CPD foundations are ready for staff rollout. This checks configuration, not teaching quality or staff performance.</p></section>{message&&<div className="phaseNotice">{message}</div>}
    <section className="readinessSummary"><div className="stageCard readinessScore"><strong>{readiness}%</strong><span>setup complete</span><progress max="100" value={readiness}/></div><div className={`stageCard readinessGate ${requiredDone===required.length?"ready":"blocked"}`}><span className="eyebrow">CRITICAL ACCESS GATE</span><strong>{requiredDone}/{required.length} required checks complete</strong><p>{requiredDone===required.length?"Core school-access requirements are configured. Run a real staff sign-in test before launch.":"Complete the missing critical items before inviting the whole school."}</p></div></section>
    <section className="readinessGrid">{checks.map(c=><a className={`stageCard readinessCheck ${c.done?"done":"pending"} ${c.critical?"critical":""}`} href={c.href} key={c.key}><div className="readinessIcon">{c.done?"✓":"!"}</div><div><div className="readinessCheckHead"><strong>{c.title}</strong>{c.critical&&<span>Required</span>}</div><p>{c.detail}</p>{c.count!==undefined&&<small>{c.count} configured</small>}{c.note&&<small>{c.note}</small>}</div><b>→</b></a>)}</section>
    <section className="stageGrid"><div className="stageCard stageSpan6"><span className="eyebrow">PLATFORM-OWNER DEPENDENCIES</span><h2>One-time platform configuration</h2><div className="readinessManual"><div><strong>Google Workspace OAuth</strong><p>The Google sign-in button needs platform OAuth credentials configured in Supabase Auth.</p></div><div><strong>Leaked-password protection</strong><p>Enable Supabase leaked-password protection if the password fallback remains available.</p></div></div><a className="secondary phaseLinkButton" href="/help">Open setup help</a></div><div className="stageCard stageSpan6"><span className="eyebrow">FINAL ROLLOUT TEST</span><h2>Test with real school accounts</h2><ol className="readinessTest"><li>Use a non-admin staff school account.</li><li>Confirm Google sign-in completes.</li><li>Confirm the verified domain maps to the correct school.</li><li>Check role, department and site from Staff Sync.</li><li>Open Reminders and acknowledge a test policy.</li><li>Complete a short CPD item and confirm progress persists after sign-out.</li></ol><p className="muted">A successful production build and database advisor check do not replace this real identity-provider test.</p></div></section>
  </main>;
}
function subscriptionAllowsAccess(s:Subscription|null){if(!s)return false;if(["active","trialing"].includes(s.status))return true;if(s.status!=="past_due")return false;const grace=s.grace_until?new Date(s.grace_until):null;return Boolean(grace&&grace.getTime()>Date.now());}
