"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { getSupabaseBrowserClient } from "@/lib/supabase";

type SchoolRow={organisation_id:string;organisation_name:string;access_mode:string;subscription_status:string|null;plan:string|null;seat_limit:number|null;current_period_end:string|null;domain_id:string|null;domain:string|null;domain_status:string|null;domain_primary:boolean|null};
type School={id:string;name:string;accessMode:string;subscriptionStatus:string;plan:string;seatLimit:number|null;periodEnd:string|null;domains:{id:string;domain:string;status:string;primary:boolean}[]};

export default function PlatformPage(){
  const [allowed,setAllowed]=useState<boolean|null>(null); const [rows,setRows]=useState<SchoolRow[]>([]); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false); const [showCreate,setShowCreate]=useState(true);
  useEffect(()=>{let alive=true;(async()=>{const c=getSupabaseBrowserClient();const {data:auth}=await c.auth.getUser();if(!auth.user){window.location.href="/auth?next=/platform";return;}const {data:role}=await c.from("platform_admins").select("user_id").eq("user_id",auth.user.id).maybeSingle();if(!alive)return;if(!role){setAllowed(false);return;}setAllowed(true);await reload();})();return()=>{alive=false};},[]);
  async function reload(){const c=getSupabaseBrowserClient();const {data,error}=await c.rpc("platform_list_schools");if(error)setMessage(error.message);else setRows((data||[]) as SchoolRow[]);}
  const schools=useMemo(()=>{const map=new Map<string,School>();for(const r of rows){if(!map.has(r.organisation_id))map.set(r.organisation_id,{id:r.organisation_id,name:r.organisation_name,accessMode:r.access_mode,subscriptionStatus:r.subscription_status||"none",plan:r.plan||"school",seatLimit:r.seat_limit,periodEnd:r.current_period_end,domains:[]});if(r.domain_id&&r.domain)map.get(r.organisation_id)!.domains.push({id:r.domain_id,domain:r.domain,status:r.domain_status||"pending",primary:Boolean(r.domain_primary)});}return [...map.values()].sort((a,b)=>a.name.localeCompare(b.name));},[rows]);

  async function createSchool(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget,fd=new FormData(f),c=getSupabaseBrowserClient();setBusy(true);setMessage("");const seats=String(fd.get("seat_limit")||"").trim();const {data,error}=await c.rpc("platform_create_school",{p_name:String(fd.get("name")||"").trim(),p_academic_year:String(fd.get("academic_year")||"2026/27").trim(),p_domain:String(fd.get("domain")||"").trim().toLowerCase().replace(/^@/,""),p_admin_email:String(fd.get("admin_email")||"").trim().toLowerCase(),p_plan:String(fd.get("plan")||"school").trim(),p_seat_limit:seats?Number(seats):null});setBusy(false);if(error){setMessage(error.message);return;}f.reset();setMessage(`School created on a 14-day trial. Review and verify its domain below before staff access is enabled.${data?` Organisation ID: ${data}`:""}`);setShowCreate(false);await reload();}
  async function verify(id:string,verified:boolean){const c=getSupabaseBrowserClient();setBusy(true);const {error}=await c.rpc("platform_verify_domain",{p_domain_id:id,p_verified:verified});setBusy(false);if(error)setMessage(error.message);else{setMessage(verified?"Domain verified. Staff with confirmed accounts on this domain can now be matched while the subscription is active.":"Domain disabled.");await reload();}}
  async function saveSubscription(e:FormEvent<HTMLFormElement>,orgId:string){e.preventDefault();const fd=new FormData(e.currentTarget),c=getSupabaseBrowserClient();setBusy(true);const period=String(fd.get("period_end")||"");const grace=String(fd.get("grace_until")||"");const seats=String(fd.get("seat_limit")||"");const {error}=await c.rpc("platform_set_subscription",{p_org:orgId,p_status:String(fd.get("status")),p_plan:String(fd.get("plan")||"school"),p_seat_limit:seats?Number(seats):null,p_period_end:period?new Date(`${period}T23:59:59`).toISOString():null,p_grace_until:grace?new Date(`${grace}T23:59:59`).toISOString():null});setBusy(false);if(error)setMessage(error.message);else{setMessage("School subscription updated.");await reload();}}

  if(allowed===null)return <main className="stagePage"><div className="stageCard">Checking platform permissions…</div></main>;
  if(!allowed)return <main className="stagePage"><section className="stageHero"><span className="eyebrow">PLATFORM ADMINISTRATION</span><h1>Platform-owner access required.</h1><p>This console is separate from school administrator permissions.</p></section></main>;
  return <main className="stagePage platformPage">
    <section className="stageHero platformHero"><span className="eyebrow">TEACHING CPD · PLATFORM CONTROL</span><h1>School subscriptions & domain verification</h1><p>Provision a school, nominate its first CPD lead, verify the school email domain and control commercial access without giving school administrators the ability to activate their own licence.</p><div className="stageHeroActions"><button className="primary" onClick={()=>setShowCreate(v=>!v)}>{showCreate?"Hide school setup":"Create a school"}</button></div></section>
    {message&&<div className="phaseNotice">{message}</div>}
    <section className="stageStatGrid"><div className="stageStat"><strong>{schools.length}</strong><span>school organisations</span></div><div className="stageStat"><strong>{schools.filter(s=>["active","trialing"].includes(s.subscriptionStatus)).length}</strong><span>active / trial</span></div><div className="stageStat"><strong>{schools.flatMap(s=>s.domains).filter(d=>d.status==="pending").length}</strong><span>domains awaiting review</span></div><div className="stageStat"><strong>{schools.reduce((n,s)=>n+(s.seatLimit||0),0)||"—"}</strong><span>configured seats</span></div></section>

    {showCreate&&<section className="stageCard platformCreateSchool"><div className="platformCreateIntro"><span className="eyebrow">NEW CUSTOMER</span><h2>Provision a school subscription</h2><p>This creates the organisation, main site, 14-day trial, default onboarding programmes, KCSIE required-reading item, primary domain request and the nominated initial CPD-lead identity.</p></div><form className="platformCreateForm" onSubmit={createSchool}><label>School name<input required name="name" placeholder="Example School"/></label><label>Academic year<input required name="academic_year" defaultValue="2026/27"/></label><label>School email domain<input required name="domain" placeholder="school.org.uk" autoCapitalize="none" autoCorrect="off"/></label><label>Initial CPD lead email<input required name="admin_email" type="email" placeholder="cpdlead@school.org.uk"/></label><label>Plan<input required name="plan" defaultValue="school"/></label><label>Seat limit<input name="seat_limit" type="number" min="1" placeholder="Leave blank for unlimited"/></label><div className="platformCreateHelp"><strong>Safe activation sequence</strong><span>1. Create school → 2. Verify ownership/domain → 3. Staff sign in with school identity → 4. Initial CPD lead is promoted automatically → 5. Other staff join as Staff.</span></div><button className="primary" disabled={busy}>{busy?"Creating school…":"Create 14-day trial school"}</button></form></section>}

    <section className="platformSchoolList">{schools.map(s=><article className="stageCard platformSchool" key={s.id}><header><div><span className="eyebrow">{s.accessMode}</span><h2>{s.name}</h2></div><span className={`subscriptionStatus ${s.subscriptionStatus}`}>{s.subscriptionStatus}</span></header><div className="platformColumns"><div><h3>Email domains</h3>{s.domains.length?s.domains.map(d=><div className="platformDomain" key={d.id}><div><strong>@{d.domain}</strong><small>{d.primary?"Primary · ":""}{d.status}</small></div>{d.status==="pending"&&<div><button disabled={busy} className="primary" onClick={()=>verify(d.id,true)}>Verify</button><button disabled={busy} className="secondary" onClick={()=>verify(d.id,false)}>Reject</button></div>}{d.status==="verified"&&<button disabled={busy} className="secondary" onClick={()=>verify(d.id,false)}>Disable</button>}</div>):<p className="muted">No domain requests yet.</p>}</div><div><h3>Subscription</h3><form className="platformSubscriptionForm" onSubmit={e=>saveSubscription(e,s.id)}><label>Status<select name="status" defaultValue={s.subscriptionStatus==="none"?"trialing":s.subscriptionStatus}><option value="trialing">Trialing</option><option value="active">Active</option><option value="past_due">Past due</option><option value="cancelled">Cancelled</option><option value="expired">Expired</option></select></label><label>Plan<input name="plan" defaultValue={s.plan}/></label><label>Seat limit<input type="number" min="1" name="seat_limit" defaultValue={s.seatLimit||""} placeholder="Unlimited"/></label><label>Period end<input type="date" name="period_end" defaultValue={isoDate(s.periodEnd)}/></label><label>Grace until<input type="date" name="grace_until"/></label><button className="primary" disabled={busy}>Save licence</button></form></div></div></article>)}{!schools.length&&<div className="stageCard"><h2>No commercial school organisations yet</h2><p>Create the first school above. Its domain starts pending and must be verified before automatic staff access is enabled.</p></div>}</section>
  </main>;
}
function isoDate(v:string|null){return v?new Date(v).toISOString().slice(0,10):""}
