"use client";

import { useEffect, useMemo, useState } from "react";
import { courses } from "@/lib/catalogue";
import { getSupabaseBrowserClient } from "@/lib/supabase";
import { addMonths, complianceStatus, formatWorkflowDate } from "@/lib/schoolWorkflows";

type Profile={id:string;full_name:string;role:string;department:string;organisation_id:string|null};
type Requirement={id:string;title:string;description:string;target_type:"catalogue"|"custom";target_id:string;frequency_months:number|null;mandatory:boolean;audience_type:string;audience_value:string|null;active:boolean;organisation_id:string|null;created_at:string};
type RecordRow={user_id:string;requirement_id:string;completed_at:string;expires_at:string|null;source_course_id:string|null;verified_by:string|null;evidence_reference:string|null;note:string};
type Progress={user_id:string;course_id:string;completed_at:string|null};
type Status="current"|"due_soon"|"expired"|"missing";

export default function CompliancePage(){
  const [me,setMe]=useState<Profile|null>(null);const [requirements,setRequirements]=useState<Requirement[]>([]);const [records,setRecords]=useState<RecordRow[]>([]);const [progress,setProgress]=useState<Progress[]>([]);const [staff,setStaff]=useState<Profile[]>([]);const [notice,setNotice]=useState("");const [loading,setLoading]=useState(true);
  const [title,setTitle]=useState("");const [description,setDescription]=useState("");const [targetType,setTargetType]=useState<"catalogue"|"custom">("catalogue");const [targetId,setTargetId]=useState("");const [frequency,setFrequency]=useState("12");const [audienceType,setAudienceType]=useState("all");const [audienceValue,setAudienceValue]=useState("");
  const [recordUser,setRecordUser]=useState("");const [recordRequirement,setRecordRequirement]=useState("");const [recordDate,setRecordDate]=useState(new Date().toISOString().slice(0,10));const [recordEvidence,setRecordEvidence]=useState("");const [recordNote,setRecordNote]=useState("");
  const isAdmin=Boolean(me&&["CPD Lead","Admin"].includes(me.role));

  async function load(){
    const client=getSupabaseBrowserClient();const {data:auth}=await client.auth.getUser();if(!auth.user){window.location.href="/auth?next=/compliance";return;}
    const {data:profile,error:pe}=await client.from("staff_profiles").select("id,full_name,role,department,organisation_id").eq("id",auth.user.id).maybeSingle();const p=(profile||null) as Profile|null;setMe(p);setRecordUser(auth.user.id);
    const admin=Boolean(p&&["CPD Lead","Admin"].includes(p.role));
    const [rq,rr,pr,sp]=await Promise.all([
      client.from("training_requirements").select("*").eq("active",true).order("title"),
      client.from("training_records").select("*"),
      client.from("course_progress").select("user_id,course_id,completed_at").eq("user_id",auth.user.id),
      admin&&p?.organisation_id?client.from("staff_profiles").select("id,full_name,role,department,organisation_id").eq("organisation_id",p.organisation_id).order("full_name"):Promise.resolve({data:p?[p]:[],error:null}),
    ]);
    setRequirements((rq.data||[]) as Requirement[]);setRecords((rr.data||[]) as RecordRow[]);setProgress((pr.data||[]) as Progress[]);setStaff((sp.data||[]) as Profile[]);setNotice([pe,rq.error,rr.error,pr.error,sp.error].filter(Boolean).map(x=>x!.message).join(" · "));setLoading(false);
  }
  useEffect(()=>{void load();},[]);

  function applies(req:Requirement,person:Profile){if(req.audience_type==="all")return true;if(req.audience_type==="role")return person.role===req.audience_value;if(req.audience_type==="department")return person.department===req.audience_value;return true;}
  function stateFor(req:Requirement,userId:string):{status:Status;completedAt:string|null;expiresAt:Date|null;source:string}{
    const record=records.filter(r=>r.requirement_id===req.id&&r.user_id===userId).sort((a,b)=>b.completed_at.localeCompare(a.completed_at))[0];
    const courseProgress=req.target_type==="catalogue"?progress.filter(p=>p.user_id===userId&&p.course_id===req.target_id&&p.completed_at).sort((a,b)=>(b.completed_at||"").localeCompare(a.completed_at||""))[0]:undefined;
    const completedAt=[record?.completed_at,courseProgress?.completed_at].filter(Boolean).sort().reverse()[0]||null;
    let expiresAt:Date|null=record?.expires_at?new Date(record.expires_at):null;if(!expiresAt&&completedAt&&req.frequency_months)expiresAt=addMonths(completedAt,req.frequency_months);
    return {status:complianceStatus(expiresAt,Boolean(completedAt)),completedAt,expiresAt,source:courseProgress&&(!record||String(courseProgress.completed_at)>=record.completed_at)?"CPD completion":record?"Verified record":"—"};
  }
  const ownRequirements=me?requirements.filter(r=>applies(r,me)):[];
  const ownStates=ownRequirements.map(r=>({r,...stateFor(r,me?.id||"")}));
  const statusCounts=useMemo(()=>({current:ownStates.filter(x=>x.status==="current").length,due:ownStates.filter(x=>x.status==="due_soon").length,expired:ownStates.filter(x=>x.status==="expired").length,missing:ownStates.filter(x=>x.status==="missing").length}),[ownStates]);

  async function createRequirement(){
    if(!me?.organisation_id||!isAdmin||!title.trim()||!targetId.trim())return setNotice("Add a title and linked course or custom requirement first.");
    const client=getSupabaseBrowserClient();const {error}=await client.from("training_requirements").insert({title:title.trim(),description:description.trim(),target_type:targetType,target_id:targetId,frequency_months:frequency?Number(frequency):null,mandatory:true,audience_type:audienceType,audience_value:audienceType==="all"?null:audienceValue.trim(),active:true,created_by:me.id,organisation_id:me.organisation_id,site_id:null,school_id:null});if(error)return setNotice(error.message);setTitle("");setDescription("");setTargetId("");setNotice("Mandatory training requirement added.");await load();
  }
  async function verifyCompletion(){
    if(!me||!isAdmin||!recordUser||!recordRequirement||!recordDate)return;const req=requirements.find(r=>r.id===recordRequirement);const expires=req?.frequency_months?addMonths(`${recordDate}T12:00:00`,req.frequency_months).toISOString():null;const client=getSupabaseBrowserClient();const {error}=await client.from("training_records").upsert({user_id:recordUser,requirement_id:recordRequirement,completed_at:new Date(`${recordDate}T12:00:00`).toISOString(),expires_at:expires,source_course_id:req?.target_type==="catalogue"?req.target_id:null,verified_by:me.id,evidence_reference:recordEvidence.trim()||null,note:recordNote.trim(),updated_at:new Date().toISOString()},{onConflict:"user_id,requirement_id"});if(error)return setNotice(error.message);setRecordEvidence("");setRecordNote("");setNotice("Completion verified.");await load();
  }

  if(loading)return <main className="stagePage"><div className="stageCard">Loading compliance dashboard…</div></main>;
  const matrix=requirements.map(req=>{const people=staff.filter(person=>applies(req,person));const states=people.map(person=>stateFor(req,person.id).status);return {req,total:people.length,current:states.filter(s=>s==="current").length,due:states.filter(s=>s==="due_soon").length,overdue:states.filter(s=>s==="expired"||s==="missing").length};});
  return <main className="stagePage schoolWorkflowPage"><section className="stageHero workflowHero"><span className="eyebrow">MANDATORY TRAINING & COMPLIANCE</span><h1>Know what is current, due soon or missing.</h1><p>Combine course completion and verified external or policy training into one renewal-aware compliance view, without reducing staff development to a leaderboard.</p><div className="stageHeroActions"><a className="primary phaseLinkButton" href="/training">My training</a><a className="secondary phaseLinkButton" href="/policy-training">Policy training</a><a className="secondary phaseLinkButton" href="/dashboard">Dashboard</a></div></section>{notice&&<div className="phaseNotice">{notice}</div>}
    <section className="workflowStats"><div><strong>{statusCounts.current}</strong><span>current</span></div><div><strong>{statusCounts.due}</strong><span>due within 30 days</span></div><div><strong>{statusCounts.expired}</strong><span>expired</span></div><div><strong>{statusCounts.missing}</strong><span>not yet completed</span></div></section>
    <section className="stageCard"><span className="eyebrow">MY COMPLIANCE</span><h2>Training requirements that apply to your role</h2><div className="stageList">{ownStates.map(({r,status,completedAt,expiresAt,source})=><div className="stageRow" key={r.id}><div className="stageRowMain"><strong>{r.title}</strong><span>{r.description}</span><small>{completedAt?`Completed ${formatWorkflowDate(completedAt)} · ${source}`:"No completion recorded"}{expiresAt?` · renew by ${expiresAt.toLocaleDateString("en-GB",{day:"numeric",month:"short",year:"numeric"})}`:""}</small></div><span className={`stageBadge ${status==="current"?"good":status==="due_soon"?"warn":"danger"}`}>{status.replace("_"," ")}</span>{r.target_type==="catalogue"&&status!=="current"&&<a className="secondary phaseLinkButton" href={`/cpd?course=${encodeURIComponent(r.target_id)}`}>Open course</a>}</div>)}{!ownStates.length&&<div className="emptyCompact">No mandatory requirements currently apply to your profile.</div>}</div></section>
    {isAdmin&&<><section className="stageGrid"><article className="stageCard stageSpan6"><span className="eyebrow">CREATE REQUIREMENT</span><h2>Add mandatory or renewable training</h2><div className="workflowForm"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Requirement title"/><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="What staff must know or complete"/><select value={targetType} onChange={e=>{setTargetType(e.target.value as "catalogue"|"custom");setTargetId("")}}><option value="catalogue">CPD course</option><option value="custom">Policy / external training</option></select>{targetType==="catalogue"?<select value={targetId} onChange={e=>setTargetId(e.target.value)}><option value="">Choose course</option>{courses.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select>:<input value={targetId} onChange={e=>setTargetId(e.target.value)} placeholder="Policy or external training title / identifier"/>}<label>Renew every (months)<input type="number" min="1" max="120" value={frequency} onChange={e=>setFrequency(e.target.value)}/></label><select value={audienceType} onChange={e=>setAudienceType(e.target.value)}><option value="all">All staff</option><option value="role">Specific role</option><option value="department">Specific department</option></select>{audienceType!=="all"&&<input value={audienceValue} onChange={e=>setAudienceValue(e.target.value)} placeholder={audienceType==="role"?"Exact role name":"Department name"}/>}<button className="primary" onClick={createRequirement}>Add requirement</button></div></article>
      <article className="stageCard stageSpan6"><span className="eyebrow">VERIFY EXTERNAL COMPLETION</span><h2>Add evidence-backed completion</h2><div className="workflowForm"><select value={recordUser} onChange={e=>setRecordUser(e.target.value)}>{staff.map(person=><option key={person.id} value={person.id}>{person.full_name} · {person.department}</option>)}</select><select value={recordRequirement} onChange={e=>setRecordRequirement(e.target.value)}><option value="">Choose requirement</option>{requirements.map(r=><option value={r.id} key={r.id}>{r.title}</option>)}</select><input type="date" value={recordDate} onChange={e=>setRecordDate(e.target.value)}/><input value={recordEvidence} onChange={e=>setRecordEvidence(e.target.value)} placeholder="Certificate/reference (optional)"/><textarea value={recordNote} onChange={e=>setRecordNote(e.target.value)} placeholder="Verification note"/><button className="primary" onClick={verifyCompletion}>Verify completion</button></div></article></section>
      <section className="stageCard"><span className="eyebrow">ORGANISATION OVERVIEW</span><h2>Compliance coverage by requirement</h2><p className="workflowPrivacy">This view is operational: it highlights missing/expiring mandatory training. It does not rank staff performance.</p><div className="stageList">{matrix.map(({req,total,current,due,overdue})=><div className="stageRow" key={req.id}><div className="stageRowMain"><strong>{req.title}</strong><span>{req.audience_type==="all"?"All staff":`${req.audience_type}: ${req.audience_value}`}</span><small>{current}/{total} current · {due} due soon · {overdue} missing/expired</small></div><span className={`stageBadge ${overdue?"warn":"good"}`}>{total?Math.round(current/total*100):100}% current</span></div>)}</div></section></>}
  </main>;
}
