"use client";

import { useEffect, useMemo, useState } from "react";
import { getSupabaseBrowserClient } from "@/lib/supabase";

type Profile={role:string;organisation_id:string|null};
type Org={name:string;support_email:string|null};
type Check={key:string;title:string;detail:string;href:string;done:boolean;adminOnly?:boolean};

export default function HelpPage(){
  const [profile,setProfile]=useState<Profile|null>(null);const [org,setOrg]=useState<Org|null>(null);const [checks,setChecks]=useState<Record<string,boolean>>({});const [loading,setLoading]=useState(true);const [query,setQuery]=useState("");
  useEffect(()=>{let live=true;(async()=>{const c=getSupabaseBrowserClient();const {data:auth}=await c.auth.getUser();if(!auth.user){window.location.href="/auth?next=/help";return;}const {data:p}=await c.from("staff_profiles").select("role,organisation_id").eq("id",auth.user.id).single();if(!live)return;setProfile(p as Profile);if(!p?.organisation_id){setLoading(false);return;}const results=await Promise.all([c.from("organisations").select("name,support_email").eq("id",p.organisation_id).single(),c.from("organisation_domains").select("id").eq("organisation_id",p.organisation_id).eq("status","verified").limit(1),c.from("organisation_staff_directory").select("id").eq("organisation_id",p.organisation_id).limit(1),c.from("school_policies").select("id").eq("organisation_id",p.organisation_id).eq("active",true).limit(1),c.from("training_requirements").select("id").eq("organisation_id",p.organisation_id).eq("active",true).limit(1),c.from("onboarding_programmes").select("id").eq("organisation_id",p.organisation_id).eq("active",true).limit(1),c.from("inset_days").select("id").eq("organisation_id",p.organisation_id).limit(1)]);if(!live)return;if(results[0].data)setOrg(results[0].data as Org);setChecks({domain:Boolean(results[1].data?.length),staff:Boolean(results[2].data?.length),policy:Boolean(results[3].data?.length),training:Boolean(results[4].data?.length),onboarding:Boolean(results[5].data?.length),inset:Boolean(results[6].data?.length)});setLoading(false);})();return()=>{live=false};},[]);
  const admin=Boolean(profile&&["CPD Lead","Admin"].includes(profile.role));
  const setup:Check[]=[{key:"domain",title:"Verify the school email domain",detail:"Required before automatic staff school-account access can start.",href:"/school-access",done:checks.domain,adminOnly:true},{key:"staff",title:"Import or prepare the staff directory",detail:"Optional but recommended: pre-assign departments, roles and sites before first login.",href:"/staff-sync",done:checks.staff,adminOnly:true},{key:"policy",title:"Publish required school policies",detail:"Add policies that staff should read and acknowledge with version/date evidence.",href:"/school-hub",done:checks.policy,adminOnly:true},{key:"training",title:"Configure mandatory training",detail:"Set requirements, renewal frequencies and role/department audiences.",href:"/training",done:checks.training,adminOnly:true},{key:"onboarding",title:"Review onboarding pathways",detail:"New Staff, ECT and Teaching Assistant templates are created for new commercial schools.",href:"/school-hub",done:checks.onboarding,adminOnly:true},{key:"inset",title:"Build the first INSET programme",detail:"Create the day, workshops, rooms, capacities and linked CPD sessions.",href:"/school-hub",done:checks.inset,adminOnly:true},{key:"branding",title:"Apply school branding",detail:"Add display name, colours, logo and support contact.",href:"/school-hub",done:Boolean(org),adminOnly:true},{key:"report",title:"Review the governance evidence report",detail:"Check the live report before sharing it with governors, trustees or inspectors.",href:"/school-hub",done:false,adminOnly:true}];
  const articles=[
    {title:"Staff: signing in for the first time",tags:"login google microsoft school domain access",body:"Use Google Workspace or Microsoft 365 with your school email. The platform checks the confirmed email domain against the school's verified subscription and connects you automatically. If a school has prepared your directory record, your department, role and site are applied at first access."},
    {title:"CPD Leads: adding the school domain",tags:"domain verification school access",body:"Open School access and request the domain used for staff email. Domain requests do not activate themselves; platform verification is deliberately separate so another organisation cannot claim a domain it does not control."},
    {title:"Importing staff",tags:"staff sync csv mis import",body:"Use Staff sync and download the CSV template. Columns are email, full_name, department, role and site_code. Staff can still join without a directory import; the import mainly improves role, department and site provisioning."},
    {title:"Mandatory training and renewals",tags:"compliance training expiry mandatory",body:"Create training requirements in My training/CPD admin. The Reminders page surfaces missing or expiring mandatory training from the existing records, and leadership dashboards can review organisation patterns without exposing private reflections."},
    {title:"Policy acknowledgement",tags:"policy safeguarding kcsie acknowledgement",body:"The School hub can publish a policy version and require staff acknowledgement. The acknowledgement records the staff user, version and time. Updating the policy version creates a new acknowledgement need rather than treating an older acknowledgement as current."},
    {title:"INSET and live CPD",tags:"inset workshop booking live qr",body:"Build an INSET day in School hub, add sessions and link them to a CPD course. Facilitators can then use the course's full-screen deck and Live CPD mode for QR joining, activities, confidence checks and exit reflections."},
    {title:"Appraisal and Teachers' Standards",tags:"appraisal standards objectives teachers",body:"Staff can create development objectives and map them to relevant Teachers' Standards and CPD courses. An objective is private unless the member of staff chooses the share-with-leadership option; this avoids turning reflective CPD notes into automatic performance data."},
    {title:"What happens when a subscription pauses?",tags:"subscription cancelled expired past due",body:"School records remain stored, but normal CPD access is paused. The platform owner can apply a grace period for past-due accounts. School access and platform administration remain separated so a school cannot reactivate its own commercial entitlement."},
    {title:"Google or Microsoft button says provider not enabled",tags:"oauth provider disabled setup",body:"The application code supports both providers, but the Supabase project must also have the matching Google and/or Microsoft OAuth provider credentials configured. This is a one-time platform setup, not something each school should enter."},
    {title:"Privacy and safeguarding",tags:"privacy safeguarding pupil data",body:"The CPD platform is not a safeguarding case-management system. Do not place confidential pupil case records into CPD reflections, evidence notes or group activities. Use the school's approved safeguarding system and reporting route for actual concerns."},
  ];
  const visible=useMemo(()=>articles.filter(a=>`${a.title} ${a.tags} ${a.body}`.toLowerCase().includes(query.toLowerCase())),[query]);
  if(loading)return <main className="stagePage"><div className="stageCard">Opening help centre…</div></main>;
  return <main className="stagePage helpPage"><section className="stageHero helpHero"><span className="eyebrow">HELP & SCHOOL ONBOARDING</span><h1>{org?.name?`${org.name} support centre`:"Teaching CPD support centre"}</h1><p>Quick-start guidance for staff and a practical setup checklist for school CPD leads.</p>{org?.support_email&&<div className="stageHeroActions"><a className="secondary phaseLinkButton" href={`mailto:${org.support_email}`}>Contact school support</a></div>}</section>
    {admin&&<section className="stageCard setupChecklist"><span className="eyebrow">SCHOOL SETUP CHECKLIST</span><h2>Go from purchase to staff-ready</h2><div className="setupProgress"><progress max={setup.length} value={setup.filter(x=>x.done).length}/><span>{setup.filter(x=>x.done).length}/{setup.length} checked</span></div><div className="setupSteps">{setup.map((item,i)=><a href={item.href} key={item.key} className={item.done?"done":""}><span>{item.done?"✓":i+1}</span><div><strong>{item.title}</strong><p>{item.detail}</p></div><b>→</b></a>)}</div></section>}
    <section className="stageGrid"><div className="stageCard stageSpan4"><span className="eyebrow">STAFF QUICK START</span><h2>Your first five minutes</h2><ol className="helpQuickSteps"><li><b>Sign in</b><span>Use your school Google or Microsoft account.</span></li><li><b>Open Reminders</b><span>See training, policies, onboarding and reviews that need attention.</span></li><li><b>Choose CPD</b><span>Start a course or follow an assigned pathway.</span></li><li><b>Apply it</b><span>Use Course Lab or an action plan to test one change.</span></li><li><b>Review impact</b><span>Return to your portfolio/action plan and record proportionate evidence.</span></li></ol></div><div className="stageCard stageSpan8"><span className="eyebrow">KNOWLEDGE BASE</span><h2>Find an answer</h2><input className="helpSearch" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search login, policies, INSET, appraisal, privacy…"/><div className="helpArticles">{visible.map(a=><details key={a.title}><summary>{a.title}</summary><p>{a.body}</p></details>)}{!visible.length&&<p className="muted">No help article matched that search.</p>}</div></div></section>
    <section className="stageCard helpBoundary"><strong>Launch support note</strong><p>Google/Microsoft school sign-in still requires the platform's OAuth provider credentials to be configured in Supabase before those buttons can complete a real sign-in. The school access/domain/subscription logic in this app is separate from that one-time provider configuration.</p></section>
  </main>;
}
