"use client";

import { useEffect } from "react";
import { courses } from "@/lib/catalogue";
import { getPhase24Pack } from "../../lib/courseExpertChallengesPhase24";

function clean(v:string|null|undefined){return(v||"").replace(/\s+/g," ").trim();}
function esc(v:string){return v.replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]||c));}
function courseFor(modal:HTMLElement){const title=clean(modal.querySelector(".courseModalHead h2")?.textContent);return courses.find(c=>c.title===title)||null;}
function parse(k:string){try{return JSON.parse(localStorage.getItem(k)||"{}")}catch{return{}}}
function passedAssessment(title:string){for(let i=0;i<localStorage.length;i+=1){const k=localStorage.key(i);if(!k?.startsWith(`cpd-phase5:${title}|`)||k.includes("Diagnostic pre-check"))continue;try{if(JSON.parse(localStorage.getItem(k)||"{}").passed===true)return true;}catch{}}return false;}
function mastery(courseId:string,title:string){const advanced=[16,17,18,19].filter(p=>parse(`cpd-phase${p}:${courseId}`).complete===true).length;return{assessment:passedAssessment(title),advanced,unlocked:passedAssessment(title)&&advanced>=2};}

type Stored={current?:string;selections?:Record<string,string[]>;passed?:string[];written?:string;complete?:boolean;updatedAt?:string};
function key(id:string){return`cpd-phase24:${id}`;}
function read(id:string):Stored{try{return JSON.parse(localStorage.getItem(key(id))||"{}")}catch{return{}}}
function write(id:string,patch:Partial<Stored>){const next={...read(id),...patch,updatedAt:new Date().toISOString()};try{localStorage.setItem(key(id),JSON.stringify(next));}catch{}window.dispatchEvent(new CustomEvent("cpd:meaningful-progress",{detail:{courseId:id,phase:24}}));return next;}
function reset(id:string){try{localStorage.removeItem(key(id));}catch{}window.dispatchEvent(new CustomEvent("cpd:meaningful-progress",{detail:{courseId:id,phase:24}}));}

function render(modal:HTMLElement,force=false){const course=courseFor(modal);if(!course)return;const head=modal.querySelector<HTMLElement>(".courseModalHead");if(!head)return;const pack=getPhase24Pack(course as never);const m=mastery(course.id,course.title);const stored=read(course.id);const current=pack.challenges.find(c=>c.id===stored.current)||pack.challenges[0];const passed=new Set(stored.passed||[]);const selections=stored.selections||{};const complete=Boolean(stored.complete);const sig=`${course.id}|${m.assessment?1:0}|${m.advanced}|${current.id}|${[...passed].join(",")}|${(stored.written||"").length}|${complete?1:0}`;if(!force&&modal.dataset.phase24Signature===sig)return;modal.dataset.phase24Signature=sig;
let badge=head.querySelector<HTMLButtonElement>(".phase24ExpertBadge");if(!badge){badge=document.createElement("button");badge.type="button";badge.className="phase24ExpertBadge";badge.addEventListener("click",()=>{const d=modal.querySelector<HTMLElement>(".phase24ExpertDrawer");if(!d)return;d.classList.toggle("open");});head.appendChild(badge);}badge.innerHTML=`<span>★</span><strong>${m.unlocked?(complete?"✓":`${passed.size}/3`):"LOCK"}</strong><small>expert</small>`;
let drawer=modal.querySelector<HTMLElement>(".phase24ExpertDrawer");if(!drawer){drawer=document.createElement("section");drawer.className="phase24ExpertDrawer";head.insertAdjacentElement("afterend",drawer);}const open=drawer.classList.contains("open");
if(!m.unlocked){drawer.innerHTML=`<header><div><span>PRESENTATION OVERHAUL · PHASE 24</span><h3>${esc(pack.title)}</h3><p>${esc(pack.subtitle)}</p></div><button class="phase24Close" type="button">×</button></header><section class="phase24Locked"><span>MASTERY GATE</span><h4>Expert challenges are still locked</h4><p>${esc(pack.unlockRule)}</p><div><article class="${m.assessment?"done":""}"><b>${m.assessment?"✓":"1"}</b><span>Pass a substantive Phase 5 assessment</span></article><article class="${m.advanced>=2?"done":""}"><b>${m.advanced>=2?"✓":String(m.advanced)}</b><span>Complete at least two advanced applied activities from Phases 16–19</span></article></div><small>These are optional stretch tasks. The main course remains fully usable without unlocking them.</small></section>`;drawer.classList.toggle("open",open);drawer.querySelector(".phase24Close")?.addEventListener("click",()=>drawer?.classList.remove("open"));return;}
const tabs=pack.challenges.map(c=>`<button type="button" data-phase24-tab="${c.id}" class="${c.id===current.id?"current":""} ${passed.has(c.id)?"passed":""}"><span>${esc(c.kind.replaceAll("_"," ").toUpperCase())}</span><strong>${esc(c.title)}</strong><b>${passed.has(c.id)?"✓":""}</b></button>`).join("");
let activity="";if(current.options){const selected=new Set(selections[current.id]||[]);activity=`<div class="phase24Options">${current.options.map(o=>`<button type="button" data-phase24-option="${o.id}" class="${selected.has(o.id)?"selected":""}"><b>${o.id}</b><span>${esc(o.label)}</span></button>`).join("")}</div><div class="phase24Action"><small>${selected.size}/${current.requiredSelections||1} selected</small><button type="button" class="phase24Check">Check expert answer</button></div><div class="phase24Feedback"></div>`;}else{const written=stored.written||"";activity=`<textarea class="phase24Written" rows="7" placeholder="Build a professional response that handles the constraint explicitly…">${esc(written)}</textarea><div class="phase24Action"><small class="phase24WrittenCount">${clean(written).length} / 120 characters</small><button type="button" class="phase24CheckWritten">Submit expert design</button></div>`;}
drawer.innerHTML=`<header><div><span>PRESENTATION OVERHAUL · PHASE 24</span><h3>${esc(pack.title)}</h3><p>${esc(pack.subtitle)}</p></div><button class="phase24Close" type="button">×</button></header><section class="phase24Tabs">${tabs}</section><section class="phase24Challenge"><span>UNLOCKED EXPERT TASK</span><h4>${esc(current.title)}</h4><p>${esc(current.prompt)}</p>${activity}${passed.has(current.id)?`<aside><strong>Expert note</strong><p>${esc(current.expertNote)}</p></aside>`:""}</section><footer><div><strong>${complete?"Expert set complete":"Optional stretch — no course gate"}</strong><p>These tasks are intentionally harder and only appear after mastery evidence.</p></div><button type="button" class="phase24Reset">Reset expert set</button></footer>`;drawer.classList.toggle("open",open);drawer.querySelector(".phase24Close")?.addEventListener("click",()=>drawer?.classList.remove("open"));drawer.querySelectorAll<HTMLButtonElement>("[data-phase24-tab]").forEach(b=>b.addEventListener("click",()=>{write(course.id,{current:b.dataset.phase24Tab});render(modal,true);}));drawer.querySelectorAll<HTMLButtonElement>("[data-phase24-option]").forEach(b=>b.addEventListener("click",()=>{const set=new Set(read(course.id).selections?.[current.id]||[]);const id=b.dataset.phase24Option||"";if(set.has(id))set.delete(id);else if(set.size<(current.requiredSelections||1))set.add(id);write(course.id,{selections:{...(read(course.id).selections||{}),[current.id]:[...set]}});render(modal,true);}));drawer.querySelector(".phase24Check")?.addEventListener("click",()=>{if(!current.options)return;const picks=new Set(read(course.id).selections?.[current.id]||[]);const correct=new Set(current.options.filter(o=>o.correct).map(o=>o.id));const ok=picks.size===correct.size&&[...picks].every(x=>correct.has(x));const box=drawer?.querySelector<HTMLElement>(".phase24Feedback");if(!ok){if(box)box.innerHTML=`<strong>Not yet</strong><p>Re-read the constraint and identify which evidence or principle rules out the tempting option.</p>`;return;}const next=new Set(read(course.id).passed||[]);next.add(current.id);write(course.id,{passed:[...next],complete:next.size===pack.challenges.length});render(modal,true);});const writtenBox=drawer.querySelector<HTMLTextAreaElement>(".phase24Written");const writtenCount=drawer.querySelector<HTMLElement>(".phase24WrittenCount");writtenBox?.addEventListener("input",()=>{write(course.id,{written:writtenBox.value});if(writtenCount)writtenCount.textContent=`${clean(writtenBox.value).length} / 120 characters`;});drawer.querySelector(".phase24CheckWritten")?.addEventListener("click",()=>{const value=clean(writtenBox?.value);if(value.length<120)return;const next=new Set(read(course.id).passed||[]);next.add(current.id);write(course.id,{written:value,passed:[...next],complete:next.size===pack.challenges.length});render(modal,true);});drawer.querySelector(".phase24Reset")?.addEventListener("click",()=>{reset(course.id);render(modal,true);});}

export default function CourseExpertChallengesPhase24Controller(){useEffect(()=>{let q=false;const apply=()=>{if(q)return;q=true;requestAnimationFrame(()=>{q=false;document.querySelectorAll<HTMLElement>(".courseModal").forEach(m=>render(m));});};apply();const o=new MutationObserver(apply);o.observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:["class"]});const refresh=()=>document.querySelectorAll<HTMLElement>(".courseModal").forEach(m=>render(m,true));window.addEventListener("storage",refresh);window.addEventListener("cpd:meaningful-progress",refresh as EventListener);window.addEventListener("cpd:phase5-assessment",refresh as EventListener);return()=>{o.disconnect();window.removeEventListener("storage",refresh);window.removeEventListener("cpd:meaningful-progress",refresh as EventListener);window.removeEventListener("cpd:phase5-assessment",refresh as EventListener);};},[]);return null;}
