"use client";

import { useEffect } from "react";
import { courses } from "@/lib/catalogue";
import { getPhase25Pack } from "../../lib/courseInteractiveModelsPhase25";

function clean(v:string|null|undefined){return(v||"").replace(/\s+/g," ").trim();}
function esc(v:string){return v.replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]||c));}
function courseFor(modal:HTMLElement){const title=clean(modal.querySelector(".courseModalHead h2")?.textContent);return courses.find(c=>c.title===title)||null;}
function moduleIndex(modal:HTMLElement){return Array.from(modal.querySelectorAll<HTMLButtonElement>(".moduleNav button")).findIndex(b=>b.classList.contains("current"));}

type Stored={stage?:number;visited?:string[];answers?:Record<string,string>;complete?:boolean;updatedAt?:string};
function key(id:string){return`cpd-phase25:${id}`;}
function read(id:string):Stored{try{return JSON.parse(localStorage.getItem(key(id))||"{}")}catch{return{}}}
function write(id:string,patch:Partial<Stored>){const next={...read(id),...patch,updatedAt:new Date().toISOString()};try{localStorage.setItem(key(id),JSON.stringify(next));}catch{}window.dispatchEvent(new CustomEvent("cpd:meaningful-progress",{detail:{courseId:id,phase:25}}));return next;}
function reset(id:string){try{localStorage.removeItem(key(id));}catch{}window.dispatchEvent(new CustomEvent("cpd:meaningful-progress",{detail:{courseId:id,phase:25}}));}

function render(modal:HTMLElement,force=false){if(modal.classList.contains("labMode"))return;const course=courseFor(modal);const idx=moduleIndex(modal);const module=course?.modules[idx];const content=modal.querySelector<HTMLElement>(".moduleContent");if(!course||!module||!content)return;const pack=getPhase25Pack(course as never);if(module.id!==pack.anchorId){content.querySelector(".phase25ModelShell")?.remove();delete content.dataset.phase25Signature;return;}const stored=read(course.id);const stageIndex=Math.max(0,Math.min(pack.stages.length-1,stored.stage||0));const stage=pack.stages[stageIndex];const visited=new Set(stored.visited||[]);visited.add(stage.id);const answers=stored.answers||{};const complete=Boolean(stored.complete);const sig=`${course.id}|${stageIndex}|${[...visited].join(",")}|${Object.entries(answers).map(x=>x.join(":"))}|${complete?1:0}`;if(!force&&content.dataset.phase25Signature===sig)return;content.dataset.phase25Signature=sig;content.querySelector(".phase25ModelShell")?.remove();
const nodes=pack.stages.map((s,i)=>`<button type="button" data-phase25-stage="${i}" class="${i===stageIndex?"current":""} ${visited.has(s.id)?"visited":""}"><span>${i+1}</span><strong>${esc(s.headline)}</strong></button>`).join("");
const selected=answers[stage.id]||"";const options=stage.decision.options.map(o=>`<button type="button" data-phase25-answer="${o.id}" class="${selected===o.id?"selected":""} ${selected&&o.best?"best":""}"><b>${o.id}</b><span>${esc(o.label)}</span></button>`).join("");
const answered=Boolean(selected);const feedback=answered?stage.decision.options.find(o=>o.id===selected)?.best?`<div class="phase25Feedback success"><strong>Strong decision</strong><p>${esc(stage.decision.feedback)}</p></div>`:`<div class="phase25Feedback"><strong>Reconsider the model</strong><p>${esc(stage.decision.feedback)}</p></div>`:"";
const shell=document.createElement("section");shell.className=`phase25ModelShell ${complete?"completed":""}`;shell.innerHTML=`<header><div><span>PRESENTATION OVERHAUL · PHASE 25</span><h3>${esc(pack.title)}</h3><p>${esc(pack.subtitle)}</p></div><b>${complete?"✓":`${stageIndex+1}/4`}</b></header><div class="phase25ModelMap">${nodes}</div><section class="phase25Stage"><div class="phase25StageVisual"><span>${esc(stage.label)}</span><div><b>${stageIndex+1}</b></div><small>Click another stage above to explore the model non-linearly.</small></div><div class="phase25StageText"><span>EXPLANATION</span><h4>${esc(stage.headline)}</h4><p>${esc(stage.explanation)}</p><aside><strong>Watch for</strong><p>${esc(stage.watchFor)}</p></aside></div></section><section class="phase25Decision"><span>MINI DECISION</span><h4>${esc(stage.decision.prompt)}</h4><div>${options}</div>${feedback}</section><footer><div><strong>${visited.size}/4 stages explored · ${Object.keys(answers).length}/4 decisions made</strong><p>${complete?"Interactive model complete — revisit any stage to review the reasoning.":"Explore all four stages and make a decision at each point to complete the model."}</p></div><div><button type="button" class="phase25Next">${stageIndex===3?"Review model":"Next stage"}</button><button type="button" class="phase25Reset">Reset</button></div></footer>`;
const target=content.querySelector(".moduleActions");content.insertBefore(shell,target||null);if(!stored.visited?.includes(stage.id))write(course.id,{visited:[...visited]});
shell.querySelectorAll<HTMLButtonElement>("[data-phase25-stage]").forEach(b=>b.addEventListener("click",()=>{write(course.id,{stage:Number(b.dataset.phase25Stage||0),visited:[...visited]});render(modal,true);}));shell.querySelectorAll<HTMLButtonElement>("[data-phase25-answer]").forEach(b=>b.addEventListener("click",()=>{const nextAnswers={...read(course.id).answers,[stage.id]:b.dataset.phase25Answer||""};const nextVisited=new Set(read(course.id).visited||[]);nextVisited.add(stage.id);const allAnswered=pack.stages.every(s=>Boolean(nextAnswers[s.id]));const allVisited=pack.stages.every(s=>nextVisited.has(s.id));write(course.id,{answers:nextAnswers,visited:[...nextVisited],complete:allAnswered&&allVisited});render(modal,true);}));shell.querySelector(".phase25Next")?.addEventListener("click",()=>{write(course.id,{stage:stageIndex===3?0:stageIndex+1,visited:[...visited]});render(modal,true);});shell.querySelector(".phase25Reset")?.addEventListener("click",()=>{reset(course.id);render(modal,true);});}

export default function CourseInteractiveModelsPhase25Controller(){useEffect(()=>{let q=false;const apply=()=>{if(q)return;q=true;requestAnimationFrame(()=>{q=false;document.querySelectorAll<HTMLElement>(".courseModal").forEach(m=>render(m));});};apply();const o=new MutationObserver(apply);o.observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:["class"]});return()=>o.disconnect();},[]);return null;}
