"use client";
import {useState} from "react";
import {downloadText} from "@/lib/schoolReporting";
import {procurementFields,procurementSections,missingProcurementFields,procurementMarkdown,type CatalogueFacts,type ProcurementDetails} from "@/lib/schoolProcurement";
export default function SchoolProcurementPack({facts}:{facts:CatalogueFacts}){
 const [details,setDetails]=useState<ProcurementDetails>({}),[notice,setNotice]=useState("");
 const sections=procurementSections(facts),missing=missingProcurementFields(details);
 return <main className="stagePage schoolOperations procurementPage">
 <header className="stageHero"><span className="eyebrow">SCHOOL PROCUREMENT</span><h1>Teaching CPD: buyer information pack</h1><p>Product information, a school evaluation checklist and draft schedules for provider and school review.</p><nav className="schoolOperationLinks noPrint" aria-label="Procurement navigation"><a href="/school-onboarding">School setup & tutorial</a><a href="/school-reporting">School reporting (sign-in required)</a><a href="/auth">Sign in</a></nav></header>
 <section className="stageCard procurementDraft" aria-labelledby="draft-title"><h2 id="draft-title">Draft for review · not approved for contracting</h2><p>This pack is not a signed contract, approved quotation, legal advice or security/accessibility certification. The provider must confirm the outstanding details and obtain appropriate review before sale.</p><p role="status">{missing.length} / {procurementFields.length} details still to confirm. Entering a value does not verify or approve it.</p><div className="schoolOperationLinks noPrint"><button type="button" className="primary" onClick={()=>{downloadText(procurementMarkdown(facts,details),"teaching-cpd-school-procurement-DRAFT.md","text/markdown;charset=utf-8");setNotice("Draft download requested. If your browser blocks downloads, use Print / Save PDF.");}}>Download draft pack (Markdown)</button><button type="button" className="secondary" onClick={()=>window.print()}>Print / Save PDF</button></div>{notice?<p role="status" className="noPrint">{notice}</p>:null}</section>
 <nav className="procurementContents noPrint" aria-label="Pack contents">{sections.map(section=><a key={section.id} href={"#pack-"+section.id}>{section.title}</a>)}<a href="#pack-details">Draft details</a></nav>
 {sections.map(section=><section className="stageCard procurementSection" id={"pack-"+section.id} key={section.id}><span className="eyebrow">{section.status}</span><h2>{section.title}</h2>{section.paragraphs.map(p=><p key={p}>{p}</p>)}<ul>{section.items.map(item=><li key={item}>{item}</li>)}</ul>{section.source?<p>Review reference: <a href={section.source.href} target="_blank" rel="noreferrer">{section.source.title}</a>.</p>:null}</section>)}
 <section className="stageCard procurementSection" id="pack-details"><h2>Draft details supplied for review</h2><p>Notes stay in this page's memory; they are not uploaded, published or saved to your school. Download a copy before leaving. Do not enter credentials or sensitive personal information.</p><div className="procurementFields">{procurementFields.map(field=><label key={field.id}><strong>{field.label}</strong><span>{field.hint}</span><textarea className="noPrint" rows={3} maxLength={2000} value={details[field.id]||""} placeholder="TO CONFIRM" onChange={e=>setDetails(current=>({...current,[field.id]:e.target.value}))}/><span className="printOnly">{details[field.id]?.trim()||"TO CONFIRM — "+field.hint}</span></label>)}</div><p>Unresolved: {missing.length?missing.map(f=>f.label).join("; "):"All details entered — all still require review and approval."}</p></section>
 <footer className="stageCard procurementSection"><h2>Approval handoff</h2><p>Confirm the provider reviewer, school procurement reviewer, school data-protection reviewer and approved contract/quote references outside this tool. Printing, downloading or completing notes does not sign an agreement or approve a purchase.</p><a className="noPrint" href="/school-onboarding">Return to the school rollout tutorial</a></footer>
 </main>;
}
