"use client";
import {useEffect,useRef,useState} from 'react';import Link from 'next/link';
import {getSupabaseBrowserClient} from '@/lib/supabase';import './SchoolTimetableBuilder.css';
type School={id:string;name:string;canManage:boolean;staff:{id:string;name:string}[]};
type Draft={school?:{name?:string};staff?:{id:string;name?:string;initials?:string}[];generatedTimetables?:{id:string;name:string}[];activeTimetableId?:string;publishedTimetable?:unknown;[key:string]:unknown};
type Context={org:string;revision:number;data:Draft;links:Record<string,string>;queue:Promise<unknown>;failed:boolean;publishedAt?:string};
const channel='teaching-cpd:time-maker';
export default function SchoolTimetableBuilder(){
 const [schools,setSchools]=useState<School[]>([]),[org,setOrg]=useState(''),[userId,setUserId]=useState(''),[draft,setDraft]=useState<Draft>({}),[links,setLinks]=useState<Record<string,string>>({}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState(''),[frameVersion,setFrameVersion]=useState(0),[frameReady,setFrameReady]=useState(false);
 const frame=useRef<HTMLIFrameElement>(null),context=useRef<Context|null>(null),requests=useRef(new Map<number,{resolve:(v:Draft)=>void;reject:(e:Error)=>void;timer:ReturnType<typeof setTimeout>}>()),counter=useRef(0);
 useEffect(()=>()=>{for(const request of requests.current.values()){clearTimeout(request.timer);request.reject(new Error("Builder closed."));}requests.current.clear();},[]);
 const school=schools.find(s=>s.id===org);
 useEffect(()=>{let active=true;const client=getSupabaseBrowserClient();const {data:listener}=client.auth.onAuthStateChange(event=>{if(event==='SIGNED_OUT'){active=false;context.current=null;setSchools([]);setOrg('');setDraft({});setLinks({});window.location.replace('/auth?next=%2Ftimetable');}});(async()=>{const {data}=await client.auth.getUser();if(!data.user){window.location.replace('/auth?next=%2Ftimetable');return;}const {data:items,error}=await client.rpc('school_timetable_context');if(error)throw error;if(active){setUserId(data.user.id);setSchools(items || []);setOrg(items?.[0]?.id || '');setLoading(false);}})().catch(e=>{if(active){setError(e.message);setLoading(false);}});return()=>{active=false;listener.subscription.unsubscribe();};},[]);
 async function loadSchool(){if(!org||!school?.canManage){context.current=null;return;}context.current=null;setLoading(true);setFrameReady(false);setError('');try{const {data,error}=await getSupabaseBrowserClient().rpc('school_timetable_admin',{org_id:org,operation:'load'});if(error)throw error;const initial=data.data?.school?data.data:{school:{name:school.name}};const next={org,revision:data.revision,data:initial,links:data.links || {},queue:Promise.resolve(),failed:false,publishedAt:data.publishedAt};context.current=next;setDraft(next.data);setLinks(next.links);setFrameVersion(v=>v+1);setStatus(data.publishedAt?'Last published '+new Date(data.publishedAt).toLocaleString():'No timetable published yet.');}catch(e){setError(e instanceof Error?e.message:'Could not load school timetable.');}finally{setLoading(false);}}
 useEffect(()=>{void loadSchool();},[org]);
 function post(message:object,target=frame.current?.contentWindow){target?.postMessage({channel,...message},location.origin);}
 function initialise(){const ctx=context.current;if(ctx)post({type:'init',scope:ctx.org+':'+userId,data:ctx.data});}
 function enqueue(ctx:Context,data:Draft,nextLinks=ctx.links){if(JSON.stringify(ctx.data)===JSON.stringify(data)&&JSON.stringify(ctx.links)===JSON.stringify(nextLinks))return ctx.queue;nextLinks=Object.fromEntries(Object.entries(nextLinks).filter(([id])=>data.staff?.some(t=>t.id===id)));ctx.data=data;ctx.links=nextLinks;if(context.current===ctx)setLinks(nextLinks);const promise=ctx.queue.then(async()=>{if(ctx.failed)throw new Error('Reload the draft to resolve the previous save error.');const {data:result,error}=await getSupabaseBrowserClient().rpc('school_timetable_admin',{org_id:ctx.org,operation:'save',expected_revision:ctx.revision,payload:{data,links:nextLinks}});if(error){ctx.failed=true;throw error;}ctx.revision=result.revision;if(context.current===ctx)setStatus(ctx.publishedAt?'School draft saved. Last published '+new Date(ctx.publishedAt).toLocaleString()+'. Publish further allocation changes when ready.':'School draft saved. Publish to update staff planners.');});ctx.queue=promise.catch(()=>{});return promise;}
 useEffect(()=>{const receive=(event:MessageEvent)=>{if(event.origin!==location.origin||event.source!==frame.current?.contentWindow||event.data?.channel!==channel)return;const m=event.data,ctx=context.current,target=event.source as Window;if(m.type==='ready'){setFrameReady(true);if(ctx)post({type:'init',scope:ctx.org+':'+userId,data:ctx.data},target);return;}if(m.type==='publication'){const request=requests.current.get(m.id);if(request){clearTimeout(request.timer);requests.current.delete(m.id);m.error?request.reject(new Error(m.error)):request.resolve(m.data);}return;}if(m.type==='error'){setError(m.error);return;}if(m.type==='save'&&ctx){setDraft(m.data);enqueue(ctx,m.data).then(()=>post({type:'ack',id:m.id},target)).catch(e=>{post({type:'ack',id:m.id,error:e.message},target);if(context.current===ctx)setError(e.message);});}};window.addEventListener('message',receive);return()=>window.removeEventListener('message',receive);},[org,userId]);
 function prepare(){return new Promise<Draft>((resolve,reject)=>{const id=++counter.current;const timer=setTimeout(()=>{requests.current.delete(id);reject(new Error('The builder did not respond. Reload the draft and retry.'));},15000);requests.current.set(id,{resolve,reject,timer});post({type:'prepare-publication',id});});}
 async function publish(daily=false){const ctx=context.current;if(!ctx)return;setBusy(true);setError('');try{const data=daily?ctx.data:await prepare();await ctx.queue;if(ctx.failed)throw new Error('Reload the draft before publishing.');const {data:result,error}=await getSupabaseBrowserClient().rpc('school_timetable_admin',{org_id:ctx.org,operation:daily?'daily':'publish',expected_revision:ctx.revision,payload:daily?{}:{data,links:ctx.links}});if(error)throw error;ctx.revision=result.revision;ctx.publishedAt=result.publishedAt;if(!daily){ctx.data=data;setDraft(data);setFrameReady(false);setFrameVersion(v=>v+1);}setStatus(daily?'Daily changes synced. Staff planners refresh automatically.':'Timetable published and synced to linked CPD staff accounts.');}catch(e){setError(e instanceof Error?e.message:'Publication failed.');}finally{setBusy(false);}}
 async function updateLink(id:string,value:string){const ctx=context.current;if(!ctx)return;const next={...ctx.links};if(value)next[id]=value;else delete next[id];setLinks(next);try{await enqueue(ctx,ctx.data,next);setError('');}catch(e){setError(e instanceof Error?e.message:'Staff link could not be saved.');}}
 return <main className="schoolTimetablePage"><header><span className="schoolTimetableEyebrow">SCHOOL TIMETABLE</span><h1>Timetable</h1><p>Build the school timetable, publish it, and send each teacher their allocation in the existing lesson planner.</p><Link href="/staff-timetable">My timetable & lesson planner →</Link></header>{schools.length>0&&<label>School<select value={org} disabled={busy||loading} onChange={e=>setOrg(e.target.value)}>{schools.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>}{error&&<p role="alert" className="schoolTimetableError">{error}</p>}{loading&&<p role="status">Loading school timetable…</p>}{!loading&&school&&!school.canManage&&<section><h2>Your school timetable</h2><p>Your school timetabler publishes your lessons directly into your personal planner. School owners, administrators and SLT can build and publish here.</p><Link href="/staff-timetable">Open my planner</Link></section>}{!loading&&!schools.length&&!error&&<p>Join or create a school organisation to use a shared timetable.</p>}{school?.canManage&&!loading&&<><section><div className="schoolTimetableActions"><button onClick={()=>publish()} disabled={busy||!frameReady||!Object.keys(links).length}>{busy?'Working…':'Publish & sync timetable'}</button><button onClick={()=>publish(true)} disabled={busy||!frameReady}>Sync daily changes</button><button onClick={loadSchool} disabled={busy}>Reload school draft</button></div><p role="status">{status}</p><p>Draft edits stay in the builder. Publishing updates staff allocations; syncing daily changes sends room changes, cancellations and cover for the approved timetable.</p><details><summary>Link timetable teachers to CPD staff accounts ({Object.keys(links).length} linked)</summary><p>Choose the matching signed-in school account for each teacher. Unlinked teachers remain in the school timetable but do not receive an automatic personal allocation.</p><div className="schoolTimetableLinks">{(draft.staff || []).map(t=><label key={t.id}>{t.name || t.initials || t.id}<select value={links[t.id] || ''} disabled={busy} onChange={e=>void updateLink(t.id,e.target.value)}><option value="">Not linked</option>{school.staff.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>)}</div>{!draft.staff?.length&&<p>Add staff in the builder first.</p>}</details></section><iframe key={frameVersion} ref={frame} title="School timetable builder" src="/time-maker/index.html" onLoad={initialise} className="schoolTimetableFrame"/></>}</main>;
}
