"use client";
import { useMemo, useState } from "react";
import { courses } from "@/lib/catalogue";
import { buildSchoolReport, downloadText, reportCsv, validDay, type ReportingSnapshot, type ReportTab } from "@/lib/schoolReporting";

const tabs: [ReportTab,string][]=[["staff","Staff summary"],["completions","Course completions"],["requirements","Mandatory training"],["pathways","Connected pathways"],["assignments","Assignments"]];
export default function SchoolReportDashboard({snapshot,onRefresh}:{snapshot:ReportingSnapshot;onRefresh:()=>void}) {
  const [department,setDepartment]=useState("All"),[search,setSearch]=useState(""),[from,setFrom]=useState(""),[to,setTo]=useState(""),[tab,setTab]=useState<ReportTab>("staff"),[trainingStatus,setTrainingStatus]=useState("All");
  const invalid=Boolean((from&&!validDay(from))||(to&&!validDay(to))||(from&&to&&from>to));
  const filters={department,search,from:invalid?"":from,to:invalid?"":to};
  const report=useMemo(()=>buildSchoolReport(snapshot,courses,filters),[snapshot,department,search,from,to,invalid]);
  const required=report.requirementRows, gaps=required.filter(r=>r.status==="missing"||r.status==="expired").length;
  const requirements=required.filter(r=>trainingStatus==="All"||r.status===trainingStatus);
  const shown={...report,requirementRows:requirements};
  return <main className="stagePage schoolOperations reportPage"><header className="stageHero"><span className="eyebrow">SCHOOL REPORTING</span><h1>{snapshot.organisation.name}</h1><p>{snapshot.organisation.academic_year} · as of {report.today} ({snapshot.organisation.timezone})</p><p>Active school members only. Completion is a learning record, not evidence of competence or statutory compliance. Private reflections and assessment responses are excluded.</p><nav className="schoolOperationLinks noPrint" aria-label="School reporting navigation"><a href="/school-onboarding">School setup & tutorial</a><a href="/admin">Assign learning</a><a href="/procurement">Procurement pack</a><button type="button" className="secondary" onClick={onRefresh}>Refresh records</button></nav></header>
    <section className="schoolReportFilters noPrint" aria-label="Report filters"><label>Department<select value={department} onChange={e=>setDepartment(e.target.value)}><option>All</option>{[...new Set(snapshot.staff.map(s=>s.department))].sort().map(d=><option value={d} key={d}>{d||"No department"}</option>)}</select></label><label>Staff search<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name, department or role"/></label><label>Completions from<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Completions to<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button type="button" className="secondary" onClick={()=>{setDepartment("All");setSearch("");setFrom("");setTo("");setTrainingStatus("All");}}>Reset filters</button></section>
    {invalid?<p role="alert">Choose valid dates with the start on or before the end. Export is disabled until corrected.</p>:null}
    <p className="reportScope">Date filters apply to completed courses and planned hours only. Mandatory training, assignment deadlines and pathway progress show current status as of {report.today}.</p>
    <section className="schoolReportMetrics" aria-label="Report summary">{[[report.staffRows.length,"Staff in view"],[report.completionRows.length,"Course completions in period"],[report.hours.toFixed(1),"Planned CPD hours in period"],[gaps,"Missing / expired requirements"],[required.filter(r=>r.status==="due-soon").length,"Renewals within 30 days"],[report.assignmentRows.filter(r=>r.status==="overdue").length,"Overdue assignments"]].map(([value,label])=><div className="stageCard" key={label}><strong>{value}</strong><span>{label}</span></div>)}</section>
    <div className="schoolReportActions noPrint"><nav aria-label="Report views">{tabs.map(([id,label])=><button type="button" className={tab===id?"primary":"secondary"} key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}>{label}</button>)}</nav><div><button type="button" className="secondary" disabled={invalid} onClick={()=>downloadText(reportCsv(shown,tab,snapshot),"teaching-cpd-"+tab+"-"+report.today+".csv")}>Download this view (CSV)</button><button type="button" className="secondary" disabled={invalid} onClick={()=>window.print()}>Print / Save PDF</button></div></div>
    <section className="stageCard reportResults" aria-labelledby="report-view-heading"><h2 id="report-view-heading">{tabs.find(([id])=>id===tab)![1]}</h2>{!report.staffRows.length?<p role="status">No active staff match this view. Check school membership or reset your filters.</p>:null}
      {tab==="pathways"?<p>These are suggested catalogue pathways, not assigned obligations. A staff member can complete any course; existing completed records count.</p>:null}
      {tab==="requirements"?<label className="noPrint">Training status<select value={trainingStatus} onChange={e=>setTrainingStatus(e.target.value)}><option>All</option>{["current","due-soon","expired","missing"].map(s=><option key={s}>{s}</option>)}</select></label>:null}
      <div className="reportTableScroll" tabIndex={0} aria-label="Scrollable report table"><table><caption>{tabs.find(([id])=>id===tab)![1]} · {snapshot.organisation.name}</caption><thead><tr><th scope="col">Staff</th><th scope="col">Department</th>{(tab==="staff"?["Completed courses","Planned hours","Current / applicable training","Missing / expired","Overdue"]:tab==="completions"?["Course","Completed","Planned minutes"]:tab==="requirements"?["Requirement","Status","Completed","Expires","Source"]:tab==="pathways"?["Pathway","Complete / total","Next unfinished"]:["Assignment","Status","Due","Mandatory"]).map(h=><th scope="col" key={h}>{h}</th>)}</tr></thead><tbody>
        {tab==="staff"?report.staffRows.map(r=><tr key={r.person.id}><th scope="row">{r.person.full_name}</th><td>{r.person.department||"—"}</td><td>{r.courses}</td><td>{r.hours.toFixed(1)}</td><td>{r.required?r.current+" / "+r.required:"Not applicable"}</td><td>{r.missing}</td><td>{r.overdue}</td></tr>):null}
        {tab==="completions"?report.completionRows.map(r=><tr key={r.person.id+r.course.id}><th scope="row">{r.person.full_name}</th><td>{r.person.department||"—"}</td><td>{r.course.title}</td><td>{r.day}</td><td>{r.course.duration}</td></tr>):null}
        {tab==="requirements"?requirements.map(r=><tr key={r.person.id+r.requirement.id}><th scope="row">{r.person.full_name}</th><td>{r.person.department||"—"}</td><td>{r.requirement.title}</td><td>{r.status}</td><td>{r.completed||"—"}</td><td>{r.expires||"No expiry"}</td><td>{r.source}</td></tr>):null}
        {tab==="pathways"?report.pathwayRows.map(r=><tr key={r.person.id+r.pathway.id}><th scope="row">{r.person.full_name}</th><td>{r.person.department||"—"}</td><td>{r.pathway.title}</td><td>{r.completed} / {r.steps.length}</td><td>{r.next?.course.title||"All complete"}</td></tr>):null}
        {tab==="assignments"?report.assignmentRows.map(r=><tr key={r.assignment.id}><th scope="row">{r.person.full_name}</th><td>{r.person.department||"—"}</td><td>{r.assignment.title_snapshot}</td><td>{r.status}</td><td>{r.assignment.due_date||"Not set"}</td><td>{r.assignment.mandatory?"Yes":"No"}</td></tr>):null}
      </tbody></table></div><p>{tab==="completions"&&!report.completionRows.length?"No dated catalogue completions match this period.":tab==="requirements"&&!requirements.length?"No mandatory requirements match this view.":tab==="assignments"&&!report.assignmentRows.length?"No active assignments match this view.":""}</p>
    </section><footer className="reportScope">Exports contain staff personal data. Store and share them through your school's approved channels. Generated from the school-scoped snapshot at {snapshot.generated_at}.</footer></main>;
}
