"use client";

import { useState } from 'react';
import resources from '@/lib/senResources.json';
import { due, interventionSummary, monthsOld, readingChange, strandMean, today, validateCase, type SenCase, type Intervention, type EalAssessment } from '@/lib/senWorkspace';

type Field = {key:string;label:string;type?:'textarea'|'date'|'number'|'select';options?:string[];required?:boolean;min?:number;max?:number;value?:string};
function EntryForm({title,fields,add,disabled}:{title:string;fields:Field[];add:(values:Record<string,string>)=>boolean;disabled:boolean}) {
  return <details className="senEntry"><summary>{title}</summary><form onSubmit={e=>{e.preventDefault();const form=e.currentTarget;const values=Object.fromEntries(new FormData(form).entries()) as Record<string,string>;if(add(values))form.reset();}}><fieldset disabled={disabled}><legend>{title}</legend><div className="senFormGrid">{fields.map(f=><label key={f.key}>{f.label}{f.type==='textarea'?<textarea name={f.key} required={f.required} maxLength={5000}/>:f.type==='select'?<select name={f.key} required={f.required} defaultValue={f.value||''}><option value="">Choose…</option>{f.options?.map(o=><option key={o}>{o}</option>)}</select>:<input name={f.key} type={f.type||'text'} required={f.required} min={f.min} max={f.max} maxLength={500} defaultValue={f.value??(f.type==='date'?today():undefined)} step={f.type==='number'?'any':undefined}/>}</label>)}</div><button type="submit">Add to pupil draft</button><p>Then use Save pupil record to store the changes. Demonstration changes are never stored.</p></fieldset></form></details>;
}
const text=(key:string,label:string,required=false):Field=>({key,label,required,type:'textarea'});
const date=(key:string,label:string):Field=>({key,label,type:'date',required:true});
const number=(key:string,label:string,min:number,max:number,value?:string):Field=>({key,label,type:'number',required:true,min,max,value});
const select=(key:string,label:string,options:string[]):Field=>({key,label,type:'select',required:true,options});
const id=()=>crypto.randomUUID();
export default function SenCasePanels({section,pupil,update,disabled}:{section:string;pupil:SenCase;update:(p:SenCase)=>void;disabled:boolean}) {
  const [error,setError]=useState(''),[task,setTask]=useState<keyof typeof resources.eal.tasks>('community');
  function commit(next:SenCase){const errors=validateCase(next);if(errors.length){setError(errors.join(' '));return false;}update(next);setError('');return true;}
  const assessmentForm = (form:HTMLFormElement)=>{const values=Object.fromEntries(new FormData(form).entries()) as Record<string,string>;
    const scores=Object.fromEntries(Object.keys(resources.eal.strands).map(key=>[key,Array.from({length:5},(_,index)=>values[`${key}-${index}`]?Number(values[`${key}-${index}`]):null)]));
    const assessment:EalAssessment={id:id(),date:values.date,assessor:values.assessor,task,band:values.band,confidence:values.confidence,scores,evidence:values.evidence,adjustments:values.adjustments,nextSteps:values.nextSteps};
    if(commit({...pupil,assessments:[...pupil.assessments,assessment]}))form.reset();
  };
  return <div className="senPanels">{error&&<p role="alert" className="senNotice">{error}</p>}
    {section==='register'&&<><details className="senCard"><summary>Printable pupil passport</summary><p>Print only the agreed classroom-support summary. Check accuracy and share through your approved school channels; printing may save a local PDF. Unsaved changes are included.</p><button onClick={()=>window.print()}>Print support passport</button><article className="senPassport"><h2>Pupil support passport</h2><h3>{pupil.name||'Pupil name not recorded'} · {pupil.year}</h3><p>Reference: {pupil.reference} · Review: {pupil.plan.reviewDate||'Not set'}</p>{Object.entries({'Strengths & interests':pupil.strengths,'What the pupil says':pupil.plan.pupilVoice,'Classroom adjustments':pupil.plan.adjustments,'Current outcome':pupil.plan.outcome,'Help and regulation':pupil.checkIns.at(-1)?.strategy||'Agree a discreet help signal and preferred support.','Transition support':pupil.plan.transition,'Named lead':pupil.plan.owner}).map(([k,v])=><section key={k}><h4>{k}</h4><p>{v||'Not recorded'}</p></section>)}</article></details>
      <article className="senCard"><h3>Family, pupil voice & professional contact</h3><p>Record a concise school-approved summary, not contact details or safeguarding narratives. This does not send messages.</p><EntryForm title="Record a conversation / meeting" disabled={disabled} fields={[date('date','Date'),select('type','Contact type',['Pupil voice','Family discussion','Professional advice','Transition meeting','SEN review meeting']),{key:'participants',label:'Participants / roles'},text('summary','Agreed summary',true),text('actions','Actions and owner')]} add={v=>commit({...pupil,contacts:[...pupil.contacts,{id:id(),date:v.date,type:v.type,participants:v.participants,summary:v.summary,actions:v.actions}]})}/>{[...pupil.contacts].sort((a,b)=>b.date.localeCompare(a.date)).map(c=><details key={c.id}><summary>{c.date} · {c.type}</summary><p>{c.participants}</p><p>{c.summary}</p><p>Actions: {c.actions||'Not recorded'}</p></details>)}</article></>}
    {section==='interventions'&&<><article className="senCard"><h3>Plan targeted provision</h3><p>Baseline → Goal → Deliver → Evidence → Review → Continue, adjust, fade or close. An outcome score is a locally defined observation, not a diagnostic assessment.</p><EntryForm title="Add an intervention / staff allocation" disabled={disabled} fields={[{key:'title',label:'Intervention title',required:true},{key:'owner',label:'Named lead / delivery staff',required:true},text('baseline','Observable baseline'),text('goal','Measurable outcome',true),text('measure','Success measure / meaning of the 0–4 outcome scale'),select('strategy','Agreed strategy',resources.strategies.map(s=>s.name)),{key:'frequency',label:'Delivery routine / location'},number('minutes','Minutes per session',1,480,'15'),number('weeklySessions','Sessions per week',1,35,'2'),number('hourlyCost','Estimated hourly staff cost (£)',0,1000,'0'),date('startDate','Start date'),date('reviewDate','Review date')]} add={v=>commit({...pupil,interventions:[...pupil.interventions,{id:id(),title:v.title,owner:v.owner,baseline:v.baseline,goal:v.goal,measure:v.measure,strategy:v.strategy,frequency:v.frequency,minutes:Number(v.minutes),weeklySessions:Number(v.weeklySessions),hourlyCost:Number(v.hourlyCost),startDate:v.startDate,reviewDate:v.reviewDate,status:'Active',sessions:[]}]})}/></article>
      {pupil.interventions.map(i=>{const stats=interventionSummary(i);return <article key={i.id} className="senCard"><div className="senActions"><h3>{i.title}</h3><span className="senTag">{i.status} · {due(i.reviewDate)}</span></div><p><strong>Lead:</strong> {i.owner} · {i.minutes} min × {i.weeklySessions}/week · Review {i.reviewDate}</p><p><strong>Baseline:</strong> {i.baseline||'Not recorded'}</p><p><strong>Goal:</strong> {i.goal}</p><p><strong>Measure:</strong> {i.measure||'Define the scale before recording outcomes.'}</p><p><strong>Delivery:</strong> {i.strategy} · {i.frequency}</p><div className="senStats"><article><strong>{stats.count}</strong><span>Recorded sessions</span></article><article><strong>{stats.change===null?'—':`${stats.change>0?'+':''}${stats.change}`}</strong><span>First-to-latest outcome change /4</span></article><article><strong>{stats.fidelity===null?'—':`${stats.fidelity}%`}</strong><span>Mean recorded fidelity</span></article></div><p>{stats.count<2?'Collect comparable observations before drawing conclusions.':'Discuss progress alongside delivery consistency, context and pupil feedback. Scores do not determine review decisions automatically.'}</p>
        <label>Review decision / intervention status<select disabled={disabled} value={i.status} onChange={e=>update({...pupil,interventions:pupil.interventions.map(x=>x.id===i.id?{...x,status:e.target.value as Intervention['status']}:x)})}>{['Active','Adjust','Fade','Closed'].map(s=><option key={s}>{s}</option>)}</select></label>
        <EntryForm title="Record delivery & session evidence" disabled={disabled||i.status==='Closed'} fields={[date('date','Session date'),number('minutes','Actual delivered minutes',0,480,String(i.minutes)),number('outcome','Outcome observation (0–4)',0,4),number('fidelity','Agreed provision delivered (%)',0,100),{key:'usefulness',label:'Pupil usefulness (optional, 0–4)',type:'number',min:0,max:4},text('evidence','Concrete evidence, context and adaptations',true)]} add={v=>commit({...pupil,interventions:pupil.interventions.map(x=>x.id===i.id?{...x,sessions:[...x.sessions,{id:id(),date:v.date,minutes:Number(v.minutes),outcome:Number(v.outcome),fidelity:Number(v.fidelity),usefulness:v.usefulness===''?null:Number(v.usefulness),evidence:v.evidence}]}:x)})}/>
        {[...i.sessions].sort((a,b)=>b.date.localeCompare(a.date)).map(s=><details key={s.id}><summary>{s.date} · {s.minutes} min · Outcome {s.outcome}/4 · Delivery {s.fidelity}%</summary><p>{s.evidence}</p><p>Pupil usefulness: {s.usefulness===null?'Not recorded':`${s.usefulness}/4`}</p></details>)}</article>;})}
      <article className="senCard"><h3>Support-plan / EHCP review coordination</h3><p>Track dates agreed by your school. This is not a statutory case-management, EHCP decision or safeguarding system. Check requirements with your SENCO and local authority.</p><EntryForm title="Record a review & next steps" disabled={disabled} fields={[date('date','Review held on'),{key:'attendees',label:'Attendees / roles'},text('evidence','Evidence compared with baseline',true),text('pupilVoice','Pupil view'),text('familyVoice','Family view'),select('decision','Agreed decision',['Continue','Adjust','Fade','Close','Seek professional advice']),text('actions','Actions, owner and deadline',true),date('nextDate','Next review')]} add={v=>commit({...pupil,plan:{...pupil.plan,reviewDate:v.nextDate},reviews:[...pupil.reviews,{id:id(),date:v.date,attendees:v.attendees,evidence:v.evidence,pupilVoice:v.pupilVoice,familyVoice:v.familyVoice,decision:v.decision,actions:v.actions,nextDate:v.nextDate}]})}/>{[...pupil.reviews].sort((a,b)=>b.date.localeCompare(a.date)).map(r=><details key={r.id}><summary>{r.date} · {r.decision} · Next {r.nextDate}</summary><p>Attendees: {r.attendees}</p><p>{r.evidence}</p><p>Pupil: {r.pupilVoice||'Not recorded'} · Family: {r.familyVoice||'Not recorded'}</p><p>Actions: {r.actions}</p></details>)}</article></>}
    {section==='eal'&&<><article className="senCard"><h3>Language assessment centre</h3><p>Original school assessment materials from your EAL repository, not an official or standardised Bell Foundation test. Use age-appropriate tasks and record adjustments. EAL is not, by itself, SEN.</p><label>Choose original task set<select value={task} onChange={e=>setTask(e.target.value as keyof typeof resources.eal.tasks)}>{Object.entries(resources.eal.tasks).map(([key,pack])=><option key={key} value={key}>{pack.name}</option>)}</select></label>{Object.entries(resources.eal.strands).map(([key,strand])=><details key={key}><summary>{strand.label} · task materials</summary><p>{resources.eal.tasks[task][key as 'listening'|'speaking'|'reading'|'writing']}</p></details>)}
      <details className="senEntry"><summary>Record a language assessment — 20 criteria</summary><form onSubmit={e=>{e.preventDefault();assessmentForm(e.currentTarget);}}><fieldset disabled={disabled}><legend>EAL assessment</legend><div className="senFormGrid"><label>Assessment date<input name="date" type="date" required defaultValue={today()}/></label><label>Assessor<input name="assessor" required maxLength={250}/></label></div>{Object.entries(resources.eal.strands).map(([key,strand])=><details key={key} open><summary>{strand.label}</summary>{strand.criteria.map((criterion,index)=><label key={criterion.name}>{criterion.name}<small>{criterion.detail}</small><select name={`${key}-${index}`} defaultValue=""><option value="">Not observed — no score</option>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n} — {['A · New to English','B · Early acquisition','C · Developing competence','D · Competent','E · Fluent'][n-1]}</option>)}</select><small>Possible next step: {criterion.next}</small></label>)}</details>)}<label>Teacher-confirmed best-fit band<select name="band" required defaultValue=""><option value="">Use evidence and professional judgement</option>{['A','B','C','D','E'].map(b=><option key={b}>{b}</option>)}</select></label><label>Evidence confidence<select name="confidence" required><option>Provisional — one context</option><option>Developing — two contexts</option><option>Secure — repeated evidence</option></select></label><label>Evidence and language-background context<textarea name="evidence" required maxLength={5000}/></label><label>Adjustments / support used<textarea name="adjustments" maxLength={3000}/></label><label>Agreed language targets<textarea name="nextSteps" maxLength={3000}/></label><button>Add assessment to pupil draft</button></fieldset></form></details>
      {[...pupil.assessments].sort((a,b)=>b.date.localeCompare(a.date)).map(a=><details key={a.id}><summary>{a.date} · Confirmed band {a.band} · {a.confidence}</summary><p>Assessor: {a.assessor}</p><p>{a.evidence}</p><p>Support used: {a.adjustments||'Not recorded'}</p><p>Targets: {a.nextSteps||'Not recorded'}</p>{Object.entries(a.scores).map(([key,s])=><p key={key}>{key}: {s.filter(n=>n!==null).length}/5 observed · mean {strandMean(s)?.toFixed(1)||'—'} (descriptive only)</p>)}</details>)}</article>
      <article className="senCard"><h3>Reading-age history</h3><p>Compare like-for-like tools. Reading age alone does not establish SEN or language proficiency. Record confidence and testing adjustments.</p><EntryForm title="Add a reading assessment" disabled={disabled} fields={[date('date','Assessment date'),{key:'tool',label:'Assessment tool / edition',required:true},number('ageMonths','Reading age in total months (e.g. 10 years 6 months = 126)',12,300),text('notes','Evidence, confidence and adjustments')]} add={v=>commit({...pupil,reading:[...pupil.reading,{id:id(),date:v.date,tool:v.tool,ageMonths:Number(v.ageMonths),notes:v.notes}]})}/>{(()=>{const change=readingChange(pupil.reading);return <p>{change?`Recorded reading-age change: ${change.gain>0?'+':''}${change.gain} months across ${change.elapsedMonths.toFixed(1)} elapsed months. Interpret alongside test reliability and classroom evidence.`:'A change is shown only for two different dates using the same named tool / edition.'}</p>;})()}{[...pupil.reading].sort((a,b)=>b.date.localeCompare(a.date)).map(r=>{const age=monthsOld(pupil.dob,r.date);return <details key={r.id}><summary>{r.date} · {r.tool} · Reading age {Math.floor(r.ageMonths/12)}y {r.ageMonths%12}m</summary><p>Chronological age: {age===null?'Not available':`${Math.floor(age/12)}y ${age%12}m`} · {age===null?'No comparison':`Reading-age difference: ${r.ageMonths-age} months`}</p><p>{r.notes}</p></details>;})}</article></>}
    {section==='regulation'&&<><article className="senCard"><h3>Check in → choose support → check out</h3><p>All states are valid. These are private descriptions, not rewards, behaviour scores or diagnoses. Use the pupil’s agreed support plan. Safety and safeguarding procedures take priority.</p><EntryForm title="Record a supported regulation check-in" disabled={disabled} fields={[date('date','Date'),select('before','Before — pupil-described state',['Lower energy','Calm / ready','Higher energy','Very intense energy','Prefer not to say']),text('signals','Body signals, context and pupil voice'),select('strategy','Agreed support',resources.strategies.map(s=>s.name)),select('after','After — pupil-described state',['Lower energy','Calm / ready','Higher energy','Very intense energy','Prefer not to say']),number('usefulness','Pupil-rated usefulness (0–4)',0,4),text('nextStep','Agreed next step / return to learning',true)]} add={v=>commit({...pupil,checkIns:[...pupil.checkIns,{id:id(),date:v.date,before:v.before,after:v.after,signals:v.signals,strategy:v.strategy,usefulness:Number(v.usefulness),nextStep:v.nextStep}]})}/>{[...pupil.checkIns].sort((a,b)=>b.date.localeCompare(a.date)).map(c=><details key={c.id}><summary>{c.date} · {c.strategy} · Usefulness {c.usefulness}/4</summary><p>{c.before} → {c.after}</p><p>{c.signals}</p><p>Next: {c.nextStep}</p></details>)}</article><article className="senCard"><h3>Strategy feedback</h3>{resources.strategies.flatMap(s=>{const entries=pupil.checkIns.filter(c=>c.strategy===s.name);return entries.length?[<p key={s.id}><strong>{s.name}</strong> · {entries.length} observations · pupil usefulness {(entries.reduce((n,c)=>n+c.usefulness,0)/entries.length).toFixed(1)}/4</p>]:[];})}<p>Small samples are descriptive only. Ask the pupil what helped, and check context rather than choosing a strategy automatically.</p></article></>}
  </div>;
}
