"use client";
import { useState } from 'react';
import Link from 'next/link';
import resources from '@/lib/senResources.json';

export default function SenToolkit(){
  const [search,setSearch]=useState(''),[transition,setTransition]=useState<keyof typeof resources.operations.transitions>('lesson'),[checked,setChecked]=useState<string[]>([]),[language,setLanguage]=useState<keyof typeof resources.languages>('en'),[room,setRoom]=useState<keyof typeof resources.operations.roomTypes>('classroom'),[audit,setAudit]=useState<Record<string,string>>({}),[notes,setNotes]=useState('');
  const transitionPlan=resources.operations.transitions[transition], phrase=resources.languages[language];
  return <div className="senToolkit"><h2>Staff toolkit</h2><p>Practical resources from your Zones and EAL repositories. These tools do not save information. Keep pupil names out of free-text notes here.</p>
    <article className="senCard"><h3>Find an accessible support strategy</h3><label>Search by need, strategy or setting<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Try overload, movement, task or rehearsal"/></label><div className="senGrid">{resources.strategies.filter(s=>`${s.name} ${s.need} ${s.place} ${s.instruction}`.toLowerCase().includes(search.toLowerCase())).map(s=><details key={s.id}><summary>{s.name} · {s.time}</summary><p><strong>Need:</strong> {s.need} · {s.place}</p><p>{s.instruction}</p><p>Offer choice and use agreed adjustments. Stop if uncomfortable; this is not treatment.</p></details>)}</div></article>
    <details className="senCard"><summary>Transitions, trips & assessment planning</summary><label>Transition context<select value={transition} onChange={e=>{setTransition(e.target.value as typeof transition);setChecked([]);}}>{Object.entries(resources.operations.transitions).map(([key,t])=><option key={key} value={key}>{t.name}</option>)}</select></label>{transitionPlan.supports.map(s=><label className="senCheck" key={s}><input type="checkbox" checked={checked.includes(s)} onChange={e=>setChecked(e.target.checked?[...checked,s]:checked.filter(x=>x!==s))}/>{s}</label>)}<p>{checked.length}/{transitionPlan.supports.length} supports prepared. Agree a named adult and review after the transition.</p><h4>Off-site readiness</h4><ul>{resources.operations.tripChecks.map(s=><li key={s}>{s}</li>)}</ul><h4>Assessment preparation</h4>{resources.operations.assessmentRoutines.map(s=><details key={s.id}><summary>{s.name}</summary><ol>{s.steps.map(step=><li key={step}>{step}</li>)}</ol></details>)}<p>Exam access arrangements must follow your school’s formal process; this checklist does not approve them.</p></details>
    <details className="senCard"><summary>Environment audit & classroom action plan</summary><label>Setting<select value={room} onChange={e=>setRoom(e.target.value as typeof room)}>{Object.keys(resources.operations.roomTypes).map(key=><option key={key}>{key}</option>)}</select></label><ul>{resources.operations.roomTypes[room].map(s=><li key={s}>{s}</li>)}</ul>{resources.operations.environmentCriteria.map(([key,label])=><label key={key}>{label}<select value={audit[key]||''} onChange={e=>setAudit({...audit,[key]:e.target.value})}><option value="">Not reviewed</option><option>Support in place</option><option>Needs adjustment</option><option>Follow-up required</option></select></label>)}<label>Agreed actions, staff owner and review date (no pupil identifiers)<textarea value={notes} maxLength={3000} onChange={e=>setNotes(e.target.value)}/></label><p>{Object.values(audit).filter(Boolean).length}/{resources.operations.environmentCriteria.length} areas reviewed. Notes and ratings are temporary, not a saved school audit.</p></details>
    <details className="senCard"><summary>Teacher language coach</summary><p>Maintain safe boundaries while reducing processing demands. Use the pupil’s preferred communication method.</p>{resources.languageCoach.map(s=><article key={s.situation}><h4>{s.situation}</h4><p>Instead of: {s.avoid}</p><p><strong>Try:</strong> {s.use}</p><p>{s.why}</p></article>)}</details>
    <details className="senCard"><summary>Multilingual help & regulation cards</summary><p>Phrase cards from your Zones repository. Check wording with the pupil or an appropriate language professional; they are not a substitute for interpretation.</p><label>Language<select value={language} onChange={e=>setLanguage(e.target.value as typeof language)}>{Object.entries(resources.languages).map(([key,l])=><option key={key} value={key}>{l.name}</option>)}</select></label><div lang={language} dir={language==='ar'?'rtl':'ltr'} className="senPhraseCards">{Object.entries(phrase).filter(([k])=>k!=='name').map(([key,value])=><p key={key}>{value}</p>)}</div></details>
    <details className="senCard"><summary>Tutor activities & pupil voice</summary><div className="senGrid">{resources.activities.map(a=><article key={a.name}><h4>{a.name} · {a.time}</h4><p>{a.phase} · {a.setting}</p><p>{a.steps}</p></article>)}</div><h4>Pupil voice prompts</h4><ul>{resources.operations.voiceQuestions.map(s=><li key={s}>{s}</li>)}</ul><p>Offer accessible alternatives to spoken or written responses. A pupil can decline to answer; do not turn these prompts into a behaviour score.</p></details>
    <details className="senCard"><summary>New-arrival EAL checklist & classroom scaffolds</summary><ol><li>Agree communication with the pupil and family, including interpretation if needed.</li><li>Record languages, prior schooling, strengths and literacy in home languages.</li><li>Orient the pupil to routines, safe help routes and a trusted adult.</li><li>Gather a baseline across listening, speaking, reading and writing without assuming limited English means limited understanding.</li><li>Use visuals, models, partner rehearsal, vocabulary previews and sentence frames while maintaining curriculum challenge.</li><li>Agree language targets and a review date. Check classroom participation as well as assessment performance.</li></ol><h4>Subject-language planning</h4><p>Choose essential vocabulary, model an explanation, make instructions visible and allow oral rehearsal before writing. Check meaning rather than asking only “Do you understand?”.</p><Link href="/send-eal">Open subject and need-specific classroom guidance →</Link></details>
    <details className="senCard"><summary>Department implementation, training & guidance</summary><h4>Review implementation, not pupil rankings</h4><ul>{resources.operations.fidelityAreas.map(s=><li key={s}>{s}</li>)}</ul><h4>Observation prompts</h4><ul>{resources.operations.observationItems.map(s=><li key={s}>{s}</li>)}</ul><div className="senActions"><Link href="/micro-cpd">Short staff refreshers</Link><Link href="/">Full CPD library</Link><Link href="/school-reporting">School CPD reporting</Link></div><p><a href="https://www.gov.uk/government/publications/send-code-of-practice-0-to-25" target="_blank" rel="noreferrer">SEND Code of Practice (England)</a> · Check local school policy and jurisdiction. Dates entered here are reminders, not verified statutory deadlines.</p><p>This is an independent adaptation of your school’s original Zones and EAL tools, not an official Zones of Regulation product or licensed Bell Foundation assessment.</p></details>
  </div>;
}
