"use client";

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { getSupabaseBrowserClient } from '@/lib/supabase';
import { resolveStaffAccess } from '@/lib/rolePermissions';
import resources from '@/lib/senResources.json';
import { demoCases, due, interventionSummary, needAreas, newCase, planGaps, senStatuses, today, validateCase, type CaseRow, type SenCase } from '@/lib/senWorkspace';
import SenCasePanels from './SenCasePanels';
import SenToolkit from './SenToolkit';
import './SenWorkspace.css';

const sections = [{id:'overview',label:'Department overview',hint:'Priorities and provision'}, {id:'register',label:'Pupils & support plans',hint:'Register, referrals and passports'}, {id:'interventions',label:'Provision & reviews',hint:'Delivery, evidence and impact'}, {id:'eal',label:'EAL & reading',hint:'Language assessment and progress'}, {id:'regulation',label:'Regulation support',hint:'Check-in, strategy, check-out'}, {id:'toolkit',label:'Staff toolkit',hint:'Transitions, environments and resources'}];
type Mode = 'loading'|'unavailable'|'live'|'demo';
export default function SenWorkspace() {
  const [mode,setMode]=useState<Mode>('loading'), [org,setOrg]=useState<string|null>(null), [rows,setRows]=useState<CaseRow[]>([]), [section,setSection]=useState('overview');
  const [selected,setSelected]=useState<CaseRow|null>(null), [draft,setDraft]=useState<SenCase|null>(null), [dirty,setDirty]=useState(false), [busy,setBusy]=useState(false), [message,setMessage]=useState(''), [query,setQuery]=useState(''), [filter,setFilter]=useState('All'), [archived,setArchived]=useState(false);
  useEffect(()=>{ let active=true; const client=getSupabaseBrowserClient();
    const load=async()=>{try{
      const {data:{user}}=await client.auth.getUser(); if(!user){if(active)setMode('unavailable');return;}
      const access=await resolveStaffAccess(client,user); if(!active)return; setOrg(access.organizationId);
      if(!access.organizationId){setMode('unavailable');return;}
      // The RPC checks canonical membership, SEN role and school activation in the database.
      // Neither a role selector nor preferred_organization_id authorises pupil records.
      const {data:allowed,error}=await client.rpc('sen_workspace_access',{org_id:access.organizationId});
      if(!active)return; if(error||allowed!==true){setMode('unavailable');return;}
      const result=await client.from('sen_department_cases').select('id,organization_id,body,version,archived_at,updated_at').eq('organization_id',access.organizationId).order('id').limit(1000);
      if(!active)return; if(result.error){setMode('unavailable');return;} setRows((result.data||[]) as CaseRow[]);setMode('live');
    }catch{if(active)setMode('unavailable');}};void load();
    const {data:{subscription}}=client.auth.onAuthStateChange((event)=>{if(event==='SIGNED_OUT'){setRows([]);setDraft(null);setSelected(null);setMode('unavailable');setDirty(false);}});
    return()=>{active=false;subscription.unsubscribe();}; },[]);
  useEffect(()=>{const listener=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',listener);return()=>window.removeEventListener('beforeunload',listener);},[dirty]);
  const canEdit=(mode==='live'||mode==='demo')&&!selected?.archived_at;
  function discard() { return !dirty||window.confirm('Discard the unsaved changes to this pupil?'); }
  function choose(row:CaseRow) {if(busy||!discard())return;setSelected(row);setDraft(structuredClone(row.body));setDirty(false);setMessage('');}
  function change(next:SenCase){setDraft(next);setDirty(true);setMessage('');}
  function startDemo(){if(busy||!discard())return;setRows(demoCases());setSelected(null);setDraft(null);setMode('demo');setDirty(false);setMessage('Fictional demonstration only. Changes stay in memory and disappear on reload. Do not enter real pupil information.');}
  function create(){if(!canEdit||busy||!discard())return;setSelected(null);setDraft(newCase());setDirty(false);setSection('register');setMessage('');}
  async function save(){if(!draft||!canEdit||busy)return;const errors=validateCase(draft);if(errors.length){setMessage(errors.join(' '));return;}setBusy(true);setMessage('');
    try{let row:CaseRow;
      if(mode==='demo'){row={id:selected?.id||crypto.randomUUID(),organization_id:'demo',body:structuredClone(draft),version:(selected?.version||0)+1,archived_at:null,updated_at:new Date().toISOString()};}
      else {if(!org)throw new Error('No authorised school selected.');const client=getSupabaseBrowserClient();const result=selected?await client.from('sen_department_cases').update({body:draft}).eq('id',selected.id).eq('organization_id',org).eq('version',selected.version).select('id,organization_id,body,version,archived_at,updated_at').single():await client.from('sen_department_cases').insert({organization_id:org,body:draft}).select('id,organization_id,body,version,archived_at,updated_at').single();
        if(result.error||!result.data)throw new Error('Not saved. Access may have changed, or someone else edited this record. Reload before trying again; keep a copy of your unsaved notes in your approved school system.');row=result.data as CaseRow;}
      setRows(old=>selected?old.map(r=>r.id===row.id?row:r):[row,...old]);setSelected(row);setDraft(structuredClone(row.body));setDirty(false);setMessage(mode==='demo'?'Updated the fictional demonstration; nothing was stored.':'Saved to your school’s restricted SEN workspace.');
    }catch(e){setMessage(e instanceof Error?e.message:'Unable to save.');}finally{setBusy(false);}}
  async function toggleArchive(){if(!selected||busy||!discard()||!window.confirm(selected.archived_at?'Restore this pupil record?':'Archive this pupil record? It will remain recoverable for authorised SEN staff.'))return;setBusy(true);
    try{let row:CaseRow={...selected,archived_at:selected.archived_at?null:new Date().toISOString(),version:selected.version+1};
      if(mode==='live'){const result=await getSupabaseBrowserClient().from('sen_department_cases').update({archived_at:row.archived_at}).eq('id',selected.id).eq('organization_id',org!).eq('version',selected.version).select('id,organization_id,body,version,archived_at,updated_at').single();if(result.error||!result.data)throw new Error('Archive change not saved. Reload and check your access.');row=result.data as CaseRow;}
      setRows(old=>old.map(r=>r.id===row.id?row:r));setSelected(row);setDraft(structuredClone(row.body));setDirty(false);setMessage(row.archived_at?'Record archived; it can be restored.':'Record restored.');
    }catch(e){setMessage(e instanceof Error?e.message:'Unable to archive.');}finally{setBusy(false);}}
  const active=rows.filter(r=>!r.archived_at), listed=rows.filter(r=>Boolean(r.archived_at)===archived&&(filter==='All'||r.body.status===filter)&&`${r.body.name} ${r.body.reference} ${r.body.year} ${r.body.className} ${r.body.languages} ${r.body.needs.join(' ')}`.toLowerCase().includes(query.toLowerCase()));
  const actions=active.flatMap(r=>[{row:r,date:r.body.plan.reviewDate,title:'Support plan review'},...(r.body.status==='EHCP'?[{row:r,date:r.body.plan.ehcpReviewDate,title:'EHCP review coordination'}]:[]),...r.body.interventions.filter(i=>i.status!=='Closed').map(i=>({row:r,date:i.reviewDate,title:i.title}))]).filter(a=>['Overdue','Due soon'].includes(due(a.date))).sort((a,b)=>a.date.localeCompare(b.date));
  const allProvision=active.flatMap(r=>r.body.interventions.filter(i=>i.status!=='Closed').map(i=>({row:r,i,summary:interventionSummary(i)})));
  return <main className="senWorkspace">
    <header className="senHeading"><div><p className="senEyebrow">INCLUSION · ONE CONNECTED WORKSPACE</p><h1>SEN department</h1><p>Understand needs. Plan support. Review what helps.</p></div><Link href="/students">Student support home →</Link></header>
    <div className={`senNotice ${mode==='demo'?'senDemo':''}`} role="status">{mode==='loading'?'Checking school access…':mode==='live'?'Restricted pupil records · authorised SEND/EAL and SLT staff only':mode==='demo'?'DEMONSTRATION · fictional pupils only · no saving to a device or database':'Live pupil records are not available for this account or school. Database setup and authorised access are required. Staff tools work without pupil records.'} {mode!=='demo'&&mode!=='loading'&&<button onClick={startDemo}>Try fictional demo</button>}{mode==='demo'&&<button onClick={()=>window.location.reload()}>Exit demo & clear changes</button>}</div>
    <div className="senLayout"><nav aria-label="SEN workspace" className="senNav">{sections.map(s=><button key={s.id} aria-current={section===s.id?'page':undefined} onClick={()=>setSection(s.id)}><strong>{s.label}</strong><span>{s.hint}</span></button>)}<details><summary>Guidance & existing tools</summary><Link href="/send-eal">Inclusive classroom guidance</Link><Link href="/regulation-behaviour">Regulation hub</Link><Link href="/interventions">Existing intervention tracker</Link><Link href="/subject-cpd">Staff development</Link></details></nav>
    <section className="senContent" aria-label={sections.find(s=>s.id===section)?.label}>
      {message&&<p className="senNotice" role="status">{message}</p>}
      {section==='overview'&&<><h2>Your department at a glance</h2><p>SEN and EAL are separate needs: learning English alone does not identify a pupil as having SEN. This workspace supports professional judgement, not diagnosis or statutory decisions.</p><div className="senStats"><article><strong>{active.length}</strong><span>Active pupils loaded</span></article><article><strong>{actions.length}</strong><span>Reviews due within 14 days</span></article><article><strong>{allProvision.length}</strong><span>Open interventions</span></article><article><strong>{allProvision.reduce((n,x)=>n+x.summary.weeklyMinutes,0)}</strong><span>Planned weekly staff minutes</span></article></div>
        <div className="senGrid"><article className="senCard"><h3>What needs attention</h3>{actions.length?actions.slice(0,12).map((a,index)=><button className="senListItem" key={`${a.row.id}-${index}`} onClick={()=>{choose(a.row);setSection('interventions');}}><span><strong>{a.row.body.name}</strong><small>{a.title} · {a.date}</small></span><span className="senTag">{due(a.date)}</span></button>):<p>No due reviews in the loaded records. Add a review date to each support plan.</p>}</article><article className="senCard"><h3>Start with the pupil</h3><ol><li>Record strengths, barriers and pupil/family voice.</li><li>Agree a measurable outcome and classroom adjustments.</li><li>Plan provision, staff responsibility and review date.</li><li>Record delivery and compare evidence at review.</li></ol><button onClick={()=>setSection('register')}>Open pupil register</button><button onClick={()=>setSection('toolkit')}>Explore staff tools</button><p>Follow your school’s safeguarding system for concerns or emergencies. Do not record safeguarding narratives here.</p></article></div>
        <article className="senCard"><h3>Provision map</h3><p>Planned costs are estimates, not actual expenditure. Totals cover loaded active records only.</p><div className="senTableWrap"><table><thead><tr><th>Pupil / intervention</th><th>Lead</th><th>Weekly minutes</th><th>Weekly estimate</th><th>Review</th></tr></thead><tbody>{allProvision.map(({row,i,summary})=><tr key={i.id}><td><button onClick={()=>{choose(row);setSection('interventions');}}>{row.body.name} · {i.title}</button></td><td>{i.owner}</td><td>{summary.weeklyMinutes}</td><td>£{summary.weeklyCost.toFixed(2)}</td><td>{i.reviewDate||'Not set'}</td></tr>)}</tbody></table></div>{!allProvision.length&&<p>No open provision recorded.</p>}</article></>}
      {section==='toolkit'&&<SenToolkit/>}
      {['register','interventions','eal','regulation'].includes(section)&&<><div className="senActions"><h2>{sections.find(s=>s.id===section)?.label}</h2>{(mode==='live'||mode==='demo')&&<button disabled={busy} onClick={()=>{if(selected?.archived_at){if(!discard())return;setSelected(null);setDraft(newCase());setDirty(false);setSection('register');}else create();}}>Add pupil / referral</button>}</div>
        <div className="senRecordLayout"><aside className="senRegister"><label>Find a pupil<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name, reference, year or language"/></label><label>SEN status<select value={filter} onChange={e=>setFilter(e.target.value)}><option>All</option>{senStatuses.map(s=><option key={s}>{s}</option>)}</select></label><label className="senCheck"><input type="checkbox" checked={archived} onChange={e=>setArchived(e.target.checked)}/> Show archived records</label>{listed.map(r=><button key={r.id} aria-pressed={selected?.id===r.id} onClick={()=>choose(r)}><strong>{r.body.name}</strong><small>{r.body.reference} · {r.body.year}<br/>{r.body.status}</small></button>)}{!listed.length&&<p>No records to show. {mode==='unavailable'?'Use the fictional demo to explore these features.':'Add a pupil or change the filters.'}</p>}{rows.length===1000&&<p>First 1,000 records shown. Ask your administrator to review capacity before using reports.</p>}</aside>
          <div>{draft?<><div className="senRecordHeading"><div><h3>{draft.name||'New pupil / referral'}</h3><p>{selected?.archived_at?'Archived · read only':dirty?'Unsaved changes':selected?'Saved record':'Complete the pupil details, then save'} {mode==='demo'&&' · fictional demo'}</p></div><div className="senActions"><button disabled={!canEdit||busy||(!dirty&&Boolean(selected))} onClick={save}>{busy?'Saving…':mode==='demo'?'Update demo':'Save pupil record'}</button>{selected&&<button disabled={busy} onClick={toggleArchive}>{selected.archived_at?'Restore':'Archive'}</button>}</div></div>
            {section==='register'&&<fieldset disabled={!canEdit||busy}><legend>Pupil profile & graduated support</legend><div className="senFormGrid">{(['reference','name','year','className','languages','dob','arrival'] as const).map(k=><label key={k}>{({reference:'School-approved pupil reference',name:'Display name',year:'Year group',className:'Class / tutor group',languages:'Home languages & language background',dob:'Date of birth (optional)',arrival:'School arrival date (optional)'})[k]}<input type={['dob','arrival'].includes(k)?'date':'text'} maxLength={250} value={draft[k]} onChange={e=>change({...draft,[k]:e.target.value})}/></label>)}<label>SEN status<select value={draft.status} onChange={e=>change({...draft,status:e.target.value as SenCase['status']})}>{senStatuses.map(s=><option key={s}>{s}</option>)}</select></label></div><label>Strengths, interests & what works<textarea value={draft.strengths} maxLength={3000} onChange={e=>change({...draft,strengths:e.target.value})}/></label><div className="senChecks"><p>Areas of need (only where identified)</p>{needAreas.map(n=><label className="senCheck" key={n}><input type="checkbox" checked={draft.needs.includes(n)} onChange={e=>change({...draft,needs:e.target.checked?[...draft.needs,n]:draft.needs.filter(v=>v!==n)})}/>{n}</label>)}</div>
              <h3>Assess → Plan → Do → Review</h3><p>{planGaps(draft.plan).length?'Still to record: '+planGaps(draft.plan).join(', '):'Core support-plan fields completed. Review the quality of the evidence with the pupil and family.'}</p>{Object.entries({baseline:'Assess: observable baseline and barriers',outcome:'Plan: measurable pupil outcome',measure:'How success will be measured',adjustments:'Classroom adjustments and accessible instruction',provision:'Do: provision, frequency and staff allocation',owner:'Named lead / SENCO',reviewDate:'Next support-plan review',pupilVoice:'Pupil voice and preferred support',familyVoice:'Family voice and agreed communication',transition:'Transition and handover arrangements',externalAdvice:'Relevant professional advice — school-approved summary only',ehcpReviewDate:'EHCP review coordination date (where applicable)'}).map(([key,label])=><label key={key}>{label}{key.endsWith('Date')?<input type="date" value={draft.plan[key as keyof typeof draft.plan]} onChange={e=>change({...draft,plan:{...draft.plan,[key]:e.target.value}})}/>:<textarea maxLength={5000} value={draft.plan[key as keyof typeof draft.plan]} onChange={e=>change({...draft,plan:{...draft.plan,[key]:e.target.value}})}/>}</label>)}
            </fieldset>}
            <SenCasePanels section={section} pupil={draft} update={change} disabled={!canEdit||busy}/>
          </>:<article className="senCard"><h3>Choose a pupil to start</h3><p>Support plans, EAL assessments, regulation evidence and reviews connect to one pupil record. Restricted records are never copied into browser storage or external AI tools.</p></article>}</div>
        </div></>}
    </section></div>
  </main>;
}
