"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { authenticatedFetch } from "@/lib/authenticatedFetch";
import { getSupabaseBrowserClient } from "@/lib/supabase";

type Profile={id:string;full_name:string;role:string;organisation_id:string|null};
type Doc={id:string;title:string;category:string;summary:string;content:string;tags:string[]};
type Block={block_type:"text"|"quiz"|"scenario"|"poll"|"reflection"|"action_plan";title:string;content:Record<string,unknown>;required:boolean};
type Draft={title:string;summary:string;objectives:string[];recommended_for:string[];blocks:Block[]};

const categories=["Teaching & Learning","Safeguarding","SEND","Leadership","Wellbeing","Digital Teaching"];

export default function AiCourseBuilderPage(){
  const [profile,setProfile]=useState<Profile|null>(null);const [docs,setDocs]=useState<Doc[]>([]);const [selected,setSelected]=useState<string[]>([]);const [draft,setDraft]=useState<Draft|null>(null);const [meta,setMeta]=useState({category:"Teaching & Learning",duration:60,level:"Developing",topic:"",audience:"All teaching staff",notes:""});const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
  const canBuild=useMemo(()=>meta.topic.trim().length>3&&!busy,[meta.topic,busy]);
  useEffect(()=>{const client=getSupabaseBrowserClient();(async()=>{const {data:auth}=await client.auth.getUser();if(!auth.user){window.location.href="/auth?next=/ai-course-builder";return;}const {data:p}=await client.from("staff_profiles").select("id,full_name,role,organisation_id").eq("id",auth.user.id).maybeSingle();setProfile((p||null) as Profile|null);if(p?.organisation_id){const {data}=await client.from("school_knowledge_documents").select("id,title,category,summary,content,tags").eq("organization_id",p.organisation_id).eq("status","active").order("updated_at",{ascending:false});setDocs((data||[]) as Doc[]);}setLoading(false);})();},[]);

  async function generate(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!canBuild)return;setBusy(true);setDraft(null);setMessage("");const sources=docs.filter(d=>selected.includes(d.id)).map(d=>({title:d.title,category:d.category,summary:d.summary,content:d.content}));const response=await authenticatedFetch("/api/ai-course-builder",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...meta,sources})});const data=await response.json().catch(()=>({error:"Unable to generate the course."}));setBusy(false);if(!response.ok||!data.course){setMessage(String(data.error||"Unable to generate the course."));return;}setDraft(data.course as Draft);setMessage(`Draft generated with ${data.course.blocks.length} learning blocks using ${data.model||"Gemini"}. Review it before saving.`);}

  async function saveDraft(){if(!draft||!profile?.organisation_id)return;const client=getSupabaseBrowserClient();setBusy(true);const slugBase=slugify(draft.title).slice(0,70)||"ai-course";const slug=`${slugBase}-${Date.now().toString(36).slice(-5)}`;const base={title:draft.title,summary:draft.summary,duration_minutes:meta.duration,level:meta.level,objectives:draft.objectives,recommended_for:draft.recommended_for};const {data:course,error}=await client.from("custom_courses").insert({slug,category:meta.category,...base,created_by:profile.id,organisation_id:profile.organisation_id}).select("id,slug").single();if(error||!course){setBusy(false);setMessage(error?.message||"Could not create the course draft.");return;}const {data:version,error:versionError}=await client.from("custom_course_versions").insert({course_id:course.id,version_number:1,...base,created_by:profile.id}).select("id").single();if(versionError||!version){setBusy(false);setMessage(versionError?.message||"Could not create the first course version.");return;}const rows=draft.blocks.map((block,index)=>({version_id:version.id,sort_order:index,block_type:block.block_type,title:block.title,content:block.content,required:block.required!==false}));const {error:blockError}=await client.from("custom_course_blocks").insert(rows);setBusy(false);if(blockError){setMessage(blockError.message);return;}setMessage("AI course saved as a draft. Open the Course Creator to edit, reorder or publish it.");window.setTimeout(()=>{window.location.href="/builder";},900);}

  if(loading)return <main className="stagePage"><div className="stageCard">Loading AI Course Builder…</div></main>;
  if(!profile||!["Admin","CPD Lead"].includes(profile.role))return <main className="stagePage"><section className="stageCard"><h1>CPD Lead or Admin access required</h1><p>AI-generated courses can be created only by authorised CPD staff.</p></section></main>;
  return <main className="stagePage aiPlatformPage">
    <section className="stageHero aiBuilderHero"><span className="eyebrow">GEMINI AI COURSE BUILDER</span><h1>Turn a topic or school document into editable CPD.</h1><p>Gemini creates a complete draft using your Phase 1–8 approach, then saves it into the existing Course Creator for human review, versioning and publishing.</p><div className="stageHeroActions"><a className="secondary phaseLinkButton" href="/knowledge-base">School knowledge</a><a className="secondary phaseLinkButton" href="/builder">Visual Course Creator</a></div></section>
    {message&&<div className="phaseNotice">{message}</div>}
    <section className="stageGrid"><form className="stageCard stageSpan7 stageForm" onSubmit={generate}><span className="eyebrow">COURSE BRIEF</span><label className="full">Topic / purpose<textarea rows={3} value={meta.topic} onChange={e=>setMeta({...meta,topic:e.target.value})} placeholder="e.g. Improve classroom questioning so teachers collect evidence from the whole class before moving on"/></label><label>Audience<input value={meta.audience} onChange={e=>setMeta({...meta,audience:e.target.value})}/></label><label>Category<select value={meta.category} onChange={e=>setMeta({...meta,category:e.target.value})}>{categories.map(x=><option key={x}>{x}</option>)}</select></label><label>Duration<select value={meta.duration} onChange={e=>setMeta({...meta,duration:Number(e.target.value)})}>{[30,45,60,90,120].map(x=><option value={x} key={x}>{x} minutes</option>)}</select></label><label>Level<select value={meta.level} onChange={e=>setMeta({...meta,level:e.target.value})}><option>Foundation</option><option>Developing</option><option>Advanced</option></select></label><label className="full">Extra instructions<textarea rows={3} value={meta.notes} onChange={e=>setMeta({...meta,notes:e.target.value})} placeholder="Optional local emphasis, examples or constraints…"/></label><button className="primary" disabled={!canBuild}>{busy?"Building course…":"Generate complete draft"}</button></form>
      <aside className="stageCard stageSpan5"><span className="eyebrow">SCHOOL SOURCES</span><h2>Ground the course in local documents</h2><p>Select relevant approved sources. Gemini is told not to invent school-specific requirements.</p><div className="aiSourcePicker">{docs.slice(0,20).map(doc=><label key={doc.id}><input type="checkbox" checked={selected.includes(doc.id)} onChange={e=>setSelected(prev=>e.target.checked?[...prev,doc.id]:prev.filter(id=>id!==doc.id))}/><span><strong>{doc.title}</strong><small>{doc.category}</small></span></label>)}{!docs.length&&<div className="emptyCompact">Add documents in the School Knowledge Base first, or generate from the course brief alone.</div>}</div></aside></section>

    {draft&&<section className="stageCard aiDraftPreview"><div className="aiDraftHead"><div><span className="eyebrow">GENERATED DRAFT</span><h2>{draft.title}</h2><p>{draft.summary}</p></div><button className="primary" disabled={busy} onClick={saveDraft}>Save to Course Creator</button></div><div className="stageGrid"><div className="stageSpan5"><h3>Objectives</h3>{draft.objectives.map(x=><p key={x}>✓ {x}</p>)}</div><div className="stageSpan7"><h3>{draft.blocks.length} learning blocks</h3><div className="aiBlockPreview">{draft.blocks.map((block,index)=><article key={`${block.title}-${index}`}><span>{index+1}</span><div><strong>{block.title}</strong><small>{block.block_type.replaceAll("_"," ")}{block.required?" · required":""}</small></div></article>)}</div></div></div></section>}
  </main>;
}

function slugify(value:string){return value.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");}
