import type { Course } from "./data";
export type PracticeCase = { setting: string; observations: string[]; inference: string; question: string; options: string[]; answer: number; feedback: string; followUp: string; review: string };
const cases: Record<Course["category"], PracticeCase> = {
  "Teaching & Learning": { setting: "A class has completed the examples, but a new explanation question produces mixed answers.", observations: ["Six of ten sampled answers explain the method accurately.", "Three pupils copied the example but cannot explain the first step.", "One pupil uses a different correct method and explains why it works."], inference: "The class was quiet, so everybody understood.", question: "What is the most useful next teaching move?", options: ["Move on because the work is complete", "Model the misunderstood step, then check a new example with responses from the whole class", "Repeat every part of the lesson without checking the difficulty"], answer: 1, feedback: "Target the difficulty revealed by the explanations, then collect fresh evidence. Quiet work and task completion cannot settle the learning question.", followUp: "On a new example, eight sampled explanations are accurate, but two pupils still copy the first step.", review: "The evidence suggests progress, not universal mastery. Give the remaining pupils targeted support and check independent reasoning before withdrawing it." },
  SEND: { setting: "A pupil explains the idea orally but is slow to start the multi-step written task. Their agreed support plan is available.", observations: ["The pupil explains the main idea accurately aloud.", "They start after the instructions are shown in three numbered steps.", "They pause at the second example and ask the adult what to write."], inference: "The pupil is lazy and needs an easier learning objective.", question: "Which response fits the observed barrier?", options: ["Keep the goal, use a small visible sequence and review independent use alongside the agreed plan", "Have an adult complete the written task", "Keep the same permanent support without reviewing it"], answer: 0, feedback: "The evidence points to task access and organisation, not a reason to remove the thinking. Check the agreed plan, choose a proportionate scaffold and review independence.", followUp: "With a visible sequence the pupil starts independently, but still needs one prompt to explain the final link.", review: "Review which part of the scaffold is useful. Do not declare the whole task secure from a quicker start; check the explanation and fade support responsively." },
  Safeguarding: { setting: "During a normal school day a pupil makes a worrying comment. You need to use the current school safeguarding route.", observations: ["The pupil says, 'I feel worried about going home today.'", "The conversation happens after lunch in a supervised school area.", "The pupil asks whether you will tell anyone else."], inference: "These details prove a specific cause at home.", question: "What response stays within your professional safeguarding role?", options: ["Promise secrecy and investigate the cause", "Wait for proof before sharing the concern", "Listen calmly, do not promise secrecy, record facts and follow the current safeguarding route promptly"], answer: 2, feedback: "Use the designated process, including its alternative arrangements if the usual contact is unavailable. This fictional exercise is not an investigation or a substitute for current policy.", followUp: "You receive another relevant factual comment after the initial report.", review: "Pass new factual information through the appropriate safeguarding process. Do not circulate it informally or assume the initial report removes the need to share relevant new information." },
  Leadership: { setting: "A department has introduced one agreed routine. A fortnight later its use varies across the team.", observations: ["Two colleagues can describe the routine and its purpose.", "Three colleagues report that they did not see a worked example.", "One team member reports that the shared resource is inaccessible."], inference: "Variation proves that staff are unwilling to improve.", question: "What is the most useful leadership response?", options: ["Rank staff by compliance immediately", "Clarify the routine, model it and remove the access barrier before reviewing implementation", "Launch several additional initiatives"], answer: 1, feedback: "Separate an implementation barrier from a judgement about motivation. Expectations, examples and resources should be clear before monitoring is interpreted.", followUp: "After modelling and access changes, staff can describe the routine, but the team has not yet reviewed its effect.", review: "Understanding the routine is implementation evidence. Gather proportionate evidence about the intended outcome before deciding whether to keep, adapt or scale it." },
  Wellbeing: { setting: "A team reports that a recurring recording task is adding evening work. Two systems appear to request similar information.", observations: ["Four colleagues report copying the same information into both systems.", "The team spends approximately twenty minutes on the repeated entry in this fictional sample.", "One leader uses an output from the first system but cannot identify a user for the second."], inference: "The staff need to become more resilient; the system cannot be the problem.", question: "What is a useful first workload response?", options: ["Clarify the purpose and users of both outputs, then agree a small trial to reduce duplication", "Transfer all entry to one colleague", "Tell everyone to work faster at home"], answer: 0, feedback: "Investigate the task and agree a proportionate change. Check that time savings do not reduce necessary support or move the burden elsewhere.", followUp: "The trial reduces repeated entry, but one colleague now spends longer assembling the remaining output.", review: "Review workload across the team, not just the original task. Adapt the process if the burden has shifted rather than reduced." },
  "Digital Teaching": { setting: "A member of staff has a plausible-looking draft from a digital tool and is preparing to use it with pupils.", observations: ["One source in the draft cannot be located.", "The worked example includes a step the teacher cannot justify.", "A real pupil's distinctive support details were included in the proposed prompt."], inference: "The output sounds confident, so it is accurate and safe.", question: "What should happen before the draft is used?", options: ["Publish it because it is fluent", "Add more pupil details and trust the output", "Use approved data arrangements, remove inappropriate information and verify the content before use"], answer: 2, feedback: "Human judgement remains responsible for suitability, accuracy and privacy. Confidence is not evidence; use the school's incident route if information has already been shared inappropriately.", followUp: "The example is corrected, but the supposed source still cannot be verified.", review: "Do not present the unverified claim as established evidence. Remove or properly verify it, and check that the remaining resource is suitable for its learning purpose." },
};
const safetyCase: PracticeCase = {
  setting: "A planned school activity is about to start. The space and equipment have changed since the usual arrangements were checked.",
  observations: ["A cable crosses the route pupils will use.", "A piece of equipment has visible damage and its condition has not been checked by the appropriate person.", "The adult supervising is unsure which current risk assessment and support arrangements apply."],
  inference: "No one has been injured, so the activity must be safe.",
  question: "What is a proportionate first response within your role?",
  options: ["Proceed and tell pupils to be careful", "Pause the affected activity, control immediate hazards safely within your competence and seek the current arrangements and designated support", "Improvise a repair and assume the old arrangements still apply"], answer: 1,
  feedback: "Deal with real risk through the current school arrangements. Do not replace competent checks, specialist training or pupil-specific plans with a warning or an improvised repair.",
  followUp: "The access-route hazard is controlled, but the equipment condition and activity arrangements are still unresolved.",
  review: "One resolved hazard does not make the whole activity safe. Keep the affected equipment/activity paused and obtain the appropriate checks and guidance before proceeding.",
};
export function isSafetyCourse(course: Pick<Course, "id">): boolean {
  return /health|safety|fire-|accident-|near-miss|medical-|allergy-|security-|coshh|asbestos|first-aid/.test(course.id) && !/online-safety|cybersecurity/.test(course.id);
}
export function classroomCase(course: Course): PracticeCase {
  if (isSafetyCourse(course)) return safetyCase;
  return cases[course.category];
}
export function classroomScore(practice: PracticeCase, classifications: string[], decision: number | null) {
  const evidence = classifications.reduce((sum, value, i) => sum + (value === (i < 3 ? "observation" : "inference") ? 1 : 0), 0);
  return { evidence, decision: decision === practice.answer };
}

