import type { Course, CourseCategory } from "./data";

export const PRESENTATION_OVERHAUL_PHASE25_VERSION = "2026.26";

export type Phase25Stage={id:string;label:string;headline:string;explanation:string;watchFor:string;decision:{prompt:string;options:{id:string;label:string;best:boolean}[];feedback:string}};
export type Phase25Pack={id:string;anchorId:string;title:string;subtitle:string;stages:Phase25Stage[]};
export type Phase25Audit={courseId:string;title:string;stages:number;decisions:number;clickable:boolean;anchorFound:boolean;ready:boolean;score:number};

type StageTuple=[string,string,string,string,string,string,string[],number,string];
type Lens={title:string;stages:StageTuple[]};

function safeId(v:string){return v.replace(/[^a-z0-9-]/gi,"-").replace(/-+/g,"-").replace(/^-|-$/g,"").toLowerCase();}
function option(labels:string[],best:number){return labels.map((label,index)=>({id:String.fromCharCode(65+index),label,best:index===best}));}
function anchor(course:Course){return course.modules.find(m=>m.type==="visual")?.id||course.modules.find(m=>m.type==="content")?.id||course.modules[0]?.id||"";}
function s(id:string,label:string,headline:string,explanation:string,watchFor:string,prompt:string,labels:string[],best:number,feedback:string):StageTuple{return[id,label,headline,explanation,watchFor,prompt,labels,best,feedback];}

function lens(category:CourseCategory,course:Course):Lens{
  if(category==="Safeguarding")return{title:"Safeguarding response pathway",stages:[
    s("notice","1 · Notice","Recognise the signal","Notice what was seen, heard or reported without deciding the cause.","Jumping from a signal to a confident explanation.","A pupil says something worrying but incomplete. What comes first?",["Listen calmly and clarify only what is necessary for immediate safety","Ask detailed questions until the whole story is known","Share with several colleagues to compare impressions"],0,"The safest starting point preserves the pupil's account and avoids staff-led investigation."),
    s("record","2 · Record","Separate fact from interpretation","Capture factual observations and the pupil's words where appropriate, keeping uncertainty visible.","Writing diagnosis, motive or causal claims as if they were facts.","Which record is strongest?",["What was observed or said, with clear source and time","A polished explanation of what probably happened","Only the conclusion, without the underlying information"],0,"A factual record remains useful because later safeguarding decisions can distinguish evidence from interpretation."),
    s("report","3 · Report","Use the designated route","Pass the concern promptly through the school's current safeguarding procedure.","Waiting for proof before reporting.","What should determine whether the route is used?",["A concern or relevant factual information within the school's procedure","Whether the staff member personally believes the account","Whether the whole team agrees first"],0,"Staff report concerns; designated safeguarding staff manage the next safeguarding decision."),
    s("boundary","4 · Boundary","Stay inside the staff role","Continue normal professional support while avoiding investigation, unnecessary sharing or promises of secrecy.","Trying to solve the case personally after reporting.","What is the best ongoing stance?",["Support, observe and pass relevant new factual information through the route","Keep questioning until certainty is reached","Discuss details informally so everyone can help"],0,"Professional curiosity and clear boundaries can coexist."),
  ]};
  if(category==="SEND")return{title:"Adaptive support cycle",stages:[
    s("barrier","1 · Barrier","Identify the access barrier","Use task and learner evidence to locate the specific demand blocking access.","Treating a label as the explanation.","What should be identified first?",["The task demand creating the barrier","The learner's label as a fixed plan","A generic intervention list"],0,"Good adaptation begins with the barrier in this task and context."),
    s("goal","2 · Goal","Protect the learning goal","Keep the intended learning outcome unless evidence shows it is inappropriate.","Lowering challenge before testing access support.","Which element should usually stay stable first?",["The core learning goal","The amount of prompting","The surface format"],0,"Adapt the route before assuming the destination must change."),
    s("scaffold","3 · Scaffold","Use the smallest useful support","Make the difficult access step clearer without doing the thinking for the learner.","Support that creates prompt dependence.","Which scaffold is most proportionate?",["A visible sequence or brief start cue","An adult completing each step","A permanently easier task"],0,"A useful scaffold removes an access obstacle while leaving cognitive work with the learner."),
    s("review","4 · Review","Fade, keep or adapt","Collect evidence of accuracy and independence, then decide whether support should change.","Keeping support forever because completion improved once.","What evidence matters most?",["Independent access and accuracy","Worksheet neatness","Whether the scaffold was popular"],0,"Support should be responsive to evidence, not permanent by habit."),
  ]};
  if(category==="Leadership")return{title:"Implementation system model",stages:[
    s("clarity","1 · Clarity","Define the core practice","Make the smallest non-negotiable element and purpose explicit.","Expecting consistency from vague guidance.","What should a team know first?",["What the core practice is and why it matters","Who will be monitored most","Which team is currently best"],0,"Clarity is a precondition for meaningful implementation evidence."),
    s("capability","2 · Capability","Model and rehearse","Give staff examples, rehearsal and feedback where the practice is unfamiliar.","Assuming written guidance creates skill.","What best tests capability?",["Can staff explain and enact the practice?","Did staff open the document?","How many reminders were sent?"],0,"Capability is demonstrated through professional enactment, not exposure to information."),
    s("capacity","3 · Capacity","Check workload and conditions","Identify whether time, systems or competing priorities prevent reliable use.","Calling capacity problems motivation problems.","Which signal suggests a capacity barrier?",["Quality drops when workload peaks across teams","One person dislikes wording","A team asks a question"],0,"Patterns across conditions are more informative than assumptions about motivation."),
    s("review","4 · Review","Use evidence to adapt","Review implementation, workload and intended outcomes before deciding keep/adapt/stop.","Treating visible compliance as proof of impact.","What completes the loop?",["A review decision tied to evidence","A permanent monitoring schedule","A staff ranking"],0,"Implementation evidence should drive support and adaptation, not merely surveillance."),
  ]};
  if(category==="Wellbeing")return{title:"Workload pressure system",stages:[
    s("signal","1 · Signal","Identify the pressure signal","Use staff experience alongside workflow evidence to locate recurring pressure.","Assuming every pressure has the same cause.","What strengthens the diagnosis?",["Repeated patterns across time, tasks and staff experience","A single popular event","A general statement that everyone is busy"],0,"Patterns help separate temporary peaks from avoidable system friction."),
    s("cause","2 · Cause","Trace the system cause","Look for duplication, deadline clustering, low-value process or unnecessary transfer points.","Treating system friction as individual resilience failure.","Which is most controllable?",["A duplicated reporting process","A colleague's personality","The fact that school work can be demanding"],0,"The strongest organisational action targets conditions the organisation can change."),
    s("change","3 · Change","Make one bounded change","Remove, simplify, sequence or redesign one source of avoidable friction.","Adding another initiative without removing anything.","What makes the change testable?",["One defined workflow change","Several simultaneous activities","A motivational message"],0,"A bounded change makes it possible to learn what actually helped."),
    s("evidence","4 · Evidence","Check for displaced burden","Measure whether workload reduced and whether the burden simply moved elsewhere.","Celebrating time saved for one team while another absorbs it.","What is the strongest review?",["Process evidence plus staff experience across affected teams","Attendance at launch","Number of communications"],0,"System improvement should reduce avoidable burden rather than redistribute it invisibly."),
  ]};
  if(category==="Digital Teaching")return{title:"Safe digital workflow model",stages:[
    s("purpose","1 · Purpose","Start with the professional task","Use a digital tool only where it offers a clear educational or workload benefit.","Starting with novelty rather than need.","What comes before choosing the tool?",["The professional problem and intended benefit","The newest feature","The most impressive demo"],0,"Purpose makes it possible to judge whether the tool is actually helping."),
    s("boundary","2 · Boundary","Set privacy and access boundaries","Define appropriate data handling and accessibility before routine use.","Leaving privacy and access to individual improvisation.","What belongs in the workflow design?",["Data and accessibility boundaries","Only a longer prompt","A promise errors are rare"],0,"Safe use is designed in before scale."),
    s("verify","3 · Verify","Check important outputs","Match verification to the risk of the task and importance of the output.","Treating fluent wording as evidence of truth.","Which output needs strongest checking?",["A factual or evaluative output affecting pupils","Low-stakes brainstorming","A decorative heading"],0,"Verification should be proportionate to consequence and uncertainty."),
    s("human","4 · Human","Keep professional responsibility","A human remains accountable for final decisions, resources and communications.","Outsourcing judgement to the tool.","Who owns the final decision?",["The professional using and approving the output","The AI model","Whoever wrote the prompt"],0,"Tools can support judgement but cannot remove professional accountability."),
  ]};
  return{title:`Evidence-to-action model · ${course.title}`,stages:[
    s("signal","1 · Signal","Notice the learning signal","Begin with evidence of what pupils are doing, saying or producing.","Mistaking visible activity for secure learning.","Which signal deserves most attention?",["Evidence of pupil thinking","How busy the room looks","How many pages were completed"],0,"Learning decisions need evidence of thinking, not only appearance."),
    s("diagnose","2 · Diagnose","Name the learning problem","Identify the misconception, missing connection or task demand precisely.","Responding before diagnosing.","What should the diagnosis describe?",["The specific gap in understanding or access","Whether pupils enjoyed the lesson","Which activity looked impressive"],0,"Precision makes the next teaching move more likely to match the problem."),
    s("act","3 · Act","Choose the smallest strong response","Reteach, contrast, model, scaffold or practise in direct response to the diagnosis.","Adding activity without causal clarity.","Which response is strongest?",["One targeted move linked to the diagnosis","Several new strategies at once","Repeating the original lesson unchanged"],0,"Targeted responses preserve causal clarity and reduce unnecessary complexity."),
    s("check","4 · Check","Test independent transfer","Use a follow-up response that shows whether pupils can apply the idea independently.","Stopping at participation or guided success.","What completes the cycle?",["Independent evidence that determines the next decision","A positive class reaction","More completed work"],0,"The check turns teaching into an evidence-led cycle rather than a one-off technique."),
  ]};
}

export function getPhase25Pack(course:Course):Phase25Pack{const l=lens(course.category,course);return{id:`phase25-${safeId(course.id)}`,anchorId:anchor(course),title:l.title,subtitle:"Explore each stage, reveal the explanation, inspect the professional risk and make a mini decision before moving through the model.",stages:l.stages.map(([id,label,headline,explanation,watchFor,prompt,labels,best,feedback])=>({id,label,headline,explanation,watchFor,decision:{prompt,options:option(labels,best),feedback}}))};}
export function validateInteractiveModelsPhase25(course:Course){const p=getPhase25Pack(course);if(!p.anchorId)throw new Error(`Phase 25 ${course.id}: missing model anchor`);if(p.stages.length!==4)throw new Error(`Phase 25 ${course.id}: requires four model stages`);if(p.stages.some(s=>s.decision.options.length<3||s.decision.options.filter(o=>o.best).length!==1))throw new Error(`Phase 25 ${course.id}: every stage needs a mini decision with one strongest answer`);return true;}
export function auditInteractiveModelsPhase25(course:Course):Phase25Audit{const p=getPhase25Pack(course);let ready=true;try{validateInteractiveModelsPhase25(course);}catch{ready=false;}const anchorFound=course.modules.some(m=>m.id===p.anchorId);const decisions=p.stages.length;const score=Math.min(100,(p.stages.length===4?30:0)+(decisions===4?25:0)+(anchorFound?25:0)+(p.subtitle.toLowerCase().includes("explore")?10:0)+(ready?10:0));return{courseId:course.id,title:course.title,stages:p.stages.length,decisions,clickable:true,anchorFound,ready,score};}
export function summariseInteractiveModelsPhase25(courses:Course[]){const reports=courses.map(auditInteractiveModelsPhase25);return{courseCount:reports.length,ready:reports.filter(r=>r.ready).length,totalStages:reports.reduce((s,r)=>s+r.stages,0),totalDecisions:reports.reduce((s,r)=>s+r.decisions,0),averageScore:reports.length?Math.round(reports.reduce((s,r)=>s+r.score,0)/reports.length):0,reports};}
