import type { Course, CourseCategory } from "./data";

export const PRESENTATION_OVERHAUL_PHASE24_VERSION = "2026.25";

export type Phase24ChallengeKind = "edge_case" | "conflicting_evidence" | "design_constraint";
export type Phase24Challenge = {
  id:string;
  kind:Phase24ChallengeKind;
  title:string;
  prompt:string;
  options?:{id:string;label:string;correct:boolean}[];
  requiredSelections?:number;
  expertNote:string;
};
export type Phase24Pack = {id:string;title:string;subtitle:string;challenges:Phase24Challenge[];unlockRule:string};
export type Phase24Audit = {courseId:string;title:string;challenges:number;kinds:number;optional:boolean;masteryGated:boolean;ready:boolean;score:number};

function safeId(v:string){return v.replace(/[^a-z0-9-]/gi,"-").replace(/-+/g,"-").replace(/^-|-$/g,"").toLowerCase();}
function opts(labels:string[],correct:number[]){return labels.map((label,index)=>({id:String.fromCharCode(65+index),label,correct:correct.includes(index)}));}

type Lens={edge:[string,string[],number[],string];conflict:[string,string[],number[],string];design:[string,string]};
function lens(category:CourseCategory,course:Course):Lens{
  if(category==="Safeguarding")return{edge:["A pupil retracts part of an earlier account after asking whether anyone else will know. Which response is most defensible?",["Record the change factually and pass it through the safeguarding route without deciding which version is true","Challenge the pupil until one version is confirmed","Delete the earlier record because the pupil changed their account","Ask several colleagues which account seems more believable"],[0],"Retraction changes the information but not the staff role: preserve the factual record and use the designated process."],conflict:["Which TWO statements best protect the evidence trail when information conflicts?",["Record what was said or observed separately from interpretation","Resolve the conflict yourself before reporting","Keep uncertainty visible in the record","Share the whole story widely so colleagues can compare versions"],[0,2],"Good safeguarding records preserve uncertainty accurately instead of hiding it behind a confident conclusion."],design:["Design a response for a staff member who receives a concern during a busy transition between lessons. Keep it prompt, factual and realistic without turning the conversation into an investigation.","A strong answer protects immediate safety, records facts, uses the current route and avoids leading questions or unnecessary sharing."]};
  if(category==="SEND")return{edge:["A scaffold improves accuracy but slows the learner so much that they complete very little independently. What is the strongest next move?",["Review the barrier and redesign or fade the scaffold rather than assuming more support is better","Keep adding support because accuracy improved","Lower the learning goal permanently","Remove all support immediately"],[0],"Expert adaptation weighs access, accuracy, cognitive load and independence together."],conflict:["Which TWO pieces of evidence matter most before deciding whether to keep a scaffold?",["Independent starts and accuracy across comparable tasks","Whether the learner says they like the colour of the resource","Whether the support reduces the identified barrier","Whether every pupil in the class uses the same scaffold"],[0,2],"Support should be reviewed against the barrier it was designed to remove and whether independence is growing."],design:["Design a support plan for a learner who needs help starting a complex task but becomes prompt-dependent quickly.","A strong answer keeps the goal, makes the first step accessible, defines what the adult will not do and includes a fade/review rule."]};
  if(category==="Leadership")return{edge:["Implementation data improve after monitoring increases, but staff report that they are optimising what is visible rather than the underlying practice. What next?",["Re-centre the purpose, clarify quality indicators and reduce performative monitoring","Increase monitoring further","Publish staff rankings","Abandon the change immediately"],[0],"Expert implementation distinguishes visible compliance from the intended professional practice."],conflict:["Which TWO signals together best suggest an implementation problem is about capacity rather than motivation?",["Staff can explain the practice accurately","The same workload barrier appears across multiple teams","One staff member dislikes the wording of the policy","Quality drops most when workload peaks"],[1,3],"Patterns across teams and workload conditions are stronger evidence of capacity than isolated attitudes."],design:["Design a 4-week implementation reset where staff understand the priority but workload and uneven rehearsal are undermining consistency.","A strong answer defines the smallest non-negotiable, adds modelling/rehearsal, removes avoidable burden and sets a review point using implementation and workload evidence."]};
  if(category==="Wellbeing")return{edge:["A process change saves time for one team but creates extra work for another. What is the strongest next move?",["Review the whole workflow and redesign the transfer point so burden is not simply displaced","Keep the change because one team improved","Add a wellbeing session for the team with extra work","Ask the second team to become more efficient"],[0],"System improvement must check where workload moves, not only where it disappears."],conflict:["Which TWO findings best justify keeping a workload change?",["Measured time or duplication reduces","The launch event was popular","Staff experience improves without a new burden appearing elsewhere","The change generated lots of communications"],[0,2],"The strongest evidence combines actual workload change with staff experience and checks for displaced burden."],design:["Design a small workload trial where duplicated reporting is removed but leaders still need necessary assurance information.","A strong answer preserves the essential assurance outcome while simplifying how evidence is captured and reviewed."]};
  if(category==="Digital Teaching")return{edge:["A tool is highly accurate for planning but unreliable when generating pupil-facing explanations. What is the strongest policy response?",["Use different boundaries by task risk instead of one blanket rule","Approve all uses because planning accuracy is high","Ban the tool completely","Let each user decide without shared expectations"],[0],"Expert digital governance is task-sensitive: different workflows can require different verification and access controls."],conflict:["Which TWO conditions most strongly justify scaling an AI-supported workflow?",["Verified benefit for the defined task","High novelty value","Reliable human checking appropriate to the risk","A polished interface"],[0,2],"Scale should follow demonstrated benefit plus proportionate governance, not novelty or appearance."],design:["Design a safe-use workflow for a time-saving tool that sometimes produces subtle factual errors.","A strong answer defines the task, data boundary, verification step, accessibility check and who remains accountable for the final output."]};
  return{edge:[`A strategy from ${course.title} improves participation but independent transfer remains weak. What is the strongest next move?`,["Keep the principle but change the teaching move using evidence from independent responses","Increase the same activity because participation improved","Judge success from engagement alone","Lower the transfer task for everyone"],[0],"Expert teaching separates participation from secure learning and adapts the next move to the evidence."],conflict:["Which TWO signals together give the strongest evidence that pupils are ready to move on?",["Independent accuracy on the target idea","High task completion","Successful application in a less familiar example","Lots of volunteered answers"],[0,2],"Independent accuracy plus transfer is stronger evidence than visible participation or quantity of work."],design:[`Design a next lesson when pupils appear fluent in ${course.title} during guided work but struggle independently.`,"A strong answer identifies the likely gap, selects a focused teaching response and defines a check that can distinguish success from surface fluency."]};
}

export function getPhase24Pack(course:Course):Phase24Pack{const x=lens(course.category,course);return{id:`phase24-${safeId(course.id)}`,title:`Expert Challenges · ${course.title}`,subtitle:"Optional high-difficulty problems for staff who have already demonstrated mastery in the main course activities.",unlockRule:"Unlock after a passed substantive assessment plus at least two advanced applied activities from Phases 16–19.",challenges:[{id:"edge",kind:"edge_case",title:"Expert 1 · Edge case",prompt:x.edge[0],options:opts(x.edge[1],x.edge[2]),requiredSelections:1,expertNote:x.edge[3]},{id:"conflict",kind:"conflicting_evidence",title:"Expert 2 · Conflicting evidence",prompt:x.conflict[0],options:opts(x.conflict[1],x.conflict[2]),requiredSelections:2,expertNote:x.conflict[3]},{id:"design",kind:"design_constraint",title:"Expert 3 · Design under constraint",prompt:x.design[0],expertNote:x.design[1]}]};}
export function validateExpertChallengesPhase24(course:Course){const p=getPhase24Pack(course);if(p.challenges.length!==3)throw new Error(`Phase 24 ${course.id}: requires three expert challenges`);if(new Set(p.challenges.map(c=>c.kind)).size!==3)throw new Error(`Phase 24 ${course.id}: requires three challenge kinds`);if(!/passed substantive assessment/i.test(p.unlockRule)||!/two advanced/i.test(p.unlockRule))throw new Error(`Phase 24 ${course.id}: mastery gate missing`);if(p.challenges.filter(c=>c.options).some(c=>c.options!.filter(o=>o.correct).length!==(c.requiredSelections||1)))throw new Error(`Phase 24 ${course.id}: answer key mismatch`);return true;}
export function auditExpertChallengesPhase24(course:Course):Phase24Audit{const p=getPhase24Pack(course);let ready=true;try{validateExpertChallengesPhase24(course);}catch{ready=false;}const kinds=new Set(p.challenges.map(c=>c.kind)).size;const masteryGated=/assessment/i.test(p.unlockRule)&&/advanced/i.test(p.unlockRule);const score=Math.min(100,(p.challenges.length===3?25:0)+(kinds===3?25:0)+(masteryGated?25:0)+(p.subtitle.toLowerCase().includes("optional")?15:0)+(ready?10:0));return{courseId:course.id,title:course.title,challenges:p.challenges.length,kinds,optional:true,masteryGated,ready,score};}
export function summariseExpertChallengesPhase24(courses:Course[]){const reports=courses.map(auditExpertChallengesPhase24);return{courseCount:reports.length,ready:reports.filter(r=>r.ready).length,totalChallenges:reports.reduce((s,r)=>s+r.challenges,0),masteryGated:reports.filter(r=>r.masteryGated).length,averageScore:reports.length?Math.round(reports.reduce((s,r)=>s+r.score,0)/reports.length):0,reports};}
