import type { Course, Module } from "./data";

const reflect=(id:string,prompt:string):Module=>({id,type:"reflection",title:"Apply it to your practice",prompt});

export const expandedCoursesBatch2:Course[]=[
{
 id:"behaviour-management",title:"Behaviour Management: Prevention Before Correction",category:"Teaching & Learning",duration:75,level:"Foundation",summary:"Build calm, predictable classrooms through explicit routines, active supervision, proportionate correction and thoughtful follow-up.",objectives:["Teach behaviour routines explicitly","Reduce predictable triggers for disruption","Use calm, proportionate correction","Distinguish behaviour support from assumptions about motive"],recommendedFor:["Teacher","ECT","Teaching Assistant"],modules:[
  {id:"bm1",type:"content",title:"Behaviour is shaped by the environment",body:"Strong behaviour practice begins before a problem occurs. Clear routines, well-sequenced tasks, active supervision and predictable responses reduce ambiguity and protect learning time.",keyPoints:["State observable expectations","Practise routines rather than merely announcing them","Position yourself to notice success and difficulty","Use the school's agreed behaviour system consistently"]},
  {id:"bm2",type:"quiz",title:"Routine check",question:"What makes a classroom routine most likely to become reliable?",options:["Mentioning it once","Explicit teaching, rehearsal, feedback and consistent cues","Changing expectations according to mood","Correcting only when senior staff are present"],answer:1,feedback:"Routines become dependable when pupils know exactly what to do and experience consistent teaching and reinforcement of the routine."},
  {id:"bm3",type:"content",title:"Correct privately where possible",body:"Low-key correction can protect dignity and keep attention on learning. The exact response must follow school policy, but calm reminders, proximity, redirection and predictable stepped consequences often prevent minor disruption becoming a public confrontation.",keyPoints:["Keep language brief","Describe the expected behaviour","Avoid public debates about motive","Escalate through agreed systems when needed"]},
  {id:"bm4",type:"scenario",title:"Independent-work scenario",prompt:"Several pupils begin talking off task during a long independent task. What should you consider first?",options:[{label:"Assume they are deliberately challenging authority",feedback:"Motive cannot be inferred reliably from the behaviour alone."},{label:"Re-establish the work routine, check task clarity/difficulty and use the agreed behaviour response consistently",feedback:"This addresses both classroom conditions and expectations without excusing disruption."},{label:"Stop teaching the class for a long public lecture",feedback:"Lengthy whole-class interruption can reward disruption with attention and reduce learning time."}]},
  {id:"bm5",type:"scenario",title:"Repeated behaviour scenario",prompt:"A pupil repeatedly fails to follow the same routine despite calm reminders. What is the strongest next step?",options:[{label:"Invent a new consequence outside policy",feedback:"Consistency with school systems matters."},{label:"Follow the next agreed step, record patterns where required, and seek pastoral/SEND input if a persistent barrier is suspected",feedback:"This combines consistent boundaries with appropriate professional curiosity."},{label:"Ignore all future incidents",feedback:"Repeated unaddressed disruption can undermine expectations."}]},
  {id:"bm6",type:"quiz",title:"Professional judgement check",question:"Which statement is strongest?",options:["A behaviour system should be identical in wording and support for every situation","High expectations and reasonable adjustments can coexist","SEND means behaviour expectations should disappear","Every behaviour problem can be solved by sanctions alone"],answer:1,feedback:"Schools can maintain clear expectations while using reasonable, pupil-specific support and following SEND/pastoral plans."},
  reflect("bm7","Choose one recurring classroom transition or routine. Write the exact cue, expected pupil behaviour, how you will rehearse it, and what you will do when it begins to drift.")
 ]
},
{
 id:"send-inclusive-practice",title:"SEND: Inclusive Classroom Practice",category:"SEND",duration:80,level:"Foundation",summary:"Plan ambitious teaching that anticipates barriers, uses pupil-specific information and adapts access without automatically reducing challenge.",objectives:["Use pupil plans and specialist information intelligently","Identify barriers created by tasks and environments","Select proportionate reasonable adjustments","Review whether support builds independence"],recommendedFor:["Teacher","Teaching Assistant","ECT","Department Lead"],modules:[
  {id:"se1",type:"content",title:"Start with the pupil, not the label",body:"A diagnosis or broad area of need does not prescribe one teaching strategy. Effective inclusive practice combines knowledge of the individual pupil with careful analysis of what the lesson is asking pupils to perceive, remember, communicate and do.",keyPoints:["Read current pupil information","Know the core learning goal","Identify the specific barrier","Avoid assuming identical needs from identical labels"]},
  {id:"se2",type:"quiz",title:"Planning check",question:"What is the best starting point for a reasonable classroom adjustment?",options:["The diagnostic label alone","The pupil's current information plus the demands of the specific task","A permanently easier curriculum","Whatever worked for another pupil last year"],answer:1,feedback:"The adjustment should respond to the learner and the actual barrier in the task or environment."},
  {id:"se3",type:"content",title:"Anticipate common access barriers",body:"Barriers can arise from dense language, working-memory demand, sensory load, unclear routines, motor demands, inaccessible layouts or assumptions about prior knowledge. Many useful adaptations can be planned in advance while retaining the same important learning.",keyPoints:["Clarify vocabulary and instructions","Use appropriate representations","Chunk complex sequences","Make routines and success criteria visible","Use assistive technology where specified and useful"]},
  {id:"se4",type:"scenario",title:"Same goal, different route",prompt:"A pupil understands the science concept orally but struggles to organise a written explanation. What is the strongest first adjustment?",options:[{label:"Replace the concept with a simpler one",feedback:"This changes the learning intention unnecessarily."},{label:"Provide a temporary structure, model or sentence framework for the same conceptual explanation",feedback:"This supports access while maintaining the important learning."},{label:"Write the response for the pupil",feedback:"This removes the pupil's opportunity to practise the target thinking."}]},
  {id:"se5",type:"content",title:"Support should have a purpose",body:"Scaffolds should help pupils participate more successfully and, where possible, become increasingly independent. Review whether the support is still needed, whether it is working, and whether it unintentionally creates dependence or stigma."},
  {id:"se6",type:"scenario",title:"When support is not working",prompt:"A pupil's usual scaffold is no longer helping and the pupil is increasingly frustrated. What should the teacher do?",options:[{label:"Continue it indefinitely because it is written on an old plan",feedback:"Support should be reviewed when evidence shows it is ineffective."},{label:"Record the pattern, adapt immediate teaching where reasonable, and feed evidence into the school's SEND review process",feedback:"Classroom evidence should inform collaborative review rather than unilateral diagnosis."},{label:"Remove all support immediately",feedback:"Abrupt removal may create additional barriers."}]},
  {id:"se7",type:"quiz",title:"Inclusion check",question:"Which statement best describes inclusive adaptive teaching?",options:["Lower the expected learning for every pupil with SEND","Keep ambitious goals while changing support when evidence shows a barrier","Create a unique curriculum for every pupil in every lesson","Ignore individual plans to treat everyone identically"],answer:1,feedback:"Inclusion aims to remove avoidable barriers while preserving ambitious, meaningful learning wherever appropriate."},
  reflect("se8","Select one upcoming lesson and one known learner need. Identify the exact barrier, the adaptation you will use, and the evidence you will collect to decide whether it helped.")
 ]
},
{
 id:"eal-inclusive-teaching",title:"EAL: Language-Rich Classroom Practice",category:"SEND",duration:75,level:"Developing",summary:"Support pupils learning through English by making disciplinary language visible while preserving conceptual challenge.",objectives:["Distinguish language demand from conceptual demand","Teach high-value vocabulary explicitly","Use modelling and structured talk","Assess knowledge without confusing language proficiency with subject understanding"],recommendedFor:["Teacher","Teaching Assistant","ECT","Department Lead"],modules:[
  {id:"ea1",type:"content",title:"Language and knowledge develop together",body:"A pupil may understand an idea more deeply than they can yet express in English. Strong EAL teaching keeps the conceptual goal ambitious while explicitly teaching the vocabulary, sentence patterns and discourse needed to participate in the subject.",keyPoints:["Do not equate quietness with lack of understanding","Make disciplinary vocabulary visible","Model how experts in the subject explain and justify","Use visuals and examples to support meaning"]},
  {id:"ea2",type:"quiz",title:"EAL misconception check",question:"Which response best preserves ambition for a pupil new to English?",options:["Give only simplified content indefinitely","Teach the key language needed to access the same important concept and provide structured opportunities to use it","Avoid all speaking tasks","Assess only grammar"],answer:1,feedback:"Language scaffolding should open access to challenging subject learning rather than replace it."},
  {id:"ea3",type:"content",title:"Vocabulary beyond definitions",body:"Knowing a word includes recognising it, understanding it in context, connecting it to related concepts and using it accurately. Teach a manageable number of high-value words through examples, non-examples, morphology where useful and repeated use."},
  {id:"ea4",type:"scenario",title:"Class discussion",prompt:"An EAL pupil rarely contributes in whole-class discussion but gives thoughtful responses after partner rehearsal. What is a useful adaptation?",options:[{label:"Remove them from future discussion",feedback:"This removes opportunities to develop disciplinary talk."},{label:"Build in rehearsal time, sentence prompts where helpful, then invite contribution without unnecessary pressure",feedback:"Structured rehearsal can support access to whole-class academic talk."},{label:"Require an immediate unprepared speech every lesson",feedback:"High public pressure may measure language confidence more than subject understanding."}]},
  {id:"ea5",type:"content",title:"Make writing structures visible",body:"Subject writing contains recurring structures: cause and effect, comparison, evaluation, explanation and argument. Models, annotated examples and sentence-level practice can reveal how knowledge is organised in the discipline."},
  {id:"ea6",type:"scenario",title:"Assessment interpretation",prompt:"A pupil gives a short grammatically imperfect answer that contains the correct scientific relationship. What should the teacher do?",options:[{label:"Treat the science as wrong because the English is imperfect",feedback:"This confuses language accuracy with conceptual understanding."},{label:"Recognise the correct science, then teach the language needed to express it more precisely",feedback:"This separates diagnosis of subject knowledge from the language-development next step."},{label:"Ignore subject terminology completely",feedback:"Pupils still need support to develop accurate disciplinary language."}]},
  {id:"ea7",type:"quiz",title:"Planning check",question:"Which words should usually receive the most deliberate attention?",options:["Every word on every page equally","High-value words pupils need to understand and communicate important subject ideas","Only everyday conversational words","Only words pupils already know"],answer:1,feedback:"Prioritisation makes vocabulary teaching manageable and tightly connected to curriculum learning."},
  reflect("ea8","Choose one upcoming lesson. Identify five high-value words or language structures, how you will model them, and one structured opportunity pupils will have to use them.")
 ]
},
{
 id:"effective-feedback",title:"Feedback That Leads to Improvement",category:"Teaching & Learning",duration:70,level:"Developing",summary:"Design feedback around learning goals, pupil action and manageable next steps rather than quantity of marking.",objectives:["Identify when feedback is likely to help","Select the highest-value next step","Build pupil response into the lesson sequence","Avoid feedback practices that create workload without learning"],recommendedFor:["Teacher","ECT","Department Lead"],modules:[
  {id:"fb1",type:"content",title:"Feedback is information for action",body:"Feedback is useful when it helps a learner close a meaningful gap between current performance and the learning goal. The amount written is much less important than whether the pupil understands and acts on it.",keyPoints:["Link feedback to the learning goal","Prioritise one or two high-value changes","Give pupils time to act","Check whether the response actually improved the work"]},
  {id:"fb2",type:"quiz",title:"Feedback check",question:"Which feature most increases the chance that feedback improves learning?",options:["Maximum written detail","A clear, usable next step followed by time and expectation to act on it","A grade with no explanation","Giving feedback long after the knowledge is needed"],answer:1,feedback:"Feedback needs both usable information and an opportunity for the learner to respond."},
  {id:"fb3",type:"content",title:"Choose the right level",body:"Sometimes the best feedback addresses the task; sometimes it addresses a process or strategy. Feedback that focuses only on the person—such as vague praise—often gives less useful information about what to do next."},
  {id:"fb4",type:"scenario",title:"Whole-class pattern",prompt:"You notice the same misconception in two-thirds of a class's books. What is likely to be the most efficient response?",options:[{label:"Write the same long paragraph in every book",feedback:"This creates workload without guaranteeing pupil action."},{label:"Plan a short whole-class reteach/check, then require pupils to correct or reattempt the relevant part",feedback:"Common misconceptions are often better addressed collectively and followed by pupil action."},{label:"Ignore it because marking is complete",feedback:"The misconception should inform subsequent teaching."}]},
  {id:"fb5",type:"scenario",title:"Too much feedback",prompt:"A pupil receives corrections on ten separate features of one paragraph and changes none of them. What should you consider?",options:[{label:"Add another ten comments",feedback:"More information may increase overload."},{label:"Prioritise the most important next step, model it if necessary and build in response time",feedback:"Focused feedback is more actionable and easier to learn from."},{label:"Give no future feedback",feedback:"The issue is design and actionability, not feedback itself."}]},
  {id:"fb6",type:"quiz",title:"Workload check",question:"Which approach can reduce teacher workload without reducing feedback quality?",options:["Duplicating identical comments","Using whole-class feedback for common patterns and targeted individual feedback where it adds value","Marking every piece of work in maximum detail","Giving pupils no information about errors"],answer:1,feedback:"Efficient feedback focuses teacher effort where it has the greatest instructional value."},
  reflect("fb7","Take one routine marking task. Redesign it so pupils receive one high-value next step and protected time to act on it. What evidence will show the feedback changed performance?")
 ]
},
{
 id:"metacognition-self-regulation",title:"Metacognition and Self-Regulated Learning",category:"Teaching & Learning",duration:75,level:"Developing",summary:"Teach pupils to plan, monitor and evaluate strategies inside authentic subject tasks, with modelling and scaffolds that gradually fade.",objectives:["Explain planning, monitoring and evaluation","Model expert strategy choice through think-alouds","Use prompts that support self-monitoring","Build independence without turning metacognition into generic study tips"],recommendedFor:["Teacher","ECT","Teaching Assistant"],modules:[
  {id:"mc1",type:"content",title:"Metacognition happens inside subject learning",body:"Metacognition is thinking about and regulating one's approach to learning. It is most useful when embedded in authentic tasks: choosing a method, checking progress, noticing an error and deciding what to change.",keyPoints:["Plan a strategy","Monitor whether it is working","Evaluate the result","Connect decisions to subject knowledge"]},
  {id:"mc2",type:"quiz",title:"Knowledge check",question:"Which teacher move most directly makes metacognitive thinking visible?",options:["Give the final answer silently","Think aloud while choosing, checking and revising a strategy","Ask pupils to work faster","Remove all support before modelling"],answer:1,feedback:"Think-alouds expose decisions that experts often make automatically."},
  {id:"mc3",type:"content",title:"Model the decisions, not only the procedure",body:"A useful think-aloud includes uncertainty and checking: 'I could use method A or B; I am choosing A because…', 'This result looks unreasonable, so I will…'. This gives pupils a model for monitoring rather than just a set of steps."},
  {id:"mc4",type:"scenario",title:"Problem-solving scenario",prompt:"Pupils can copy a worked method but freeze when the problem looks slightly different. What is a useful next step?",options:[{label:"Give more identical copying",feedback:"This may strengthen routine performance without strategy selection."},{label:"Model how to recognise problem features, choose a strategy and check whether it fits, then let pupils practise those decisions",feedback:"This targets the metacognitive decisions behind transfer."},{label:"Tell pupils simply to 'think harder'",feedback:"Generic advice does not reveal a usable strategy."}]},
  {id:"mc5",type:"content",title:"Prompts and gradual independence",body:"Questions such as 'What is the goal?', 'What do I know?', 'Which strategy fits?', 'How will I know this is working?' and 'What would I change next time?' can structure self-regulation. Prompts should reduce as pupils internalise the routine."},
  {id:"mc6",type:"scenario",title:"Reflection quality",prompt:"A pupil's evaluation says only 'I need to revise more'. How can you improve the reflection?",options:[{label:"Accept any statement as equally useful",feedback:"Very general reflection may not change future behaviour."},{label:"Prompt for the specific error, strategy used, evidence it worked or failed, and the change they will make next time",feedback:"Specific reflection is more likely to inform future planning."},{label:"Write the pupil's reflection for them",feedback:"The pupil needs practice evaluating their own approach."}]},
  {id:"mc7",type:"quiz",title:"Independence check",question:"When should metacognitive prompts be reduced?",options:["Never","As pupils demonstrate they can plan, monitor and evaluate without the prompt","Before pupils understand the task","At the same date for every class"],answer:1,feedback:"Prompts are scaffolds and should fade responsively as self-regulation becomes more secure."},
  reflect("mc8","Choose one recurring subject task. Write a short teacher think-aloud and three pupil self-monitoring prompts you will use, then decide what evidence would show the prompts can be faded.")
 ]
}
];
