import type { Course, CourseCategory } from "./data";

export const PRESENTATION_OVERHAUL_PHASE30_VERSION = "2026.31";

export type Phase30FieldId="problem"|"action"|"context"|"barrier"|"evidence"|"review";
export type Phase30Field={id:Phase30FieldId;label:string;prompt:string;hint:string;minimumCharacters:number};
export type Phase30Pack={id:string;anchorId:string;title:string;subtitle:string;fields:Phase30Field[];reviewWindows:number[]};
export type Phase30Audit={courseId:string;title:string;fields:number;reviewWindows:number;substantial:boolean;followThrough:boolean;ready:boolean;score:number};

function lens(category:CourseCategory){
  if(category==="Safeguarding")return{problem:"Name a professional practice issue without including confidential pupil details.",action:"State the safe staff action or routine you will strengthen, aligned to your school's current procedure.",context:"Where, when and with which staff role will this matter?",barrier:"What could cause delay, ambiguity, over-questioning or inappropriate information sharing?",evidence:"What non-confidential evidence will show that staff understanding or response is clearer?",review:"At 7, 30 and 90 days, what would make you keep, adapt or stop the implementation approach?"};
  if(category==="SEND")return{problem:"Identify a specific access or independence barrier rather than a label.",action:"State the smallest adaptation or routine you will test while protecting the learning goal.",context:"Which task, class, learner need or team context will you focus on?",barrier:"What could make the support too broad, too dependent on adults or too difficult to sustain?",evidence:"What will show improved access, accuracy or independence?",review:"What evidence at 7, 30 and 90 days would lead you to fade, adapt or retain the support?"};
  if(category==="Leadership")return{problem:"Name the implementation problem precisely: clarity, capability, capacity or system design.",action:"State the smallest leadership action you will model, support or simplify.",context:"Which team, routine or priority will this apply to?",barrier:"What workload, ambiguity or capability issue could block implementation?",evidence:"What implementation and outcome evidence will you gather without relying on visible compliance alone?",review:"What will you decide at the 7, 30 and 90-day points if evidence is strong, mixed or weak?"};
  if(category==="Wellbeing")return{problem:"Name one recurring workload or system pressure within organisational control.",action:"State one bounded change that removes, simplifies, sequences or redesigns the source of friction.",context:"Which workflow and staff groups are affected?",barrier:"What could displace the burden elsewhere or create a new process cost?",evidence:"What time/process evidence and staff experience will show whether pressure actually reduced?",review:"At 7, 30 and 90 days, what would make you keep, adapt or reverse the change?"};
  if(category==="Digital Teaching")return{problem:"Name the professional task or learning problem, not the technology.",action:"State how a digital tool will support the task, including verification and human approval.",context:"Where will the workflow be used and who is responsible for the final decision?",barrier:"What privacy, accuracy, accessibility or dependency risk could undermine the approach?",evidence:"What will show genuine educational or workload benefit without compromising safety?",review:"What should be checked at 7, 30 and 90 days before the workflow becomes routine?"};
  return{problem:"Identify a specific learning or practice problem supported by evidence.",action:"Choose one targeted teaching or professional action linked directly to that problem.",context:"Name the class, topic, routine or professional context where you will test it.",barrier:"What misconception, workload, habit or contextual barrier could weaken the action?",evidence:"What pupil or professional evidence will show whether the action made a difference?",review:"At 7, 30 and 90 days, what evidence would make you keep, adapt or stop the approach?"};
}

export function getPhase30Pack(course:Course):Phase30Pack{const l=lens(course.category);const field=(id:Phase30FieldId,label:string,prompt:string,hint:string):Phase30Field=>({id,label,prompt,hint,minimumCharacters:35});return{id:`phase30-${course.id}`,anchorId:course.modules.at(-1)?.id||"",title:`Final implementation challenge · ${course.title}`,subtitle:"Turn the course into one testable professional change. Define the problem, action, context, barrier, evidence and review plan before entering the 7/30/90-day follow-through cycle.",fields:[field("problem","Problem",l.problem,"Be precise enough that another professional could recognise the issue."),field("action","Action",l.action,"Choose one bounded action rather than several simultaneous changes."),field("context","Context",l.context,"Keep the context specific enough to review fairly."),field("barrier","Barrier",l.barrier,"Anticipate what could stop the action working or being sustained."),field("evidence","Evidence",l.evidence,"Use evidence that can inform a professional decision, not just activity completion."),field("review","Review",l.review,"Make the future decision rule explicit before you know the outcome.")],reviewWindows:[7,30,90]};}
export function validateImplementationChallengePhase30(course:Course){const p=getPhase30Pack(course);if(!p.anchorId)throw new Error(`Phase 30 ${course.id}: missing final module anchor`);if(p.fields.length!==6)throw new Error(`Phase 30 ${course.id}: requires six implementation fields`);if(new Set(p.fields.map(f=>f.id)).size!==6)throw new Error(`Phase 30 ${course.id}: field ids must be unique`);if(p.fields.some(f=>f.minimumCharacters<30||!f.prompt||!f.hint))throw new Error(`Phase 30 ${course.id}: challenge fields are not substantial enough`);if(p.reviewWindows.join(",")!=="7,30,90")throw new Error(`Phase 30 ${course.id}: must feed 7/30/90 follow-through`);return true;}
export function auditImplementationChallengePhase30(course:Course):Phase30Audit{const p=getPhase30Pack(course);let ready=true;try{validateImplementationChallengePhase30(course);}catch{ready=false;}const substantial=p.fields.every(f=>f.minimumCharacters>=30);const followThrough=p.reviewWindows.includes(7)&&p.reviewWindows.includes(30)&&p.reviewWindows.includes(90);const score=Math.min(100,(p.fields.length===6?30:0)+(substantial?25:0)+(followThrough?25:0)+(course.modules.some(m=>m.id===p.anchorId)?10:0)+(ready?10:0));return{courseId:course.id,title:course.title,fields:p.fields.length,reviewWindows:p.reviewWindows.length,substantial,followThrough,ready,score};}
export function summariseImplementationChallengePhase30(courses:Course[]){const reports=courses.map(auditImplementationChallengePhase30);return{courseCount:reports.length,ready:reports.filter(r=>r.ready).length,totalFields:reports.reduce((s,r)=>s+r.fields,0),reviewWindows:[7,30,90],followThroughReady:reports.filter(r=>r.followThrough).length,averageScore:reports.length?Math.round(reports.reduce((s,r)=>s+r.score,0)/reports.length):0,reports};}
