import type { Course, Module } from "./data";

const reflection=(id:string,prompt:string):Module=>({id,type:"reflection",title:"Apply it to your practice",prompt});

export const expandedCourses:Course[]=[
{
 id:"rosenshine-principles",title:"Rosenshine's Principles in Practice",category:"Teaching & Learning",duration:90,level:"Developing",
 summary:"Turn Rosenshine's ten research-informed principles into a coherent lesson cycle: review, small steps, modelling, questioning, guided practice, checking, scaffolding, independent practice and planned review.",
 objectives:["Explain the ten principles and the research ideas behind them","Design review, modelling and guided practice deliberately","Use questioning and checking to decide when support can fade","Plan independent practice and longer-term review without treating the principles as a rigid checklist"],
 recommendedFor:["Teacher","ECT","Teaching Assistant","Department Lead"],
 modules:[
  {id:"ro1",type:"content",title:"What Rosenshine was trying to capture",body:"Rosenshine brought together findings from cognitive science, classroom observation and research on effective instruction. The principles are best understood as mutually reinforcing teaching practices, not ten boxes that every lesson must tick in the same order.",keyPoints:["Use the principles responsively rather than mechanically","Build on secure prior knowledge","Keep new material manageable","Make pupil thinking visible before removing support"]},
  {id:"ro2",type:"content",title:"The ten principles at a glance",body:"A practical summary is: review previous learning; present new material in small steps; ask many questions; provide models; guide initial practice; check understanding; aim for a high level of successful practice; provide temporary scaffolds; require independent practice; and return to important learning through weekly and monthly review.",keyPoints:["Review","Small steps","Questions","Models","Guided practice","Check understanding","High success","Scaffolds","Independent practice","Weekly and monthly review"]},
  {id:"ro3",type:"quiz",title:"Knowledge check: the core idea",question:"Which interpretation best reflects Rosenshine's principles?",options:["Every lesson must follow ten fixed stages","Teachers should provide appropriate support, check learning frequently and gradually move pupils towards independence","Independent discovery should always come before explanation","The principles only apply to factual recall"],answer:1,feedback:"Rosenshine emphasises supported acquisition, practice, checking and gradual movement towards independent performance."},
  {id:"ro4",type:"content",title:"Review and prior knowledge",body:"Short review gives pupils repeated access to important prior learning and lets the teacher identify gaps before new material depends on it. Review is strongest when pupils retrieve and use knowledge rather than simply rereading it.",keyPoints:["Select knowledge that matters for today's learning","Sample older as well as recent material","Correct important errors before building on them","Keep review purposeful rather than automatic"]},
  {id:"ro5",type:"scenario",title:"Starter scenario",prompt:"A class repeatedly struggles with today's algebra because an earlier rearranging skill is insecure. What is the strongest Rosenshine-aligned response?",options:[{label:"Continue with the new content and hope fluency develops",feedback:"New learning will continue to compete with an insecure prerequisite."},{label:"Use a short diagnostic review, reteach the prerequisite where needed, then return to the new material",feedback:"This reconnects new learning to the knowledge pupils need in order to succeed."},{label:"Replace the lesson with a completely unrelated retrieval quiz",feedback:"Review should support the learning that follows, not simply fill time."}]},
  {id:"ro6",type:"content",title:"Small steps, models and worked examples",body:"When material is unfamiliar, working memory can be overloaded by too many new elements at once. Breaking a process into meaningful steps and modelling expert thinking can make the structure visible before pupils are expected to perform it alone.",keyPoints:["Model the whole goal as well as individual steps","Think aloud where the decision-making matters","Use worked examples before expecting novices to generate complete solutions","Avoid over-explaining steps pupils already know securely"]},
  {id:"ro7",type:"quiz",title:"Worked-example check",question:"When is a worked example most useful?",options:["Only after pupils have failed repeatedly","When pupils are novices and need to see the structure of a process before independent problem solving","Instead of any pupil practice","Only for mathematics"],answer:1,feedback:"Worked examples can reduce unnecessary search for novices, but should be followed by guided and increasingly independent practice."},
  {id:"ro8",type:"content",title:"Questions, guided practice and checking",body:"Questions are not just for participation. They help the teacher find out what pupils understand. Guided practice gives pupils a chance to attempt the process while support and feedback are still available. Checks should sample the class broadly rather than relying on volunteers.",keyPoints:["Ask questions that reveal thinking","Use whole-class response techniques when useful","Correct misconceptions promptly","Re-model when errors show the explanation has not landed","Do not confuse silence with understanding"]},
  {id:"ro9",type:"scenario",title:"When should scaffolding fade?",prompt:"After a modelled example, about half the class still makes the same error during guided practice. What should happen next?",options:[{label:"Move immediately to independent work because the explanation has already been given",feedback:"The check shows that pupils are not ready for reduced support."},{label:"Diagnose the common error, re-model or add a prompt, then check again before fading support",feedback:"Support should fade in response to evidence, not simply because a timetable says it is time."},{label:"Give the answers so everyone reaches the end",feedback:"This removes the thinking pupils need to practise."}]},
  {id:"ro10",type:"content",title:"High success, scaffolds and independence",body:"Rosenshine described effective teachers as monitoring practice closely enough that pupils experience substantial success while still doing the thinking themselves. Scaffolds are temporary: prompts, partially completed examples, checklists or cues should be reduced as performance becomes more secure.",keyPoints:["Success should come from supported thinking, not answer-giving","Fade prompts gradually","Independent practice should consolidate what pupils can already perform with reasonable success","Circulate and sample work early during independent practice"]},
  {id:"ro11",type:"content",title:"Weekly and monthly review",body:"Learning becomes more durable when important knowledge is revisited over time and used in varied contexts. Longer-term review should be planned across the curriculum rather than left to last-minute revision.",keyPoints:["Revisit important knowledge after delays","Mix recall with application","Connect ideas across topics","Use errors from review to inform future teaching"]},
  {id:"ro12",type:"scenario",title:"Lesson-design challenge",prompt:"You are planning a lesson with a difficult new process. Which sequence is strongest?",options:[{label:"Long explanation → silent independent work → mark at the end",feedback:"This gives little information about understanding before support disappears."},{label:"Relevant review → small modelled step → pupil practice/check → next step → guided practice → independent practice → later review",feedback:"This uses review, modelling, checking and gradual release as a coherent cycle."},{label:"Independent problem solving first for all pupils, with explanation only if everyone fails",feedback:"For novices, unsupported search can create avoidable cognitive load."}]},
  {id:"ro13",type:"quiz",title:"Misconception check",question:"Which statement about Rosenshine is least accurate?",options:["The principles are research-informed instructional ideas","Checking for understanding should affect what the teacher does next","Every principle must appear in every lesson in exactly the same order","Review and practice help build accessible knowledge"],answer:2,feedback:"The principles are not a mandatory lesson template. Teachers combine and emphasise them according to the content and pupils."},
  reflection("ro14","Choose one upcoming lesson. Map where review, modelling, guided practice, checking and independent practice will occur. Which one element will you deliberately strengthen, and what evidence will show it helped?")
 ]
},
{
 id:"maslow-needs",title:"Maslow's Hierarchy of Needs: A Critical Classroom Lens",category:"Wellbeing",duration:65,level:"Foundation",
 summary:"Use Maslow's influential needs framework cautiously to notice possible barriers to learning while avoiding the myth that every pupil moves through a fixed pyramid in the same order.",
 objectives:["Describe the five familiar need areas associated with Maslow","Explain why the hierarchy should not be treated as a rigid diagnostic model","Identify classroom conditions that can support safety, belonging and competence","Respond to observed needs using school pastoral and safeguarding systems rather than making assumptions"],
 recommendedFor:["Teacher","ECT","Teaching Assistant","Pastoral","Tutor"],
 modules:[
  {id:"ma1",type:"content",title:"The framework",body:"Maslow's motivational theory is commonly presented through five need areas: physiological needs, safety, love and belonging, esteem, and self-actualisation. In schools it can prompt useful questions about whether a pupil is ready to engage, but it should not be used to diagnose a pupil or explain behaviour on its own.",keyPoints:["Physiological: basic physical needs such as food, rest and comfort","Safety: predictability and freedom from threat","Belonging: connection and acceptance","Esteem: competence, recognition and self-respect","Self-actualisation: growth, purpose and developing potential"]},
  {id:"ma2",type:"quiz",title:"Knowledge check",question:"Which is the most responsible classroom use of Maslow's framework?",options:["Use the pyramid to diagnose the exact cause of a pupil's behaviour","Treat it as one lens for noticing possible barriers, then use evidence and school systems to understand the pupil","Assume learning is impossible until every lower need is completely satisfied","Rank pupils according to which level they have reached"],answer:1,feedback:"The framework can prompt questions, but decisions should be based on what is actually known about the pupil and on school pastoral, SEND and safeguarding information."},
  {id:"ma3",type:"content",title:"Do not turn it into a rigid staircase",body:"The familiar hierarchy is often taught too rigidly. People can pursue belonging, achievement, creativity and meaning even when some basic needs are not fully met, and several needs can matter at the same time. Culture, circumstances and individual differences also affect priorities.",keyPoints:["Needs can overlap","The order is not universal or fixed","A framework is not a diagnosis","Avoid using Maslow to lower expectations automatically"]},
  {id:"ma4",type:"scenario",title:"Morning lesson scenario",prompt:"A normally engaged pupil is unusually tired, quiet and has not completed the starter. What is the strongest response?",options:[{label:"Assume their physiological needs are unmet and record that as the cause",feedback:"The observation does not tell you the cause. Avoid diagnosis by assumption."},{label:"Use a calm check-in, maintain reasonable learning support and follow pastoral/safeguarding procedures if a concern emerges",feedback:"This responds to what you can observe while using the school's systems appropriately."},{label:"Remove all academic expectations for the rest of the term",feedback:"A temporary concern should not automatically become a permanent reduction in ambition."}]},
  {id:"ma5",type:"content",title:"Classroom conditions that support learning",body:"Teachers cannot control every aspect of a pupil's life, but they can improve the learning environment. Predictable routines, emotionally and physically safe classrooms, respectful relationships, meaningful participation and opportunities for genuine success can reduce avoidable barriers.",keyPoints:["Make routines predictable","Use respectful, non-humiliating correction","Build belonging through inclusive participation","Design tasks that make success achievable without removing challenge","Notice changes and use pastoral systems when needed"]},
  {id:"ma6",type:"scenario",title:"Belonging without assumptions",prompt:"A new pupil rarely volunteers and spends break alone. Which interpretation is most appropriate?",options:[{label:"They definitely have an unmet belonging need",feedback:"That may be one possibility, but the observations do not prove it."},{label:"Notice the pattern, create low-pressure opportunities to participate, and share concerns through the appropriate pastoral route if needed",feedback:"This combines supportive classroom practice with evidence-based follow-up."},{label:"Force public group participation immediately",feedback:"Public pressure may make participation harder and does not establish why the pupil is quiet."}]},
  {id:"ma7",type:"content",title:"Esteem, competence and high expectations",body:"A useful classroom interpretation of esteem is not constant praise. Pupils benefit from credible experiences of competence: clear success criteria, appropriately challenging tasks, useful feedback and chances to improve. Support and high expectations can coexist.",keyPoints:["Praise should be specific and credible","Teach pupils how to improve","Use scaffolds that preserve the learning goal","Create multiple ways for pupils to contribute successfully"]},
  {id:"ma8",type:"quiz",title:"Critical-thinking check",question:"Which statement best reflects the limitations of Maslow's hierarchy?",options:["The five areas are useless in any context","Everyone must satisfy each level fully before the next can matter","The need areas can be a useful prompt, but evidence does not support treating the order as a strict universal sequence","A teacher can infer a pupil's home circumstances from classroom behaviour"],answer:2,feedback:"Use the framework as a prompt for professional curiosity, not as a fixed law or a shortcut to conclusions about pupils."},
  {id:"ma9",type:"scenario",title:"Safeguarding boundary",prompt:"A pupil says they do not feel safe going home. What should you do?",options:[{label:"Try to solve the home situation yourself using Maslow's hierarchy",feedback:"This is not an appropriate classroom response to a safeguarding concern."},{label:"Listen appropriately, avoid investigating, and follow the school's safeguarding reporting procedure promptly",feedback:"Safeguarding procedures take priority over any motivational framework."},{label:"Wait several weeks to see whether motivation improves",feedback:"A disclosed safety concern should be passed through the school's safeguarding process promptly."}]},
  reflection("ma10","Choose one class. Identify one classroom condition you can improve—predictability, belonging, safety, competence or opportunity for growth—without making assumptions about individual pupils. What will you change and how will you know whether it helped?")
 ]
},
{
 id:"effective-questioning",title:"Effective Questioning",category:"Teaching & Learning",duration:60,level:"Foundation",summary:"Use purposeful questions, wait time, whole-class response and follow-up prompts to make pupil thinking visible and adapt teaching.",objectives:["Plan questions around learning goals","Increase participation without lowering challenge","Use responses diagnostically","Build routines that make pupils explain and justify thinking"],recommendedFor:["Teacher","ECT","Teaching Assistant"],modules:[
  {id:"q1x",type:"content",title:"Questions should reveal thinking",body:"A useful question helps you decide what pupils understand and what to do next. Planning a few high-value questions is often more effective than asking many low-information questions.",keyPoints:["Ask for reasoning, not only answers","Plan hinge points","Sample beyond volunteers","Build in thinking time"]},
  {id:"q2x",type:"quiz",title:"Whole-class check",question:"Which method gives the best evidence about the whole class?",options:["Ask for hands up","Ask the fastest pupil","Use a question answered simultaneously by everyone","Ask whether everyone understands"],answer:2,feedback:"Simultaneous response systems reduce sampling bias and make misconceptions easier to spot."},
  {id:"q3x",type:"scenario",title:"Wait-time scenario",prompt:"You ask a demanding question and get no response after two seconds. What is the best next move?",options:[{label:"Answer it immediately",feedback:"This may remove productive thinking time."},{label:"Give structured thinking time, perhaps rehearsal with a partner, then sample responses",feedback:"This preserves challenge while increasing access."},{label:"Replace it with a much easier question immediately",feedback:"That can hide whether pupils could answer with adequate thinking time."}]},
  {id:"q4x",type:"content",title:"Follow-up prompts",body:"The first answer is often the start of the diagnostic process. Prompts such as 'why?', 'what makes you think that?', 'can you give an example?' and 'does anyone disagree?' make reasoning visible and help pupils connect ideas."},
  {id:"q5x",type:"scenario",title:"Misconception response",prompt:"A pupil gives the correct numerical answer but cannot explain the method. What should the teacher infer?",options:[{label:"Understanding is definitely secure",feedback:"A correct answer alone may not show secure reasoning."},{label:"Probe the method and sample other pupils before deciding whether to move on",feedback:"Follow-up questions help distinguish secure understanding from guessing or procedural imitation."},{label:"Ignore the answer because explanation never matters",feedback:"Explanation can reveal the structure of the pupil's thinking."}]},
  {id:"q6x",type:"quiz",title:"Question design check",question:"Which question is most useful as a hinge question?",options:["One that takes ten minutes to mark","One where common wrong answers correspond to useful misconceptions","One that only the highest-attaining pupil can answer","One asked after the lesson has ended"],answer:1,feedback:"A good hinge question is quick to answer and interpret, and its distractors reveal meaningful misunderstandings."},
  reflection("q7x","Write one hinge question for an upcoming lesson, including three plausible wrong answers and what each wrong answer would tell you.")
 ]
},
{
 id:"retrieval-practice",title:"Retrieval Practice That Improves Learning",category:"Teaching & Learning",duration:55,level:"Foundation",summary:"Use low-stakes retrieval, spacing and feedback to strengthen access to important knowledge without turning every lesson into a test.",objectives:["Distinguish retrieval from rereading","Select high-value knowledge for retrieval","Use spacing and mixed review","Correct errors after retrieval"],recommendedFor:["Teacher","ECT"],modules:[
  {id:"rt1",type:"content",title:"What retrieval is",body:"Retrieval practice requires pupils to bring information to mind before seeing the answer. The effort of successful recall can strengthen later access to that knowledge, particularly when retrieval is spaced and followed by feedback.",keyPoints:["Recall before checking","Keep stakes low","Revisit after delays","Correct errors"]},
  {id:"rt2",type:"quiz",title:"Retrieval or review?",question:"Which task is retrieval practice?",options:["Copying a definition","Rereading a highlighted page","Answering a question from memory, then checking and correcting","Watching the same explanation again"],answer:2,feedback:"The defining feature is attempting to retrieve before the answer is supplied."},
  {id:"rt3",type:"content",title:"Select what is worth retrieving",body:"Retrieval time is limited. Prioritise knowledge that pupils will need repeatedly: key vocabulary, concepts, procedures, relationships and prerequisite knowledge that unlocks later topics."},
  {id:"rt4",type:"scenario",title:"Starter design",prompt:"Your daily starter always asks yesterday's five questions. Pupils score highly but forget earlier units. What change is strongest?",options:[{label:"Make yesterday's questions easier",feedback:"This does not address longer-term forgetting."},{label:"Mix a small amount of recent material with important knowledge from previous weeks and months",feedback:"Spacing and cumulative review strengthen access to older learning."},{label:"Stop giving feedback",feedback:"Uncorrected errors can become reinforced."}]},
  {id:"rt5",type:"quiz",title:"Feedback check",question:"Why should retrieval usually be followed by feedback?",options:["So pupils can compare handwriting","To correct errors and strengthen the intended answer","Because retrieval only works if every answer was initially correct","To make the task high stakes"],answer:1,feedback:"Feedback is especially important when retrieval attempts are unsuccessful or uncertain."},
  {id:"rt6",type:"scenario",title:"Difficulty level",prompt:"A retrieval quiz produces near-zero success across the class. What is the best response?",options:[{label:"Keep repeating exactly the same inaccessible quiz without support",feedback:"Repeated failure gives little useful successful retrieval."},{label:"Diagnose the gap, reteach or cue where needed, then return to retrieval after pupils can access the knowledge",feedback:"Retrieval should be effortful but possible enough to generate successful recall and useful feedback."},{label:"Record the score as a final grade",feedback:"The purpose here is learning and diagnosis, not high-stakes judgement."}]},
  reflection("rt7","Design a five-minute cumulative retrieval routine for one class. Which knowledge will appear tomorrow, next week and next month, and how will pupils check corrections?")
 ]
},
{
 id:"adaptive-teaching",title:"Adaptive Teaching in Practice",category:"Teaching & Learning",duration:70,level:"Developing",summary:"Maintain ambitious learning goals while adapting explanations, scaffolds, representations and practice in response to evidence of pupil need.",objectives:["Separate adaptation from lowered expectations","Anticipate barriers in tasks","Select temporary scaffolds","Use checks to decide when support should change"],recommendedFor:["Teacher","ECT","Teaching Assistant"],modules:[
  {id:"at1",type:"content",title:"Keep the goal, adapt the route",body:"Adaptive teaching starts from a shared ambitious learning goal. Teachers vary explanations, models, practice, vocabulary support or scaffolding so that pupils can access the same important learning wherever appropriate.",keyPoints:["Know the learning goal","Anticipate barriers","Use pupil-specific information","Adapt responsively rather than by fixed labels"]},
  {id:"at2",type:"scenario",title:"Writing barrier",prompt:"Several pupils can explain the concept orally but cannot organise an extended written response. What is a sensible adaptation?",options:[{label:"Give them a different, much easier concept",feedback:"This changes the learning goal rather than the access barrier."},{label:"Provide a temporary structure or model for organising the same conceptual response",feedback:"This preserves ambition while supporting the specific difficulty."},{label:"Write the answer for them",feedback:"That removes the thinking and practice pupils need."}]},
  {id:"at3",type:"content",title:"Scaffolds should be temporary",body:"A scaffold is useful when it helps the pupil perform thinking they could not yet organise independently. If the scaffold remains forever, it can become a dependency. Plan how prompts, sentence stems, worked examples or checklists will reduce as competence grows."},
  {id:"at4",type:"quiz",title:"Adaptation check",question:"Which is the strongest example of adaptive teaching?",options:["Giving every pupil with the same label identical work","Using checks to identify a barrier, adding targeted support and reviewing whether it can be faded","Permanently lowering the curriculum for any pupil who struggles once","Creating a separate worksheet for every pupil in every lesson"],answer:1,feedback:"Adaptive teaching is responsive to evidence and aims to preserve ambitious learning while varying support."},
  {id:"at5",type:"scenario",title:"Vocabulary barrier",prompt:"Pupils understand a process when demonstrated but struggle with the technical language used in exam questions. What is the strongest adaptation?",options:[{label:"Remove technical vocabulary permanently",feedback:"Pupils still need access to disciplinary language."},{label:"Explicitly teach and revisit the key terms, model their use, and provide temporary language prompts",feedback:"This addresses the language barrier while preserving the subject demand."},{label:"Ignore the issue because vocabulary is not part of learning",feedback:"Language can be a major access route to disciplinary knowledge and assessment."}]},
  {id:"at6",type:"content",title:"Use assessment to adjust support",body:"Adaptation should change when evidence changes. Short checks, pupil work, questioning and observation help decide whether to re-explain, model differently, add a scaffold, provide more practice or remove support."},
  reflection("at7","Choose one upcoming task and one pupil or group who may face a barrier. State the learning goal, the likely barrier, the temporary adaptation and the evidence you will use to decide whether to keep, change or fade it.")
 ]
}
];
