import type { Course, CourseCategory } from "./data";

export const PRESENTATION_OVERHAUL_PHASE26_VERSION = "2026.27";

export type Phase26Option={id:string;label:string;best:boolean};
export type Phase26Point={id:string;timestamp:string;scene:string;narration:string;prompt:string;options:Phase26Option[];feedback:string};
export type Phase26Pack={id:string;anchorId:string;title:string;context:string;points:Phase26Point[]};
export type Phase26Audit={courseId:string;title:string;decisionPoints:number;videoStyle:boolean;transcript:boolean;anchorFound:boolean;ready:boolean;score:number};

type PointTuple=[string,string,string,string,string,string[],number,string];
type Lens={title:string;context:string;points:PointTuple[]};

function safeId(v:string){return v.replace(/[^a-z0-9-]/gi,"-").replace(/-+/g,"-").replace(/^-|-$/g,"").toLowerCase();}
function opts(labels:string[],best:number){return labels.map((label,index)=>({id:String.fromCharCode(65+index),label,best:index===best}));}
function anchor(course:Course){return course.modules.find(m=>m.type==="scenario")?.id||course.modules.find(m=>m.type==="activity")?.id||course.modules.find(m=>m.type==="content")?.id||course.modules[0]?.id||"";}
function p(id:string,time:string,scene:string,narration:string,prompt:string,labels:string[],best:number,feedback:string):PointTuple{return[id,time,scene,narration,prompt,labels,best,feedback];}

function lens(category:CourseCategory,course:Course):Lens{
  if(category==="Safeguarding")return{title:"Safeguarding: the corridor conversation",context:"A short scenario pauses at the points where calm listening, factual recording and correct reporting matter most.",points:[
    p("listen","00:12","A pupil asks to speak privately and begins with an incomplete concern.","The member of staff notices the pupil is hesitant and avoids filling the silence for them.","What should happen next?",["Listen calmly and clarify only what is necessary for immediate safety","Ask detailed questions until the full account is established","Promise confidentiality so the pupil keeps talking"],0,"The staff role is to listen and respond safely, not conduct an investigation or promise secrecy."),
    p("record","00:27","The pupil has shared a short account and returns to lesson.","The member of staff opens the school's reporting route and prepares a factual record.","Which approach is strongest?",["Record what was observed or said, distinguishing fact from interpretation","Write what the member of staff thinks probably happened","Wait until another colleague confirms the concern"],0,"A clear factual record protects the integrity of the information and supports the designated safeguarding process."),
    p("report","00:41","The concern has been recorded but the member of staff is unsure whether it is serious enough.","The scenario pauses before the final professional decision.","What should determine the next step?",["Follow the school's current safeguarding procedure and pass the concern through the designated route","Keep the concern personally unless further proof appears","Discuss it informally with several colleagues first"],0,"Staff pass concerns through the school's safeguarding route; designated staff determine the next safeguarding response."),
  ]};
  if(category==="SEND")return{title:"Adaptive teaching: the stuck start",context:"A learner understands the idea verbally but cannot begin a multi-step written task independently.",points:[
    p("notice","00:10","The teacher circulates after independent work begins.","One learner can explain the concept aloud but has not started the written task.","What is the most useful first interpretation?",["There may be an access barrier in the task demands","The learning goal is definitely too difficult","The learner is choosing not to work"],0,"Start by identifying the barrier in this task rather than assuming ability or motivation."),
    p("support","00:24","The teacher considers how to help without removing the thinking.","A visible sequence of the task steps is available on the desk.","Which response best protects ambition?",["Use a brief visual sequence or start cue while keeping the same learning goal","Replace the task with a permanently easier objective","Complete the first half of the task for the learner"],0,"A proportionate scaffold improves access while preserving the cognitive work."),
    p("fade","00:39","The learner completes the next example with less prompting.","The teacher decides what to do on the next similar task.","What is the strongest next step?",["Check whether the learner can now start with less support and fade the scaffold if appropriate","Keep every prompt permanently because it worked once","Remove all support immediately without checking independence"],0,"Adaptive support should respond to evidence and move towards independence where possible."),
  ]};
  if(category==="Leadership")return{title:"Leadership: the inconsistent initiative",context:"A department priority is visible in some classrooms but inconsistent across the team.",points:[
    p("clarify","00:11","A leader reviews examples of practice from across the department.","The evidence shows staff are interpreting the same expectation in different ways.","What should the leader do first?",["Re-establish the small core practice and why it matters","Increase monitoring immediately without further clarification","Add a second initiative to create momentum"],0,"Consistency requires a clear shared understanding before monitoring can be diagnostic."),
    p("diagnose","00:26","The team can now describe the expectation accurately.","Several colleagues explain that time and workflow make the routine hard to sustain.","What is the strongest response?",["Identify whether the barrier is capability, capacity or system design and target support accordingly","Treat inconsistency as a motivation problem","Publish a comparison of individual staff performance"],0,"A precise implementation diagnosis leads to more proportionate support."),
    p("review","00:43","Targeted support has been in place for several weeks.","The leader has implementation evidence and staff feedback.","What should happen next?",["Review intended outcomes, implementation and workload, then decide what to keep or adapt","Keep the process unchanged because it has already launched","Judge success only by visible compliance"],0,"Review should connect evidence to a deliberate keep, adapt or stop decision."),
  ]};
  if(category==="Wellbeing")return{title:"Wellbeing: the duplicated workflow",context:"A team reports that a recurring process is taking more time than the educational value it produces.",points:[
    p("signal","00:09","Several staff describe the same weekly pressure point.","The leader checks whether the complaint reflects a repeatable workflow pattern.","What evidence is most useful?",["Repeated staff experience plus where time is being spent in the process","A single wellbeing survey score with no process detail","How positive the last wellbeing event felt"],0,"Workload improvement is stronger when it connects staff experience to a specific system."),
    p("change","00:23","The review finds the same information is entered twice.","The team proposes a small process change.","Which change is easiest to evaluate?",["Remove or merge the duplicated step and compare the workflow before and after","Launch several wellbeing initiatives at once","Ask staff to work faster within the same process"],0,"A bounded system change makes cause and effect easier to judge."),
    p("check","00:37","The revised process saves time for one team.","A second team now completes a new handoff step.","What should the review ask?",["Whether total avoidable burden reduced across everyone affected","Whether the first team is satisfied","Whether the change can be declared complete immediately"],0,"System improvement should not simply move workload from one group to another."),
  ]};
  if(category==="Digital Teaching")return{title:"Digital practice: the AI-assisted resource",context:"A member of staff uses a digital tool to draft a pupil-facing resource and must decide how to check it before use.",points:[
    p("purpose","00:08","The teacher identifies a repetitive drafting task.","A digital tool could save preparation time.","What should be defined before choosing the tool?",["The professional task, intended benefit and boundaries","The most impressive feature available","How quickly the output can be generated"],0,"Purpose and boundaries make it possible to judge whether a tool is genuinely useful."),
    p("verify","00:22","The generated resource is fluent but includes factual claims.","The teacher prepares to use it with pupils.","What is the strongest next action?",["Verify important claims and check educational suitability before use","Assume fluent wording means the content is accurate","Give the resource to pupils and correct errors later"],0,"Fluency is not evidence of accuracy; verification should match the consequence of the task."),
    p("responsibility","00:36","The resource is ready for final approval.","The tool has suggested a judgement about a pupil's needs.","Who owns the final professional decision?",["The staff member, using appropriate evidence and school procedures","The digital tool because it processed more information","Whoever wrote the original prompt"],0,"Digital tools can support professional work but do not remove human accountability."),
  ]};
  return{title:`Teaching decision film: ${course.title}`,context:"A classroom moment develops in three short scenes. Pause at each decision point and choose the response most likely to reveal or improve learning.",points:[
    p("notice","00:10","A lesson is underway and pupil responses show uneven understanding.","The teacher notices a learning signal rather than relying on how busy the room looks.","What should the teacher use first?",["Evidence of pupil thinking from responses or work","How quiet the class appears","How much of the activity has been completed"],0,"The strongest teaching decision begins with evidence of thinking."),
    p("respond","00:25","The teacher identifies a specific misconception or access barrier.","There is time for one deliberate response before pupils continue.","What is the strongest move?",["Choose a targeted explanation, model, contrast or scaffold linked to the diagnosis","Add several unrelated activities","Repeat the original instruction unchanged"],0,"Targeted action keeps the response connected to the diagnosed problem."),
    p("check","00:40","Pupils have practised with support and appear more confident.","The teacher needs evidence that the improvement will transfer.","What completes the cycle?",["An independent check that informs the next teaching decision","A show of hands asking whether pupils understand","Moving on because guided practice looked successful"],0,"Independent evidence distinguishes temporary supported success from secure learning."),
  ]};
}

export function getPhase26Pack(course:Course):Phase26Pack{const l=lens(course.category,course);return{id:`phase26-${safeId(course.id)}`,anchorId:anchor(course),title:l.title,context:l.context,points:l.points.map(([id,timestamp,scene,narration,prompt,labels,best,feedback])=>({id,timestamp,scene,narration,prompt,options:opts(labels,best),feedback}))};}
export function validateVideoDecisionPointsPhase26(course:Course){const pack=getPhase26Pack(course);if(!pack.anchorId)throw new Error(`Phase 26 ${course.id}: missing scenario anchor`);if(pack.points.length!==3)throw new Error(`Phase 26 ${course.id}: requires three decision points`);if(pack.points.some(point=>point.options.length<3||point.options.filter(o=>o.best).length!==1))throw new Error(`Phase 26 ${course.id}: each pause needs one strongest response`);if(pack.points.some(point=>!point.scene||!point.narration||!point.timestamp))throw new Error(`Phase 26 ${course.id}: incomplete video-style scene`);return true;}
export function auditVideoDecisionPointsPhase26(course:Course):Phase26Audit{const pack=getPhase26Pack(course);let ready=true;try{validateVideoDecisionPointsPhase26(course);}catch{ready=false;}const anchorFound=course.modules.some(m=>m.id===pack.anchorId);const score=Math.min(100,(pack.points.length===3?30:0)+(pack.points.every(p=>p.scene&&p.narration)?20:0)+(pack.points.every(p=>p.options.length>=3)?20:0)+(anchorFound?20:0)+(ready?10:0));return{courseId:course.id,title:course.title,decisionPoints:pack.points.length,videoStyle:true,transcript:true,anchorFound,ready,score};}
export function summariseVideoDecisionPointsPhase26(courses:Course[]){const reports=courses.map(auditVideoDecisionPointsPhase26);return{courseCount:reports.length,ready:reports.filter(r=>r.ready).length,totalDecisionPoints:reports.reduce((sum,r)=>sum+r.decisionPoints,0),videoStyle:reports.filter(r=>r.videoStyle).length,transcriptReady:reports.filter(r=>r.transcript).length,averageScore:reports.length?Math.round(reports.reduce((sum,r)=>sum+r.score,0)/reports.length):0,reports};}
