import type { Course, Module } from "./data";

const reflect = (id: string, prompt: string): Module => ({ id, type: "reflection", title: "Apply it to your practice", prompt });

export const deepTeachingCourses2: Course[] = [
  {
    id: "retrieval-practice",
    title: "Retrieval Practice That Improves Learning",
    category: "Teaching & Learning",
    duration: 85,
    level: "Developing",
    summary: "Design retrieval that strengthens access to important knowledge over time, uses spacing and feedback intelligently, and avoids turning retrieval into repetitive quizzing for its own sake.",
    objectives: ["Distinguish retrieval from rereading and recognition", "Select high-value knowledge for cumulative retrieval", "Use spacing, interleaving and feedback appropriately", "Adjust retrieval difficulty when success is too high or too low", "Build subject-specific retrieval that includes application as well as recall"],
    recommendedFor: ["Teacher", "ECT", "Teaching Assistant", "Department Lead"],
    modules: [
      { id: "rt1", type: "content", title: "What retrieval actually is", body: "Retrieval practice requires pupils to attempt to bring information to mind before the answer is supplied. This is different from rereading, copying or recognising an answer that is already visible. Retrieval can involve facts, vocabulary, procedures, diagrams, explanations, relationships or worked steps. Its purpose is not simply to produce a score; it is to strengthen future access to knowledge and reveal what needs more teaching.", keyPoints: ["Attempt recall before seeing the answer", "Keep the stakes low when the purpose is learning", "Retrieve important knowledge repeatedly over time", "Use errors as diagnostic information", "Include conceptual and procedural knowledge, not only isolated facts"] },
      { id: "rt2", type: "quiz", title: "Retrieval or review?", question: "Which task is retrieval practice?", options: ["Copying a definition", "Rereading a highlighted page", "Answering a question from memory, then checking and correcting", "Watching the same explanation again"], answer: 2, feedback: "The defining feature is attempting to retrieve before the answer is supplied." },
      { id: "rt3", type: "content", title: "Select what is worth retrieving", body: "Retrieval time is limited, so the strongest routines prioritise knowledge with future value. That includes prerequisite concepts, disciplinary vocabulary, procedures, relationships, key examples and ideas pupils will need to recognise in new contexts. A retrieval starter containing trivia from yesterday may feel busy without strengthening the curriculum. Start from the curriculum map: what will pupils need again next week, next month and next year?", keyPoints: ["Prioritise knowledge with long-term curriculum value", "Include prerequisite knowledge", "Retrieve relationships as well as labels", "Use curriculum sequencing to choose content", "Avoid filling retrieval time with low-value trivia"] },
      { id: "rt4", type: "scenario", title: "Starter design", prompt: "Your daily starter always asks yesterday's five questions. Pupils score highly but forget earlier units. What change is strongest?", options: [{ label: "Make yesterday's questions easier", feedback: "This does not address longer-term forgetting." }, { label: "Mix a small amount of recent material with important knowledge from previous weeks and months", feedback: "Spacing and cumulative review strengthen access to older learning." }, { label: "Stop giving feedback", feedback: "Uncorrected errors can become reinforced." }] },
      { id: "rt5", type: "quiz", title: "Feedback check", question: "Why should retrieval usually be followed by feedback?", options: ["So pupils can compare handwriting", "To correct errors and strengthen the intended answer", "Because retrieval only works if every answer was initially correct", "To make the task high stakes"], answer: 1, feedback: "Feedback is especially important when retrieval attempts are unsuccessful or uncertain." },
      { id: "rt6", type: "scenario", title: "Difficulty level", prompt: "A retrieval quiz produces near-zero success across the class. What is the best response?", options: [{ label: "Keep repeating exactly the same inaccessible quiz without support", feedback: "Repeated failure gives little useful successful retrieval." }, { label: "Diagnose the gap, reteach or cue where needed, then return to retrieval after pupils can access the knowledge", feedback: "Retrieval should be effortful but possible enough to generate successful recall and useful feedback." }, { label: "Record the score as a final grade", feedback: "The purpose here is learning and diagnosis, not high-stakes judgement." }] },
      { id: "rt7", type: "reflection", title: "Apply it to your practice", prompt: "Design a five-minute cumulative retrieval routine for one class. Which knowledge will appear tomorrow, next week and next month, and how will pupils check corrections?" },
      { id: "rt8", type: "visual", title: "A spacing cycle", layout: "timeline", caption: "Spacing means returning after a delay rather than clustering all review immediately after teaching.", items: [
        { heading: "Teach", text: "Establish the idea clearly enough that pupils have something to retrieve.", icon: "1" },
        { heading: "Tomorrow", text: "Retrieve the core idea soon after initial learning.", icon: "2" },
        { heading: "Next week", text: "Retrieve after some forgetting has occurred.", icon: "3" },
        { heading: "Later unit", text: "Use the knowledge again in a different context.", icon: "4" },
        { heading: "Long-term review", text: "Return to high-value knowledge cumulatively.", icon: "5" }
      ] },
      { id: "rt9", type: "content", title: "Spacing, interleaving and desirable difficulty", body: "Retrieval should not be made difficult merely to make it feel rigorous. Spacing creates useful effort because some forgetting has occurred. Interleaving can help when pupils must distinguish between related problem types or concepts, but mixing everything too early can overwhelm novices. The design question is whether the difficulty helps pupils retrieve, discriminate or transfer the intended knowledge rather than simply increasing failure.", keyPoints: ["Space important knowledge over time", "Interleave when discrimination between similar ideas matters", "Do not mix too much before core knowledge is secure", "Use success patterns to adjust difficulty", "Productive effort should still produce useful feedback"] },
      { id: "rt10", type: "scenario", title: "Interleaving scenario", prompt: "Pupils can solve each maths problem type when practised in separate blocks but choose the wrong method when problems are mixed. What is the strongest next step?", options: [{ label: "Keep every method permanently in separate blocks", feedback: "This does not practise choosing between methods." }, { label: "Use a mixed set and ask pupils to identify which method applies before solving, with feedback on the choice", feedback: "Interleaving can help pupils discriminate between problem types once the individual methods are sufficiently familiar." }, { label: "Remove feedback so pupils become independent", feedback: "Feedback remains useful while the discrimination is being learned." }] },
      { id: "rt11", type: "content", title: "Retrieval beyond simple recall", body: "Retrieval can include explanation and application. Pupils might label a diagram from memory, recreate a process, explain why two concepts differ, complete part of a worked problem, sketch a graph, write a causal chain or recall evidence for an argument. Subject-specific retrieval is strongest when it rehearses the forms of knowledge pupils will later need to use, not just definitions detached from context.", keyPoints: ["Use diagrams, sequences, examples and explanations", "Retrieve procedures as well as facts", "Ask pupils to connect ideas", "Include occasional application after core recall", "Keep tasks short enough that retrieval remains practical"] },
      { id: "rt12", type: "activity", title: "Build a one-month retrieval map", prompt: "Create a cumulative retrieval plan for one unit or half term.", instructions: ["List five to ten pieces of high-value knowledge.", "Identify which items are prerequisites for later content.", "Schedule each item for short-term, one-week and later retrieval.", "Choose at least two different retrieval formats.", "State how pupils will correct errors.", "Add one application task that combines several items."], placeholder: "High-value knowledge…\nPrerequisites…\nTomorrow…\nNext week…\nLater…\nRetrieval formats…\nFeedback…\nApplication…", minimumCharacters: 220 },
      { id: "rt13", type: "checklist", title: "Retrieval-quality audit", prompt: "Audit a retrieval routine before using it regularly.", items: ["The knowledge is worth remembering", "Pupils attempt retrieval before seeing answers", "Older material is included", "Feedback/correction follows", "Difficulty is achievable enough to generate useful retrieval", "The routine is low stakes when used for learning", "Different forms of knowledge are represented", "The routine does not consume disproportionate lesson time", "Results inform later teaching"], completionText: "Retrieval-quality audit complete." },
      { id: "rt14", type: "quiz", title: "Final retrieval check", question: "Which statement best captures effective retrieval practice?", options: ["The same five questions every day regardless of curriculum", "Frequent high-stakes testing", "Planned attempts to recall important knowledge over increasing intervals, followed by useful feedback", "Rereading notes until they feel familiar"], answer: 2, feedback: "Effective retrieval is planned around valuable knowledge, spaced over time and followed by feedback." }
    ]
  },
  {
    id: "adaptive-teaching",
    title: "Adaptive Teaching in Practice",
    category: "Teaching & Learning",
    duration: 95,
    level: "Developing",
    summary: "Maintain ambitious learning while adapting explanations, scaffolds, representations, language support, practice and classroom conditions in response to evidence of pupil need.",
    objectives: ["Separate adaptive teaching from automatic lowering of expectations", "Analyse barriers in tasks and explanations", "Choose proportionate scaffolds and representations", "Use assessment evidence to adapt support in real time", "Plan how temporary scaffolds will fade as independence grows"],
    recommendedFor: ["Teacher", "ECT", "Teaching Assistant", "Department Lead"],
    modules: [
      { id: "at1", type: "content", title: "Keep the goal, adapt the route", body: "Adaptive teaching starts from clarity about the intended learning. The teacher then varies explanations, examples, representations, language support, practice, grouping, scaffolds or environmental conditions so pupils can access that learning. This is different from permanently creating easier parallel curricula whenever a pupil struggles. Some pupils do need individualised goals, but those decisions should come from appropriate assessment and planning rather than assumptions.", keyPoints: ["Start with the intended learning", "Identify the specific barrier", "Use pupil-specific information", "Adapt the route before automatically lowering the destination", "Review whether the support is working"] },
      { id: "at2", type: "scenario", title: "Writing barrier", prompt: "Several pupils can explain the concept orally but cannot organise an extended written response. What is a sensible adaptation?", options: [{ label: "Give them a different, much easier concept", feedback: "This changes the learning goal rather than the access barrier." }, { label: "Provide a temporary structure or model for organising the same conceptual response", feedback: "This preserves ambition while supporting the specific difficulty." }, { label: "Write the answer for them", feedback: "That removes the thinking and practice pupils need." }] },
      { id: "at3", type: "content", title: "Scaffolds should be temporary where possible", body: "A scaffold is useful when it enables pupils to perform important thinking they could not yet organise independently. Sentence stems, worked examples, checklists, visual prompts, vocabulary banks and partially completed models can all be effective. The risk is not scaffolding itself but support that remains unchanged long after pupils can cope with less. Teachers should plan what evidence would justify reducing or removing the scaffold.", keyPoints: ["Match scaffolds to a specific barrier", "Keep the important thinking with the pupil", "Teach pupils how to use the scaffold", "Collect evidence of growing independence", "Fade support deliberately when appropriate"] },
      { id: "at4", type: "quiz", title: "Adaptation check", question: "Which is the strongest example of adaptive teaching?", options: ["Giving every pupil with the same label identical work", "Using checks to identify a barrier, adding targeted support and reviewing whether it can be faded", "Permanently lowering the curriculum for any pupil who struggles once", "Creating a separate worksheet for every pupil in every lesson"], answer: 1, feedback: "Adaptive teaching is responsive to evidence and aims to preserve ambitious learning while varying support." },
      { id: "at5", type: "scenario", title: "Vocabulary barrier", prompt: "Pupils understand a process when demonstrated but struggle with the technical language used in exam questions. What is the strongest adaptation?", options: [{ label: "Remove technical vocabulary permanently", feedback: "Pupils still need access to disciplinary language." }, { label: "Explicitly teach and revisit the key terms, model their use, and provide temporary language prompts", feedback: "This addresses the language barrier while preserving the subject demand." }, { label: "Ignore the issue because vocabulary is not part of learning", feedback: "Language can be a major access route to disciplinary knowledge and assessment." }] },
      { id: "at6", type: "content", title: "Use assessment to adjust support", body: "Adaptation should change when evidence changes. Short checks, pupil work, questioning and observation help decide whether to re-explain, model differently, add a scaffold, provide more practice, change a representation or remove support. Adaptive teaching is therefore inseparable from formative assessment: without evidence, adaptation can become guesswork.", keyPoints: ["Use quick checks before changing support", "Look for patterns across the class", "Distinguish lack of knowledge from access barriers", "Re-model when a common misconception persists", "Remove support when pupils no longer need it"] },
      { id: "at7", type: "reflection", title: "Apply it to your practice", prompt: "Choose one upcoming task and one pupil or group who may face a barrier. State the learning goal, the likely barrier, the temporary adaptation and the evidence you will use to decide whether to keep, change or fade it." },
      { id: "at8", type: "visual", title: "Adaptive teaching decision cycle", layout: "cycle", items: [
        { heading: "Clarify", text: "What is the important learning goal?", icon: "1" },
        { heading: "Anticipate", text: "What demands could create barriers?", icon: "2" },
        { heading: "Teach", text: "Use strong universal instruction first.", icon: "3" },
        { heading: "Check", text: "Gather evidence of understanding and access.", icon: "4" },
        { heading: "Adapt", text: "Change support, explanation, representation or practice.", icon: "5" },
        { heading: "Review", text: "Keep, change or fade the adaptation.", icon: "6" }
      ] },
      { id: "at9", type: "content", title: "Universal support before unnecessary individualisation", body: "Many adaptations can be designed into ordinary teaching: clear explanations, explicit vocabulary, visible instructions, worked examples, chunked tasks, predictable routines and multiple checks for understanding. Good universal design reduces the number of pupils who need a separate workaround. Individual support remains important where universal teaching does not remove the barrier, but the goal is not to create a different lesson for every pupil.", keyPoints: ["Strengthen universal teaching first", "Use accessible layouts and clear routines", "Teach vocabulary explicitly", "Make instructions visible where useful", "Add individual adaptations when evidence shows they are needed"] },
      { id: "at10", type: "scenario", title: "Over-differentiation scenario", prompt: "A teacher prepares four worksheets with different learning goals for four broad ability groups every lesson. What is the main concern?", options: [{ label: "Differentiation is always wrong", feedback: "Different goals can be appropriate in some circumstances." }, { label: "Fixed grouping and permanently different goals may lower expectations and create unnecessary workload when shared ambitious goals with targeted support would be possible", feedback: "Adaptive teaching asks whether support can vary while important learning remains shared." }, { label: "The teacher should instead give everyone identical support", feedback: "Adaptive teaching still responds to real barriers and pupil-specific information." }] },
      { id: "at11", type: "content", title: "Representations: choose them for meaning, not decoration", body: "Alternative representations can make an idea more accessible, but adding more representations does not automatically help. A diagram, manipulatives, worked example, concrete model or sentence frame should make a relationship clearer. Teachers should explain how the representation connects to the underlying concept and avoid presenting several unfamiliar representations at once if pupils do not yet understand any of them.", keyPoints: ["Choose representations that expose important structure", "Explain the connection to the concept", "Avoid unnecessary novelty", "Move between representations deliberately", "Check that pupils can interpret the representation"] },
      { id: "at12", type: "activity", title: "Adaptive lesson redesign", prompt: "Redesign one upcoming task using an evidence-first adaptive approach.", instructions: ["State the shared learning goal.", "List the main cognitive, language, literacy, sensory or executive demands.", "Identify one likely barrier.", "Choose one universal support and one targeted adaptation if needed.", "Write the check that will tell you whether the adaptation is working.", "State how support could be faded."], placeholder: "Learning goal…\nTask demands…\nBarrier…\nUniversal support…\nTargeted adaptation…\nCheck…\nFade when…", minimumCharacters: 230 },
      { id: "at13", type: "checklist", title: "Adaptive-planning audit", prompt: "Check an upcoming lesson for responsive adaptation rather than unnecessary complexity.", items: ["The learning goal is clear", "Likely barriers have been anticipated", "Strong universal teaching is planned", "Technical language is explicitly supported where needed", "Scaffolds have a clear purpose", "Checks for understanding are built in", "There is a response plan for common misconceptions", "Targeted support does not remove the core thinking", "There is a plan to review/fade support"], completionText: "Adaptive-planning audit complete." },
      { id: "at14", type: "quiz", title: "Final adaptive-teaching check", question: "What makes an adaptation adaptive rather than simply different?", options: ["It uses a different worksheet", "It responds to evidence about a barrier while preserving the intended learning as far as appropriate", "It permanently lowers challenge", "It is unique to one pupil"], answer: 1, feedback: "Adaptive teaching is defined by responsive support linked to evidence and the learning goal, not by producing different materials for their own sake." }
    ]
  },
  {
    id: "effective-feedback",
    title: "Feedback That Leads to Improvement",
    category: "Teaching & Learning",
    duration: 85,
    level: "Developing",
    summary: "Design feedback around learning goals, manageable next steps and pupil action so it improves performance without creating unnecessary marking workload.",
    objectives: ["Identify when feedback is likely to help", "Choose task, process or self-regulation feedback deliberately", "Prioritise the most useful next step", "Build pupil response time into teaching", "Use whole-class feedback and exemplars efficiently"],
    recommendedFor: ["Teacher", "ECT", "Department Lead"],
    modules: [
      { id: "fb1", type: "content", title: "Feedback is information for action", body: "Feedback is useful when it helps a learner close a meaningful gap between current performance and the learning goal. The amount written is much less important than whether the pupil understands the message, can act on it and has an opportunity to do so. Feedback therefore begins with clarity about the goal and ends with changed performance, not with the teacher finishing the marking.", keyPoints: ["Link feedback to the learning goal", "Prioritise one or two high-value changes", "Make the next step understandable", "Provide time to act", "Check whether the response improved performance"] },
      { id: "fb2", type: "quiz", title: "Feedback check", question: "Which feature most increases the chance that feedback improves learning?", options: ["Maximum written detail", "A clear, usable next step followed by time and expectation to act on it", "A grade with no explanation", "Giving feedback long after the knowledge is needed"], answer: 1, feedback: "Feedback needs both usable information and an opportunity for the learner to respond." },
      { id: "fb3", type: "content", title: "Choose the right level of feedback", body: "Task feedback identifies something about the specific answer. Process feedback focuses on the method or strategy used. Self-regulation feedback helps pupils monitor and improve their own work. Personal comments such as 'clever' or 'good student' provide much less information about what to do next. The most useful level depends on the cause of the error: a missing fact, a flawed process or weak monitoring require different responses.", keyPoints: ["Diagnose the cause before giving the comment", "Use task feedback for specific errors", "Use process feedback for strategy improvement", "Build self-checking routines over time", "Avoid vague person-focused praise as the main feedback"] },
      { id: "fb4", type: "scenario", title: "Whole-class pattern", prompt: "You notice the same misconception in two-thirds of a class's books. What is likely to be the most efficient response?", options: [{ label: "Write the same long paragraph in every book", feedback: "This creates workload without guaranteeing pupil action." }, { label: "Plan a short whole-class reteach/check, then require pupils to correct or reattempt the relevant part", feedback: "Common misconceptions are often better addressed collectively and followed by pupil action." }, { label: "Ignore it because marking is complete", feedback: "The misconception should inform subsequent teaching." }] },
      { id: "fb5", type: "scenario", title: "Too much feedback", prompt: "A pupil receives corrections on ten separate features of one paragraph and changes none of them. What should you consider?", options: [{ label: "Add another ten comments", feedback: "More information may increase overload." }, { label: "Prioritise the most important next step, model it if necessary and build in response time", feedback: "Focused feedback is more actionable and easier to learn from." }, { label: "Give no future feedback", feedback: "The issue is design and actionability, not feedback itself." }] },
      { id: "fb6", type: "quiz", title: "Workload check", question: "Which approach can reduce teacher workload without reducing feedback quality?", options: ["Duplicating identical comments", "Using whole-class feedback for common patterns and targeted individual feedback where it adds value", "Marking every piece of work in maximum detail", "Giving pupils no information about errors"], answer: 1, feedback: "Efficient feedback focuses teacher effort where it has the greatest instructional value." },
      { id: "fb7", type: "reflection", title: "Apply it to your practice", prompt: "Take one routine marking task. Redesign it so pupils receive one high-value next step and protected time to act on it. What evidence will show the feedback changed performance?" },
      { id: "fb8", type: "visual", title: "Feedback loop", layout: "cycle", items: [
        { heading: "Goal", text: "Clarify what quality or success looks like.", icon: "1" },
        { heading: "Evidence", text: "Notice the most important gap in current performance.", icon: "2" },
        { heading: "Response", text: "Choose the smallest useful feedback move.", icon: "3" },
        { heading: "Action", text: "Pupil corrects, improves or reattempts.", icon: "4" },
        { heading: "Check", text: "Teacher/pupil verifies whether performance improved.", icon: "5" }
      ] },
      { id: "fb9", type: "content", title: "Grades, comments and attention", body: "When a grade and detailed comment are given together, pupils may focus mainly on the grade. This does not mean grades should never be used, but the timing should fit the purpose. If the goal is improvement, separating formative feedback from final judgement can help direct attention towards the next action. Similarly, too many comments compete for attention; prioritisation matters.", keyPoints: ["Match feedback format to purpose", "Do not assume more comments create more learning", "Separate formative improvement from final judgement where useful", "Make the next action visible", "Check that pupils understand the feedback"] },
      { id: "fb10", type: "activity", title: "Redesign a feedback routine", prompt: "Take one existing marking or feedback routine and redesign it around pupil action.", instructions: ["State the learning goal the feedback should support.", "Identify the most common error pattern.", "Decide what should be handled whole-class and what needs individual feedback.", "Write the pupil response task.", "State when pupils will complete it.", "Describe how you will check whether performance improved."], placeholder: "Learning goal…\nCommon pattern…\nWhole-class response…\nIndividual response…\nPupil action…\nCheck…", minimumCharacters: 220 },
      { id: "fb11", type: "checklist", title: "Feedback-quality audit", prompt: "Audit a feedback routine before investing teacher time in it.", items: ["The learning goal is clear", "The feedback targets a meaningful gap", "The amount is manageable", "Common errors are handled efficiently", "Pupils know what action to take", "Time is protected for response", "The teacher will check the response", "The routine is sustainable for staff"], completionText: "Feedback-quality audit complete." },
      { id: "fb12", type: "scenario", title: "Peer feedback scenario", prompt: "Pupils give each other vague comments such as 'good work'. What is the strongest next step?", options: [{ label: "Stop peer feedback permanently", feedback: "Peer feedback can improve with better structure." }, { label: "Use clear criteria and model how to identify one specific strength and one actionable improvement", feedback: "Structured criteria and modelling make peer feedback more useful." }, { label: "Ask pupils to write longer comments without guidance", feedback: "Length alone does not improve quality." }] }
    ]
  },
  {
    id: "metacognition-self-regulation",
    title: "Metacognition and Self-Regulated Learning",
    category: "Teaching & Learning",
    duration: 90,
    level: "Developing",
    summary: "Teach pupils to plan, monitor and evaluate strategies inside authentic subject tasks, using modelling, prompts and gradual release rather than generic advice to 'think about thinking'.",
    objectives: ["Explain planning, monitoring and evaluation", "Model expert strategy selection through think-alouds", "Teach pupils to monitor whether a strategy is working", "Use prompts and checklists that gradually fade", "Build subject-specific reflection that changes future action"],
    recommendedFor: ["Teacher", "ECT", "Teaching Assistant", "Department Lead"],
    modules: [
      { id: "mc1", type: "content", title: "Metacognition happens inside subject learning", body: "Metacognition is the regulation of thinking: planning how to approach a task, monitoring progress and evaluating the result. It becomes useful when connected to real disciplinary knowledge. A pupil cannot choose an effective chemistry calculation method, historical source strategy or writing plan without enough subject knowledge to recognise the features of the task.", keyPoints: ["Planning requires knowledge of the task", "Monitoring means checking whether the strategy is working", "Evaluation should change future action", "Teach metacognition through authentic subject tasks", "Avoid generic reflection detached from curriculum content"] },
      { id: "mc2", type: "quiz", title: "Knowledge check", question: "Which teacher move most directly makes metacognitive thinking visible?", options: ["Give the final answer silently", "Think aloud while choosing, checking and revising a strategy", "Ask pupils to work faster", "Remove all support before modelling"], answer: 1, feedback: "Think-alouds expose decisions that experts often make automatically." },
      { id: "mc3", type: "content", title: "Model the decisions, not only the procedure", body: "A useful think-aloud exposes choices and monitoring: 'I could use method A or B; I am choosing A because…', 'This evidence does not answer the question yet, so I need…', or 'This result is unreasonable because…'. The teacher should model enough internal dialogue to expose expert decision-making without turning the explanation into a long monologue pupils cannot follow.", keyPoints: ["Model why a strategy is chosen", "Show error detection", "Explain when to abandon an unhelpful strategy", "Keep the think-aloud concise", "Follow modelling with pupil practice"] },
      { id: "mc4", type: "scenario", title: "Problem-solving scenario", prompt: "Pupils can copy a worked method but freeze when the problem looks slightly different. What is a useful next step?", options: [{ label: "Give more identical copying", feedback: "This may strengthen routine performance without strategy selection." }, { label: "Model how to recognise problem features, choose a strategy and check whether it fits, then let pupils practise those decisions", feedback: "This targets the metacognitive decisions behind transfer." }, { label: "Tell pupils simply to 'think harder'", feedback: "Generic advice does not reveal a usable strategy." }] },
      { id: "mc5", type: "content", title: "Prompts and gradual independence", body: "Prompts such as 'What is the goal?', 'What do I know already?', 'Which strategy fits?', 'How will I know this is working?' and 'What would I change next time?' can structure self-regulation. The long-term aim is for pupils to internalise these questions, so the external prompt should become shorter or less frequent as the routine becomes familiar.", keyPoints: ["Use a small number of reusable prompts", "Connect prompts to subject strategy", "Teach pupils what a useful answer sounds like", "Reduce prompts as independence grows", "Avoid permanent worksheet dependence"] },
      { id: "mc6", type: "scenario", title: "Reflection quality", prompt: "A pupil's evaluation says only 'I need to revise more'. How can you improve the reflection?", options: [{ label: "Accept any statement as equally useful", feedback: "Very general reflection may not change future behaviour." }, { label: "Prompt for the specific error, strategy used, evidence it worked or failed, and the change they will make next time", feedback: "Specific reflection is more likely to affect future strategy choice." }, { label: "Tell the pupil reflection is unnecessary", feedback: "The issue is quality and specificity, not reflection itself." }] },
      { id: "mc7", type: "quiz", title: "Metacognition misconception check", question: "Which statement is strongest?", options: ["Metacognition is a generic study skill that works without subject knowledge", "Metacognition is most useful when pupils regulate strategies within meaningful subject tasks", "Metacognition means pupils should discover all strategies independently", "Reflection must happen after every task regardless of value"], answer: 1, feedback: "Metacognition depends on knowledge of the task and useful strategies; it should be taught within disciplinary learning." },
      { id: "mc8", type: "visual", title: "Plan–monitor–evaluate cycle", layout: "cycle", items: [
        { heading: "Understand the goal", text: "What am I trying to produce or solve?", icon: "1" },
        { heading: "Plan", text: "What do I know and which strategy fits?", icon: "2" },
        { heading: "Monitor", text: "Is this strategy working? What evidence tells me?", icon: "3" },
        { heading: "Adjust", text: "What should I change if progress stalls?", icon: "4" },
        { heading: "Evaluate", text: "What worked, what did not and what will I do next time?", icon: "5" }
      ] },
      { id: "mc9", type: "content", title: "Teach strategy knowledge explicitly", body: "Pupils need to know not only how to use a strategy but when and why it is useful. For example, self-testing can reveal forgotten knowledge; a diagram may expose relationships; planning an essay can organise evidence before writing. Teachers should name these purposes so pupils learn to select strategies rather than following them mechanically.", keyPoints: ["Teach how the strategy works", "Teach when to use it", "Teach why it helps", "Compare strategies for different tasks", "Ask pupils to justify strategy choice"] },
      { id: "mc10", type: "activity", title: "Create a think-aloud", prompt: "Write a short teacher think-aloud for a difficult recurring task in your subject.", instructions: ["Name the task and goal.", "Identify the decision an expert makes that novices may not notice.", "Write what you would say while choosing a strategy.", "Include one monitoring check.", "Include what you would do if the strategy failed.", "Plan the pupil practice that follows."], placeholder: "Task…\nGoal…\nExpert decision…\nThink-aloud…\nMonitoring check…\nIf it fails…\nPupil practice…", minimumCharacters: 220 },
      { id: "mc11", type: "checklist", title: "Self-regulation teaching audit", prompt: "Audit a sequence intended to build pupil independence.", items: ["Pupils know the task goal", "Useful strategies have been taught", "The teacher has modelled strategy choice", "Pupils practise choosing, not just following", "Monitoring prompts are explicit", "Pupils receive feedback on strategy use", "Prompts can fade over time", "Evaluation asks for a specific future change"], completionText: "Self-regulation teaching audit complete." },
      { id: "mc12", type: "reflection", title: "Implementation reflection", prompt: "Choose one recurring task in your subject. Which planning, monitoring or evaluation decision do expert pupils make that novices often miss? How will you make that decision visible and then gradually hand it over to pupils?" }
    ]
  }
];
