import type { Course, Module } from "./data";

const reflect = (id: string, prompt: string): Module => ({ id, type: "reflection", title: "Apply it to your practice", prompt });

export const deepTeachingCourses: Course[] = [
  {
    id: "rosenshine-principles",
    title: "Rosenshine's Principles in Practice",
    category: "Teaching & Learning",
    duration: 120,
    level: "Developing",
    summary: "A detailed, practice-rich exploration of Rosenshine's ten principles, showing how review, modelling, questioning, guided practice, checking, scaffolding and independent practice fit together without becoming a rigid lesson template.",
    objectives: [
      "Explain each of Rosenshine's ten principles and the instructional reasoning behind it",
      "Distinguish the principles from a fixed ten-step lesson structure",
      "Design review, explanation, modelling, guided practice and checking as a coherent sequence",
      "Use evidence from pupil responses to decide when to re-teach, scaffold, fade support or move on",
      "Plan longer-term review and independent practice that builds durable knowledge"
    ],
    recommendedFor: ["Teacher", "ECT", "Teaching Assistant", "Department Lead", "Coach"],
    modules: [
      { id: "ro1", type: "content", title: "What Rosenshine was trying to capture", body: "Rosenshine synthesised findings from cognitive science, studies of classroom instruction and observation of effective teachers. His principles are best understood as a connected set of instructional habits that help novices acquire, practise and eventually use new knowledge independently. They are not a script and they do not require every principle to appear in every lesson. The emphasis should change according to the content, the prior knowledge pupils bring and the evidence the teacher gathers during the lesson.", keyPoints: ["Think principles, not prescription", "Use prior knowledge as the foundation for new learning", "Keep unfamiliar material manageable", "Make pupil thinking visible", "Fade support in response to evidence"] },
      { id: "ro2", type: "visual", title: "The ten principles as a learning cycle", layout: "cycle", caption: "The principles overlap and feed into one another rather than operating as isolated boxes.", items: [
        { heading: "Review", text: "Activate important prior knowledge before depending on it.", icon: "1" },
        { heading: "Small steps", text: "Introduce unfamiliar material in manageable units.", icon: "2" },
        { heading: "Question", text: "Sample pupil thinking frequently and broadly.", icon: "3" },
        { heading: "Model", text: "Make expert processes, decisions and examples visible.", icon: "4" },
        { heading: "Guide", text: "Let pupils practise while support and feedback remain available.", icon: "5" },
        { heading: "Check", text: "Use responses to decide whether to continue, re-model or scaffold.", icon: "6" },
        { heading: "Success", text: "Keep practice challenging but achievable enough to build accurate habits.", icon: "7" },
        { heading: "Scaffold", text: "Provide temporary prompts or structures where needed.", icon: "8" },
        { heading: "Independent practice", text: "Consolidate processes pupils can perform with reasonable success.", icon: "9" },
        { heading: "Review over time", text: "Revisit important learning after delays and in varied contexts.", icon: "10" }
      ] },
      { id: "ro3", type: "quiz", title: "Knowledge check: the core idea", question: "Which interpretation best reflects Rosenshine's principles?", options: ["Every lesson must follow ten fixed stages", "Teachers should provide appropriate support, check learning frequently and gradually move pupils towards independence", "Independent discovery should always come before explanation", "The principles only apply to factual recall"], answer: 1, feedback: "The principles support responsive instruction: explain and model clearly, gather evidence, guide practice and gradually reduce support." },
      { id: "ro4", type: "content", title: "Daily review and prerequisite knowledge", body: "Review should prepare pupils for the learning that follows. A good review might retrieve definitions, procedures, examples or concepts that today's explanation will rely on. It should not become an unrelated ritual. When review exposes a prerequisite gap, the teacher has useful information: re-teach the missing component, provide a short scaffold or alter the next step before adding more complexity.", keyPoints: ["Choose review content because it matters for today's learning", "Include older knowledge as well as yesterday's lesson", "Use retrieval before showing answers", "Treat errors as diagnostic information", "Do not spend lesson time reviewing knowledge that has little connection to the curriculum goal"] },
      { id: "ro5", type: "scenario", title: "Starter scenario", prompt: "A class repeatedly struggles with today's algebra because an earlier rearranging skill is insecure. What is the strongest Rosenshine-aligned response?", options: [{ label: "Continue with the new content and hope fluency develops", feedback: "New learning will continue to compete with an insecure prerequisite." }, { label: "Use a short diagnostic review, reteach the prerequisite where needed, then return to the new material", feedback: "This reconnects new learning to the knowledge pupils need in order to succeed." }, { label: "Replace the lesson with a completely unrelated retrieval quiz", feedback: "Review should support the learning that follows, not simply fill time." }] },
      { id: "ro6", type: "content", title: "Small steps and managing complexity", body: "A 'small step' is not necessarily a tiny amount of content. It is a chunk that pupils can process successfully given what they already know. In a science calculation, one step may be selecting an equation before substitution; in history it may be separating evidence from inference; in English it may be noticing how a writer's choice creates an effect. The teacher should expose enough structure to make success possible without breaking the task into meaningless fragments.", keyPoints: ["Chunk around meaningful decisions", "Connect each step to the overall goal", "Increase complexity as knowledge becomes secure", "Avoid adding several unfamiliar representations at the same time", "Check after important steps rather than explaining the whole process and checking only at the end"] },
      { id: "ro7", type: "quiz", title: "Worked-example check", question: "When is a worked example most useful?", options: ["Only after pupils have failed repeatedly", "When pupils are novices and need to see the structure of a process before independent problem solving", "Instead of any pupil practice", "Only for mathematics"], answer: 1, feedback: "Worked examples are especially useful for novices when they make the structure and decisions in a task visible before support is faded." },
      { id: "ro8", type: "content", title: "Modelling expert thinking", body: "A model is more than showing a polished final answer. Useful modelling reveals decisions pupils cannot yet see: what the teacher notices first, why one strategy is chosen rather than another, how an error is detected and what quality looks like. Think-alouds should be concise enough that pupils can follow the process. Where possible, alternate modelling with pupil practice so pupils do something with each part rather than watching a long demonstration passively.", keyPoints: ["Model decisions as well as procedures", "Show how experts check their work", "Contrast a weak and strong example where useful", "Pause modelling for pupil prediction or explanation", "Avoid narrating every obvious action when it adds no learning value"] },
      { id: "ro9", type: "scenario", title: "When should scaffolding fade?", prompt: "After a modelled example, about half the class still makes the same error during guided practice. What should happen next?", options: [{ label: "Move immediately to independent work because the explanation has already been given", feedback: "The check shows that pupils are not ready for reduced support." }, { label: "Diagnose the common error, re-model or add a prompt, then check again before fading support", feedback: "Support should fade in response to evidence, not simply because a timetable says it is time." }, { label: "Give the answers so everyone reaches the end", feedback: "This removes the thinking pupils need to practise." }] },
      { id: "ro10", type: "content", title: "Guided practice: where learning becomes visible", body: "Guided practice sits between teacher explanation and independent performance. Pupils attempt the task while the teacher still has opportunities to prompt, question, correct and re-model. This is often where misconceptions first become visible. A strong guided-practice sequence increases pupil responsibility gradually: complete a step together, ask pupils to complete the next step, sample responses, then remove prompts as success becomes more consistent.", keyPoints: ["Make pupils do the thinking during guided practice", "Sample enough responses to judge the class rather than one volunteer", "Correct errors before they are rehearsed repeatedly", "Use prompts that direct attention rather than give away the answer", "Increase independence gradually"] },
      { id: "ro11", type: "content", title: "Checking for understanding", body: "Checking should answer a decision question: are pupils ready for the next step, is the misconception local or widespread, does the model need repeating, or can support be reduced? Useful checks are quick enough to interpret during teaching. Mini-whiteboards, multiple-choice hinge questions, short explanations, worked steps and targeted examples can all reveal more than asking 'Does everyone understand?'.", keyPoints: ["Decide in advance what a correct response would show", "Use plausible wrong answers to expose misconceptions", "Sample everyone where possible", "Respond to the evidence rather than merely collecting it", "Separate participation from understanding"] },
      { id: "ro12", type: "scenario", title: "Lesson-design challenge", prompt: "You are planning a lesson with a difficult new process. Which sequence is strongest?", options: [{ label: "Long explanation → silent independent work → mark at the end", feedback: "This gives little information about understanding before support disappears." }, { label: "Relevant review → small modelled step → pupil practice/check → next step → guided practice → independent practice → later review", feedback: "This uses review, modelling, checking and gradual release as a coherent cycle." }, { label: "Independent problem solving first for all pupils, with explanation only if everyone fails", feedback: "For novices, unsupported search can create avoidable cognitive load." }] },
      { id: "ro13", type: "quiz", title: "Misconception check", question: "Which statement about Rosenshine is least accurate?", options: ["The principles are research-informed instructional ideas", "Checking for understanding should affect what the teacher does next", "Every principle must appear in every lesson in exactly the same order", "Review and practice help build accessible knowledge"], answer: 2, feedback: "The principles are not a mandatory lesson template. Teachers combine and emphasise them according to the content and pupils." },
      reflect("ro14", "Choose one upcoming lesson. Map where review, modelling, guided practice, checking and independent practice will occur. Which one element will you deliberately strengthen, and what evidence will show it helped?"),
      { id: "ro15", type: "visual", title: "From support to independence", layout: "ladder", caption: "The goal is not maximum support or maximum independence; it is the right support at the right time.", items: [
        { heading: "Teacher model", text: "Make the process and quality visible.", icon: "1" },
        { heading: "Shared attempt", text: "Complete part of the process together.", icon: "2" },
        { heading: "Prompted practice", text: "Pupils work while prompts direct attention.", icon: "3" },
        { heading: "Reduced prompts", text: "Remove supports when checks show readiness.", icon: "4" },
        { heading: "Independent practice", text: "Pupils consolidate the process without unnecessary help.", icon: "5" }
      ] },
      { id: "ro16", type: "checklist", title: "Rosenshine lesson-planning audit", prompt: "Use this checklist on one upcoming lesson. Not every item must appear equally, but each should be considered deliberately.", items: ["The prerequisite knowledge is identified", "Review is connected to the new learning", "New material is chunked into meaningful steps", "At least one model or worked example exposes important decisions", "Questions sample more than volunteers", "Guided practice occurs before full independence", "Checks have planned teacher responses", "Scaffolds can be faded when evidence supports it", "Independent practice rehearses what pupils are ready to do", "Important learning is scheduled for later review"], completionText: "Rosenshine planning audit complete." },
      { id: "ro17", type: "activity", title: "Build a lesson sequence", prompt: "Design a short sequence for a genuinely difficult piece of new learning in your subject.", instructions: ["Name the prerequisite knowledge pupils need.", "Write the first modelled step and what you will think aloud.", "Add one check for understanding and the misconception it is designed to reveal.", "Describe the guided-practice task.", "State what evidence would make you fade support.", "Plan one later review point."], placeholder: "Topic…\nPrerequisite…\nModel…\nCheck…\nGuided practice…\nFade support when…\nLater review…", minimumCharacters: 220 },
      { id: "ro18", type: "content", title: "Subject-specific examples", body: "Rosenshine's principles look different across subjects because the objects of expertise differ. In science, modelling may mean a calculation, graph interpretation or practical decision. In English, it may mean constructing an analytical paragraph and explaining why evidence is selected. In history, it may mean evaluating a source or building an argument. In PE, it may mean modelling a movement and using concise cues. The principle is stable; the representation and practice should be disciplinary.", keyPoints: ["Science: model calculations, explanations, graph reading and practical decisions", "English: model interpretation, sentence construction and evidence selection", "Maths: use worked examples and faded steps", "Humanities: model disciplinary reasoning and source use", "Practical subjects: combine demonstration with explicit cues and deliberate practice"] },
      { id: "ro19", type: "scenario", title: "Experienced class challenge", prompt: "A class has already become fluent in a process that previously required heavy modelling. What is the strongest response?", options: [{ label: "Keep exactly the same scaffolds indefinitely", feedback: "Over-support can reduce productive independence once knowledge is secure." }, { label: "Increase independence, vary contexts and use review to maintain fluency", feedback: "As expertise increases, support can fade and tasks can demand transfer." }, { label: "Stop checking understanding completely", feedback: "Checks remain useful even when support is reduced." }] },
      { id: "ro20", type: "reflection", title: "Implementation commitment", prompt: "Which Rosenshine principle is already strongest in your practice? Which one is most likely to improve pupil learning if strengthened next? Describe one observable change you will make and one piece of evidence you will collect." }
    ]
  },
  {
    id: "maslow-needs",
    title: "Maslow's Hierarchy of Needs: A Critical Classroom Lens",
    category: "Wellbeing",
    duration: 90,
    level: "Foundation",
    summary: "Explore Maslow's needs framework in depth while treating it as a cautious lens for classroom conditions rather than a rigid diagnostic pyramid.",
    objectives: ["Describe the familiar need areas associated with Maslow", "Explain the limitations of treating the hierarchy as a fixed universal sequence", "Identify classroom practices that support safety, belonging, competence and growth", "Maintain high expectations while responding sensitively to barriers", "Know when school pastoral, SEND or safeguarding systems take priority"],
    recommendedFor: ["Teacher", "ECT", "Teaching Assistant", "Pastoral", "Tutor", "Department Lead"],
    modules: [
      { id: "ma1", type: "content", title: "The framework and why schools use it", body: "Maslow's theory is commonly summarised through physiological needs, safety, belonging, esteem and self-actualisation. In schools, the framework is most useful as a prompt to consider whether aspects of the environment are making engagement harder. It should not be used to infer a pupil's home life, diagnose a need or decide that academic learning is impossible until a lower level is fully satisfied.", keyPoints: ["Use it as a prompt, not a diagnosis", "Several needs may matter at the same time", "The familiar pyramid is a simplified representation", "Observed behaviour rarely identifies one cause", "School procedures and pupil-specific information are more important than assumptions"] },
      { id: "ma2", type: "quiz", title: "Knowledge check", question: "Which is the most responsible classroom use of Maslow's framework?", options: ["Use the pyramid to diagnose the exact cause of a pupil's behaviour", "Treat it as one lens for noticing possible barriers, then use evidence and school systems to understand the pupil", "Assume learning is impossible until every lower need is completely satisfied", "Rank pupils according to which level they have reached"], answer: 1, feedback: "The framework can prompt professional curiosity, but decisions should be based on evidence and appropriate school systems." },
      { id: "ma3", type: "visual", title: "The familiar five areas", layout: "pyramid", caption: "These areas can overlap. The diagram should not be read as a rigid sequence every person follows in the same way.", items: [
        { heading: "Physiological", text: "Basic physical conditions such as food, rest, warmth and comfort.", icon: "1" },
        { heading: "Safety", text: "Physical and emotional predictability, security and freedom from threat.", icon: "2" },
        { heading: "Belonging", text: "Connection, acceptance and a sense of membership.", icon: "3" },
        { heading: "Esteem", text: "Competence, self-respect, recognition and credible success.", icon: "4" },
        { heading: "Growth", text: "Purpose, creativity, challenge and developing potential.", icon: "5" }
      ] },
      { id: "ma4", type: "scenario", title: "Morning lesson scenario", prompt: "A normally engaged pupil is unusually tired, quiet and has not completed the starter. What is the strongest response?", options: [{ label: "Assume their physiological needs are unmet and record that as the cause", feedback: "The observation does not tell you the cause. Avoid diagnosis by assumption." }, { label: "Use a calm check-in, maintain reasonable learning support and follow pastoral/safeguarding procedures if a concern emerges", feedback: "This responds to what you can observe while using the school's systems appropriately." }, { label: "Remove all academic expectations for the rest of the term", feedback: "A temporary concern should not automatically become a permanent reduction in ambition." }] },
      { id: "ma5", type: "content", title: "Physiological and safety needs in classroom design", body: "Teachers cannot resolve every factor affecting a pupil's physical wellbeing, but they can reduce avoidable classroom barriers. Reasonable comfort, predictable routines, clear transitions, calm corrections and reliable adult responses make the learning environment easier to navigate. Safety includes emotional safety: pupils should be corrected without humiliation and should know what will happen when routines are followed or not followed.", keyPoints: ["Make routines and transitions predictable", "Avoid public humiliation", "Use calm, proportionate correction", "Notice significant changes in presentation or engagement", "Use school systems when concerns extend beyond the classroom"] },
      { id: "ma6", type: "scenario", title: "Belonging without assumptions", prompt: "A new pupil rarely volunteers and spends break alone. Which interpretation is most appropriate?", options: [{ label: "They definitely have an unmet belonging need", feedback: "That may be one possibility, but the observations do not prove it." }, { label: "Notice the pattern, create low-pressure opportunities to participate, and share concerns through the appropriate pastoral route if needed", feedback: "This combines supportive classroom practice with evidence-based follow-up." }, { label: "Force public group participation immediately", feedback: "Public pressure may make participation harder and does not establish why the pupil is quiet." }] },
      { id: "ma7", type: "content", title: "Belonging, participation and classroom identity", body: "Belonging is strengthened when pupils can participate meaningfully, experience predictable relationships and see themselves as legitimate members of the learning community. This is different from insisting every pupil is socially confident. Low-pressure participation routines, careful group structures, respectful pronunciation of names, inclusive examples and consistent expectations can all contribute to belonging.", keyPoints: ["Create predictable participation routines", "Avoid making quietness itself a problem", "Use group work structures rather than hoping inclusion happens", "Make classroom language inclusive", "Keep academic participation open to every pupil"] },
      { id: "ma8", type: "quiz", title: "Critical-thinking check", question: "Which statement best reflects the limitations of Maslow's hierarchy?", options: ["The five areas are useless in any context", "Everyone must satisfy each level fully before the next can matter", "The need areas can be a useful prompt, but evidence does not support treating the order as a strict universal sequence", "A teacher can infer a pupil's home circumstances from classroom behaviour"], answer: 2, feedback: "Use the framework as a prompt for professional curiosity, not as a fixed law or shortcut to conclusions about pupils." },
      { id: "ma9", type: "scenario", title: "Safeguarding boundary", prompt: "A pupil tells you something that indicates they may not be safe. What should take priority?", options: [{ label: "Try to solve the situation yourself using Maslow's hierarchy", feedback: "A needs framework must never replace safeguarding procedures." }, { label: "Listen appropriately and follow the school's safeguarding reporting procedure promptly", feedback: "Safeguarding procedures take priority over motivational frameworks." }, { label: "Wait to see whether motivation improves", feedback: "A safety concern should be handled through the school's safeguarding process." }] },
      { id: "ma10", type: "reflection", title: "Apply it to your practice", prompt: "Choose one class. Identify one classroom condition you can improve—predictability, belonging, safety, competence or opportunity for growth—without making assumptions about individual pupils. What will you change and how will you know whether it helped?" },
      { id: "ma11", type: "content", title: "Esteem is not constant praise", body: "A useful interpretation of esteem is credible competence. Pupils benefit when they know what quality looks like, receive feedback they can act on and experience genuine success through worthwhile effort. Empty praise can be less useful than specific acknowledgement of the process or improvement that produced success. High expectations and support should therefore operate together rather than being treated as opposites.", keyPoints: ["Praise should be specific and believable", "Success criteria make competence visible", "Feedback should identify a route forward", "Scaffolding should preserve the learning goal", "Avoid lowering expectations based on assumptions about vulnerability"] },
      { id: "ma12", type: "visual", title: "Classroom conditions teachers can influence", layout: "flow", items: [
        { heading: "Predictability", text: "Routines, transitions and expectations are clear.", icon: "1" },
        { heading: "Participation", text: "There are safe, structured ways to contribute.", icon: "2" },
        { heading: "Competence", text: "Pupils can see what success looks like and how to improve.", icon: "3" },
        { heading: "Challenge", text: "Work remains ambitious and meaningful.", icon: "4" },
        { heading: "Support", text: "Concerns are passed through the right pastoral, SEND or safeguarding route.", icon: "5" }
      ] },
      { id: "ma13", type: "checklist", title: "Needs-aware classroom audit", prompt: "Audit the classroom conditions you can reasonably influence without trying to diagnose individual pupils.", items: ["Entry and transition routines are predictable", "Correction is calm and non-humiliating", "Pupils have more than one safe way to participate", "Examples and language communicate belonging", "Success criteria are clear", "Scaffolds preserve challenge", "Significant concerns are passed through the right school system", "Staff avoid making assumptions from behaviour alone"], completionText: "Needs-aware classroom audit complete." },
      { id: "ma14", type: "activity", title: "Improve one classroom condition", prompt: "Plan a small environmental change through the lens of needs, while keeping expectations high.", instructions: ["Choose one class or routine.", "Identify the observable barrier without diagnosing its cause.", "Choose one change to predictability, participation, competence or challenge.", "State what evidence you will look for.", "Identify when pastoral, SEND or safeguarding support would be needed."], placeholder: "Context…\nObserved barrier…\nChange…\nEvidence…\nEscalation/support route…", minimumCharacters: 180 },
      { id: "ma15", type: "quiz", title: "Application check", question: "A pupil appears disengaged during difficult work. Which response best reflects a careful use of Maslow?", options: ["Assume an unmet lower need is the cause", "Reduce challenge permanently", "Consider whether classroom conditions are creating avoidable barriers, gather evidence and use appropriate school information before deciding on support", "Ignore the pupil because motivation is personal"], answer: 2, feedback: "A careful approach considers the environment and available evidence without turning the framework into a diagnosis." }
    ]
  },
  {
    id: "effective-questioning",
    title: "Effective Questioning: Making Thinking Visible",
    category: "Teaching & Learning",
    duration: 90,
    level: "Developing",
    summary: "Plan and use questions that reveal pupil thinking, expose misconceptions, increase participation and give the teacher information that changes what happens next.",
    objectives: ["Distinguish participation questions from diagnostic questions", "Design hinge questions with meaningful distractors", "Use wait time and response routines to increase thinking", "Probe answers without lowering challenge", "Use whole-class evidence to adapt teaching"],
    recommendedFor: ["Teacher", "ECT", "Teaching Assistant", "Department Lead"],
    modules: [
      { id: "q1x", type: "content", title: "Questions should reveal thinking", body: "Questioning is most powerful when it produces evidence that helps the teacher decide what to do next. A correct answer from one volunteer tells you very little about the rest of the class. High-value questions therefore target an important concept, require pupils to think and are asked through a response routine that samples more than the quickest or most confident pupils.", keyPoints: ["Plan questions around likely misconceptions", "Ask for reasoning as well as answers", "Sample beyond volunteers", "Build in thinking time", "Use responses to change teaching"] },
      { id: "q2x", type: "quiz", title: "Whole-class check", question: "Which method gives the best evidence about the whole class?", options: ["Ask for hands up", "Ask the fastest pupil", "Use a question answered simultaneously by everyone", "Ask whether everyone understands"], answer: 2, feedback: "Simultaneous response systems reduce sampling bias and make misconceptions easier to spot." },
      { id: "q3x", type: "scenario", title: "Wait-time scenario", prompt: "You ask a demanding question and get no response after two seconds. What is the best next move?", options: [{ label: "Answer it immediately", feedback: "This may remove productive thinking time." }, { label: "Give structured thinking time, perhaps rehearsal with a partner, then sample responses", feedback: "This preserves challenge while increasing access." }, { label: "Replace it with a much easier question immediately", feedback: "That can hide whether pupils could answer with adequate thinking time." }] },
      { id: "q4x", type: "content", title: "Follow-up prompts that deepen thinking", body: "The first answer should often open the diagnostic conversation rather than end it. Prompts such as 'What makes you think that?', 'Which evidence supports it?', 'Can you represent that another way?', 'What would change your mind?' and 'Who can build on that?' encourage elaboration. Follow-up should serve the learning goal; relentless probing of every answer can become slow and performative.", keyPoints: ["Probe reasoning selectively", "Ask pupils to connect answers to evidence or examples", "Invite comparison between methods", "Use another pupil's response to test general understanding", "Stop probing when enough evidence has been gathered"] },
      { id: "q5x", type: "scenario", title: "Misconception response", prompt: "A pupil gives the correct numerical answer but cannot explain the method. What should the teacher infer?", options: [{ label: "Understanding is definitely secure", feedback: "A correct answer alone may not show secure reasoning." }, { label: "Probe the method and sample other pupils before deciding whether to move on", feedback: "Follow-up questions help distinguish secure understanding from guessing or procedural imitation." }, { label: "Ignore the answer because explanation never matters", feedback: "Explanation can reveal the structure of the pupil's thinking." }] },
      { id: "q6x", type: "quiz", title: "Question design check", question: "Which question is most useful as a hinge question?", options: ["One that takes ten minutes to mark", "One where common wrong answers correspond to useful misconceptions", "One that only the highest-attaining pupil can answer", "One asked after the lesson has ended"], answer: 1, feedback: "A good hinge question is quick to answer and interpret, and its distractors reveal meaningful misunderstandings." },
      { id: "q7x", type: "reflection", title: "Apply it to your practice", prompt: "Write one hinge question for an upcoming lesson, including three plausible wrong answers and what each wrong answer would tell you." },
      { id: "q8x", type: "visual", title: "A diagnostic questioning sequence", layout: "flow", items: [
        { heading: "Target", text: "Choose the idea or misconception you need evidence about.", icon: "1" },
        { heading: "Think", text: "Give enough thinking time for the cognitive demand.", icon: "2" },
        { heading: "Respond", text: "Use a routine that samples broadly.", icon: "3" },
        { heading: "Interpret", text: "Identify the pattern in answers, not only who was correct.", icon: "4" },
        { heading: "Act", text: "Move on, re-model, scaffold or question further.", icon: "5" }
      ] },
      { id: "q9x", type: "content", title: "Cold call, hands up and participation routines", body: "No single participation routine is automatically best. Cold call can broaden participation when pupils expect it, receive thinking time and are treated respectfully. Hands up can be useful for collecting ideas but produces a biased sample. Think-pair-share can improve rehearsal but needs accountability to avoid one pupil doing all the thinking. Mini-whiteboards or digital responses can produce whole-class evidence quickly. The key question is: what information do you need, and which routine gives you that information fairly?", keyPoints: ["Match the response routine to the purpose", "Establish routines before using them under pressure", "Give thinking time before sampling", "Do not use questioning to humiliate pupils", "Use whole-class responses when you need whole-class evidence"] },
      { id: "q10x", type: "activity", title: "Build a hinge question", prompt: "Design a hinge question for a misconception pupils commonly have in your subject.", instructions: ["State the learning point.", "Write one unambiguously correct response.", "Create three plausible wrong responses, each linked to a different misconception.", "Choose a response routine that lets you see the class pattern quickly.", "Write what you will do for each main response pattern."], placeholder: "Learning point…\nQuestion…\nCorrect answer…\nDistractor 1 and misconception…\nDistractor 2…\nDistractor 3…\nResponse routine…\nTeacher response…", minimumCharacters: 220 },
      { id: "q11x", type: "scenario", title: "Participation without lowering challenge", prompt: "Only a small group of confident pupils regularly answers difficult questions. What is the strongest next step?", options: [{ label: "Make all future questions easier", feedback: "Lowering the cognitive demand does not solve the participation problem." }, { label: "Build predictable thinking and response routines so everyone prepares an answer before sampling", feedback: "This widens participation while preserving challenge." }, { label: "Continue using volunteers and assume silence means understanding", feedback: "Volunteer responses provide a narrow sample." }] },
      { id: "q12x", type: "checklist", title: "Question-quality audit", prompt: "Audit a questioning sequence you plan to use this week.", items: ["The question is linked to a specific learning goal", "Likely misconceptions are anticipated", "Pupils receive appropriate thinking time", "The response routine samples broadly", "Follow-up prompts reveal reasoning", "I know what evidence would make me re-teach", "I know what evidence would make me move on", "The routine avoids public humiliation"], completionText: "Questioning audit complete." },
      { id: "q13x", type: "content", title: "Subject-specific questioning examples", body: "In science, a hinge question might distinguish confusion between mass and weight or current and voltage. In maths, distractors can represent common procedural errors. In English, pupils might choose the strongest interpretation and justify it with evidence. In history, questions can distinguish source content from source utility. In practical subjects, pupils can predict the consequence of a technique change before performing it. Good questioning is disciplinary: it should reveal the reasoning that matters in that subject.", keyPoints: ["Use distractors based on real misconceptions", "Ask pupils to explain relationships, not just recall labels", "Use prediction before demonstrations or practical work", "Make disciplinary reasoning explicit"] },
      { id: "q14x", type: "quiz", title: "Final application check", question: "What makes a questioning strategy genuinely formative?", options: ["It involves many questions", "Pupils enjoy it", "The teacher uses the evidence from responses to decide what to do next", "It always uses mini-whiteboards"], answer: 2, feedback: "Questioning becomes formative when evidence is interpreted and used to adapt teaching or learning." }
    ]
  },
  {
    id: "cognitive-load-theory",
    title: "Cognitive Load Theory for the Classroom",
    category: "Teaching & Learning",
    duration: 85,
    level: "Developing",
    summary: "Understand how working-memory limits, prior knowledge, presentation design, modelling and practice interact so lessons are challenging without creating avoidable processing demands.",
    objectives: ["Explain the relationship between working memory and long-term memory", "Distinguish task complexity from avoidable instructional load", "Use worked examples, chunking and signalling appropriately", "Recognise when expertise changes the support pupils need", "Audit lesson resources for split attention and unnecessary information"],
    recommendedFor: ["Teacher", "ECT", "Teaching Assistant", "Department Lead"],
    modules: [
      { id: "cl1", type: "content", title: "Working memory and long-term memory", body: "Working memory has limited capacity when learners deal with unfamiliar information. Long-term memory changes the picture because well-organised knowledge allows experts to treat several elements as one meaningful chunk. This is why a task that overwhelms a novice can feel straightforward to a knowledgeable learner. Effective teaching therefore aims both to protect working memory during new learning and to build the knowledge structures that make future thinking easier.", keyPoints: ["Working-memory limits matter most for unfamiliar material", "Prior knowledge reduces processing demand", "Teaching should build organised long-term knowledge", "Difficulty is not automatically harmful; avoidable difficulty is the key concern"] },
      { id: "cl2", type: "quiz", title: "Knowledge check", question: "Which change most directly reduces unnecessary cognitive load?", options: ["Add more decorative animations", "Split instructions across several unrelated places", "Place a worked example beside the task it supports", "Introduce several new representations at once"], answer: 2, feedback: "Keeping relevant guidance close to the task reduces avoidable search and split attention." },
      { id: "cl3", type: "scenario", title: "Planning scenario", prompt: "Pupils struggle to start a complex multi-step calculation. What is the strongest first response?", options: [{ label: "Give more questions immediately", feedback: "More practice is not useful if pupils cannot yet manage the process." }, { label: "Model a worked example and then fade support", feedback: "This reduces initial processing demand while preserving the full learning goal." }, { label: "Remove the difficult content", feedback: "The aim is to scaffold access, not lower the intended learning." }] },
      { id: "cl4", type: "reflection", title: "Apply it to your practice", prompt: "Choose one lesson resource. What could you remove, combine, signal or sequence differently to reduce avoidable cognitive load while preserving the intended challenge?" },
      { id: "cl5", type: "visual", title: "Three sources of load to think about", layout: "compare", caption: "The terminology is useful only when it helps improve instructional decisions.", items: [
        { heading: "Task complexity", text: "The interacting elements pupils genuinely need to process to learn the material.", icon: "A" },
        { heading: "Avoidable demand", text: "Search, clutter, split attention or unclear instructions that do not contribute to the goal.", icon: "B" },
        { heading: "Learning effort", text: "Productive thinking devoted to understanding, practising and connecting the target knowledge.", icon: "C" }
      ] },
      { id: "cl6", type: "content", title: "Split attention and redundancy", body: "Pupils can waste working-memory capacity searching between a diagram and a distant explanation, copying information already visible, or processing narration that merely reads dense text on a slide. Integrating labels into diagrams, removing decorative detail and coordinating spoken and visual information can reduce avoidable processing. However, 'less information' is not automatically better: the information pupils need to understand the idea must remain available.", keyPoints: ["Place related information together", "Signal the part pupils should attend to", "Remove decoration that competes for attention", "Avoid reading long on-screen paragraphs aloud", "Do not remove essential explanation in the name of simplicity"] },
      { id: "cl7", type: "scenario", title: "Slide-design scenario", prompt: "A slide contains a complex diagram, a long paragraph explaining it and an unrelated animated image. What is the strongest redesign?", options: [{ label: "Add another paragraph for completeness", feedback: "More text may increase avoidable processing." }, { label: "Remove the decorative animation, integrate short labels with the diagram and explain key relationships verbally", feedback: "This reduces competing information and split attention while preserving meaning." }, { label: "Remove the diagram and all explanation", feedback: "Reducing load should not mean removing the information needed to understand." }] },
      { id: "cl8", type: "content", title: "Worked examples and fading", body: "Worked examples can reduce the amount of unguided search novices must perform while still showing the full structure of a problem. The next step is not endless example watching. Support should fade: complete one example together, leave one step for pupils, then increase the amount they complete. As expertise grows, too much guidance can become inefficient because knowledgeable pupils no longer need every step explained.", keyPoints: ["Use worked examples before demanding full independent problem solving from novices", "Alternate examples and practice", "Fade steps deliberately", "Increase challenge as knowledge grows", "Avoid assuming one support level suits every class indefinitely"] },
      { id: "cl9", type: "activity", title: "Resource redesign challenge", prompt: "Audit and redesign one slide, worksheet or explanation you use often.", instructions: ["Identify the exact learning goal.", "Circle information pupils must process.", "Identify any search, copying, decoration or split attention that is not essential.", "Rewrite or reorganise the resource.", "State how you will check that the redesign improved understanding rather than merely looking cleaner."], placeholder: "Learning goal…\nEssential information…\nAvoidable demand…\nRedesign…\nEvidence of improvement…", minimumCharacters: 190 },
      { id: "cl10", type: "checklist", title: "Cognitive-load resource audit", prompt: "Use this checklist before using a complex resource or explanation.", items: ["The learning goal is clear", "Prerequisite knowledge has been considered", "Related text and visuals are close together", "Decorative information is limited", "Instructions are visible where useful", "New representations are introduced deliberately", "A worked example is available if pupils are novices", "Support can be faded later", "Pupils will have to think, not just copy"], completionText: "Resource audit complete." },
      { id: "cl11", type: "quiz", title: "Expertise check", question: "Why might a scaffold that helps a novice become less useful for an expert pupil?", options: ["Experts never need support", "The expert already has organised knowledge, so processing redundant guidance can become unnecessary", "Scaffolds always lower standards", "Working memory becomes unlimited with age"], answer: 1, feedback: "Support should respond to expertise. Guidance that reduces search for novices may become redundant when the structure is already known." },
      { id: "cl12", type: "content", title: "Cognitive load is not a reason to remove productive thinking", body: "A common misuse of cognitive load theory is to treat all struggle as harmful. Learning requires effort: retrieving, explaining, comparing, practising and solving appropriately chosen problems all consume cognitive resources. The design goal is to reduce processing that does not serve the learning goal so that pupils can spend more effort on the thinking that does.", keyPoints: ["Productive effort is necessary", "Avoidable processing is the main target", "Challenge should be matched to prior knowledge", "Use evidence from pupil performance to judge whether support is sufficient"] }
    ]
  },
  {
    id: "behaviour-management",
    title: "Behaviour Management: Prevention Before Correction",
    category: "Teaching & Learning",
    duration: 85,
    level: "Developing",
    summary: "Build calm, predictable classrooms through explicit routines, active supervision, proportionate correction, relationship-safe communication and consistent follow-through.",
    objectives: ["Define behaviour expectations in observable terms", "Teach and rehearse routines deliberately", "Use active supervision and positive narration appropriately", "Correct behaviour calmly without lengthy confrontation", "Distinguish classroom management from pastoral or safeguarding concerns"],
    recommendedFor: ["Teacher", "ECT", "Teaching Assistant", "Department Lead"],
    modules: [
      { id: "bm1", type: "content", title: "Prevention before correction", body: "Strong behaviour management starts before misbehaviour occurs. Pupils need to know what routines look like, when they apply and what adults will do consistently. Ambiguous instructions, slow transitions, inaccessible tasks and inconsistent follow-through create opportunities for disruption. Prevention does not remove the need for consequences; it makes expectations easier to understand and reduces unnecessary confrontation.", keyPoints: ["Teach routines explicitly", "Make expectations observable", "Plan transitions", "Use school policy consistently", "Reduce avoidable ambiguity"] },
      { id: "bm2", type: "scenario", title: "Low-level disruption", prompt: "A pupil repeatedly talks during independent work. What is a sensible first response within a normal school behaviour policy?", options: [{ label: "Publicly argue about motive", feedback: "Extended public debate can increase disruption." }, { label: "Use the agreed calm reminder and follow the school's stepped response", feedback: "A predictable response keeps attention on the expected behaviour." }, { label: "Ignore every recurrence", feedback: "Unaddressed repeated disruption can undermine the routine." }] },
      { id: "bm3", type: "reflection", title: "Apply it to your practice", prompt: "Identify one behaviour expectation that could be stated more clearly or rehearsed more explicitly in your classroom." },
      { id: "bm4", type: "visual", title: "A preventive behaviour cycle", layout: "cycle", items: [
        { heading: "Specify", text: "Define the routine in observable terms.", icon: "1" },
        { heading: "Teach", text: "Explain and model what success looks like.", icon: "2" },
        { heading: "Rehearse", text: "Give pupils a chance to practise the routine.", icon: "3" },
        { heading: "Notice", text: "Actively supervise and acknowledge successful compliance.", icon: "4" },
        { heading: "Correct", text: "Use the agreed calm response when needed.", icon: "5" },
        { heading: "Reset", text: "Re-teach the routine if the pattern breaks down.", icon: "6" }
      ] },
      { id: "bm5", type: "content", title: "Routines that protect learning time", body: "High-leverage routines often include entry, equipment, transitions, independent work, obtaining help, practical work, discussion and dismissal. A routine should answer: what is the cue, what do pupils do, how long should it take and what happens if support is needed? The more frequently a routine occurs, the more worthwhile it is to teach it explicitly rather than relying on repeated reminders.", keyPoints: ["Prioritise high-frequency routines", "Use consistent cues", "Keep instructions concise", "Practise before expecting fluency", "Review routines after holidays or class changes"] },
      { id: "bm6", type: "scenario", title: "Transition scenario", prompt: "A class becomes noisy and slow whenever moving from explanation to practical work. What is the strongest first intervention?", options: [{ label: "Raise your voice over the class each time", feedback: "This treats the symptom but does not improve the routine." }, { label: "Define the transition steps, model them, rehearse them and use the same cue consistently", feedback: "A repeated transition problem usually benefits from explicit routine teaching." }, { label: "Cancel all practical work", feedback: "Removing valuable learning is not the first solution to a routine problem." }] },
      { id: "bm7", type: "content", title: "Correction without escalation", body: "Corrections are most effective when they are brief, predictable and linked to the behaviour standard rather than the pupil's character or motive. Lengthy public exchanges can create an audience and shift attention away from learning. Where possible, use the school's agreed language, give the pupil a clear route back to success and keep more detailed conversations for an appropriate private moment.", keyPoints: ["Correct the behaviour, not the person's character", "Avoid debating motive in public", "Use concise language", "Follow policy consistently", "Give a clear route back to the expected routine"] },
      { id: "bm8", type: "quiz", title: "Correction check", question: "Which correction is most likely to preserve calm and clarity?", options: ["Why are you always so disrespectful?", "Everyone look at this pupil and notice what they are doing", "The expectation is silent independent work. Return to question three now, please.", "A five-minute public debate about fairness"], answer: 2, feedback: "The correction is brief, behaviour-specific and gives a clear next action." },
      { id: "bm9", type: "content", title: "Relationships and boundaries are compatible", body: "Warm relationships and clear boundaries are not opposites. Pupils are more likely to trust adults whose responses are fair, predictable and respectful. Relationship-building is not about avoiding correction; it includes listening appropriately, showing interest, pronouncing names correctly, noticing effort and repairing interactions after difficult moments while still maintaining expectations.", keyPoints: ["Consistency supports trust", "Use respectful language", "Repair after conflict where appropriate", "Do not trade expectations for approval", "Know when behaviour may indicate a pastoral or safeguarding concern"] },
      { id: "bm10", type: "activity", title: "Teach one routine explicitly", prompt: "Design the teaching sequence for one classroom routine that currently costs learning time.", instructions: ["Name the routine and the cue.", "Write the steps pupils should follow.", "Describe how you will model it.", "Plan a short rehearsal.", "Write the correction you will use if it breaks down.", "State how you will know the routine has become fluent."], placeholder: "Routine…\nCue…\nSteps…\nModel…\nRehearsal…\nCorrection…\nEvidence of fluency…", minimumCharacters: 200 },
      { id: "bm11", type: "checklist", title: "Behaviour-routine audit", prompt: "Audit one class against the foundations of a predictable behaviour environment.", items: ["Entry is explicitly taught", "Task-start routines are clear", "Transitions have a consistent cue", "Pupils know how to get help", "Corrections are brief and predictable", "Consequences follow school policy", "Successful routines are noticed", "Staff language avoids humiliation", "Pastoral/safeguarding concerns are passed through the correct route"], completionText: "Behaviour-routine audit complete." },
      { id: "bm12", type: "scenario", title: "When behaviour may signal something else", prompt: "A pupil's behaviour changes suddenly and significantly compared with their normal pattern. What is the strongest response?", options: [{ label: "Assume the pupil has decided to become defiant", feedback: "A sudden change should not be reduced to a motive without evidence." }, { label: "Maintain appropriate boundaries while also sharing the change through relevant pastoral or safeguarding systems", feedback: "Behaviour management and pastoral/safeguarding awareness can operate together." }, { label: "Ignore the change because behaviour is only a classroom issue", feedback: "Significant changes can be important information for the wider school team." }] }
    ]
  },
  {
    id: "send-inclusive-practice",
    title: "SEND: Inclusive Classroom Practice",
    category: "SEND",
    duration: 95,
    level: "Developing",
    summary: "Plan ambitious, accessible teaching by identifying barriers in the task, using pupil-specific information well and selecting adaptations that support participation without automatically lowering the learning goal.",
    objectives: ["Use pupil-specific information rather than label-based assumptions", "Analyse the demands of a task", "Choose adaptations that preserve ambition", "Coordinate teacher and teaching-assistant support", "Fade scaffolds where appropriate to build independence"],
    recommendedFor: ["Teacher", "ECT", "Teaching Assistant", "Department Lead", "SENDCO"],
    modules: [
      { id: "se1", type: "content", title: "Start with the pupil and the learning goal", body: "SEND-inclusive practice begins with two questions: what is the intended learning, and what is creating a barrier for this pupil in this task? A diagnosis or broad category does not tell you exactly what support to use. Current pupil information, teacher observation, the pupil's own perspective where appropriate and the specific demands of the lesson are more useful than stereotypes.", keyPoints: ["Keep the learning goal visible", "Use current pupil-specific information", "Identify the task barrier", "Avoid assuming pupils with the same label need the same support", "Review whether adaptations are actually helping"] },
      { id: "se2", type: "quiz", title: "Knowledge check", question: "Which is the strongest starting point when planning support for a pupil with SEND?", options: ["Assume pupils with the same label need identical support", "Use the pupil's current information and identify barriers in this specific task", "Lower the objective automatically", "Remove all challenge"], answer: 1, feedback: "Support should respond to the individual pupil and the demands of the task." },
      { id: "se3", type: "reflection", title: "Apply it to your practice", prompt: "Choose one upcoming task. What barrier might it create for a particular learner, and what adjustment could preserve the learning goal?" },
      { id: "se4", type: "visual", title: "Barrier-to-support planning", layout: "flow", items: [
        { heading: "Goal", text: "What do pupils need to learn or demonstrate?", icon: "1" },
        { heading: "Demand", text: "What reading, memory, language, sensory, motor or executive demands does the task create?", icon: "2" },
        { heading: "Barrier", text: "Which demand is creating difficulty for this pupil?", icon: "3" },
        { heading: "Adapt", text: "Change access, representation, scaffolding or environment while preserving the goal where possible.", icon: "4" },
        { heading: "Review", text: "Check whether the adaptation increased access and independence.", icon: "5" }
      ] },
      { id: "se5", type: "content", title: "Task analysis: where barriers hide", body: "A task can contain several demands beyond the subject knowledge you intend to assess. A science practical may require sequencing, reading, fine-motor control and working memory. An essay may require planning, handwriting, vocabulary, sustained attention and recall. Good adaptation separates the intended learning from these additional demands so staff can decide which demands are essential and which can be supported.", keyPoints: ["Separate subject goal from access demands", "Consider reading and language load", "Consider working-memory and sequencing load", "Consider sensory and motor demands", "Do not remove an essential skill if it is the actual learning goal"] },
      { id: "se6", type: "scenario", title: "Same goal, different access", prompt: "A pupil can explain a concept accurately aloud but struggles to organise an extended written response. What is the strongest first adaptation if the lesson goal is conceptual explanation rather than handwriting?", options: [{ label: "Replace the concept with easier content", feedback: "This lowers the learning goal rather than supporting the access barrier." }, { label: "Use a planning scaffold or sentence structure while keeping the same conceptual goal", feedback: "This supports organisation without changing the intended concept." }, { label: "Complete the response for the pupil", feedback: "Over-support removes the thinking the pupil needs to practise." }] },
      { id: "se7", type: "content", title: "Scaffolding without creating dependence", body: "A scaffold should make a difficult task accessible while keeping the important thinking with the pupil. Examples include worked examples, visual schedules, vocabulary banks, sentence starters, checklists, chunked instructions and partially completed models. The next question should always be: how will we know when this scaffold can be reduced? Permanent support can sometimes be appropriate, but many instructional scaffolds should fade as independence grows.", keyPoints: ["Keep the thinking with the pupil", "Choose the smallest support that addresses the barrier", "Teach pupils how to use the scaffold", "Review impact", "Fade instructional scaffolds when evidence supports it"] },
      { id: "se8", type: "quiz", title: "Scaffolding check", question: "Which scaffold is most likely to build independence?", options: ["An adult gives every answer", "A checklist that prompts the pupil through steps they can increasingly complete alone", "Permanent removal of the task", "A simpler learning objective for every lesson"], answer: 1, feedback: "A good scaffold supports successful thinking and can often be reduced as the pupil becomes more independent." },
      { id: "se9", type: "content", title: "Teaching assistants: support the learning, not just task completion", body: "Teaching assistants can be most effective when they know the intended learning, use prompts that encourage pupil thinking and avoid becoming the pupil's permanent interpreter of teacher instructions. Teacher and TA should agree the purpose of support, useful prompts, when to step back and what information should be fed back after the lesson.", keyPoints: ["Share the learning goal", "Agree prompt hierarchy", "Avoid unnecessary adult dependence", "Create opportunities for peer and teacher interaction", "Feed back patterns of difficulty to the teacher"] },
      { id: "se10", type: "scenario", title: "TA support scenario", prompt: "A teaching assistant sits beside one pupil for the entire lesson and repeatedly rephrases every teacher instruction before the pupil tries to process it. What is the main risk?", options: [{ label: "There is no risk because more help is always better", feedback: "Continuous mediation can sometimes reduce independent processing and participation with the wider class." }, { label: "The pupil may become dependent on adult rephrasing rather than developing access to shared routines and prompts", feedback: "Support should be purposeful and include opportunities for independence." }, { label: "The teacher should stop giving whole-class instructions", feedback: "The issue is how support is structured, not whether shared instruction exists." }] },
      { id: "se11", type: "checklist", title: "Inclusive-planning audit", prompt: "Use this on one upcoming lesson or task.", items: ["The core learning goal is explicit", "Known pupil information has been checked", "Likely barriers in the task have been identified", "Vocabulary/language support is planned where needed", "Instructions are chunked or visible where useful", "Scaffolds preserve the learning goal", "TA support has a clear purpose", "There is a plan for independence or scaffold fading", "The pupil can still participate meaningfully with peers"], completionText: "Inclusive-planning audit complete." },
      { id: "se12", type: "activity", title: "Redesign an upcoming task", prompt: "Redesign one task to remove an avoidable barrier while maintaining appropriate challenge.", instructions: ["State the learning goal.", "List the task demands.", "Identify one likely barrier for a pupil you teach without naming them here.", "Choose one proportionate adaptation.", "Explain what the pupil will still need to think or do independently.", "State how you will review whether the support worked."], placeholder: "Learning goal…\nTask demands…\nBarrier…\nAdaptation…\nIndependent thinking retained…\nReview evidence…", minimumCharacters: 220 },
      { id: "se13", type: "content", title: "High expectations and reasonable adjustment", body: "Inclusive teaching does not mean making every task easier. It means removing barriers that are not central to the learning goal, making important information accessible and providing the support needed for pupils to participate. Sometimes the curriculum goal itself needs to be adapted according to a pupil's plan, but that decision should come from appropriate assessment and planning rather than an automatic assumption based on a label.", keyPoints: ["Access and ambition can coexist", "Adjust the route before automatically lowering the destination", "Use pupil plans and specialist advice appropriately", "Judge impact through participation, learning and independence", "Review support rather than letting it continue by habit"] }
    ]
  }
];
