import type { Course, Module } from "./data";
const reflect=(id:string,prompt:string):Module=>({id,type:"reflection",title:"Apply it to your practice",prompt});
export const schoolCoursesBatch3:Course[]=[
{
 id:"writing-across-curriculum",title:"Writing Across the Curriculum",category:"Teaching & Learning",duration:75,level:"Developing",summary:"Teach pupils how strong writing works in your subject through modelling, sentence-level support, planning and purposeful feedback.",objectives:["Identify subject-specific writing demands","Model expert writing decisions","Use scaffolds without replacing thinking","Build from oral rehearsal to independent writing"],recommendedFor:["Teacher","ECT","Department Lead"],modules:[
  {id:"wac1",type:"content",title:"Writing is disciplinary thinking",body:"A scientific explanation, historical argument and geographical evaluation are not the same writing task. Strong teaching makes the hidden structure visible: how ideas are selected, ordered, connected, evidenced and qualified. Generic advice such as 'add detail' is rarely enough.",keyPoints:["Define what successful writing looks like in your subject","Model planning as well as the finished answer","Teach connective and evaluative language in context","Use examples to discuss quality","Fade writing frames as pupils become more independent"]},
  {id:"wac2",type:"visual",title:"From idea to independent writing",layout:"flow",items:[{heading:"Know",text:"Secure the subject content first.",icon:"1"},{heading:"Rehearse",text:"Say the explanation/argument aloud.",icon:"2"},{heading:"Model",text:"Make expert writing decisions visible.",icon:"3"},{heading:"Guide",text:"Use temporary sentence or paragraph support.",icon:"4"},{heading:"Write",text:"Independent response with review.",icon:"5"}]},
  {id:"wac3",type:"scenario",title:"Weak-writing scenario",prompt:"Pupils know the science but write short, disconnected explanations. What is the strongest response?",options:[{label:"Tell them to write more",feedback:"Quantity does not reveal the structure of a strong explanation."},{label:"Model how causal links are expressed, rehearse orally and use a temporary sentence structure",feedback:"This teaches the disciplinary writing move explicitly."},{label:"Give them a finished answer to copy",feedback:"Copying removes the decisions pupils need to learn."}]},
  {id:"wac4",type:"activity",title:"Model a paragraph",prompt:"Plan a live model for one paragraph or extended response in your subject.",instructions:["State the content pupils must know.","Identify the key writing move: explain, compare, evaluate, justify or analyse.","Write two teacher think-aloud prompts.","Add one scaffold and state how it will be faded."],placeholder:"Content…\nWriting move…\nThink-aloud…\nScaffold/fade…",minimumCharacters:120},
  reflect("wac5","What writing decision do experts in your subject make automatically that pupils need you to make visible?")
 ]
},
{
 id:"numeracy-across-curriculum",title:"Numeracy Across the Curriculum",category:"Teaching & Learning",duration:70,level:"Developing",summary:"Build consistent approaches to number, proportion, graphs, units and data interpretation across subjects without turning every teacher into a maths teacher.",objectives:["Identify recurring numeracy demands","Use consistent representations and language","Teach units and proportional reasoning explicitly","Support graph/data interpretation"],recommendedFor:["Teacher","ECT","Department Lead"],modules:[
  {id:"nac1",type:"content",title:"Numeracy is embedded in many subjects",body:"Percentages, ratios, scales, units, averages, graphs and uncertainty appear across science, geography, design, PE and other subjects. Inconsistent language or notation can increase cognitive load. Departments can agree a few common conventions while still teaching subject-specific meaning.",keyPoints:["Use units consistently","Make proportional relationships explicit","Teach graph axes and scales rather than assuming","Agree common language with mathematics where practical","Use real subject contexts rather than isolated arithmetic drills"]},
  {id:"nac2",type:"visual",title:"Numeracy demand map",layout:"compare",items:[{heading:"Number",text:"Magnitude, decimals, percentages and estimation.",icon:"#"},{heading:"Proportion",text:"Ratios, rates, scaling and percentage change.",icon:"÷"},{heading:"Measure",text:"Units, conversions, precision and uncertainty.",icon:"↔"},{heading:"Data",text:"Tables, graphs, averages and interpretation.",icon:"▥"}]},
  {id:"nac3",type:"scenario",title:"Graph scenario",prompt:"Pupils can plot points but misread a non-zero axis and draw the wrong conclusion. What should the subject teacher do?",options:[{label:"Leave it entirely to maths lessons",feedback:"The graph is part of the subject meaning and should be taught in context."},{label:"Model how scale and axis choice affect interpretation, then give a similar subject example",feedback:"This connects numeracy to disciplinary reasoning."},{label:"Remove graphs from the topic",feedback:"Avoidance prevents pupils developing the required skill."}]},
  {id:"nac4",type:"checklist",title:"Numeracy consistency check",prompt:"Check one unit of work for hidden numeracy barriers.",items:["Units are explicit and consistent","Required conversions are taught/retrieved","Graphs use clear labels and scales","Percentage/ratio language is used consistently","Worked numerical examples show reasoning, not just answers","Estimation or reasonableness checks are modelled"],completionText:"Numeracy audit complete."},
  reflect("nac5","Which numerical convention in your subject causes the most avoidable confusion, and how could your department standardise it?")
 ]
},
{
 id:"high-attaining-pupils",title:"Teaching High-Attaining Pupils: Depth, Challenge & Independence",category:"Teaching & Learning",duration:75,level:"Developing",summary:"Increase intellectual challenge through depth, complexity, transfer and independence rather than simply giving more work or accelerating indiscriminately.",objectives:["Distinguish challenge from workload","Use depth and transfer","Avoid ceiling effects in tasks","Support independence and productive struggle"],recommendedFor:["Teacher","ECT","Department Lead"],modules:[
  {id:"ha1",type:"content",title:"More work is not the same as more challenge",body:"High-attaining pupils benefit when tasks demand stronger connections, justification, transfer, evaluation or abstraction. Simply adding more questions of the same type can increase workload without deepening thinking. Challenge should remain connected to curriculum goals.",keyPoints:["Use deeper questions before extra volume","Require explanation and justification","Introduce unfamiliar contexts","Use comparison and evaluation","Do not assume high attainment means no need for teaching or feedback"]},
  {id:"ha2",type:"visual",title:"Challenge ladder",layout:"ladder",items:[{heading:"Accuracy",text:"Can the pupil perform the core task securely?",icon:"1"},{heading:"Explain",text:"Can they justify how and why?",icon:"2"},{heading:"Connect",text:"Can they link ideas across the subject?",icon:"3"},{heading:"Transfer",text:"Can they use knowledge in an unfamiliar context?",icon:"4"},{heading:"Evaluate/Create",text:"Can they critique, synthesise or design?",icon:"5"}]},
  {id:"ha3",type:"scenario",title:"Early-finisher scenario",prompt:"A pupil finishes the standard task accurately in half the expected time. What is the strongest next move?",options:[{label:"Give twenty more identical questions",feedback:"This increases quantity but may not increase challenge."},{label:"Use a transfer or justification task that deepens the same curriculum goal",feedback:"This adds intellectual demand without unnecessary acceleration."},{label:"Let them disengage because they already know it",feedback:"High attainment still requires purposeful learning."}]},
  {id:"ha4",type:"activity",title:"Upgrade a task",prompt:"Transform one routine task into a deeper challenge without making it longer for the sake of it.",instructions:["Write the original task.","Identify the core knowledge/skill.","Add one depth move: justify, compare, transfer, critique or design.","State what a strong response would reveal about understanding."],placeholder:"Original…\nCore goal…\nDepth move…\nEvidence…",minimumCharacters:110},
  reflect("ha5","Where in your current curriculum do high-attaining pupils hit a ceiling because the task stops demanding deeper thinking?")
 ]
},
{
 id:"supporting-disadvantaged-pupils",title:"Supporting Disadvantaged Pupils Without Lowering Expectations",category:"Teaching & Learning",duration:80,level:"Developing",summary:"Use evidence, high-quality teaching and targeted barrier removal while avoiding deficit assumptions about pupils from disadvantaged backgrounds.",objectives:["Avoid stereotyping disadvantage","Identify specific learning barriers","Prioritise high-quality teaching","Use targeted support with clear impact measures"],recommendedFor:["Teacher","ECT","Department Lead","Leadership"],modules:[
  {id:"dp1",type:"content",title:"Disadvantage is not a pupil profile",body:"Pupils eligible for additional funding or facing socioeconomic disadvantage are diverse. Staff should not assume low vocabulary, poor home support, weak aspirations or behaviour difficulty. Strong practice starts by identifying actual barriers in attendance, prior knowledge, literacy, access to resources or learning habits and responding to evidence.",keyPoints:["Do not infer need from a label alone","Protect curriculum entitlement","Prioritise classroom teaching quality","Target support to an identified barrier","Measure whether the barrier is changing"]},
  {id:"dp2",type:"visual",title:"Barrier-to-impact cycle",layout:"flow",items:[{heading:"Identify",text:"What specific barrier is visible in evidence?",icon:"1"},{heading:"Select",text:"Choose a proportionate strategy.",icon:"2"},{heading:"Implement",text:"Define who does what and when.",icon:"3"},{heading:"Measure",text:"Use learning/attendance evidence.",icon:"4"},{heading:"Adapt",text:"Continue, change or stop based on impact.",icon:"5"}]},
  {id:"dp3",type:"scenario",title:"Intervention scenario",prompt:"A school wants to give every disadvantaged pupil the same generic intervention. What is the strongest challenge?",options:[{label:"Use it because all disadvantaged pupils have the same needs",feedback:"Disadvantage does not create one uniform learning profile."},{label:"Start from pupil-level barriers and use targeted support only where the evidence matches",feedback:"Support should respond to need rather than category alone."},{label:"Remove challenging work from the pupils involved",feedback:"Lower expectations are not an evidence-based response to disadvantage."}]},
  {id:"dp4",type:"checklist",title:"Equity check",prompt:"Check whether an intervention avoids deficit assumptions.",items:["The barrier is defined using evidence","The curriculum goal remains ambitious","The strategy has a clear rationale","The pupil is not publicly labelled","Impact measures are specified","There is a review/stop decision"],completionText:"Equity check complete."},
  reflect("dp5","Which school or department assumption about disadvantaged pupils could be replaced with a more specific question about barriers and evidence?")
 ]
},
{
 id:"gender-participation-learning",title:"Gender, Participation & Learning: Avoiding Stereotypes",category:"Teaching & Learning",duration:65,level:"Developing",summary:"Examine participation, expectations and outcomes by gender without using simplistic claims that boys and girls learn in fundamentally different ways.",objectives:["Question gender-learning myths","Use participation and outcome data carefully","Design inclusive routines","Avoid reinforcing stereotypes"],recommendedFor:["Teacher","Tutor","Department Lead"],modules:[
  {id:"gpl1",type:"content",title:"Start with evidence, not stereotypes",body:"Average outcome differences between groups do not mean every pupil within a group learns in the same way. Statements such as 'boys need competition' or 'girls prefer collaboration' can lower expectations and reinforce stereotypes. Better questions focus on who participates, who receives feedback, who opts out of challenge and which patterns appear in your actual classes.",keyPoints:["Avoid learning-style claims by gender","Analyse your own participation data","Keep expectations consistent","Notice subject-choice and confidence patterns","Use individual need over group stereotype"]},
  {id:"gpl2",type:"visual",title:"Questions to ask instead",layout:"compare",items:[{heading:"Participation",text:"Who answers, volunteers and receives follow-up questions?",icon:"?"},{heading:"Feedback",text:"Who gets challenge, correction and encouragement to persist?",icon:"↗"},{heading:"Representation",text:"Whose examples, careers and contributions are visible?",icon:"◉"},{heading:"Belonging",text:"Who feels this subject is 'for people like me'?",icon:"◎"}]},
  {id:"gpl3",type:"scenario",title:"Planning scenario",prompt:"A colleague says, 'The boys need movement, the girls need discussion.' What is the strongest professional response?",options:[{label:"Plan separate gender-based teaching styles",feedback:"This risks reinforcing unsupported stereotypes."},{label:"Use evidence from the actual class and vary pedagogy according to task and individual need",feedback:"Instruction should follow learning evidence rather than gender myths."},{label:"Never look at gender patterns at all",feedback:"Group data can reveal inequity, but it should be interpreted carefully."}]},
  {id:"gpl4",type:"activity",title:"Participation audit",prompt:"Audit one recent lesson for participation patterns.",instructions:["Estimate who volunteered and who was selected.","Note who received follow-up/challenge questions.","Check whether examples or resources implied gender stereotypes.","Choose one routine to broaden participation next lesson."],placeholder:"Audit findings…\nNext routine…",minimumCharacters:100},
  reflect("gpl5","Which classroom routine could help you broaden participation without making assumptions about why particular pupils currently participate less?")
 ]
},
{
 id:"effective-group-work",title:"Effective Group Work & Collaborative Learning",category:"Teaching & Learning",duration:70,level:"Developing",summary:"Design group tasks with genuine interdependence, individual accountability and explicit collaboration routines so group work produces learning rather than social loafing.",objectives:["Choose tasks that benefit from collaboration","Build individual accountability","Teach discussion roles and routines","Monitor group learning rather than noise level"],recommendedFor:["Teacher","ECT"],modules:[
  {id:"gw1",type:"content",title:"Use groups when the task needs them",body:"Group work is most useful when pupils need to compare ideas, combine information, solve a problem or critique alternatives. Putting pupils in groups does not automatically create collaboration. Roles, accountability, task design and teacher monitoring determine whether all pupils think.",keyPoints:["Use a clear shared outcome","Build individual accountability","Give thinking time before group discussion","Teach how to disagree and build on ideas","Avoid roles that remove thinking from some pupils"]},
  {id:"gw2",type:"visual",title:"Collaborative task structure",layout:"flow",items:[{heading:"Think alone",text:"Everyone prepares an idea.",icon:"1"},{heading:"Share",text:"Each pupil contributes.",icon:"2"},{heading:"Challenge",text:"The group compares evidence/reasoning.",icon:"3"},{heading:"Synthesize",text:"Create a shared answer/product.",icon:"4"},{heading:"Account",text:"Any member may explain the group's reasoning.",icon:"5"}]},
  {id:"gw3",type:"scenario",title:"Passenger problem",prompt:"In groups of four, one pupil completes the task while the others watch. What is the strongest redesign?",options:[{label:"Make the group larger",feedback:"More pupils may increase the passenger problem."},{label:"Require individual preparation, structured turns and random accountability for the final reasoning",feedback:"This makes participation necessary without removing collaboration."},{label:"Ban group work",feedback:"The task structure, not collaboration itself, is the problem."}]},
  {id:"gw4",type:"checklist",title:"Group-task quality",prompt:"Check a planned collaborative task.",items:["Collaboration adds value beyond individual work","Everyone prepares before discussion","Each pupil has a meaningful thinking role","The shared outcome requires combining ideas","Individuals remain accountable","The teacher has planned what to listen/look for"],completionText:"Group-task check complete."},
  reflect("gw5","Which group-work routine would most reduce passive participation in your classroom?")
 ]
},
{
 id:"cover-supply-classroom-management",title:"Practical Classroom Management for Cover & Supply Staff",category:"Teaching & Learning",duration:55,level:"Foundation",summary:"Use clear starts, simple routines, safeguarding awareness and proportionate behaviour responses when teaching unfamiliar classes.",objectives:["Establish clarity quickly","Use school behaviour systems consistently","Protect safeguarding boundaries","Leave useful handover information"],recommendedFor:["Cover Supervisor","Supply Teacher","Teacher","ECT"],modules:[
  {id:"cs1",type:"content",title:"Clarity matters more when relationships are new",body:"Cover lessons can become difficult when pupils are uncertain about routines, task expectations or consequences. A calm introduction, visible task sequence, seating information where available and consistent use of the school's behaviour system reduce ambiguity.",keyPoints:["Know emergency and safeguarding routes before teaching","State the first task immediately","Use the school's behaviour policy, not invented sanctions","Avoid lengthy public arguments","Record useful handover information factually"]},
  {id:"cs2",type:"visual",title:"The first five minutes",layout:"timeline",items:[{heading:"Entry",text:"Meet, seat and start calmly.",icon:"1"},{heading:"Task visible",text:"Give a simple first action.",icon:"2"},{heading:"Expectations",text:"State key routine/behaviour expectations.",icon:"3"},{heading:"Check",text:"Confirm pupils know what to do.",icon:"4"},{heading:"Scan",text:"Circulate early before problems grow.",icon:"5"}]},
  {id:"cs3",type:"scenario",title:"Challenge scenario",prompt:"A pupil says, 'Our normal teacher lets us do this.' What is the strongest response?",options:[{label:"Argue about whether they are lying",feedback:"A public argument wastes time and may escalate."},{label:"Calmly refer to the school expectation/task and continue using the agreed behaviour system",feedback:"Consistency with school systems is more important than winning the argument."},{label:"Invent a new punishment",feedback:"Cover staff should use existing school policy."}]},
  {id:"cs4",type:"checklist",title:"Cover readiness",prompt:"Before a cover lesson, check what you need.",items:["Register/attendance procedure","Safeguarding contact/route","Behaviour policy steps","Emergency procedure","Lesson/task materials","Key pupil information you are authorised to know","Handover method for the class teacher"],completionText:"Cover readiness check complete."},
  reflect("cs5","What is the one routine you will make explicit in the first minute of an unfamiliar class?")
 ]
},
{
 id:"difficult-parent-conversations",title:"Managing Difficult Parent & Carer Conversations",category:"Leadership",duration:75,level:"Developing",summary:"Prepare, listen, maintain boundaries and document difficult conversations while keeping the focus on the pupil and school procedures.",objectives:["Prepare evidence and purpose","Use de-escalating communication","Maintain professional boundaries","Record agreed actions and escalation routes"],recommendedFor:["Teacher","Tutor","Pastoral","Department Lead","Leadership"],modules:[
  {id:"pc1",type:"content",title:"Preparation reduces heat",body:"Difficult conversations are easier when the purpose, facts and desired next step are clear. Staff should separate evidence from interpretation, avoid discussing other pupils, know what they can and cannot promise, and understand when a colleague or senior leader should join the conversation.",keyPoints:["Prepare factual examples","Start with the shared goal for the pupil","Listen before defending","Do not discuss confidential information about others","Summarise actions and deadlines","Escalate threatening or abusive behaviour using school procedures"]},
  {id:"pc2",type:"visual",title:"Conversation structure",layout:"flow",items:[{heading:"Prepare",text:"Facts, purpose, boundaries.",icon:"1"},{heading:"Listen",text:"Understand the concern without agreeing to inaccurate claims.",icon:"2"},{heading:"Clarify",text:"Separate facts, interpretations and requests.",icon:"3"},{heading:"Agree",text:"Set realistic next actions.",icon:"4"},{heading:"Record",text:"Document outcome and follow-up.",icon:"5"}]},
  {id:"pc3",type:"scenario",title:"Escalating call",prompt:"A parent becomes increasingly angry and demands confidential information about another pupil. What should you do?",options:[{label:"Share the information to calm them down",feedback:"Confidential information about another pupil should not be disclosed."},{label:"Acknowledge the concern, restate what you can discuss, set boundaries and escalate/end the call according to policy if behaviour becomes unacceptable",feedback:"This protects confidentiality and professional boundaries."},{label:"Argue until the parent apologises",feedback:"Winning an argument is not the aim of the conversation."}]},
  {id:"pc4",type:"activity",title:"Prepare a difficult conversation",prompt:"Plan a conversation about a recurring pupil concern.",instructions:["Write the shared goal.","List two factual pieces of evidence.","Write one opening sentence that invites the parent/carer's perspective.","Define the boundary you must maintain.","Write the next action and follow-up date."],placeholder:"Shared goal…\nEvidence…\nOpening…\nBoundary…\nFollow-up…",minimumCharacters:130},
  reflect("pc5","Which part of difficult conversations do you find hardest: preparation, listening, boundary-setting or closing with clear actions?")
 ]
},
{
 id:"professional-boundaries-staff-conduct",title:"Professional Boundaries & Staff Conduct",category:"Safeguarding",duration:80,level:"Foundation",summary:"Maintain clear, safe professional relationships with pupils across communication, social media, confidentiality, physical boundaries and allegations procedures.",objectives:["Understand why boundaries protect pupils and staff","Use approved communication channels","Protect confidentiality","Know what to do when a boundary concern or allegation arises"],recommendedFor:["All staff"],modules:[
  {id:"pb1",type:"content",title:"Boundaries create safety and clarity",body:"Professional warmth and strong relationships are compatible with clear boundaries. Staff should use approved communication systems, avoid secret or private arrangements, protect pupil information, follow the school's staff code of conduct and seek advice early when unsure.",keyPoints:["Use school-approved communication channels","Avoid secrecy and favouritism","Keep personal social-media boundaries clear","Do not share confidential pupil information casually","Follow low-level concern/allegation procedures","Ask for advice before a situation becomes ambiguous"]},
  {id:"pb2",type:"visual",title:"Boundary test",layout:"compare",items:[{heading:"Transparent",text:"Could this interaction be comfortably explained to a senior colleague or parent/carer?",icon:"✓"},{heading:"Purposeful",text:"Is it clearly connected to the staff role and pupil's education/welfare?",icon:"◎"},{heading:"Proportionate",text:"Is the level of contact/support reasonable?",icon:"↔"},{heading:"Recorded/approved",text:"Does it use school systems where required?",icon:"▦"}]},
  {id:"pb3",type:"scenario",title:"Messaging scenario",prompt:"A pupil asks a teacher to move a school-related conversation to the teacher's personal social-media account. What is the safest response?",options:[{label:"Agree but delete the messages later",feedback:"Private communication outside approved systems creates avoidable safeguarding risk."},{label:"Keep communication on the school's approved platform and explain that boundary clearly",feedback:"Transparent, approved channels protect both pupil and staff member."},{label:"Ask another pupil to pass messages",feedback:"This is not an appropriate substitute for approved communication."}]},
  {id:"pb4",type:"checklist",title:"Professional-boundary check",prompt:"Check the practices that protect staff and pupils.",items:["Communication uses approved channels","One-to-one arrangements follow school procedures","Confidential information is shared only as required","Social-media privacy/boundaries are maintained","Concerns about staff conduct are reported through the correct route","Staff seek advice when a situation feels ambiguous"],completionText:"Professional-boundary check complete."},
  reflect("pb5","Which professional boundary is most likely to become blurred through convenience, and what system can keep it clear?")
 ]
},
{
 id:"school-data-protection-gdpr",title:"Data Protection & UK GDPR in Schools",category:"Digital Teaching",duration:85,level:"Foundation",summary:"Handle pupil and staff data lawfully and securely across email, photos, cloud systems, AI tools, sharing and access requests while following school data-protection procedures.",objectives:["Recognise personal and special-category data","Apply data minimisation and purpose limitation","Use secure sharing and storage","Know how to report a data incident"],recommendedFor:["All staff"],modules:[
  {id:"gdpr1",type:"content",title:"Data protection is everyday school practice",body:"Names, contact details, assessment records, behaviour notes, SEND information, safeguarding information, photographs and device/account identifiers can all be personal data. Staff should use authorised systems, access only what they need for their role and follow the school's privacy, retention and breach-reporting procedures. Current ICO guidance should be followed because data-protection guidance changes over time.",keyPoints:["Use the minimum data needed","Use authorised systems and recipients","Double-check email addresses and attachments","Protect sensitive information on shared screens/devices","Do not paste identifiable pupil data into unapproved AI tools","Report suspected data breaches promptly"]},
  {id:"gdpr2",type:"visual",title:"Safe data decision",layout:"flow",items:[{heading:"Purpose",text:"Why do I need this information?",icon:"1"},{heading:"Minimum",text:"What is the least data needed?",icon:"2"},{heading:"Authority",text:"Am I allowed to access/share it?",icon:"3"},{heading:"Secure route",text:"Which approved system/channel should I use?",icon:"4"},{heading:"Review",text:"Should it be retained, corrected or deleted under policy?",icon:"5"}]},
  {id:"gdpr3",type:"scenario",title:"Email scenario",prompt:"You are about to send a spreadsheet containing pupil information to a colleague and notice an external address has auto-completed in the recipient list. What should you do?",options:[{label:"Send quickly before the system changes again",feedback:"This risks an avoidable data breach."},{label:"Stop, verify recipients and attachment, use the approved secure route and report any accidental disclosure immediately if it has already happened",feedback:"Recipient checking and prompt breach reporting are basic safeguards."},{label:"Remove the pupil names but leave all other identifying data without checking",feedback:"Other data may still identify pupils; use school guidance on anonymisation."}]},
  {id:"gdpr4",type:"checklist",title:"Before you share pupil data",prompt:"Check each step before sending or uploading personal information.",items:["The purpose is legitimate and necessary","Only the minimum data is included","The recipient is authorised","The channel/system is approved","The attachment/link permissions are correct","Sensitive data is not exposed on screen or device","You know how to report an error immediately"],completionText:"Data-sharing checklist complete."},
  reflect("gdpr5","Which routine data-handling task in your role has the greatest risk of accidental oversharing, and what check could prevent it?")
 ]
},
{
 id:"cybersecurity-school-staff",title:"Cybersecurity for School Staff",category:"Digital Teaching",duration:70,level:"Foundation",summary:"Reduce common school cyber risks through strong authentication, phishing awareness, safe devices, updates and prompt reporting of suspicious activity.",objectives:["Recognise common phishing/social-engineering patterns","Use MFA and password practices safely","Protect devices and accounts","Report incidents promptly"],recommendedFor:["All staff"],modules:[
  {id:"cy1",type:"content",title:"Schools are attractive targets",body:"Schools depend on email, cloud platforms, MIS systems and shared devices, so a compromised account can disrupt teaching and expose sensitive data. Staff do not need to be technical experts: following secure login, update, device and reporting routines removes many common attack opportunities.",keyPoints:["Use MFA where provided","Never approve an unexpected login prompt","Use unique strong passwords/passphrases","Keep devices updated and locked","Treat urgent payment/password requests cautiously","Report suspicious emails or account activity quickly"]},
  {id:"cy2",type:"visual",title:"Phishing pause",layout:"flow",items:[{heading:"Stop",text:"Urgency is a common manipulation tactic.",icon:"1"},{heading:"Check sender",text:"Look carefully at address/domain and context.",icon:"2"},{heading:"Check request",text:"Would this person normally ask this way?",icon:"3"},{heading:"Verify separately",text:"Use a known contact route, not the message link.",icon:"4"},{heading:"Report",text:"Use the school's phishing/security route.",icon:"5"}]},
  {id:"cy3",type:"scenario",title:"Login prompt scenario",prompt:"Your phone shows an MFA approval request when you are not trying to sign in. What should you do?",options:[{label:"Approve it in case the system needs access",feedback:"Unexpected approval requests may indicate someone has your password."},{label:"Deny it and report/check the account through the school's security route",feedback:"Unexpected MFA prompts should not be approved."},{label:"Ignore every future MFA prompt",feedback:"Use MFA normally when you are genuinely signing in; the issue is the unexpected request."}]},
  {id:"cy4",type:"checklist",title:"Staff cyber hygiene",prompt:"Check the habits that reduce everyday cyber risk.",items:["MFA is enabled where available","Passwords/passphrases are unique","Devices lock when unattended","Software updates are not repeatedly postponed","Suspicious links/attachments are not opened casually","Payment/account-change requests are verified separately","Incidents are reported promptly"],completionText:"Cybersecurity checklist complete."},
  reflect("cy5","Which cyber-security habit is easiest to neglect during a busy school day, and what routine could make it automatic?")
 ]
},
{
 id:"ai-in-education",title:"Safe & Effective Use of AI in Schools",category:"Digital Teaching",duration:95,level:"Developing",summary:"Use generative AI to support staff work and learning while managing safeguarding, data, bias, accuracy, intellectual-property and assessment risks.",objectives:["Identify appropriate school AI use cases","Protect sensitive information","Verify outputs and manage bias","Align use with school policy, safeguarding and assessment rules"],recommendedFor:["All staff","Teacher","Leadership"],modules:[
  {id:"aie1",type:"content",title:"AI can assist; staff remain accountable",body:"Generative AI can draft, summarise, adapt or brainstorm, but outputs can be inaccurate, biased or unsuitable for pupils. Staff remain responsible for professional judgement, safeguarding, factual accuracy and data protection. DfE guidance emphasises safe use, checking outputs and careful planning of tools and use cases.",keyPoints:["Never treat AI output as authoritative","Do not enter identifiable sensitive pupil data into unapproved tools","Check age/safeguarding suitability","Verify important factual claims","Review for bias and accessibility","Follow school policy and approved-product decisions"]},
  {id:"aie2",type:"visual",title:"AI safety loop",layout:"cycle",items:[{heading:"Purpose",text:"What job should AI support?",icon:"1"},{heading:"Data",text:"Can the task be done without sensitive data?",icon:"2"},{heading:"Generate",text:"Give clear constraints and context.",icon:"3"},{heading:"Verify",text:"Check accuracy, bias, safety and quality.",icon:"4"},{heading:"Own",text:"A member of staff remains accountable for use.",icon:"5"}]},
  {id:"aie3",type:"scenario",title:"Pupil-data scenario",prompt:"A teacher wants to paste named SEND profiles into a public AI tool to generate differentiated worksheets. What is the safest response?",options:[{label:"Do it because the educational purpose makes any data use acceptable",feedback:"Educational value does not remove data-protection and product-safety requirements."},{label:"Do not enter identifiable sensitive data into an unapproved tool; use approved systems and remove/minimise personal data",feedback:"Data minimisation and approved-tool decisions are essential."},{label:"Replace pupil names with initials and assume the data is anonymous",feedback:"Initials plus contextual details may still identify pupils."}]},
  {id:"aie4",type:"checklist",title:"Before using AI",prompt:"Check each point before using generated content with pupils or in school work.",items:["The tool/use is permitted by school policy","No unnecessary personal/sensitive data is entered","Important facts are independently verified","Content is checked for bias/stereotypes","Safeguarding and age suitability are checked","Copyright/IP considerations are respected","The final output is reviewed by a responsible member of staff"],completionText:"AI safety check complete."},
  {id:"aie5",type:"activity",title:"Design a low-risk AI workflow",prompt:"Choose one staff task where AI could save time and design the checking process around it.",instructions:["Define the task and what AI will/not do.","State what data will be excluded.","Write two checks for accuracy/quality.","Identify the human decision that cannot be delegated."],placeholder:"Task…\nExcluded data…\nChecks…\nHuman decision…",minimumCharacters:120},
  reflect("aie6","Which AI use in your role has the clearest benefit with the lowest data/safeguarding risk, and what checks must remain human?")
 ]
},
{
 id:"academic-integrity-ai",title:"Academic Integrity in the Age of AI",category:"Digital Teaching",duration:80,level:"Developing",summary:"Design assessment and classroom routines that make pupil thinking visible, teach acceptable AI use and respond to suspected misuse fairly.",objectives:["Clarify acceptable and unacceptable AI use","Design more authentic assessment evidence","Avoid unreliable detection-only approaches","Teach pupils how to acknowledge AI support where permitted"],recommendedFor:["Teacher","Department Lead","Exams staff","Leadership"],modules:[
  {id:"aii1",type:"content",title:"Integrity needs clear rules and better evidence",body:"AI makes it easier to produce fluent text without demonstrating the pupil's own thinking. Schools should define acceptable use clearly, teach those expectations, and use assessment design that includes drafts, oral explanation, in-class work or other evidence of process. Ofqual provides current resources on AI and coursework integrity, so exam-board rules should always be checked for assessed work.",keyPoints:["Teach expectations before problems occur","Use process evidence as well as final product","Do not rely on AI detectors as proof","Ask pupils to explain reasoning and sources","Follow exam-board/coursework rules for formal assessment"]},
  {id:"aii2",type:"visual",title:"Make learning visible",layout:"flow",items:[{heading:"Set rules",text:"Clarify permitted AI use.",icon:"1"},{heading:"Capture process",text:"Plans, drafts, notes, in-class checkpoints.",icon:"2"},{heading:"Question",text:"Ask pupils to explain choices and reasoning.",icon:"3"},{heading:"Verify",text:"Check sources, facts and authorship evidence.",icon:"4"},{heading:"Respond fairly",text:"Use policy/evidence rather than guesswork.",icon:"5"}]},
  {id:"aii3",type:"scenario",title:"Suspicious coursework scenario",prompt:"A pupil submits work far beyond their usual style. What is the strongest response?",options:[{label:"Use an AI detector result as automatic proof",feedback:"Detection tools can be unreliable and should not be treated as conclusive evidence."},{label:"Follow the assessment policy, compare process evidence and ask the pupil to explain the work/decisions",feedback:"Authorship should be assessed through policy and evidence rather than a single detector score."},{label:"Ignore it because AI can never be identified",feedback:"Schools can use process evidence and clear assessment procedures."}]},
  {id:"aii4",type:"activity",title:"Redesign an assessment",prompt:"Take one homework/coursework-style task and add evidence of pupil process without making it unnecessarily burdensome.",instructions:["State the learning outcome.","Add one in-class checkpoint or draft stage.","Add one short oral/explanation element.","State the AI-use rule pupils will receive."],placeholder:"Outcome…\nCheckpoint…\nExplanation…\nAI rule…",minimumCharacters:120},
  reflect("aii5","Which assessment in your subject currently depends too heavily on a polished final product rather than visible thinking and process?")
 ]
}
];
