import type {Course} from "./data";
export type CatalogueFacts={total:number;short:number;core:number;coreMin:number;coreMax:number;shortMax:number};
export function catalogueFacts(courses:readonly Course[]):CatalogueFacts{
 const short=courses.filter(c=>c.duration<=20),core=courses.filter(c=>c.duration>20);
 return {total:courses.length,short:short.length,core:core.length,coreMin:core.length?Math.min(...core.map(c=>c.duration)):0,coreMax:core.length?Math.max(...core.map(c=>c.duration)):0,shortMax:short.length?Math.max(...short.map(c=>c.duration)):0};
}
export const procurementFields=[
 {id:"provider",label:"Provider legal name & registration",hint:"Legal entity, registration number if applicable, registered address."},
 {id:"school",label:"School / trust legal entity",hint:"The purchasing organisation and agreed data-protection roles."},
 {id:"contacts",label:"Support & privacy contacts",hint:"Named service owner, support email and privacy / incident contact."},
 {id:"quote",label:"Written price & purchase-order terms",hint:"Currency, tax, school scope, seats, term, billing and quote expiry."},
 {id:"renewal",label:"Renewal & exit arrangements",hint:"Notice periods, cancellation, export assistance and any exit costs."},
 {id:"service",label:"Agreed service levels",hint:"Support hours, response targets, maintenance and escalation; no guarantees are prefilled."},
 {id:"retention",label:"Retention, return & deletion",hint:"Retention for live records, account closure, backups and logs; verified deletion procedure."},
 {id:"hosting",label:"Hosting & subprocessors",hint:"Provider inventory, functions, regions, international transfers and authorisation process."},
 {id:"security",label:"Security & recovery evidence",hint:"Access review, password protection, incident process, backup / restore test and agreed recovery targets."},
 {id:"accessibility",label:"Accessibility assessment & adjustments",hint:"Dated assessment, tested journeys, known limitations and alternative access arrangements."},
 {id:"agreement",label:"Reviewed processing agreement",hint:"Document reference/version, processing instructions and approval owner; this pack is not the agreement."},
 {id:"rollout",label:"Pilot & rollout owner",hint:"Responsible school lead, pilot group, review date and introduction plan."}
] as const;
export type ProcurementFieldId=typeof procurementFields[number]["id"];
export type ProcurementDetails=Partial<Record<ProcurementFieldId,string>>;
export type PackSection={id:string;title:string;status:string;paragraphs:string[];items:string[];source?:{title:string;href:string}};
export function procurementSections(facts:CatalogueFacts):PackSection[]{
 return [
 {id:"overview",title:"Product overview",status:"Implemented product features",paragraphs:["Teaching CPD is a staff professional-learning platform for schools: focused courses, connected pathways, learning assignments and school-level reporting.",facts.total+" catalogue courses: "+facts.core+" core courses with planned durations from "+facts.coreMin+" to "+facts.coreMax+" minutes, and "+facts.short+" short courses of up to "+facts.shortMax+" minutes. Times are estimates, not measured attendance."],items:["Find courses by role, learning need, duration and learning status.","Read subject-specific passages, practise with interactive activities and complete knowledge checks.","Save practical takeaways and return to follow-up activities.","Review active staff completion, required-training renewals and overdue assignments."]},
 {id:"scope",title:"What a school should evaluate",status:"Buyer evaluation checklist",paragraphs:["Run a small pilot against your own staff-development priorities. Do not treat course completion as a qualification, proof of competence or a substitute for local safeguarding, safety or professional procedures."],items:["Choose an ordinary staff user and an authorised school administrator.","Test relevant courses and activities, saved progress and certificates.","Check connected pathways and whether learning leads to a useful classroom action.","Check local policy and training audiences, renewal cycles and reporting accuracy.","Agree who supports staff and who reviews course currency."]},
 {id:"data",title:"Data-handling facts and boundaries",status:"Implementation facts; full data inventory to confirm",paragraphs:["Staff accounts and school membership include identifiers, names, roles and departments. Learning records include progress, reflections and completion information. School operations can also hold local policy, assignment and training records.","The new school-reporting endpoint is limited to authenticated active school administrators. It excludes private reflections, assessment responses, evidence notes and assignment notes. CSV exports still contain staff personal data; use approved school storage.","This pack does not query or include any school's records. Do not put pupil names, health information or identifiable safeguarding cases into course reflections or procurement notes."],items:["Confirm the full production data map, logs, backups and storage locations with the provider.","Confirm all processors, subprocessors, sign-in providers and international-transfer arrangements.","Agree who handles rights requests, access changes, export, return and deletion."]},
 {id:"processing",title:"Processing-agreement review schedule",status:"Draft checklist, not a contract",paragraphs:["Have the school and provider confirm their data-protection roles and obtain an appropriately reviewed agreement. Record the processing purpose, duration, data categories, staff groups and school instructions.","Review confidentiality, security measures, subprocessor authorisation, support for individual rights, incident handling, end-of-contract return or deletion and audit information. Confirm responsibilities and any required assessment with the school's data-protection lead.","The linked ICO guidance is under review following legislative changes. Recheck current guidance when finalising terms."],items:["Attach the reviewed agreement and document reference.","Record unresolved questions and the person responsible for each.","Do not use this draft pack as a signed processing agreement."],source:{title:"ICO contracts guidance",href:"https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/accountability-and-governance/guide-to-accountability-and-governance/contracts/"}},
 {id:"security",title:"Security and service due diligence",status:"Evidence required before sale",paragraphs:["School-scoped reporting and checklist access were tested with transaction-only fixtures. These checks are not an independent penetration test or whole-platform security certification.","The deployment review found leaked-password protection disabled. The platform owner must review this alongside authentication configuration before rollout."],items:["Obtain a dated access-control and vulnerability review.","Confirm sign-in providers, recovery procedures and password protection.","Request backup coverage, a restore-test record and agreed recovery targets.","Agree incident contacts, notification process, support hours and escalation.","Verify hosting/subprocessor details; do not infer all data residency from a single database region."],source:{title:"Supabase password security guidance",href:"https://supabase.com/docs/guides/auth/password-security#password-strength-and-leaked-password-protection"}},
 {id:"accessibility",title:"Accessibility and inclusion",status:"Assessment required; no conformance certification claimed",paragraphs:["The new screens use labelled controls, keyboard focus indicators, responsive layouts and table headings. This is not proof that the full platform meets an accessibility standard.","Use WCAG 2.2 as a reference for a documented assessment. Test the actual learner and administrator journeys with keyboard, screen reader, zoom and mobile use, including interactive activities."],items:["Record tested browsers, assistive technologies, limitations and fixes.","Agree reasonable alternative ways to access activities and reading.","Publish an accurate accessibility statement after review."],source:{title:"W3C WCAG overview",href:"https://www.w3.org/WAI/standards-guidelines/wcag/"}},
 {id:"commercial",title:"Commercial and support schedule",status:"Provider and school to agree",paragraphs:["No prices, uptime promises, legal entity details or support-response guarantees are assumed. Complete the draft details below using a written provider quote and agreed terms."],items:["Confirm covered school sites, staff access and any seat limit.","Agree price, taxes, billing, purchase-order process and term.","Agree renewal, cancellation, export and exit arrangements.","Name the provider support owner and the school rollout lead."]},
 {id:"rollout",title:"Pilot and implementation plan",status:"Suggested school workflow",paragraphs:["Use School setup & tutorial to prepare the school, access, staff directory, local policies and first learning assignment. Its manual pilot checklist records administrator confirmations, not automatic launch approval."],items:["Preparation: confirm provider details and school responsibilities.","Configuration: verify school access and set policies / required training.","Pilot: test ordinary staff sign-in, course completion and saved progress after sign-out.","Reporting: confirm the pilot completion, training renewal status and exports.","Review: resolve gaps, agree the staff introduction and expand gradually."]}
 ];
}
export function missingProcurementFields(details:ProcurementDetails){return procurementFields.filter(f=>!details[f.id]?.trim());}
export function markdownText(value:string){return value.replace(/[\r\n\t]+/g," ").replace(/[\\`*_{}\[\]()<>#!|]/g,character=>"\\"+character).slice(0,2000);}
export function procurementMarkdown(facts:CatalogueFacts,details:ProcurementDetails):string{
 const missing=missingProcurementFields(details);
 const lines=["# Teaching CPD — school procurement pack","","> DRAFT FOR REVIEW — not a contract, approved quotation or compliance certification.","",missing.length+" / "+procurementFields.length+" details still to confirm. Entered details remain unverified.",""];
 for(const section of procurementSections(facts)){lines.push("## "+section.title,"","Status: "+section.status,"",...section.paragraphs.map(p=>p+"\n"),...section.items.map(item=>"- "+item),"");if(section.source)lines.push("Reference: ["+section.source.title+"]("+section.source.href+")","");}
 lines.push("## Draft details supplied for review","");
 for(const field of procurementFields)lines.push("### "+field.label,"",details[field.id]?.trim()?markdownText(details[field.id]!.trim()):"TO CONFIRM — "+field.hint,"");
 lines.push("## Approval handoff","","Provider reviewer: TO CONFIRM","School procurement reviewer: TO CONFIRM","School data-protection reviewer: TO CONFIRM","Approved contract / quote references: TO CONFIRM","","Resolve open items and obtain the appropriate approvals outside this tool. Downloading or printing does not approve a purchase or sign an agreement.");
 return lines.join("\n");
}
