export const pilotChecks=[
  {id:"pilot_login",title:"Test ordinary staff sign-in",detail:"Use a real non-admin school account. Confirm the sign-in provider, correct school, department and role. Do not invite everyone until this works."},
  {id:"pilot_save",title:"Check saved learning after sign-out",detail:"Complete a short course, sign out and sign back in. Confirm the saved learning and certificate remain available. A preview or build test is not a substitute."},
  {id:"pilot_report",title:"Check the school report",detail:"Confirm that the pilot completion appears under the correct member in School reporting. Verify its planned hours and required-training status."},
  {id:"procurement_review",title:"Review procurement and responsibilities",detail:"Ask the school and provider to review the procurement pack, data-processing terms, support arrangements and commercial details before purchase."}
] as const;
export type PilotCheckId=typeof pilotChecks[number]["id"];
export type SetupCheckpoint={checkpoint_id:PilotCheckId;completed:boolean;updated_at:string};
export type OnboardingSnapshot={generated_at:string;organisation_id:string;name:string;access_allowed:boolean;domains:number;members:number;directory:number;policies:number;requirements:number;assignments:number;checkpoints:SetupCheckpoint[]};
export const schoolTutorial=[
 {id:"school",title:"Connect your school",href:"/organisation",action:"Open organisation setup",reading:"Create the school once, or join the existing organisation. Check the academic year, timezone and school sites. If your account is ordinary Staff, ask an authorised administrator to set up the school; this tutorial does not grant administrator permissions.",tasks:["Use the school name staff recognise.","Check the correct school is attached to your account.","Add sites only where they are needed."]},
 {id:"access",title:"Prepare sign-in and access",href:"/school-access",action:"Open school access",reading:"A school licence and a verified school email domain support staff access. A platform owner must configure and test the Google or Microsoft provider. School Admins request domains; CPD Leads can review access. A recorded domain is not verified until its status says verified.",tasks:["Ask the platform owner to confirm the licence and domain.","Check the agreed staff limit and renewal arrangements.","Use a real ordinary staff account for the pilot."]},
 {id:"people",title:"Prepare your staff directory",href:"/staff-sync",action:"Open Staff Sync",reading:"Prepare names, school email addresses, departments and sites using the Staff Sync format. Review the preview before importing. A directory row is not an active sign-in account: school reporting only includes current active members.",tasks:["Start with a small pilot group.","Check departments and school sites.","Avoid importing pupil or sensitive case information."]},
 {id:"policies",title:"Add local policies and training",href:"/school-hub",action:"Open school hub",reading:"Publish current local policies with versions and review dates. Then use Training to set each mandatory requirement, audience and renewal interval. A catalogue course does not replace your school's local procedures or hands-on qualification requirements.",tasks:["Publish and check the actual school policies.","Open /training to assign requirements to the right audience.","Check review dates and renewal cycles with the responsible lead."]},
 {id:"learning",title:"Assign a focused first course",href:"/admin",action:"Open learning assignments",reading:"Start with one course linked to a genuine development need. In the Courses library, filter by role, learning need and available time. Short courses take up to 20 planned minutes. Read, practise, complete the checks and save a practical takeaway. Suggested connected pathways guide learning; they are not automatically assigned.",tasks:["Choose a relevant course, not the entire catalogue.","Set a realistic due date for the pilot.","Explain how staff find their assignment and save their learning."]},
 {id:"pilot",title:"Run the learner-to-report pilot",href:"/school-reporting",action:"Open school reporting",reading:"Follow the shared pilot checklist below using real school accounts. Check that saved progress survives sign-out and appears in school reporting. Review a CSV using approved school storage. Reports omit private reflections and answers, but exported staff names and completion records remain personal data.",tasks:["Run sign-in and saved-progress checks.","Confirm the pilot completion in School reporting.","Check missing training and overdue assignments make sense."]},
 {id:"launch",title:"Review before wider rollout",href:"/launch-readiness",action:"Open launch readiness",reading:"Configuration checks and manual attestations help you prepare; neither automatically approves launch. Review procurement, support ownership and any remaining gaps. Agree a pilot review date, staff introduction and who deals with access problems.",tasks:["Resolve missing configuration and pilot issues.","Review the draft procurement pack with the provider.","Invite staff in stages and check progress after the first week."]}
] as const;
export function setupChecks(snapshot:OnboardingSnapshot|null){
 return [
  {title:"School connected",done:Boolean(snapshot),detail:snapshot?.name||"Connect the school in Organisation setup."},
  {title:"Subscription permits access",done:snapshot?.access_allowed===true,detail:"Live server-side subscription check; this is not a purchase approval."},
  {title:"Verified email domain",done:Boolean(snapshot&&snapshot.domains>0),detail:(snapshot?.domains??0)+" verified domains"},
  {title:"Pilot members connected",done:Boolean(snapshot&&snapshot.members>1),detail:(snapshot?.members??0)+" active members; include an ordinary staff account"},
  {title:"Local policies configured",done:Boolean(snapshot&&snapshot.policies>0),detail:(snapshot?.policies??0)+" active policies; review their contents locally"},
  {title:"Mandatory training configured",done:Boolean(snapshot&&snapshot.requirements>0),detail:(snapshot?.requirements??0)+" active mandatory requirements"},
  {title:"Learning assigned",done:Boolean(snapshot&&snapshot.assignments>0),detail:(snapshot?.assignments??0)+" non-waived assignments"}
 ];
}
