import type { Course, Module } from "./data";

const reflection=(id:string,prompt:string):Module=>({id,type:"reflection",title:"Apply it to your practice",prompt});

export const schoolCoursesBatch1:Course[]=[
{
 id:"trauma-informed-practice",title:"Trauma-Informed Classroom Practice",category:"Wellbeing",duration:90,level:"Developing",
 summary:"Build predictable, relationship-rich classrooms that reduce avoidable stress while keeping expectations, safeguarding boundaries and professional roles clear.",
 objectives:["Explain core trauma-informed principles without diagnosing pupils","Recognise how stress can affect attention, memory, relationships and behaviour","Use predictable routines and regulation-supportive classroom practice","Respond through school pastoral and safeguarding systems when concerns arise"],
 recommendedFor:["All staff","Teacher","ECT","Teaching Assistant","Pastoral"],
 modules:[
  {id:"tip1",type:"content",title:"What trauma-informed practice is — and is not",body:"Trauma-informed practice asks staff to consider how past or current adversity may affect a pupil's sense of safety, attention, trust and regulation. It does not mean assuming trauma is the cause of every behaviour, diagnosing pupils, removing boundaries or lowering academic expectations. The strongest approach combines curiosity, predictable systems, good relationships and the school's safeguarding procedures.",keyPoints:["Be curious, not certain, about causes","Keep expectations clear and achievable","Avoid public humiliation or unnecessary confrontation","Use existing SEND, pastoral and safeguarding information","Do not ask pupils to disclose personal experiences for the sake of a classroom intervention"]},
  {id:"tip2",type:"visual",title:"The trauma-informed classroom cycle",caption:"A useful classroom response moves from safety and predictability towards learning and independence.",layout:"flow",items:[{heading:"Notice",text:"Observe behaviour and context without jumping to conclusions.",icon:"👀"},{heading:"Regulate",text:"Reduce avoidable stress and use calm, predictable communication.",icon:"◌"},{heading:"Relate",text:"Maintain a respectful connection and clear professional boundaries.",icon:"↔"},{heading:"Reason",text:"Return to explanation, reflection and problem-solving when the pupil is ready.",icon:"◎"},{heading:"Restore learning",text:"Re-establish the task, routine and expectations rather than abandoning learning.",icon:"↗"}]},
  {id:"tip3",type:"quiz",title:"Knowledge check",question:"Which statement best reflects trauma-informed practice?",options:["A pupil's difficult behaviour proves that they have experienced trauma","Clear boundaries should be removed when a pupil is distressed","Staff can maintain high expectations while adapting communication and support","Teachers should ask pupils to describe traumatic experiences so lessons can be personalised"],answer:2,feedback:"Trauma-informed practice can combine high expectations, predictable boundaries and responsive support without diagnosis or unnecessary disclosure."},
  {id:"tip4",type:"content",title:"Stress, attention and learning",body:"High stress can make it harder to focus attention, hold several pieces of information in mind, interpret social cues accurately or shift flexibly between tasks. This means a pupil may need concise instructions, visible steps, a calm transition or a brief reset before they can use the knowledge they already have. These supports are useful beyond trauma and can improve accessibility for many pupils.",keyPoints:["Use short, concrete instructions during high-stress moments","Make transitions and changes visible","Reduce unnecessary audiences during correction","Re-check understanding after the pupil has settled","Build independence again rather than making support permanent"]},
  {id:"tip5",type:"scenario",title:"Classroom scenario",prompt:"A normally settled pupil becomes defensive when corrected publicly and stops engaging with the task. What is the strongest first response?",options:[{label:"Continue the public correction until the pupil explains themselves",feedback:"A prolonged public interaction can increase stress and make re-engagement harder."},{label:"Use a calm, brief boundary, reduce the audience, give a clear route back into the task and follow up later if needed",feedback:"This protects the expectation while reducing unnecessary escalation."},{label:"Remove all expectations for the rest of the lesson",feedback:"Support should help the pupil return to learning where possible rather than automatically removing challenge."}]},
  {id:"tip6",type:"checklist",title:"Audit a classroom routine",prompt:"Check each feature you could reasonably build into a predictable classroom routine.",items:["The first two minutes of the lesson are consistent and explicitly taught","Important changes are signposted clearly where possible","Instructions are visible as well as spoken for complex tasks","Corrections are calm, brief and non-humiliating","Pupils know how to ask for help without drawing unnecessary attention","There is a clear route back into learning after a difficult moment"],completionText:"Routine audit complete — choose one change to implement rather than changing everything at once."},
  {id:"tip7",type:"activity",title:"Plan a regulation-supportive response",prompt:"Choose one recurring classroom moment that can become tense and redesign the response so it is calmer, clearer and more predictable.",instructions:["Describe the recurring trigger or transition without naming an individual pupil.","Write the exact calm instruction or cue staff will use.","Identify what pupils should do next so the route back to learning is explicit.","Decide what would require pastoral, SEND or safeguarding follow-up rather than classroom management alone."],placeholder:"Example: During practical transitions I will…",minimumCharacters:100},
  {id:"tip8",type:"scenario",title:"Professional boundary scenario",prompt:"A pupil hints that something outside school is making them feel unsafe. What should the member of staff do?",options:[{label:"Investigate the situation in detail before telling anyone",feedback:"Classroom staff should not conduct their own safeguarding investigation."},{label:"Listen appropriately, avoid promising secrecy, record/report through the school's safeguarding route and follow DSL guidance",feedback:"A child-centred safeguarding response takes priority over any trauma-informed classroom framework."},{label:"Use a regulation exercise and wait to see whether the concern disappears",feedback:"A possible safeguarding concern should not be managed only as a classroom-regulation issue."}]},
  reflection("tip9","Identify one routine, correction or transition you will make more predictable. What will stay the same academically, what support will change, and what evidence will show the change is helping?")
 ]
},
{
 id:"attachment-aware-practice",title:"Attachment-Aware Practice in Schools",category:"SEND",duration:80,level:"Developing",
 summary:"Use relationship-aware, consistent school practice to support pupils who find trust, separation, change or adult relationships difficult — without labelling or diagnosing them.",
 objectives:["Explain attachment as a relationship framework rather than a classroom diagnosis","Recognise school situations that can create relational stress","Use consistent adult responses and key-person approaches appropriately","Maintain boundaries, independence and high expectations"],
 recommendedFor:["Teacher","ECT","Teaching Assistant","Pastoral","SEND staff"],
 modules:[
  {id:"aap1",type:"content",title:"Attachment awareness without labels",body:"Attachment theory describes how early caregiving relationships can shape expectations about safety, comfort and trust. In schools, staff may find the framework useful when thinking about relationship-based barriers, but should avoid assigning attachment 'types' to pupils or assuming they know a pupil's history. Decisions should be based on known information, observed needs and school support plans.",keyPoints:["Do not diagnose attachment styles in school","Use the pupil's current plan and known history where appropriate","Consistency across adults matters","Relationship-aware practice is compatible with boundaries","Support should build independence rather than adult dependence"]},
  {id:"aap2",type:"visual",title:"Relationship-aware support",caption:"A stable school response can reduce uncertainty without making one adult the pupil's only source of safety.",layout:"cycle",items:[{heading:"Predictability",text:"Adults respond consistently and routines are clear.",icon:"▦"},{heading:"Connection",text:"The pupil experiences respectful, reliable interactions.",icon:"↔"},{heading:"Co-regulation",text:"Adults model calm and support recovery from difficult moments.",icon:"◌"},{heading:"Repair",text:"Relationships are restored after conflict without shame.",icon:"⟳"},{heading:"Independence",text:"Support gradually enables the pupil to manage more for themselves.",icon:"↗"}]},
  {id:"aap3",type:"quiz",title:"Knowledge check",question:"Which is the most appropriate attachment-aware statement for school staff?",options:["This pupil avoids eye contact, so they definitely have an avoidant attachment style","The pupil appears to find transitions between adults difficult; we should use known information and consistent routines to reduce uncertainty","Attachment difficulties mean normal school expectations should not apply","Only one key adult should ever support the pupil"],answer:1,feedback:"Describe observable patterns and plan support from evidence rather than assigning a diagnosis."},
  {id:"aap4",type:"content",title:"Common pressure points in school",body:"Some pupils may find arrival, separation from carers, staff absence, room changes, transitions, group work, feedback or perceived rejection particularly demanding. These situations do not prove an attachment difficulty, but they are useful points for staff to make routines clearer and adult responses more consistent.",keyPoints:["Prepare significant changes where possible","Avoid threats of relationship withdrawal","Separate the behaviour correction from the adult-pupil relationship","Use repair after conflict","Share strategies through agreed school systems rather than relying on individual memory"]},
  {id:"aap5",type:"scenario",title:"Key-adult scenario",prompt:"A pupil only agrees to work when one particular adult is present and becomes increasingly dependent on them. What is the strongest team response?",options:[{label:"Make that adult responsible for every lesson and transition",feedback:"This may strengthen dependence and is rarely sustainable."},{label:"Use the trusted relationship as a bridge while gradually widening the network of safe, consistent adults and routines",feedback:"The goal is security plus growing independence across the school environment."},{label:"Remove the trusted adult immediately with no preparation",feedback:"An abrupt withdrawal can create unnecessary distress and does not model a planned transition."}]},
  {id:"aap6",type:"checklist",title:"Consistency across adults",prompt:"Check the practices your team could standardise for a pupil who benefits from relational predictability.",items:["Adults use the same simple language for key routines","Changes in staffing are explained where possible","The pupil knows which adults can help if the usual person is unavailable","Behaviour corrections describe the action rather than rejecting the pupil","Strategies are recorded in the agreed school system","Support includes a plan for increasing independence"],completionText:"Consistency checklist complete — the next step is to agree which practice the whole team will use first."},
  {id:"aap7",type:"activity",title:"Design a transition plan",prompt:"Plan one transition that could be made more predictable for pupils who find changes in people, places or routines difficult.",instructions:["Name the transition, such as arrival, lesson change or staff absence.","Describe what will be predictable every time.","Add one visual/verbal cue that gives advance information.","Identify how adults will support the pupil without creating unnecessary dependence.","State how the support will be reviewed and faded if it is no longer needed."],placeholder:"Transition: …\nPredictable routine: …\nAdvance cue: …",minimumCharacters:120},
  reflection("aap8","Choose one relational routine you will make more consistent across adults. How will you keep the support warm and reliable while still building independence?")
 ]
},
{
 id:"ebsa-school-support",title:"Emotionally Based School Avoidance (EBSA): Early Support and Reintegration",category:"Wellbeing",duration:95,level:"Developing",
 summary:"Recognise emerging attendance barriers, work collaboratively with pupils and families, and plan supportive reintegration while following current attendance and safeguarding responsibilities.",
 objectives:["Understand EBSA as a description of attendance difficulty rather than a diagnosis","Identify interacting school, individual and family factors","Use early, collaborative support and graded reintegration","Keep attendance, SEND, pastoral and safeguarding responsibilities aligned"],
 recommendedFor:["Teacher","Tutor","Pastoral","Attendance Lead","SEND staff","Leadership"],
 modules:[
  {id:"ebsa1",type:"content",title:"What EBSA describes",body:"Emotionally Based School Avoidance describes difficulty attending school where emotional distress, anxiety or overwhelm are important factors. It is not a single diagnosis and there may be several interacting causes. Early response is important because patterns can become harder to change as absence increases. Schools should combine support with their attendance responsibilities and avoid assuming that sanctions alone will resolve an emotionally driven barrier.",keyPoints:["Use curiosity rather than blame","Look for patterns across days, lessons and transitions","Include the pupil and family in understanding barriers","Consider SEND and reasonable adjustments where relevant","Follow current statutory attendance guidance and local procedures"]},
  {id:"ebsa2",type:"visual",title:"A simple EBSA formulation",caption:"Look across interacting factors instead of searching for one cause.",layout:"compare",items:[{heading:"School factors",text:"Relationships, bullying, sensory load, transitions, academic pressure, specific lessons or unstructured times.",icon:"🏫"},{heading:"Individual factors",text:"Anxiety, health, neurodivergence, confidence, previous experiences, sleep or emotional regulation.",icon:"◎"},{heading:"Family/context",text:"Changes at home, transport, caring responsibilities, routines or wider stressors.",icon:"⌂"},{heading:"Protective factors",text:"Trusted adults, friendships, successful lessons, interests, predictable routines and family-school partnership.",icon:"＋"}]},
  {id:"ebsa3",type:"quiz",title:"Knowledge check",question:"Which response is most consistent with effective early support for EBSA?",options:["Wait until absence is severe before intervening","Treat every absence as deliberate defiance","Identify patterns early, listen to the pupil/family and coordinate support with attendance responsibilities","Promise that the pupil never has to attend difficult lessons again"],answer:2,feedback:"Early, collaborative assessment of barriers and protective factors supports a more realistic plan."},
  {id:"ebsa4",type:"content",title:"Ask: what makes attendance easier or harder?",body:"Useful assessment is practical. Look at when attendance is strongest, which parts of the day are hardest, what happens immediately before absence, what the pupil fears or avoids, what they value about school, and which adults or environments help them feel able to attend. Avoid lengthy questioning that makes the pupil repeatedly rehearse distress without moving towards a plan.",keyPoints:["Map patterns by time, place and demand","Identify successful attendance as well as absence","Agree one key contact","Keep communication regular and calm","Record adjustments and review their impact"]},
  {id:"ebsa5",type:"scenario",title:"Monday-morning pattern",prompt:"A pupil attends most afternoons but repeatedly struggles to enter school on Monday mornings. What is the best next step?",options:[{label:"Assume the family is not prioritising attendance",feedback:"This conclusion is not supported by the pattern alone."},{label:"Map the Monday-morning sequence with the pupil/family, identify specific barriers and protective factors, then agree a small reviewable support plan",feedback:"Pattern analysis can turn a broad attendance problem into specific barriers that can be addressed."},{label:"Remove Monday mornings permanently from the timetable",feedback:"Long-term avoidance without a reintegration plan may make returning harder."}]},
  {id:"ebsa6",type:"visual",title:"Reintegration: build, review, adjust",caption:"A reintegration plan should be specific enough to know whether it is working.",layout:"timeline",items:[{heading:"Agree the starting point",text:"Define what attendance is currently achievable and which barriers are being addressed.",icon:"1"},{heading:"Create a predictable arrival",text:"Name the adult, place and first activity.",icon:"2"},{heading:"Reduce priority barriers",text:"Use reasonable, time-limited adjustments linked to identified needs.",icon:"3"},{heading:"Reinforce successful attendance",text:"Notice what helped without making attendance dependent on rewards alone.",icon:"4"},{heading:"Review frequently",text:"Increase participation gradually and revise support using evidence.",icon:"5"}]},
  {id:"ebsa7",type:"checklist",title:"Reintegration-plan quality check",prompt:"A useful plan should answer each of these questions.",items:["Who is the named school contact?","What exactly should happen at arrival?","Which specific barrier is each adjustment addressing?","What will the pupil do if distress rises during the day?","How will missed learning be managed without overwhelming the pupil?","When will the plan be reviewed with the pupil and family?","What would trigger SEND, health, safeguarding or external-agency escalation?"],completionText:"Plan check complete — keep adjustments specific, reviewable and linked to an identified barrier."},
  {id:"ebsa8",type:"activity",title:"Build a graduated return plan",prompt:"Create a fictional or anonymised example of a two-week reintegration plan.",instructions:["State the main attendance barrier in observable terms.","Choose a named contact and predictable arrival routine.","Add one or two temporary adjustments — not a long list.","Define what successful participation looks like by the end of week one and week two.","Set a review point and identify what evidence will be used."],placeholder:"Barrier: …\nArrival routine: …\nWeek 1: …\nWeek 2: …\nReview evidence: …",minimumCharacters:150},
  reflection("ebsa9","Which part of your school's current attendance response could become earlier, more specific or more collaborative for pupils experiencing emotionally based barriers?")
 ]
},
{
 id:"supporting-bereaved-pupils",title:"Supporting Bereaved Pupils in School",category:"Wellbeing",duration:75,level:"Foundation",
 summary:"Respond to bereavement with calm, flexible and practical school support while recognising that grief varies greatly between pupils and over time.",
 objectives:["Recognise that grief responses vary and may change over time","Use age-appropriate, honest and sensitive communication","Plan practical classroom and pastoral support","Know when concerns need wider pastoral, safeguarding or specialist follow-up"],
 recommendedFor:["All staff","Teacher","Tutor","Pastoral","Teaching Assistant"],
 modules:[
  {id:"bp1",type:"content",title:"There is no single school grief response",body:"Bereavement can affect concentration, memory, sleep, attendance, relationships and emotional regulation, but pupils respond in very different ways. Some want normality and routine; others need brief flexibility or a trusted adult to check in. Avoid assuming that a quiet pupil is coping well or that an expressive pupil is coping badly. Support should follow the pupil's needs and family communication.",keyPoints:["Expect variation rather than a fixed set of stages","Maintain ordinary routines where they help","Offer choice without forcing disclosure","Agree what information can be shared and with whom","Review support because needs can change around anniversaries and transitions"]},
  {id:"bp2",type:"visual",title:"A supportive school response",caption:"Good bereavement support balances normality with flexibility.",layout:"cycle",items:[{heading:"Acknowledge",text:"Use clear, compassionate language and do not avoid the bereavement completely.",icon:"○"},{heading:"Listen",text:"Let the pupil choose whether and when to talk.",icon:"◌"},{heading:"Stabilise routine",text:"Keep school predictable while allowing proportionate flexibility.",icon:"▦"},{heading:"Coordinate",text:"Agree information-sharing and a key contact with the family/pastoral team.",icon:"↔"},{heading:"Review",text:"Check support again after time has passed, not only in the first week.",icon:"⟳"}]},
  {id:"bp3",type:"quiz",title:"Knowledge check",question:"Which approach is usually most appropriate after a bereavement?",options:["Avoid mentioning the bereavement under all circumstances","Require the pupil to discuss their feelings with every teacher","Offer predictable routine, a trusted contact and flexible support guided by the pupil/family","Automatically remove all homework and assessment for the rest of the year"],answer:2,feedback:"Support should be responsive and proportionate, with communication between the pupil, family and relevant school staff."},
  {id:"bp4",type:"content",title:"Language and communication",body:"Use simple, truthful language appropriate to the pupil's age and understanding. Avoid euphemisms that may confuse younger pupils. Do not ask for details the pupil does not want to share. If classmates need information, agree wording and consent with the family/pupil through the appropriate pastoral route.",keyPoints:["Acknowledge rather than avoid","Do not make the pupil repeatedly retell the story","Agree what classmates and staff need to know","Consider cultural and religious differences without making assumptions","Keep confidential information on a need-to-know basis"]},
  {id:"bp5",type:"scenario",title:"Returning to class",prompt:"A pupil returns after a close bereavement and asks not to be singled out in front of classmates. What is the best response?",options:[{label:"Arrange a public class tribute without asking them",feedback:"Even well-intended public attention may conflict with the pupil's wishes."},{label:"Respect the request, agree a discreet check-in and let relevant staff know the agreed support",feedback:"This preserves dignity while ensuring practical support is coordinated."},{label:"Avoid any school contact about the bereavement for the rest of the year",feedback:"Respecting privacy does not mean support should disappear completely."}]},
  {id:"bp6",type:"checklist",title:"Classroom support menu",prompt:"Check the options that could be discussed with the pupil/pastoral team rather than automatically imposed.",items:["A discreet way to leave the room briefly if emotions become overwhelming","A named adult or place for check-in","Advance warning before lesson content involving death or bereavement where relevant","Temporary flexibility with deadlines where concentration is affected","A plan for catching up missed learning in manageable chunks","A review point after the immediate return to school","Clear communication about anniversaries, memorials or family wishes where appropriate"],completionText:"Support menu reviewed — agree only the options that fit the pupil rather than applying every adjustment."},
  {id:"bp7",type:"activity",title:"Plan a sensitive return-to-school conversation",prompt:"Draft the structure of a short conversation with a bereaved pupil returning to lessons.",instructions:["Open by acknowledging the loss without forcing discussion.","Ask what the pupil would like staff/classmates to know.","Offer two or three practical support options rather than an overwhelming list.","Agree how the pupil can ask for help discreetly.","Set a time to review how the plan is working."],placeholder:"Opening: …\nInformation sharing: …\nSupport options: …\nReview: …",minimumCharacters:120},
  {id:"bp8",type:"scenario",title:"When support needs escalation",prompt:"Several weeks after a bereavement, a pupil's functioning has deteriorated significantly and they disclose that they do not feel safe. What should staff prioritise?",options:[{label:"Treat it only as a normal stage of grief and wait",feedback:"A safety concern should not be dismissed as an expected grief response."},{label:"Follow the school's safeguarding/pastoral procedure promptly and seek appropriate support",feedback:"Bereavement context matters, but safeguarding and immediate wellbeing procedures still apply."},{label:"Ask classmates to monitor the pupil instead",feedback:"Responsibility should remain with appropriate adults and school systems."}]},
  reflection("bp9","What could your department do to provide compassionate flexibility after bereavement without making expectations unclear or requiring a pupil to repeatedly explain their situation?")
 ]
},
{
 id:"self-harm-suicide-awareness-staff",title:"Self-Harm and Suicide Awareness for School Staff",category:"Safeguarding",duration:85,level:"Foundation",
 summary:"Recognise concerning changes, respond calmly to disclosures or immediate safety concerns, and use safeguarding and mental-health pathways without asking staff to diagnose or manage risk alone.",
 objectives:["Understand the professional role of school staff when a pupil may be at risk","Respond calmly and non-judgementally to a disclosure","Use school safeguarding, pastoral and emergency procedures appropriately","Avoid unsafe promises, secrecy, amateur investigation or unsupported diagnosis"],
 recommendedFor:["All staff","Teacher","Tutor","Pastoral","Leadership"],
 modules:[
  {id:"sha1",type:"content",title:"Your role is to notice, listen and escalate",body:"School staff are not expected to diagnose mental-health conditions or manage serious safety concerns alone. Your role is to notice meaningful changes or disclosures, respond calmly, take the pupil seriously, and use the school's safeguarding and pastoral procedures. Current school policy and DSL guidance take precedence over generic training content.",keyPoints:["Take concerns seriously without panic","Listen without judgement","Do not promise secrecy","Do not investigate beyond what is needed to understand the immediate concern","Record and pass information through the agreed safeguarding route","If there is an immediate danger, follow the school's emergency procedure"]},
  {id:"sha2",type:"visual",title:"Safe staff response",caption:"Keep the response simple and procedural rather than trying to become the pupil's clinician.",layout:"flow",items:[{heading:"Notice",text:"Pay attention to concerning changes, direct statements or information from others.",icon:"1"},{heading:"Listen",text:"Stay calm, take the pupil seriously and avoid judgement.",icon:"2"},{heading:"Clarify immediate safety",text:"Establish only what you need to know to follow the correct school response.",icon:"3"},{heading:"Report",text:"Use the school's safeguarding/pastoral route promptly.",icon:"4"},{heading:"Support and follow up",text:"Maintain ordinary respectful contact while designated staff coordinate next steps.",icon:"5"}]},
  {id:"sha3",type:"quiz",title:"Knowledge check",question:"A pupil tells you they are worried they may hurt themselves. What should you do first?",options:["Promise to keep the conversation completely secret","Stay calm, take the concern seriously and follow the school's safeguarding/emergency procedure","Ask the pupil to manage the concern alone until the end of the week","Tell the whole class so they can help"],answer:1,feedback:"A calm, prompt safeguarding response is appropriate. Do not promise secrecy or leave the pupil to manage a serious concern alone."},
  {id:"sha4",type:"content",title:"Concerning changes are signals, not diagnoses",body:"Staff may notice withdrawal, marked changes in mood or engagement, deterioration in attendance or work, repeated expressions of hopelessness, or direct statements that raise concern. No single sign proves what is happening. The correct response is professional curiosity and appropriate escalation, not diagnosis or assumptions about cause.",keyPoints:["Look for change from the pupil's usual presentation","Treat direct statements seriously","Record facts rather than interpretations","Use patterns and context, not stereotypes","Share concerns through authorised channels"]},
  {id:"sha5",type:"scenario",title:"Disclosure during a lesson",prompt:"A pupil quietly tells you they are struggling and are worried about their own safety. What is the safest response?",options:[{label:"Say you cannot help because you are not a counsellor and send them away",feedback:"You do not need to be a counsellor to respond appropriately and activate school support."},{label:"Listen calmly, explain that you need to involve the appropriate safeguarding/pastoral staff, and follow the school's procedure promptly",feedback:"This keeps the pupil supported while moving responsibility to the correct safeguarding system."},{label:"Promise confidentiality so they keep talking",feedback:"Staff should not promise secrecy when information may need to be shared to keep a pupil safe."}]},
  {id:"sha6",type:"checklist",title:"Staff response checklist",prompt:"Work through the actions that belong in a safe school response.",items:["Stay calm and take the concern seriously","Use clear, non-judgemental language","Do not promise secrecy","Avoid pressing for unnecessary detail","Follow the school's safeguarding/pastoral reporting route promptly","Record factual information in the agreed system","If the concern is immediate or urgent, follow the school's emergency arrangements","Continue ordinary respectful support after the referral rather than avoiding the pupil"],completionText:"Response checklist complete — safeguarding responsibility is shared through the school's agreed system, not carried by one member of staff alone."},
  {id:"sha7",type:"scenario",title:"Colleague handover",prompt:"You report a serious concern to the appropriate safeguarding lead. What should you do next?",options:[{label:"Assume your responsibility ends and never speak to the pupil again",feedback:"You should continue normal supportive professional contact while designated staff manage the safeguarding response."},{label:"Follow any instructions from safeguarding staff, record appropriately and continue ordinary professional support",feedback:"A good handover transfers coordination without withdrawing everyday pastoral care."},{label:"Run your own separate investigation to double-check the DSL",feedback:"Parallel investigations can create risk and are not the classroom member of staff's role."}]},
  {id:"sha8",type:"activity",title:"Practise the wording",prompt:"Draft a short, calm response you could use if a pupil tells you they are worried about their own safety.",instructions:["Acknowledge what the pupil has said and thank them for telling you.","Avoid judgement or promises of confidentiality.","Explain that you need to involve the appropriate staff to help keep them safe.","State the immediate next step in simple language."],placeholder:"Example opening: Thank you for telling me…",minimumCharacters:100},
  reflection("sha9","Which part of your school's safeguarding procedure do you need to be most confident about if a pupil raises an urgent mental-health or safety concern? Record the procedural step, not confidential pupil information.")
 ]
}
];
