import type { Course, Module } from "./data";

const reflect=(id:string,prompt:string):Module=>({id,type:"reflection",title:"Apply it to your practice",prompt});

export const schoolCoursesBatch5: Course[] = [
  {
    id:"safeguarding-essentials",
    title:"Safeguarding Essentials: KCSIE 2026",
    category:"Safeguarding",
    duration:90,
    level:"Foundation",
    summary:"A deeper all-staff safeguarding course aligned to KCSIE 2026, covering professional curiosity, disclosures, recording, reporting, online safety, child-on-child concerns, concerns about adults and whistleblowing while keeping the school DSL and local policy central.",
    objectives:["Understand core KCSIE 2026 all-staff expectations","Respond appropriately to concerns and disclosures","Record and report concerns factually and promptly","Recognise online and child-on-child safeguarding responsibilities","Know what to do if a concern relates to an adult working with children"],
    recommendedFor:["All staff"],
    modules:[
      {id:"s1",type:"content",title:"Safeguarding is everyone's responsibility",body:"KCSIE 2026 requires all staff to read Part One in full and to follow their school's safeguarding and child-protection procedures. Training supports that duty but does not replace statutory guidance, the school's policy or DSL advice.",keyPoints:["Read KCSIE 2026 Part One in full","Know the DSL and deputy arrangements","Know the school's reporting route","Act in the best interests of the child","Use early-help and safeguarding routes when concerns emerge","Never assume someone else has reported a concern"]},
      {id:"s2",type:"visual",title:"All-staff safeguarding response",layout:"flow",items:[{heading:"Notice",text:"Recognise a concern, disclosure, pattern or change that may matter.",icon:"1"},{heading:"Respond",text:"Stay calm, listen appropriately and avoid leading questions.",icon:"2"},{heading:"Record",text:"Use factual, timely information and the school's agreed system.",icon:"3"},{heading:"Report",text:"Pass the concern through the DSL/safeguarding route promptly.",icon:"4"},{heading:"Continue",text:"Follow DSL guidance and maintain appropriate professional support.",icon:"5"}]},
      {id:"s3",type:"scenario",title:"Responding to a disclosure",prompt:"A pupil begins to tell you something that may indicate a safeguarding concern. What should you prioritise?",options:[{label:"Promise to keep it secret",feedback:"Staff should not promise confidentiality they cannot keep."},{label:"Listen calmly, avoid leading questions, explain that information may need to be shared, and use the school's safeguarding route",feedback:"This supports the pupil while keeping the response within professional safeguarding procedure."},{label:"Investigate by questioning other pupils",feedback:"Investigation is not the classroom member of staff's role."}]},
      {id:"s4",type:"content",title:"Recording and information sharing",body:"Safeguarding records should be timely, factual and handled through approved systems. Staff should distinguish what they observed, what was said and what action they took. Information should be shared with the people who need it for safeguarding purposes in line with school procedure and current guidance.",keyPoints:["Record promptly","Separate fact from opinion","Use the child's own words where relevant","Do not store safeguarding notes in personal systems","Share through the authorised safeguarding route","If unsure, seek DSL advice rather than withholding a concern"]},
      {id:"s5",type:"content",title:"Online safety and child-on-child concerns",body:"KCSIE treats online safety as part of safeguarding. Staff should understand how safeguarding, behaviour and online-safety systems fit together and should take child-on-child concerns seriously rather than dismissing harmful behaviour as normal.",keyPoints:["Online and offline concerns can overlap","Follow the school's reporting process","Do not normalise harmful behaviour","Be alert to barriers that may make disclosure difficult","Preserve relevant information through approved systems rather than investigating independently"]},
      {id:"s6",type:"scenario",title:"Concern about an adult",prompt:"You become concerned about the behaviour of an adult working with children. What is the strongest response?",options:[{label:"Confront the adult and investigate yourself",feedback:"Staff should use the school's allegations or low-level-concerns procedure rather than conduct their own investigation."},{label:"Use the school's procedure for concerns or allegations about adults, including the correct senior contact or alternative route where needed",feedback:"This keeps the concern within the proper safeguarding process."},{label:"Ignore it unless a pupil makes a formal complaint",feedback:"Staff should act on concerns rather than wait for certainty."}]},
      {id:"s7",type:"content",title:"Whistleblowing and escalation",body:"Staff should know how to raise concerns about safeguarding practice, unsafe systems or the conduct of adults. Where normal routes are not appropriate or a concern is not being addressed, staff should know the school's whistleblowing and escalation arrangements.",keyPoints:["Know the school's whistleblowing route","Do not suppress a concern because it feels uncomfortable","Use the alternative senior contact where a concern relates to the usual reporting person","Keep safeguarding information within authorised channels"]},
      {id:"s8",type:"quiz",title:"Knowledge check",question:"What takes precedence if a generic CPD example differs from your school's safeguarding policy or current DSL direction?",options:["The generic example","The school's current policy, DSL direction and statutory requirements","Whichever is quicker","A colleague's personal preference"],answer:1,feedback:"Current policy, DSL direction and statutory guidance take precedence."},
      {id:"s9",type:"checklist",title:"Safeguarding readiness check",prompt:"Confirm the practical information every member of staff should know.",items:["I know who the DSL and deputies are","I know how to report a concern immediately","I know where the current safeguarding policy is","I have read KCSIE 2026 Part One in full","I know what to do if the concern relates to an adult","I know the whistleblowing/escalation route","I understand that online safety is part of safeguarding"],completionText:"Safeguarding readiness check complete."},
      reflect("s10","Without recording confidential pupil information here, identify one safeguarding procedure you need to be able to locate or use more quickly.")
    ]
  },
  {
    id:"health-safety-essentials-schools",
    title:"Health & Safety Essentials for School Staff",
    category:"Safeguarding",
    duration:65,
    level:"Foundation",
    summary:"Whole-school health-and-safety awareness covering responsibilities, proportionate risk management, local procedures, incident reporting and the point at which role-specific or specialist training is required.",
    objectives:["Understand school and employee health-and-safety responsibilities","Use proportionate risk controls","Know local reporting and emergency procedures","Recognise when specialist or role-specific training is required"],
    recommendedFor:["All staff"],
    modules:[
      {id:"hs1",type:"content",title:"Health and safety is a shared system",body:"The employer or proprietor is accountable for health and safety, with day-to-day arrangements commonly delegated to school leadership. Staff need information and training relevant to their work and should follow the school's health-and-safety policy, instructions and risk controls.",keyPoints:["Know the school's health-and-safety policy","Follow training and instructions","Take reasonable care of yourself and others","Report serious or immediate dangers","Use role-specific risk assessments where relevant","Ask for review when controls no longer fit the activity"]},
      {id:"hs2",type:"visual",title:"Proportionate risk management",layout:"flow",items:[{heading:"Identify",text:"What could cause harm?",icon:"1"},{heading:"Who",text:"Who may be affected and how?",icon:"2"},{heading:"Control",text:"What sensible measures reduce the risk?",icon:"3"},{heading:"Communicate",text:"Who needs information, training or supervision?",icon:"4"},{heading:"Review",text:"Has anything changed or stopped controls being effective?",icon:"5"}]},
      {id:"hs3",type:"scenario",title:"Changing conditions",prompt:"An activity is about to begin, but the environment or equipment has changed in a way that affects existing controls. What should staff do?",options:[{label:"Continue because it was previously risk assessed",feedback:"A material change can make an earlier assessment no longer suitable."},{label:"Pause, use the school's risk-management process and obtain appropriate advice or controls before continuing",feedback:"Risk controls should remain suitable for the actual conditions."},{label:"Ask pupils to decide whether it feels safe",feedback:"Staff retain responsibility for applying school safety arrangements."}]},
      {id:"hs4",type:"checklist",title:"All-staff safety readiness",prompt:"Check that you know the local arrangements.",items:["How to report an accident or near miss","How to report a serious or immediate hazard","Emergency evacuation arrangements","First-aid contact route","Where role-specific risk assessments are kept","Who the competent health-and-safety lead/contact is","What additional training my role requires"],completionText:"Health-and-safety readiness check complete."},
      reflect("hs5","Which health-and-safety procedure in your setting would be hardest to find quickly, and how will you make it easier to access?")
    ]
  },
  {
    id:"fire-safety-emergency-evacuation",
    title:"Fire Safety & Emergency Evacuation Awareness",
    category:"Safeguarding",
    duration:45,
    level:"Foundation",
    summary:"Understand local fire and evacuation arrangements, staff responsibilities, accountability and the importance of site-specific induction and drills.",
    objectives:["Know local fire and evacuation arrangements","Understand staff responsibilities during evacuation","Support pupils and visitors through agreed procedures","Recognise when local arrangements need review"],
    recommendedFor:["All staff"],
    modules:[
      {id:"fire1",type:"content",title:"Local procedures come first",body:"Fire-safety awareness should be rooted in the school's current fire risk assessment, alarm arrangements, evacuation routes, assembly arrangements and designated responsibilities. Generic CPD cannot replace site-specific induction and drills.",keyPoints:["Know the alarm and evacuation procedure","Know your assembly point and accountability process","Know how visitors are accounted for","Know arrangements for people who may need assistance","Keep routes and exits unobstructed","Report defects or changes through the school procedure"]},
      {id:"fire2",type:"visual",title:"Evacuation awareness",layout:"flow",items:[{heading:"Alarm",text:"Recognise and respond to the site's agreed signal.",icon:"1"},{heading:"Evacuate",text:"Use the agreed route and staff procedure.",icon:"2"},{heading:"Account",text:"Follow the school's register/visitor accountability process.",icon:"3"},{heading:"Report",text:"Pass missing-person or safety information through the designated route.",icon:"4"},{heading:"Review",text:"Record issues from drills or incidents for follow-up.",icon:"5"}]},
      {id:"fire3",type:"scenario",title:"Blocked route",prompt:"During normal operation you notice that an agreed evacuation route is obstructed. What is the strongest response?",options:[{label:"Ignore it until the next drill",feedback:"Known defects should be reported promptly."},{label:"Use the school's reporting route so the obstruction or control issue is addressed and follow any revised local instructions",feedback:"Local emergency arrangements need to remain usable."},{label:"Create an unofficial route and tell no one",feedback:"Emergency arrangements should be coordinated through the school's plan."}]},
      reflect("fire4","Can you identify your site's evacuation route, assembly arrangement and accountability procedure without searching for them during an emergency?")
    ]
  },
  {
    id:"accident-near-miss-riddor-awareness",
    title:"Accident, Incident & Near-Miss Reporting",
    category:"Safeguarding",
    duration:45,
    level:"Foundation",
    summary:"Improve staff understanding of school accident and near-miss reporting, factual records, incident learning and awareness that formal external reporting decisions belong to authorised responsible persons.",
    objectives:["Record accidents and near misses accurately","Use the school's reporting route promptly","Understand the purpose of incident review","Know that formal external reporting decisions sit with authorised responsible persons"],
    recommendedFor:["All staff","Leadership","Site staff"],
    modules:[
      {id:"ar1",type:"content",title:"Reporting helps prevent repeat incidents",body:"Schools should have clear arrangements for recording and reviewing accidents, incidents and near misses. Some work-related events can fall within statutory reporting requirements, but staff should use the school's process rather than trying to make external-reporting decisions themselves unless that responsibility is part of their role.",keyPoints:["Record facts promptly","Include what happened and where","Record known controls and immediate action","Report near misses where school policy requires","Do not alter records to make an event appear less serious","Escalate to the responsible health-and-safety lead"]},
      {id:"ar2",type:"visual",title:"Incident learning cycle",layout:"cycle",items:[{heading:"Make safe",text:"Address immediate risk using local procedures.",icon:"1"},{heading:"Record",text:"Capture accurate factual information.",icon:"2"},{heading:"Escalate",text:"Send through the school's reporting route.",icon:"3"},{heading:"Review",text:"Identify causes and control failures.",icon:"4"},{heading:"Improve",text:"Update controls, training or procedures where needed.",icon:"5"}]},
      {id:"ar3",type:"quiz",title:"Knowledge check",question:"Who should decide whether an incident requires formal external statutory reporting?",options:["Any pupil who witnessed it","The authorised employer/proprietor or responsible person following the school's arrangements","Whoever completes the first form","No one; schools never report externally"],answer:1,feedback:"Formal reporting decisions should sit with the responsible employer/proprietor or delegated competent person."},
      reflect("ar4","Does your team know the difference between an accident, an incident and a near miss in the school's own reporting system?")
    ]
  },
  {
    id:"medical-conditions-schools",
    title:"Supporting Pupils with Medical Conditions",
    category:"Safeguarding",
    duration:60,
    level:"Foundation",
    summary:"Support pupils with medical conditions through policy, Individual Healthcare Plans, trained responsibilities, communication and safe participation without turning general CPD into clinical instruction.",
    objectives:["Understand the role of the school medical-conditions policy","Use Individual Healthcare Plans appropriately","Know the boundaries of staff training and responsibility","Support safe inclusion in school activities"],
    recommendedFor:["All staff","Pastoral","Leadership","Educational Visits staff"],
    modules:[
      {id:"med1",type:"content",title:"Policy and individual plans",body:"Current statutory guidance on supporting pupils with medical conditions remains in force. Staff should know the school's policy, understand when an Individual Healthcare Plan is relevant and follow the agreed plan and any training for their role. This CPD does not teach clinical treatment.",keyPoints:["Know where the medical-conditions policy is","Follow the pupil's agreed healthcare plan where relevant","Only undertake tasks you are trained and authorised to perform","Plan for participation in trips and activities","Share relevant information through approved channels","Record administration or incidents using school procedures"]},
      {id:"med2",type:"visual",title:"Safe support pathway",layout:"flow",items:[{heading:"Know",text:"Understand the policy and relevant pupil plan.",icon:"1"},{heading:"Prepare",text:"Check trained roles, communication and activity arrangements.",icon:"2"},{heading:"Support",text:"Follow the agreed plan and professional boundaries.",icon:"3"},{heading:"Record",text:"Use approved medication or incident records where required.",icon:"4"},{heading:"Review",text:"Escalate changes or concerns to the responsible lead.",icon:"5"}]},
      {id:"med3",type:"scenario",title:"Unfamiliar request",prompt:"You are asked to carry out a medical task for which you have not received the training required by the school's plan. What is the strongest response?",options:[{label:"Try it because another adult is busy",feedback:"Staff should not exceed their training or authorisation."},{label:"Use the school's escalation route to obtain an appropriately trained or authorised response",feedback:"Role boundaries are an important part of safe medical support."},{label:"Ask another pupil to do it",feedback:"Medical support should follow the school's authorised arrangements."}]},
      reflect("med4","Which medical-condition information does your role genuinely need to know, and where is that information stored securely?")
    ]
  },
  {
    id:"allergy-safety-schools-2026",
    title:"Allergy Safety in Schools: 2026 Requirements",
    category:"Safeguarding",
    duration:70,
    level:"Foundation",
    summary:"Whole-school awareness of England's 2026 allergy-safety duties, policy, all-staff training, Individual Healthcare Plans, risk reduction and incident or near-miss learning.",
    objectives:["Understand the 2026 allergy-safety policy duty","Know the school's allergy-safety arrangements","Understand staff training and Individual Healthcare Plans","Use incident and near-miss learning to strengthen controls"],
    recommendedFor:["All staff","Leadership","Pastoral","Catering liaison","Educational Visits staff"],
    modules:[
      {id:"alg1",type:"content",title:"A statutory school duty",body:"From 1 September 2026, the relevant allergy-safety duty is in force in England for covered schools. Schools should have, publish and review an allergy-safety policy and put appropriate allergy-safety training in place for all staff. Staff must still follow their school's own policy and role-specific training.",keyPoints:["Know the school's published allergy-safety policy","Know how pupils with allergies are identified and supported","Understand relevant Individual Healthcare Plans","Follow local arrangements for reducing exposure risk","Know the trained emergency-response route","Report serious incidents and near misses through school systems"]},
      {id:"alg2",type:"visual",title:"Whole-school allergy safety",layout:"flow",items:[{heading:"Policy",text:"Published and reviewed allergy-safety arrangements.",icon:"1"},{heading:"Identify",text:"Know which pupils need individual planning and relevant staff awareness.",icon:"2"},{heading:"Prevent",text:"Use agreed controls across classrooms, catering, trips and activities.",icon:"3"},{heading:"Respond",text:"Follow trained emergency arrangements and the pupil's plan.",icon:"4"},{heading:"Learn",text:"Record and review incidents and near misses.",icon:"5"}]},
      {id:"alg3",type:"scenario",title:"Activity planning",prompt:"A planned activity changes and may affect an existing allergy control for a pupil. What is the strongest response?",options:[{label:"Assume the usual controls still apply",feedback:"Changes should be checked against the pupil's plan and school allergy-safety arrangements."},{label:"Pause and confirm the activity is consistent with the school's allergy-safety policy and relevant individual plan before proceeding",feedback:"This keeps planning aligned with the school's agreed controls."},{label:"Ask the pupil to manage the whole risk alone",feedback:"The school retains responsibilities under its policy and support arrangements."}]},
      {id:"alg4",type:"checklist",title:"Allergy-safety readiness",prompt:"Check your local knowledge.",items:["I know where the allergy-safety policy is","I know how relevant pupil information is communicated securely","I know the local route for trained emergency help","I know how allergy safety is planned for trips and special activities","I know how to report an allergy-related incident or near miss","I know which tasks require additional role-specific training"],completionText:"Allergy-safety readiness check complete."},
      reflect("alg5","Which routine in your area of the school needs the clearest allergy-safety communication or handover?")
    ]
  },
  {
    id:"school-security-emergency-awareness",
    title:"School Security & Emergency Response Awareness",
    category:"Safeguarding",
    duration:55,
    level:"Foundation",
    summary:"Understand the school's security policy, access control, incident reporting and emergency communications without publishing sensitive site-specific operational detail in generic CPD.",
    objectives:["Know the school's security policy and reporting route","Recognise links between security, safeguarding and health and safety","Understand staff responsibilities during security incidents","Protect sensitive emergency information"],
    recommendedFor:["All staff","Leadership","Reception","Site staff"],
    modules:[
      {id:"sec1",type:"content",title:"Security is part of a wider safety system",body:"DfE guidance expects schools and colleges to have a policy and plan for managing security-related incidents. Generic CPD should help staff understand responsibilities, while sensitive site-specific response details belong in controlled school security and emergency procedures.",keyPoints:["Know how to report a security concern","Follow visitor and access-control procedures","Protect keys, passes and access credentials","Use the school's emergency communication arrangements","Do not share sensitive site-security details unnecessarily","Report defects or suspicious changes promptly"]},
      {id:"sec2",type:"visual",title:"Security awareness cycle",layout:"flow",items:[{heading:"Prevent",text:"Follow access, visitor and site-security routines.",icon:"1"},{heading:"Notice",text:"Identify unusual or concerning situations.",icon:"2"},{heading:"Report",text:"Use the school's designated route promptly.",icon:"3"},{heading:"Respond",text:"Follow authorised emergency instructions.",icon:"4"},{heading:"Review",text:"Feed lessons into policy and risk assessment.",icon:"5"}]},
      {id:"sec3",type:"scenario",title:"Unfamiliar visitor",prompt:"You notice someone in a staff-only area who is not following the school's visitor arrangements. What is the strongest response?",options:[{label:"Ignore it because someone else probably knows them",feedback:"Staff should follow the school's security and visitor procedure."},{label:"Use the school's approved challenge or reporting process and seek appropriate support",feedback:"The response should follow local security arrangements rather than improvisation."},{label:"Post their photograph publicly",feedback:"This would create privacy and safeguarding concerns."}]},
      reflect("sec4","Do you know the school's security reporting route and where controlled emergency procedures are accessed by staff who need them?")
    ]
  },
  {
    id:"coshh-hazardous-substances-awareness",
    title:"COSHH & Hazardous Substances Awareness",
    category:"Safeguarding",
    duration:50,
    level:"Developing",
    summary:"Role-focused awareness for staff who work around hazardous substances, emphasising approved assessments, labelling, storage, training and escalation rather than teaching hazardous procedures.",
    objectives:["Recognise when COSHH controls may apply","Use approved assessments and local procedures","Understand role-specific training boundaries","Report damaged labels, storage issues or changed conditions"],
    recommendedFor:["Science staff","DT staff","Site staff","Cleaning supervisors","Leadership"],
    modules:[
      {id:"cos1",type:"content",title:"Use approved controls, not improvisation",body:"Staff who may encounter hazardous substances should work from the school's current COSHH assessments, labels, storage rules and role-specific training. Generic CPD should not be used to invent handling methods or substitute materials outside approved procedures.",keyPoints:["Use the current approved assessment","Check labels and local storage arrangements","Use required controls and PPE specified by the school","Do not substitute materials without authorised assessment","Report leaks, damage or missing labels through the school's procedure","Seek specialist advice where the assessment requires it"]},
      {id:"cos2",type:"visual",title:"COSHH awareness pathway",layout:"flow",items:[{heading:"Identify",text:"Recognise the task, substance and approved assessment.",icon:"1"},{heading:"Check",text:"Confirm labels, condition, controls and storage.",icon:"2"},{heading:"Use",text:"Follow the approved procedure and training.",icon:"3"},{heading:"Stop",text:"Pause if conditions, materials or controls have changed.",icon:"4"},{heading:"Report",text:"Escalate defects, incidents or uncertainty.",icon:"5"}]},
      {id:"cos3",type:"scenario",title:"Missing label",prompt:"A product in your work area no longer has the information needed to identify it safely. What should you do?",options:[{label:"Guess what it is from the container",feedback:"Unidentified substances should not be used on guesswork."},{label:"Do not use it; isolate or manage it according to the school's procedure and report it to the responsible person",feedback:"The safe response is to follow the approved local process."},{label:"Ask a pupil to test it",feedback:"Safety decisions and hazardous-substance controls are staff responsibilities."}]},
      reflect("cos4","Which approved COSHH or hazardous-substance assessment is most relevant to your role, and do you know where the current version is kept?")
    ]
  },
  {
    id:"asbestos-awareness-schools",
    title:"Asbestos Awareness for Relevant School Staff",
    category:"Safeguarding",
    duration:45,
    level:"Developing",
    summary:"Awareness for staff whose work could affect the school estate, focusing on the asbestos management plan, stop-and-check behaviour and role boundaries. This does not replace legally required task-specific training.",
    objectives:["Understand why asbestos management information matters","Know when to stop before disturbing building fabric","Use the school's estate and permit procedures","Recognise the boundary between awareness and specialist work"],
    recommendedFor:["Site staff","Estates","DT technicians","Leadership","Staff arranging contractors"],
    modules:[
      {id:"asb1",type:"content",title:"Do not disturb building materials without the right information",body:"Where asbestos-containing materials may be present, relevant staff and contractors need access to the school's current asbestos management information before work that could disturb the building fabric. Awareness training does not authorise asbestos work.",keyPoints:["Know who manages asbestos information","Check before maintenance or intrusive work","Use the school's contractor and permit arrangements","Stop if unexpected material or damage is encountered","Do not drill, cut or disturb suspect materials","Specialist work requires appropriate competent people and training"]},
      {id:"asb2",type:"visual",title:"Stop-and-check pathway",layout:"flow",items:[{heading:"Plan",text:"Define the work and whether building fabric may be affected.",icon:"1"},{heading:"Check",text:"Consult the school's current asbestos information and responsible person.",icon:"2"},{heading:"Authorise",text:"Confirm competent people, controls and permissions.",icon:"3"},{heading:"Stop",text:"Pause if conditions or materials differ from the plan.",icon:"4"},{heading:"Report",text:"Use the school's incident or estates route.",icon:"5"}]},
      {id:"asb3",type:"scenario",title:"Unexpected material",prompt:"Maintenance work exposes an unexpected material not covered by the information available to you. What is the strongest response?",options:[{label:"Continue carefully so the job is finished",feedback:"Unexpected materials should trigger a stop and check."},{label:"Stop work, prevent further disturbance and use the school's asbestos/estates escalation process",feedback:"This keeps the response within the school's management system."},{label:"Remove a sample yourself",feedback:"Sampling and specialist asbestos work require competent authorised arrangements."}]},
      reflect("asb4","If your role involves the school estate, do you know who holds the asbestos management information and what work must be checked before it starts?")
    ]
  },
  {
    id:"regulation-support-academy",
    title:"Regulation Support Academy: Whole-School Practice",
    category:"Wellbeing",
    duration:120,
    level:"Developing",
    summary:"An eight-part staff pathway adapted from the school's Regulation Hub: understand regulation, notice signals, co-regulate, use supportive language, design routines, apply strategies across subjects, plan individual support and implement consistently across the school.",
    objectives:["Understand a four-zone regulation framework without treating zones as behaviour grades","Use co-regulation and supportive language","Adapt environments, routines and transitions","Apply regulation support across subjects and individual needs","Plan and review structured interventions","Build consistent whole-school implementation"],
    recommendedFor:["All staff","SEND","Pastoral","Teachers","Teaching Assistants","Leadership"],
    modules:[
      {id:"zr1",type:"content",title:"Module 1 · Foundations: understanding regulation",body:"A four-zone framework can give staff and pupils a shared language for noticing levels of alertness, emotion and readiness. All zones are valid states. The purpose is not to reward one colour or punish another; it is to recognise needs, select support and reconnect with safety, wellbeing or learning.",keyPoints:["All zones are valid states","A zone is not a behaviour score","The same state can look different between pupils","Regulation support should preserve curriculum access where possible","Safeguarding, medical and emergency procedures remain separate"]},
      {id:"zr2",type:"visual",title:"Regulation support cycle",layout:"cycle",items:[{heading:"Notice",text:"What feelings, body signals or context are present?",icon:"1"},{heading:"Name",text:"Use neutral shared language without judgement.",icon:"2"},{heading:"Need",text:"What does the pupil need to access safety or learning?",icon:"3"},{heading:"Strategy",text:"Choose a proportionate regulation support.",icon:"4"},{heading:"Review",text:"Did it help? What should be remembered next time?",icon:"5"}]},
      {id:"zr3",type:"scenario",title:"Module 2 · Notice signals and co-regulate",prompt:"A pupil is visibly dysregulated before a demanding task. Which response best reflects co-regulation?",options:[{label:"Tell them they must get into the Green Zone before learning",feedback:"This turns the framework into compliance and implies one state is morally better."},{label:"Use a calm, non-judgemental check-in, reduce avoidable pressure and help the pupil choose an appropriate strategy while maintaining the learning goal where possible",feedback:"Co-regulation combines relational support with continued access to learning."},{label:"Remove all challenge for the rest of the lesson",feedback:"Support should be proportionate and should not automatically remove important learning."}]},
      {id:"zr4",type:"content",title:"Module 3 · Teacher language that supports regulation",body:"Regulation-supportive language is descriptive, calm and choice-oriented. It avoids labelling pupils as a colour, demanding a particular emotional state or using regulation tools as rewards and sanctions.",keyPoints:["Describe what you notice without diagnosing","Offer limited, realistic strategy choices","Keep dignity and privacy","Avoid 'you are in the red zone' as a label","Use language that reconnects the pupil with the next safe or learning step"]},
      {id:"zr5",type:"quiz",title:"Language coach",question:"Which phrase best supports regulation without turning the framework into behaviour management?",options:["You're in Red again; fix it","Green is the good zone","I can see this feels intense. Would a brief movement break or a quieter start help you get ready for the next step?","You lose break because you're not regulated"],answer:2,feedback:"Neutral observation plus a proportionate choice supports regulation without moralising the zone."},
      {id:"zr6",type:"checklist",title:"Module 4 · Environment, routines and transitions",prompt:"Audit one learning space or transition.",items:["Expectations and next steps are visible","Transition cues are predictable","Pupils know where approved regulation tools are","Sensory load has been considered","Adults use consistent language","Support does not publicly identify or shame pupils","There is a clear route back into learning"],completionText:"Environment and transition audit complete."},
      {id:"zr7",type:"activity",title:"Module 5 · Regulation across subjects",prompt:"Plan one regulation-aware adaptation for a real subject lesson without lowering the learning goal.",instructions:["Name the subject/task and likely regulation demand.","Identify a predictable pressure point such as transition, practical work, extended writing or assessment.","Choose one universal support available to everyone.","Choose one optional individual strategy if needed.","State how pupils reconnect with the original learning goal."],placeholder:"Subject/task…\nPressure point…\nUniversal support…\nOptional strategy…\nReturn to learning…",minimumCharacters:140},
      {id:"zr8",type:"scenario",title:"Module 6 · SEND, EAL and individual differences",prompt:"Two pupils describe the same zone but need different support. What is the strongest interpretation?",options:[{label:"The zone framework is inconsistent",feedback:"A shared label does not mean identical needs or strategies."},{label:"Use pupil-specific information, communication needs and previous strategy evidence to choose support",feedback:"Regulation support should be individualised rather than prescribed by colour alone."},{label:"Give both pupils the same strategy because the zone is the same",feedback:"The same state can have different causes, needs and useful responses."}]},
      {id:"zr9",type:"content",title:"Module 7 · Structured intervention planning",body:"Where universal support is not enough, use a structured cycle: baseline, goal, planned support, delivery, evidence and review. Review outcomes alongside implementation fidelity and student voice so the pupil is not judged solely on whether behaviour changed.",keyPoints:["Use observable baselines","Set a measurable, meaningful goal","Record the planned strategy and frequency","Gather evidence of implementation as well as outcome","Ask whether the strategy felt useful to the pupil","Continue, adapt, fade or close based on evidence"]},
      {id:"zr10",type:"activity",title:"Build a regulation intervention outline",prompt:"Create a short intervention outline using the Regulation Hub cycle.",instructions:["State a strength and successful condition.","Write an observable baseline without diagnostic labels.","Write one measurable goal.","Choose the support and delivery frequency.","Name the evidence source and review date.","State how student voice will be included."],placeholder:"Strength…\nBaseline…\nGoal…\nSupport/frequency…\nEvidence/review…\nStudent voice…",minimumCharacters:180},
      {id:"zr11",type:"checklist",title:"Module 8 · Whole-school implementation and review",prompt:"Check whether the approach is being implemented consistently rather than simply displayed.",items:["Staff understand that all zones are valid","Language is consistent and non-judgemental","Support is available across subjects, not only pastoral spaces","Student voice is gathered","Departments adapt support to their context","Interventions have review dates and evidence","Safeguarding, medical and behaviour procedures remain clearly separate","Leaders review implementation fidelity rather than ranking staff or pupils"],completionText:"Whole-school regulation implementation review complete."},
      {id:"zr12",type:"reflection",title:"Whole-course reflection",prompt:"What is the smallest whole-school or classroom change that would make regulation support more consistent, respectful and useful in your setting?"}
    ]
  }
];
