import type { Course, Module } from "./data";
const reflect=(id:string,prompt:string):Module=>({id,type:"reflection",title:"Apply it to your practice",prompt});

export const schoolCoursesBatch2:Course[]=[
{
 id:"bullying-cyberbullying-peer-abuse",title:"Bullying, Cyberbullying & Peer-on-Peer Abuse",category:"Safeguarding",duration:80,level:"Foundation",summary:"Recognise repeated harm, online/offline overlap and peer abuse, then respond through clear behaviour and safeguarding systems rather than treating incidents as isolated conflict.",objectives:["Distinguish bullying from ordinary disagreement","Recognise online/offline patterns","Record and respond consistently","Know when behaviour becomes a safeguarding concern"],recommendedFor:["All staff"],modules:[
  {id:"bc1",type:"content",title:"Look for patterns, power and impact",body:"Bullying is more than a single disagreement. Staff should look for repeated or sustained patterns, imbalance of power, targeting, social exclusion, online amplification and impact on the pupil. Peer-on-peer harm may require a safeguarding response even when it happens between pupils of similar age.",keyPoints:["Do not dismiss repeated harm as 'banter'","Consider online and offline contexts together","Record patterns, not just individual incidents","Follow the school's behaviour and safeguarding procedures"]},
  {id:"bc2",type:"visual",title:"From incident to pattern",layout:"flow",caption:"A consistent response joins up information across staff and settings.",items:[{heading:"Notice",text:"Record the specific behaviour and context.",icon:"1"},{heading:"Check pattern",text:"Look for repetition, targeting, power and online/offline links.",icon:"2"},{heading:"Protect",text:"Put immediate proportionate support in place for the affected pupil.",icon:"3"},{heading:"Respond",text:"Use behaviour and safeguarding routes as required.",icon:"4"},{heading:"Review",text:"Check whether the behaviour has stopped and whether support is working.",icon:"5"}]},
  {id:"bc3",type:"scenario",title:"Group-chat scenario",prompt:"A pupil reports repeated mocking messages from several peers outside school that are affecting attendance and concentration. What is the strongest response?",options:[{label:"Ignore it because it happened online outside school",feedback:"The impact is affecting school and may require behaviour/safeguarding action."},{label:"Record the report, preserve relevant evidence through school procedures, support the pupil and escalate appropriately",feedback:"Online and offline harm should be considered together."},{label:"Ask the pupil to publicly confront the group",feedback:"This may increase risk and is not a safe first response."}]},
  {id:"bc4",type:"checklist",title:"Response quality check",prompt:"Check the elements of a strong school response.",items:["The pupil's account is taken seriously","The incident is recorded factually","Relevant online/offline context is considered","Support is offered to the affected pupil","The behaviour is addressed through school systems","Safeguarding thresholds are considered","A follow-up check confirms whether the problem has stopped"],completionText:"Response checklist complete."},
  {id:"bc5",type:"activity",title:"Plan a follow-up conversation",prompt:"Draft a short follow-up that checks safety, impact and whether the behaviour has stopped without asking the pupil to repeatedly retell the whole incident.",instructions:["Acknowledge the earlier report.","Ask whether anything has changed since the last contact.","Check whether school feels safe enough today.","State the next school action or support clearly."],placeholder:"Follow-up wording…",minimumCharacters:100},
  reflect("bc6","Which part of your school's bullying response most needs consistency across staff: recording, escalation, support or follow-up?")
 ]
},
{
 id:"child-on-child-abuse-awareness",title:"Child-on-Child Abuse & Harmful Behaviour Awareness",category:"Safeguarding",duration:85,level:"Foundation",summary:"Strengthen staff understanding of child-on-child abuse, professional response and safeguarding escalation without normalising harmful behaviour as part of growing up.",objectives:["Recognise that children can harm other children","Respond without minimising or blaming","Protect privacy and evidence","Use DSL and safeguarding procedures promptly"],recommendedFor:["All staff"],modules:[
  {id:"cca1",type:"content",title:"It can happen here",body:"Child-on-child abuse can occur in school, online or in the community. Staff should avoid assumptions that harmful behaviour is simply part of adolescence or that a pupil cannot be harmed because the other person is also a child. The school safeguarding policy and DSL should guide the response.",keyPoints:["Take disclosures seriously","Avoid victim-blaming language","Do not mediate serious safeguarding allegations as if they were ordinary conflict","Share information only with those who need it","Record the pupil's account factually"]},
  {id:"cca2",type:"visual",title:"Safe safeguarding response",layout:"flow",items:[{heading:"Listen",text:"Stay calm and avoid leading questions.",icon:"1"},{heading:"Protect",text:"Consider immediate safety and separation where required by school procedure.",icon:"2"},{heading:"Record",text:"Write factual information promptly.",icon:"3"},{heading:"Report",text:"Pass the concern to the DSL or safeguarding route.",icon:"4"},{heading:"Support",text:"Maintain appropriate pastoral support and confidentiality.",icon:"5"}]},
  {id:"cca3",type:"quiz",title:"Knowledge check",question:"Which statement is safest?",options:["If both pupils are similar in age, it cannot be safeguarding","Staff should resolve serious allegations through peer mediation first","Child-on-child abuse may require safeguarding action and should not be minimised","Staff should question multiple pupils before telling the DSL"],answer:2,feedback:"Harm between children can be a safeguarding matter. Staff should follow school procedures rather than conduct their own investigation."},
  {id:"cca4",type:"scenario",title:"Disclosure scenario",prompt:"A pupil reports serious unwanted behaviour from another pupil and asks you not to tell anyone. What should you do?",options:[{label:"Promise secrecy",feedback:"Staff cannot promise confidentiality when information may need to be shared to keep a child safe."},{label:"Explain calmly that you need to involve the appropriate safeguarding staff and report promptly",feedback:"This is a clear, child-centred safeguarding response."},{label:"Arrange a meeting between both pupils yourself",feedback:"Serious concerns should not be treated as ordinary peer conflict before safeguarding assessment."}]},
  {id:"cca5",type:"checklist",title:"Language check",prompt:"Check the language practices that help avoid minimising harm.",items:["Describe behaviour specifically rather than calling everything 'drama'","Avoid asking why the affected pupil did not stop it sooner","Do not suggest responsibility is shared simply because both pupils know each other","Avoid public discussion or unnecessary detail","Keep the focus on safety, facts and procedure"],completionText:"Safeguarding language checklist complete."},
  reflect("cca6","What phrase or staff habit in your setting could unintentionally minimise child-on-child harm, and what safer wording would replace it?")
 ]
},
{
 id:"prevent-duty-awareness",title:"Prevent Duty & Radicalisation Awareness",category:"Safeguarding",duration:75,level:"Foundation",summary:"Understand Prevent as part of safeguarding, recognise concerning changes without stereotyping, and use the school's referral route appropriately.",objectives:["Explain Prevent as a safeguarding duty","Recognise why indicators must be considered in context","Avoid stereotyping communities or beliefs","Know when and how to raise a concern"],recommendedFor:["All staff"],modules:[
  {id:"pd1",type:"content",title:"Prevent is safeguarding",body:"The Prevent duty is part of the wider safeguarding responsibility to protect learners who may be susceptible to radicalisation. Staff should not try to identify a 'type' of pupil. Changes in language, behaviour, relationships or online activity may have many explanations and should be considered alongside context, professional curiosity and the school's safeguarding procedure.",keyPoints:["Use the same child-centred safeguarding mindset","Do not stereotype religion, ethnicity or political interest","Record specific behaviour or statements, not assumptions","Use DSL/Prevent procedures for concerns","Current DfE and school guidance take precedence"]},
  {id:"pd2",type:"visual",title:"From concern to safeguarding action",layout:"flow",items:[{heading:"Observe",text:"Identify the specific change or concern.",icon:"1"},{heading:"Contextualise",text:"Consider what is known and avoid assumptions.",icon:"2"},{heading:"Record",text:"Write factual information.",icon:"3"},{heading:"Consult DSL",text:"Use the school's Prevent/safeguarding route.",icon:"4"},{heading:"Follow guidance",text:"DSL coordinates any referral or additional action.",icon:"5"}]},
  {id:"pd3",type:"scenario",title:"Classroom scenario",prompt:"A pupil makes a concerning statement during discussion, but the context is unclear. What is the strongest response?",options:[{label:"Label the pupil as radicalised",feedback:"One statement does not justify a diagnosis or label."},{label:"Record the exact concern and context, then seek advice through the school's safeguarding route",feedback:"This preserves the facts and allows the DSL to assess context."},{label:"Ignore it because political topics are always protected from safeguarding consideration",feedback:"Safeguarding concerns should still be considered appropriately."}]},
  {id:"pd4",type:"checklist",title:"Bias-resistant response",prompt:"Check the habits that reduce stereotyping in Prevent practice.",items:["Focus on specific behaviour or statements","Ask what else could explain the change","Avoid treating a protected characteristic as an indicator","Use the same safeguarding threshold consistently","Consult the DSL rather than making the referral decision alone"],completionText:"Bias-resistant response checklist complete."},
  {id:"pd5",type:"activity",title:"Practise factual recording",prompt:"Turn a vague judgement into a short factual safeguarding note.",instructions:["Write the exact observable behaviour or statement.","Add date/context without interpretation.","Avoid labels or assumptions about motive.","State that the concern was passed to the appropriate safeguarding lead."],placeholder:"Factual note…",minimumCharacters:90},
  reflect("pd6","How can your department discuss controversial issues while still noticing and reporting genuine safeguarding concerns without stereotyping pupils?")
 ]
},
{
 id:"attendance-persistent-absence",title:"Attendance & Persistent Absence: Support, Challenge and Early Action",category:"Leadership",duration:85,level:"Developing",summary:"Use attendance data, early conversations and targeted support to address barriers while maintaining clear expectations and statutory responsibilities.",objectives:["Recognise early attendance patterns","Distinguish barriers from assumptions about motivation","Coordinate support with clear expectations","Use school and local attendance procedures appropriately"],recommendedFor:["Tutor","Pastoral","Attendance Lead","Department Lead","Leadership"],modules:[
  {id:"att1",type:"content",title:"Attendance is everyone's business",body:"Good attendance work combines accurate data, early contact, supportive problem-solving and clear expectations. Persistent absence rarely improves through a single conversation. Schools should identify patterns early, understand barriers, use reasonable support and follow current statutory attendance guidance and local procedures.",keyPoints:["Act before absence becomes entrenched","Look for patterns by day, subject and transition","Keep communication factual and respectful","Coordinate attendance, SEND, pastoral and safeguarding information","Review whether support changes attendance"]},
  {id:"att2",type:"visual",title:"Attendance improvement cycle",layout:"cycle",items:[{heading:"Spot",text:"Identify emerging patterns early.",icon:"1"},{heading:"Understand",text:"Explore barriers with pupil/family.",icon:"2"},{heading:"Plan",text:"Agree support and expectations.",icon:"3"},{heading:"Act",text:"Implement consistently across staff.",icon:"4"},{heading:"Review",text:"Use attendance evidence to adjust the plan.",icon:"5"}]},
  {id:"att3",type:"scenario",title:"Pattern scenario",prompt:"A pupil's overall attendance is falling, with most absence clustered around one day and two lessons. What is the best first response?",options:[{label:"Treat all absence as the same problem",feedback:"The pattern may reveal specific barriers that need investigation."},{label:"Map the pattern, talk with the pupil/family and relevant staff, then agree targeted support",feedback:"Specific patterns can make intervention more precise."},{label:"Wait until the end of term",feedback:"Early action is generally more effective than allowing the pattern to become established."}]},
  {id:"att4",type:"checklist",title:"Attendance-plan quality",prompt:"Check whether a plan is concrete enough to implement.",items:["A named school contact is identified","The attendance pattern/barrier is stated specifically","Support actions have owners","Expectations are clear","SEND/health/safeguarding factors have been considered","A review date is set","Success is measured using attendance and engagement evidence"],completionText:"Attendance-plan check complete."},
  {id:"att5",type:"activity",title:"Design an early-intervention plan",prompt:"Create an anonymised support plan for a pupil whose attendance is beginning to decline.",instructions:["Describe the attendance pattern.","Name two questions that would help identify barriers.","Choose one practical school action and one family communication action.","Set a review date and measurable outcome."],placeholder:"Pattern…\nQuestions…\nActions…\nReview…",minimumCharacters:120},
  reflect("att6","Where does your school currently lose time between spotting an attendance pattern and putting specific support in place?")
 ]
},
{
 id:"looked-after-previously-looked-after",title:"Supporting Looked-After & Previously Looked-After Children",category:"SEND",duration:80,level:"Developing",summary:"Maintain high expectations while using known information, predictable relationships and coordinated support for children in care and those previously in care.",objectives:["Understand why school stability matters","Use designated-teacher and PEP processes appropriately","Avoid deficit assumptions","Plan predictable, ambitious classroom support"],recommendedFor:["Teacher","Tutor","Pastoral","SEND staff","Leadership"],modules:[
  {id:"lac1",type:"content",title:"High expectations plus informed support",body:"Children in care and previously looked-after children are not a single group. Staff should avoid assuming low attainment, behavioural difficulty or trauma. What matters is using the information the school is authorised to hold, maintaining ambitious learning, supporting stability and coordinating with the designated teacher and relevant plans.",keyPoints:["Know who the designated teacher is","Use PEP or support-plan information appropriately","Avoid asking the pupil to explain their care history","Plan for transitions and changes","Protect confidentiality"]},
  {id:"lac2",type:"visual",title:"The stability framework",layout:"flow",items:[{heading:"Know the plan",text:"Use authorised information and agreed strategies.",icon:"1"},{heading:"Keep routines",text:"Predictability reduces unnecessary uncertainty.",icon:"2"},{heading:"Build belonging",text:"Inclusive participation matters.",icon:"3"},{heading:"Keep challenge",text:"Support should not become lowered expectations.",icon:"4"},{heading:"Coordinate",text:"Share concerns through the designated teacher/pastoral route.",icon:"5"}]},
  {id:"lac3",type:"scenario",title:"Confidentiality scenario",prompt:"A colleague asks you for details of a pupil's care history because they are curious about recent behaviour. What should you do?",options:[{label:"Share everything you know",feedback:"Sensitive information should be shared only on an appropriate need-to-know basis."},{label:"Share only the authorised strategies/information needed for the colleague's role and direct wider questions to the designated teacher",feedback:"This protects privacy while supporting consistent practice."},{label:"Ask the pupil to explain their history to the department",feedback:"Pupils should not be required to disclose personal history to satisfy staff curiosity."}]},
  {id:"lac4",type:"checklist",title:"Classroom stability check",prompt:"Check the practices that can support school stability.",items:["The pupil can participate without being singled out","Significant changes are explained where possible","Relevant support strategies are known by staff who need them","Feedback maintains challenge and dignity","Transitions between staff/classes are planned","Concerns are shared through the designated teacher/pastoral route"],completionText:"Stability checklist complete."},
  {id:"lac5",type:"activity",title:"Plan a transition",prompt:"Design a short transition plan for a pupil moving class, tutor group or key stage.",instructions:["State what information the receiving staff genuinely need.","Identify one predictable contact/routine.","Keep academic expectations explicit.","Plan a review after the transition."],placeholder:"Transition plan…",minimumCharacters:100},
  reflect("lac6","How can your team offer additional stability without making a looked-after or previously looked-after pupil feel publicly different?")
 ]
},
{
 id:"supporting-young-carers",title:"Supporting Young Carers in School",category:"Wellbeing",duration:60,level:"Foundation",summary:"Recognise how caring responsibilities can affect attendance, concentration and participation while avoiding assumptions and supporting pupils through appropriate pastoral systems.",objectives:["Understand possible school impacts of caring responsibilities","Notice patterns without labelling","Offer proportionate practical support","Use pastoral and safeguarding pathways appropriately"],recommendedFor:["All staff","Tutor","Pastoral"],modules:[
  {id:"yc1",type:"content",title:"Caring responsibilities can be hidden",body:"Some pupils provide regular practical or emotional support within their family. Staff may notice tiredness, punctuality difficulties, incomplete work, anxiety about home or reduced participation, but these signs have many possible causes. The right response is curiosity, privacy and referral through appropriate school support rather than public questioning.",keyPoints:["Do not assume the cause of a pupil's difficulties","Use a trusted pastoral route","Agree reasonable flexibility rather than vague exemptions","Keep the pupil included in normal school life","Consider safeguarding where concerns go beyond caring responsibility"]},
  {id:"yc2",type:"visual",title:"Support without lowering ambition",layout:"compare",items:[{heading:"Helpful flexibility",text:"A named contact, planned deadline flexibility, catch-up support and discreet communication.",icon:"✓"},{heading:"Unhelpful assumptions",text:"Lowering expectations automatically, public questioning or treating absence as inevitable.",icon:"×"}]},
  {id:"yc3",type:"scenario",title:"Homework pattern",prompt:"A reliable pupil begins missing homework and looks exhausted. You know they have caring responsibilities. What is the best response?",options:[{label:"Publicly explain their situation to the class",feedback:"This breaches privacy and may embarrass the pupil."},{label:"Use a private check-in, follow the agreed support plan/pastoral route and agree a manageable next step",feedback:"This combines dignity, support and continued learning."},{label:"Stop setting any work indefinitely",feedback:"Automatic removal of learning expectations may not match the pupil's wishes or needs."}]},
  {id:"yc4",type:"checklist",title:"Young-carer-friendly practice",prompt:"Check the supports your school can make predictable.",items:["There is a clear route for pupils to identify themselves privately","Staff know the named pastoral contact","Reasonable deadline flexibility can be agreed consistently","Pupils can access catch-up materials without public explanation","Attendance concerns are explored rather than assumed","Safeguarding concerns are escalated through normal procedures"],completionText:"Young-carer support checklist complete."},
  reflect("yc5","What could your department do so a pupil with caring responsibilities can ask for help discreetly without repeatedly explaining their situation?")
 ]
},
{
 id:"speech-language-communication-needs",title:"Speech, Language & Communication Needs (SLCN)",category:"SEND",duration:75,level:"Developing",summary:"Reduce hidden language barriers through explicit vocabulary, processing time, visual support and careful classroom talk while using pupil-specific SEND information.",objectives:["Identify language demands in everyday teaching","Separate conceptual understanding from expressive language","Adapt instructions and classroom talk","Support communication without over-speaking for pupils"],recommendedFor:["Teacher","Teaching Assistant","ECT","SEND staff"],modules:[
  {id:"slcn1",type:"content",title:"Language is built into every lesson",body:"A pupil can understand the concept but struggle to process long instructions, retrieve vocabulary, organise spoken responses or interpret figurative language. Staff should identify the language demand of a task instead of assuming low subject understanding.",keyPoints:["Reduce unnecessary verbal load","Pair spoken instructions with visible steps","Pre-teach essential vocabulary","Give processing time","Model the language of explanations and questions"]},
  {id:"slcn2",type:"visual",title:"Where language demand appears",layout:"cycle",items:[{heading:"Listen",text:"Following explanations and multi-step instructions.",icon:"1"},{heading:"Understand",text:"Interpreting vocabulary, grammar and implied meaning.",icon:"2"},{heading:"Plan",text:"Organising a spoken or written response.",icon:"3"},{heading:"Express",text:"Finding words and constructing sentences.",icon:"4"},{heading:"Repair",text:"Clarifying misunderstandings and asking for help.",icon:"5"}]},
  {id:"slcn3",type:"scenario",title:"Instruction scenario",prompt:"Several pupils start the wrong part of a practical after a long spoken instruction. What is the strongest first adaptation?",options:[{label:"Repeat the same long instruction more loudly",feedback:"Volume does not reduce language-processing demand."},{label:"Chunk the instruction, display the steps and check understanding before starting",feedback:"This supports processing while keeping the same task."},{label:"Remove the practical",feedback:"The aim is to improve access, not remove the learning experience."}]},
  {id:"slcn4",type:"checklist",title:"Communication-friendly lesson",prompt:"Check the features you can build into an upcoming lesson.",items:["Key vocabulary is explicitly taught","Complex instructions are chunked","Important steps are visible","Pupils receive thinking/processing time","Teachers model complete subject-specific responses","Pupils have a safe way to ask for clarification"],completionText:"Communication-friendly lesson check complete."},
  {id:"slcn5",type:"activity",title:"Rewrite an instruction",prompt:"Take a complex instruction you use and redesign it for clarity without removing the thinking pupils must do.",instructions:["Write the original instruction.","Split it into short visible steps.","Highlight vocabulary that needs pre-teaching.","Add one check for understanding."],placeholder:"Original…\nRevised steps…\nVocabulary…\nCheck…",minimumCharacters:110},
  reflect("slcn6","Which routine in your classroom currently relies too heavily on pupils remembering spoken language?")
 ]
},
{
 id:"sensory-needs-classroom",title:"Sensory Needs in the Classroom",category:"SEND",duration:65,level:"Developing",summary:"Notice sensory barriers in the learning environment and make proportionate adjustments without assuming every pupil with the same diagnosis has the same sensory profile.",objectives:["Identify common sensory demands in school","Use pupil-specific information","Reduce avoidable environmental barriers","Balance adjustment with participation and independence"],recommendedFor:["Teacher","Teaching Assistant","SEND staff"],modules:[
  {id:"sn1",type:"content",title:"Start with the environment and the pupil",body:"Noise, lighting, movement, touch, smell, crowded transitions and practical equipment can all create sensory demand. A diagnosis does not tell you exactly what a pupil experiences. Use the pupil's plan, observed patterns and discussion with appropriate staff to identify specific barriers.",keyPoints:["Do not assume one sensory profile","Look for patterns by place and time","Change the environment before blaming the pupil","Make adjustments specific and reviewable","Support participation where possible"]},
  {id:"sn2",type:"visual",title:"Sensory load map",layout:"compare",items:[{heading:"Sound",text:"Crowded rooms, scraping chairs, alarms, overlapping talk.",icon:"♫"},{heading:"Vision",text:"Glare, flicker, visual clutter, movement.",icon:"◉"},{heading:"Touch/movement",text:"Crowding, practical contact, seating, transitions.",icon:"↔"},{heading:"Smell/temperature",text:"Labs, food areas, changing rooms and variable environments.",icon:"≈"}]},
  {id:"sn3",type:"scenario",title:"Practical-lesson scenario",prompt:"A pupil who usually succeeds becomes overwhelmed during a noisy practical setup. What is the strongest first response?",options:[{label:"Conclude they cannot do practical work",feedback:"One environment does not justify removing the learning opportunity."},{label:"Identify the sensory barrier and adjust the setup, timing, position or transition while preserving the practical goal",feedback:"Target the barrier rather than the learning objective."},{label:"Tell them to ignore the noise",feedback:"This does not reduce the environmental demand."}]},
  {id:"sn4",type:"checklist",title:"Sensory audit",prompt:"Audit one room or routine.",items:["Noise hotspots are predictable","Visual clutter is kept purposeful","Transitions avoid unnecessary crowding where possible","There is a discreet agreed route for a short reset","Practical equipment/odours are considered in advance","Adjustments are reviewed for impact and independence"],completionText:"Sensory audit complete."},
  reflect("sn5","Which environmental change could improve access for a pupil with sensory needs without reducing the curriculum they experience?")
 ]
},
{
 id:"executive-function-learning",title:"Executive Function in Learning",category:"SEND",duration:75,level:"Developing",summary:"Support planning, organisation, task initiation, working memory and self-monitoring through explicit routines that gradually transfer responsibility to pupils.",objectives:["Recognise executive-function demands hidden in tasks","Externalise planning and memory demands","Teach task initiation and monitoring routines","Fade supports towards independence"],recommendedFor:["Teacher","ECT","Teaching Assistant","SEND staff"],modules:[
  {id:"ef1",type:"content",title:"The hidden task behind the task",body:"A pupil may understand the subject but struggle to start, organise materials, remember several instructions, estimate time or monitor progress. These executive demands are often invisible in lesson planning. Externalising the process can let subject knowledge, rather than organisation, determine success.",keyPoints:["Make starting steps explicit","Use visible sequences/checklists","Teach planning rather than repeatedly reminding","Reduce working-memory load","Fade prompts as routines become internalised"]},
  {id:"ef2",type:"visual",title:"Executive-function loop",layout:"cycle",items:[{heading:"Start",text:"Initiate the first action.",icon:"▶"},{heading:"Plan",text:"Sequence steps and resources.",icon:"▤"},{heading:"Hold",text:"Keep relevant information available.",icon:"◫"},{heading:"Monitor",text:"Check progress and errors.",icon:"✓"},{heading:"Shift",text:"Change strategy when needed.",icon:"↻"}]},
  {id:"ef3",type:"scenario",title:"Blank-page problem",prompt:"A pupil can explain an essay verbally but sits for ten minutes without starting. What support most directly targets executive function?",options:[{label:"Lower the essay question",feedback:"The conceptual goal may not be the barrier."},{label:"Provide a brief start routine: identify the question, choose the first point, write the opening sentence, then review",feedback:"This externalises initiation and sequencing while preserving the task."},{label:"Write the essay for them",feedback:"Over-support removes the thinking the pupil needs to practise."}]},
  {id:"ef4",type:"checklist",title:"Task-design check",prompt:"Check whether your task makes executive demands visible.",items:["The starting action is obvious","The sequence is visible","Required resources are clear","Time checkpoints are built in","Pupils know how to check progress","Prompts can be faded as independence grows"],completionText:"Executive-function task check complete."},
  {id:"ef5",type:"activity",title:"Build a start routine",prompt:"Design a three-to-five-step starting routine for one complex recurring task in your subject.",instructions:["Name the task.","Write the first observable action.","Add the next two or three steps.","State which prompt will be faded first."],placeholder:"Task…\nStart routine…\nFade…",minimumCharacters:90},
  reflect("ef6","Which pupil difficulty in your class might actually be a task-initiation or organisation barrier rather than lack of subject understanding?")
 ]
},
{
 id:"semh-classroom-practice",title:"Supporting Pupils with SEMH Needs",category:"SEND",duration:80,level:"Developing",summary:"Combine predictable teaching, calm boundaries, relational support and coordinated pastoral systems for pupils with social, emotional and mental-health needs.",objectives:["Understand SEMH as a broad area of need","Use predictable classroom support","Respond to distress without abandoning boundaries","Coordinate classroom, pastoral and safeguarding responses"],recommendedFor:["Teacher","Teaching Assistant","Pastoral","SEND staff"],modules:[
  {id:"semh1",type:"content",title:"SEMH is broad and individual",body:"SEMH needs can affect regulation, relationships, attendance, confidence and engagement, but the same classroom behaviour can have many causes. Staff should use pupil-specific information, maintain clear expectations and coordinate with SEND/pastoral teams rather than attempting diagnosis.",keyPoints:["Know the individual plan","Use calm, predictable routines","Separate emotion from behaviour expectations","Avoid public escalation","Review what helps the pupil return to learning"]},
  {id:"semh2",type:"visual",title:"Support ladder",layout:"ladder",items:[{heading:"Universal",text:"Clear routines, belonging and predictable teaching.",icon:"1"},{heading:"Targeted",text:"Specific prompts, check-ins or adaptations linked to need.",icon:"2"},{heading:"Pastoral/SEND",text:"Coordinated plan, monitoring and review.",icon:"3"},{heading:"Safeguarding/specialist",text:"Escalation where concern or need requires wider support.",icon:"4"}]},
  {id:"semh3",type:"scenario",title:"Escalation scenario",prompt:"A pupil becomes very distressed after receiving corrective feedback. What is the strongest response?",options:[{label:"Argue publicly until they admit the feedback was fair",feedback:"Public confrontation may increase distress and reduce learning."},{label:"Keep the boundary concise, reduce the audience, allow an agreed reset and return to the task when possible",feedback:"This combines regulation support with clear expectations."},{label:"Never give the pupil feedback again",feedback:"Avoidance removes an important part of learning."}]},
  {id:"semh4",type:"checklist",title:"Predictable support",prompt:"Check features of a clear support plan.",items:["Known triggers/barriers are described factually","Helpful adult responses are specific","The pupil knows how to request support","There is a route back into learning","Staff know what should be escalated","Support is reviewed using evidence"],completionText:"SEMH support check complete."},
  reflect("semh5","How could you make one difficult classroom interaction more predictable without weakening the learning or behaviour expectation?")
 ]
},
{
 id:"universal-design-learning",title:"Universal Design for Learning: Plan Access from the Start",category:"SEND",duration:75,level:"Developing",summary:"Anticipate common barriers when planning curriculum, explanation and response so fewer adaptations have to be added after pupils struggle.",objectives:["Identify barriers before teaching","Provide purposeful ways to access information","Offer appropriate ways for pupils to practise and respond","Avoid turning choice into lower challenge"],recommendedFor:["Teacher","ECT","SEND staff","Department Lead"],modules:[
  {id:"udl1",type:"content",title:"Design for variability",body:"Universal Design for Learning starts from the expectation that pupils vary in prior knowledge, language, attention, sensory access and ways of expressing understanding. The aim is not to create a separate task for everyone, but to design core teaching that is clear and accessible while keeping the learning goal stable.",keyPoints:["Clarify the learning goal","Separate the goal from accidental access barriers","Use multiple representations when they add meaning","Offer structured response options where appropriate","Keep challenge in the thinking, not in avoidable presentation barriers"]},
  {id:"udl2",type:"visual",title:"Three planning questions",layout:"compare",items:[{heading:"Access",text:"How will pupils perceive and understand the information?",icon:"1"},{heading:"Engage",text:"How will the task make purpose, progress and participation clear?",icon:"2"},{heading:"Respond",text:"How can pupils show understanding without irrelevant barriers dominating?",icon:"3"}]},
  {id:"udl3",type:"scenario",title:"Resource scenario",prompt:"A worksheet requires dense reading but the learning goal is interpreting scientific data. What is the strongest UDL response?",options:[{label:"Lower the data challenge",feedback:"The reading format, not the science goal, may be the barrier."},{label:"Improve layout, clarify key vocabulary and separate the data interpretation from unnecessary reading load",feedback:"This preserves the intended thinking while improving access."},{label:"Create a completely different easy task",feedback:"Universal design should not automatically reduce the goal."}]},
  {id:"udl4",type:"checklist",title:"Barrier-before-lesson check",prompt:"Check one upcoming task before teaching it.",items:["The learning goal is explicit","Unnecessary reading/copying demands have been identified","Key vocabulary is supported","Instructions are visible","The response format matches the learning goal","Optional supports can be faded"],completionText:"UDL planning check complete."},
  reflect("udl5","Which barrier in one frequently used resource could you remove for everyone without lowering the subject challenge?")
 ]
},
{
 id:"high-quality-teaching-send",title:"High-Quality Teaching for SEND",category:"SEND",duration:90,level:"Developing",summary:"Use explicit teaching, scaffolding, checking and pupil-specific adjustments as the first layer of inclusive classroom practice while maintaining ambitious curriculum goals.",objectives:["Connect high-quality teaching with SEND inclusion","Plan scaffolds around identified barriers","Use checks to adapt support","Know when universal practice is not enough"],recommendedFor:["Teacher","ECT","Teaching Assistant","SEND staff","Department Lead"],modules:[
  {id:"hq1",type:"content",title:"Start with strong teaching, then personalise where needed",body:"Many inclusive strategies are simply strong teaching used deliberately: clear explanation, explicit vocabulary, worked examples, guided practice, checking for understanding and well-designed routines. Pupils with SEND may still need individual adjustments, specialist advice or additional provision, so high-quality teaching should not be used as a reason to ignore specific plans.",keyPoints:["Keep curriculum ambition high","Use the pupil plan","Target the barrier rather than the label","Scaffold temporarily where possible","Escalate when classroom adjustments are not enough"]},
  {id:"hq2",type:"visual",title:"Inclusive teaching sequence",layout:"flow",items:[{heading:"Know",text:"Use pupil-specific information and prior assessment.",icon:"1"},{heading:"Plan",text:"Identify likely barriers in the task.",icon:"2"},{heading:"Teach",text:"Use explicit explanation/model/practice.",icon:"3"},{heading:"Check",text:"Gather evidence from the pupil.",icon:"4"},{heading:"Adapt",text:"Increase, change or fade support responsively.",icon:"5"}]},
  {id:"hq3",type:"scenario",title:"Same diagnosis, different needs",prompt:"Two pupils with the same diagnosis respond differently to a task. What should the teacher do?",options:[{label:"Use exactly the same support because the label is the same",feedback:"Labels do not determine an identical classroom profile."},{label:"Use individual information and evidence from the task to adapt support for each pupil",feedback:"Adaptive teaching should respond to the pupil and barrier, not just the label."},{label:"Remove the learning objective for both pupils",feedback:"High expectations and support can coexist."}]},
  {id:"hq4",type:"checklist",title:"Inclusive lesson check",prompt:"Check whether one lesson balances ambition and access.",items:["Prerequisite knowledge is activated","Vocabulary is explicit","New content is chunked appropriately","A model/example is available where useful","Understanding is checked broadly","Scaffolds can be faded","Individual plans are followed where required"],completionText:"Inclusive lesson check complete."},
  {id:"hq5",type:"activity",title:"Adapt without lowering the goal",prompt:"Choose one upcoming task and redesign one barrier while keeping the learning objective unchanged.",instructions:["Write the learning objective.","Identify one access barrier.","Choose one adaptation.","State how you will know whether the adaptation is helping.","Decide how/when it could be faded."],placeholder:"Objective…\nBarrier…\nAdaptation…\nEvidence…\nFade…",minimumCharacters:130},
  reflect("hq6","Which support in your classroom is currently too generic, and what pupil-specific evidence would help you improve it?")
 ]
},
{
 id:"explicit-vocabulary-teaching",title:"Teaching Vocabulary Explicitly",category:"Teaching & Learning",duration:70,level:"Developing",summary:"Select high-value words, teach meaning and morphology explicitly, and give pupils repeated opportunities to understand and use disciplinary vocabulary.",objectives:["Select high-value vocabulary","Teach meaning in context","Use morphology and word relationships","Plan repeated retrieval and use"],recommendedFor:["Teacher","ECT","Department Lead"],modules:[
  {id:"v1",type:"content",title:"Vocabulary is part of subject knowledge",body:"Knowing a term means more than copying a definition. Pupils need to recognise the word, connect it to the concept, distinguish it from related terms and use it accurately in speech and writing. Subject vocabulary should therefore be selected and revisited deliberately.",keyPoints:["Prioritise words that unlock important concepts","Explain student-friendly meaning and precise disciplinary meaning","Use examples and non-examples","Teach useful roots/prefixes/suffixes","Revisit words in retrieval and application"]},
  {id:"v2",type:"visual",title:"A vocabulary-teaching cycle",layout:"cycle",items:[{heading:"Select",text:"Choose a small number of high-value words.",icon:"1"},{heading:"Explain",text:"Connect word and concept clearly.",icon:"2"},{heading:"Explore",text:"Examples, morphology and relationships.",icon:"3"},{heading:"Use",text:"Pupils say and write the word in subject contexts.",icon:"4"},{heading:"Retrieve",text:"Revisit after delays.",icon:"5"}]},
  {id:"v3",type:"scenario",title:"Definition-only scenario",prompt:"Pupils can recite a definition but misuse the term in explanations. What should happen next?",options:[{label:"Give them the same definition to copy again",feedback:"Repeated copying may not deepen conceptual understanding."},{label:"Use examples/non-examples and require pupils to apply the term in varied subject contexts",feedback:"Accurate use develops through conceptual connections and practice."},{label:"Stop using technical vocabulary",feedback:"Pupils need access to disciplinary language, not its removal."}]},
  {id:"v4",type:"activity",title:"Build a vocabulary routine",prompt:"Choose one important term and design a five-minute explicit-teaching sequence.",instructions:["Write the precise meaning.","Give one example and one non-example.","Identify any useful morphology/word family.","Write one sentence stem for pupil use.","Plan one retrieval question for a later lesson."],placeholder:"Word…\nMeaning…\nExample/non-example…\nMorphology…\nSentence stem…\nRetrieval…",minimumCharacters:120},
  reflect("v5","Which five words in your next unit are most likely to unlock understanding if pupils can use them accurately?")
 ]
},
{
 id:"reading-across-curriculum",title:"Reading Across the Curriculum",category:"Teaching & Learning",duration:80,level:"Developing",summary:"Teach pupils how to approach challenging subject texts through vocabulary, fluency, questioning and disciplinary reading strategies.",objectives:["Identify reading demands in your subject","Support vocabulary and fluency","Model how experts read disciplinary texts","Use questions that require meaning-making rather than copying"],recommendedFor:["Teacher","ECT","Department Lead"],modules:[
  {id:"rac1",type:"content",title:"Reading is different in different subjects",body:"A science explanation, historical source, mathematical problem and geography case study demand different reading habits. Teachers should make those habits visible: what to notice first, how to interpret diagrams, how to track argument or causality, and which vocabulary carries technical meaning.",keyPoints:["Preview the purpose for reading","Teach essential vocabulary before or during reading","Model how an expert processes the text","Use short chunks when complexity is high","Ask pupils to reconstruct meaning, not just locate words"]},
  {id:"rac2",type:"visual",title:"Before, during, after reading",layout:"flow",items:[{heading:"Before",text:"Activate knowledge and clarify vocabulary/purpose.",icon:"1"},{heading:"During",text:"Model annotation, inference and connection-making.",icon:"2"},{heading:"After",text:"Summarise, explain and apply what was read.",icon:"3"}]},
  {id:"rac3",type:"scenario",title:"Dense-text scenario",prompt:"Pupils copy sentences from a textbook but cannot explain them. What is the strongest next move?",options:[{label:"Ask them to copy more",feedback:"Copying does not guarantee comprehension."},{label:"Chunk the text, model one section and ask pupils to paraphrase/explain the relationships",feedback:"This makes the meaning-making process explicit."},{label:"Remove subject reading entirely",feedback:"Pupils need supported access to disciplinary texts."}]},
  {id:"rac4",type:"checklist",title:"Reading-task audit",prompt:"Check the design of one subject reading task.",items:["The reason for reading is explicit","Essential vocabulary is supported","The text is appropriately challenging","Questions require meaning, not copying","Diagrams/captions are integrated into reading","There is an after-reading explanation/application task"],completionText:"Reading-task audit complete."},
  reflect("rac5","What does an expert reader in your subject do that pupils may not yet realise they need to do?")
 ]
},
{
 id:"oracy-classroom-talk",title:"Oracy & Classroom Talk",category:"Teaching & Learning",duration:70,level:"Developing",summary:"Use structured talk, rehearsal and accountable discussion to improve reasoning, vocabulary and participation rather than relying on a few confident volunteers.",objectives:["Plan talk around a clear learning purpose","Structure participation","Teach discussion routines explicitly","Use oral rehearsal to improve written responses"],recommendedFor:["Teacher","ECT","Tutor"],modules:[
  {id:"or1",type:"content",title:"Talk needs structure",body:"Simply asking pupils to discuss is not enough. Productive classroom talk needs a clear question, thinking time, roles or sentence support where helpful, and accountability for the ideas generated. Talk can act as rehearsal for writing and as evidence of understanding.",keyPoints:["Give a purposeful question","Build thinking time before discussion","Teach how to agree, challenge and build on ideas","Sample beyond volunteers","Use talk to rehearse disciplinary language"]},
  {id:"or2",type:"visual",title:"Talk-to-learning sequence",layout:"flow",items:[{heading:"Think",text:"Individual preparation prevents immediate domination by confident speakers.",icon:"1"},{heading:"Rehearse",text:"Pairs/small groups try the language of the answer.",icon:"2"},{heading:"Refine",text:"Pupils compare, challenge and improve ideas.",icon:"3"},{heading:"Share",text:"Teacher samples and connects responses.",icon:"4"},{heading:"Write/apply",text:"Pupils convert talk into a more precise response.",icon:"5"}]},
  {id:"or3",type:"scenario",title:"Group-talk scenario",prompt:"During discussion, two pupils do all the talking and the rest wait. What is the strongest adjustment?",options:[{label:"Let it continue because at least someone is participating",feedback:"The routine is not producing broad participation."},{label:"Add thinking time, defined turns/roles and a requirement that anyone may be asked to summarise the group's idea",feedback:"Structure increases participation and accountability."},{label:"Stop all discussion permanently",feedback:"The problem is the structure, not the existence of talk."}]},
  {id:"or4",type:"activity",title:"Design an accountable-talk routine",prompt:"Create a short talk routine for one difficult question in your subject.",instructions:["Write the question.","Give silent thinking/retrieval time.","Choose pair/group structure.","Add one sentence stem for agreeing/challenging/building.","State how the teacher will sample responses afterwards."],placeholder:"Question…\nThinking time…\nStructure…\nSentence stem…\nSampling…",minimumCharacters:110},
  reflect("or5","Which pupils currently get the least opportunity to rehearse subject thinking aloud in your lessons, and which routine could change that?")
 ]
}
];
