import type { Course, Module } from "./data";
const reflect=(id:string,prompt:string):Module=>({id,type:"reflection",title:"Apply it to your practice",prompt});
export const schoolCoursesBatch4:Course[]=[
{
 id:"assessment-moderation-reliability",title:"Assessment Reliability, Standardisation & Moderation",category:"Leadership",duration:85,level:"Advanced",summary:"Improve consistency of teacher assessment through shared criteria, exemplars, blind comparison and purposeful moderation rather than averaging unreliable judgements.",objectives:["Identify common sources of assessment inconsistency","Use exemplars and standardisation effectively","Run efficient moderation","Separate formative purpose from accountability pressure"],recommendedFor:["Teacher","Department Lead","Assessment Lead","Leadership"],modules:[
  {id:"am1",type:"content",title:"Reliable assessment needs shared interpretation",body:"A mark scheme alone does not guarantee consistent judgement. Teachers may interpret quality, borderline evidence or command words differently. Standardisation makes those differences visible before high-stakes decisions are made, while moderation checks whether agreed standards are being applied consistently.",keyPoints:["Clarify the purpose of the assessment","Use common exemplars","Discuss borderline responses","Sample across attainment, not only extremes","Record agreed interpretations","Avoid turning moderation into surveillance"]},
  {id:"am2",type:"visual",title:"Standardisation cycle",layout:"cycle",items:[{heading:"Agree criteria",text:"Clarify what evidence counts.",icon:"1"},{heading:"Judge independently",text:"Avoid immediate group influence.",icon:"2"},{heading:"Compare",text:"Identify differences in interpretation.",icon:"3"},{heading:"Calibrate",text:"Agree examples and thresholds.",icon:"4"},{heading:"Moderate",text:"Check later marking remains aligned.",icon:"5"}]},
  {id:"am3",type:"scenario",title:"Borderline script",prompt:"Three teachers give different marks to the same borderline response. What is the strongest response?",options:[{label:"Average the three marks automatically",feedback:"Averaging can hide disagreement about the standard rather than resolving it."},{label:"Return to criteria and exemplars, identify the exact evidence causing disagreement and agree a shared interpretation",feedback:"This improves future reliability rather than just solving one mark."},{label:"Let the most senior teacher decide without discussion",feedback:"Authority alone does not build shared understanding."}]},
  {id:"am4",type:"checklist",title:"Moderation quality check",prompt:"Check whether a moderation meeting is likely to improve reliability.",items:["The assessment purpose is clear","A manageable sample has been selected","Teachers mark some work independently first","Borderline examples are included","Disagreement is resolved by reference to evidence/criteria","Agreed decisions are recorded for future marking"],completionText:"Moderation quality check complete."},
  reflect("am5","Where does your department currently rely on implicit judgement that could be made more explicit through exemplars or standardisation?")
 ]
},
{
 id:"curriculum-intent-implementation-impact",title:"Curriculum Intent, Implementation & Impact",category:"Leadership",duration:90,level:"Advanced",summary:"Connect curriculum aims, sequencing, classroom enactment and evidence of learning so curriculum review focuses on what pupils actually know and can do over time.",objectives:["Clarify curriculum aims and endpoints","Align sequencing with prerequisite knowledge","Evaluate implementation without superficial compliance","Use learning evidence to review impact"],recommendedFor:["Department Lead","Curriculum Lead","Leadership","Teacher"],modules:[
  {id:"cii1",type:"content",title:"Intent is more than a statement",body:"Curriculum intent should be visible in the knowledge, concepts and disciplinary practices pupils are expected to build over time. Implementation is how that planned curriculum is enacted through teaching, assessment and resources. Impact is not a display board or isolated test score; it is evidence that pupils are increasingly able to remember, connect and use the intended curriculum.",keyPoints:["Define important endpoints","Map prerequisite knowledge","Align assessment with curriculum goals","Review what is actually taught","Use pupil work/response evidence thoughtfully","Avoid judging curriculum quality from lesson style alone"]},
  {id:"cii2",type:"visual",title:"Curriculum coherence chain",layout:"flow",items:[{heading:"Purpose",text:"What should pupils know/do by the endpoint?",icon:"1"},{heading:"Sequence",text:"What prerequisites build towards it?",icon:"2"},{heading:"Teach",text:"How is the curriculum enacted?",icon:"3"},{heading:"Assess",text:"What evidence shows learning over time?",icon:"4"},{heading:"Review",text:"Where does the sequence need refinement?",icon:"5"}]},
  {id:"cii3",type:"scenario",title:"Curriculum review scenario",prompt:"A department has detailed schemes of work but pupils repeatedly lack prerequisite knowledge in later units. What is the strongest review question?",options:[{label:"Are teachers using enough colourful resources?",feedback:"Resource appearance does not address the sequence problem."},{label:"Where should the prerequisite first be secured, where is it revisited, and what evidence shows pupils retained it?",feedback:"This connects intended sequence, teaching and retained learning."},{label:"Should the later unit simply be removed?",feedback:"The first step is to repair the curriculum pathway, not lower ambition."}]},
  {id:"cii4",type:"activity",title:"Trace one curriculum thread",prompt:"Follow one important idea across a key stage or course.",instructions:["State the final endpoint.","List the main prerequisite steps.","Identify where each step is first taught and later revisited.","Name the assessment evidence that shows pupils can use it later."],placeholder:"Endpoint…\nPrerequisites…\nRevisit points…\nEvidence…",minimumCharacters:140},
  reflect("cii5","Which curriculum idea in your subject most often breaks down because pupils have not retained or connected earlier learning?")
 ]
},
{
 id:"subject-leadership",title:"Effective Subject Leadership",category:"Leadership",duration:95,level:"Advanced",summary:"Lead curriculum, assessment, staff development and improvement through a small number of evidence-informed priorities and sustainable routines.",objectives:["Set a focused subject improvement agenda","Use curriculum and assessment evidence intelligently","Develop staff rather than only monitor them","Build sustainable departmental systems"],recommendedFor:["Department Lead","Aspiring leader","Curriculum Lead"],modules:[
  {id:"sl1",type:"content",title:"Subject leadership is instructional leadership",body:"Strong subject leaders connect curriculum design, teacher development, assessment and pupil outcomes. The role is not to generate paperwork or monitor everything equally. It is to identify a small number of important problems, clarify what good practice looks like, support staff to improve it and check whether the change is reaching pupils.",keyPoints:["Prioritise a few high-leverage issues","Use evidence from curriculum, work and pupil thinking","Make expectations specific","Provide modelling/resources/CPD","Follow up supportively","Stop low-value routines"]},
  {id:"sl2",type:"visual",title:"Subject improvement loop",layout:"cycle",items:[{heading:"Diagnose",text:"What is the real problem?",icon:"1"},{heading:"Specify",text:"What practice/outcome should improve?",icon:"2"},{heading:"Support",text:"What will staff need?",icon:"3"},{heading:"Implement",text:"How will routines become consistent?",icon:"4"},{heading:"Review",text:"What evidence shows progress?",icon:"5"}]},
  {id:"sl3",type:"scenario",title:"Too-many-priorities scenario",prompt:"A department plan contains twelve simultaneous teaching initiatives. What is the strongest leadership response?",options:[{label:"Add more monitoring forms",feedback:"More monitoring does not solve initiative overload."},{label:"Prioritise a small number of high-impact problems, pause lower-value initiatives and define support/implementation clearly",feedback:"Focus makes sustained improvement more realistic."},{label:"Ask every teacher to choose a completely different priority",feedback:"Some individualisation is useful, but whole-team coherence may be lost."}]},
  {id:"sl4",type:"checklist",title:"Department priority check",prompt:"Check one proposed priority before launching it.",items:["The problem is evidenced","The desired practice is specific","Staff understand why it matters","Resources/CPD are available","Implementation is manageable","Review evidence is defined","Something lower-value has been removed or deprioritised if needed"],completionText:"Subject-leadership priority check complete."},
  reflect("sl5","Which current departmental routine consumes time without giving you useful information about teaching or learning?")
 ]
},
{
 id:"effective-learning-walks",title:"Conducting Effective Learning Walks",category:"Leadership",duration:75,level:"Developing",summary:"Use focused, developmental learning walks to gather limited evidence about agreed school priorities without turning brief visits into high-stakes judgements of individual teachers.",objectives:["Set a narrow evidence focus","Avoid overclaiming from brief visits","Record descriptive evidence","Feed patterns into support and CPD"],recommendedFor:["Department Lead","CPD Lead","Leadership","Coach"],modules:[
  {id:"lw1",type:"content",title:"A learning walk is a sample, not a verdict",body:"A short visit can show what is happening at one moment, but it cannot establish the overall quality of a teacher or lesson. Effective learning walks use a specific focus, gather descriptive evidence across several contexts and look for patterns that can inform support, curriculum review or CPD.",keyPoints:["Define the question before visiting","Record what was seen/heard, not inferred motives","Avoid grading brief visits","Sample across classes/times","Triangulate with other evidence","Use findings to support improvement"]},
  {id:"lw2",type:"visual",title:"Evidence discipline",layout:"compare",items:[{heading:"Describe",text:"“Five pupils used the worked example before starting.”",icon:"✓"},{heading:"Avoid overclaiming",text:"“The teacher always scaffolds effectively.”",icon:"×"},{heading:"Pattern",text:"Combine several observations before drawing a school-level conclusion.",icon:"◎"},{heading:"Action",text:"Use patterns to shape CPD/support, not public ranking.",icon:"↗"}]},
  {id:"lw3",type:"scenario",title:"Five-minute visit",prompt:"A leader sees a quiet five minutes of independent work. What can they safely conclude?",options:[{label:"The teacher has excellent behaviour management overall",feedback:"A brief snapshot does not support such a broad conclusion."},{label:"During the observed five minutes, pupils were working quietly; wider conclusions need additional evidence",feedback:"This keeps the evidence descriptive and proportionate."},{label:"The lesson lacked interaction and was therefore weak",feedback:"The purpose and sequence of the lesson are unknown from the snapshot."}]},
  {id:"lw4",type:"activity",title:"Design a learning-walk focus",prompt:"Create a narrow developmental learning-walk question linked to a school/department priority.",instructions:["Write the priority.","Turn it into one observable question.","List three things observers may record.","Write one conclusion observers must not make from a short visit.","State how findings will feed into support/CPD."],placeholder:"Priority…\nQuestion…\nEvidence…\nDo not infer…\nFollow-up…",minimumCharacters:140},
  reflect("lw5","How can your learning-walk process make staff feel it is gathering evidence for improvement rather than searching for fault?")
 ]
},
{
 id:"developmental-lesson-feedback",title:"Giving Developmental Lesson Feedback",category:"Leadership",duration:70,level:"Developing",summary:"Turn observation evidence into a small, specific improvement step with modelling, rehearsal and follow-up rather than a long list of judgements.",objectives:["Separate evidence from evaluation","Prioritise one or two actionable steps","Use questioning and modelling","Plan follow-up practice"],recommendedFor:["Department Lead","Coach","CPD Lead","Leadership"],modules:[
  {id:"dlf1",type:"content",title:"Feedback should change practice",body:"Post-observation feedback is most useful when it identifies a specific pupil-learning problem, connects that problem to an observable teacher action and agrees a manageable next step. Lengthy lists of praise and criticism can leave the recipient unsure what to practise.",keyPoints:["Start from agreed focus/evidence","Ask for the teacher's interpretation","Prioritise a small action step","Model/rehearse where useful","Agree when the change will be reviewed"]},
  {id:"dlf2",type:"visual",title:"Feedback conversation",layout:"flow",items:[{heading:"Evidence",text:"What happened?",icon:"1"},{heading:"Interpret",text:"What did it mean for pupil learning?",icon:"2"},{heading:"Prioritise",text:"Which change matters most?",icon:"3"},{heading:"Practise",text:"Model/rehearse the action.",icon:"4"},{heading:"Follow up",text:"When will we review it?",icon:"5"}]},
  {id:"dlf3",type:"scenario",title:"Feedback overload",prompt:"An observer has twelve suggested improvements after one lesson. What is the strongest approach?",options:[{label:"Deliver all twelve so nothing is missed",feedback:"Too many actions can reduce implementation and confidence."},{label:"Identify the highest-leverage one or two actions, explain the evidence and plan follow-up",feedback:"Prioritised feedback is more likely to change practice."},{label:"Give only praise and avoid any development point",feedback:"Developmental feedback should still identify a useful next step."}]},
  {id:"dlf4",type:"activity",title:"Turn judgement into action",prompt:"Rewrite a vague observation judgement as specific developmental feedback.",instructions:["Write the vague judgement, e.g. 'questioning needs improvement'.","Add the observed evidence.","State the pupil-learning issue.","Write one specific teacher action.","Add a follow-up check."],placeholder:"Judgement…\nEvidence…\nLearning issue…\nAction…\nFollow-up…",minimumCharacters:120},
  reflect("dlf5","What would make observation feedback in your setting feel more like professional learning and less like a performance verdict?")
 ]
},
{
 id:"effective-department-meetings",title:"Effective Department Meetings",category:"Leadership",duration:60,level:"Developing",summary:"Reduce administrative meeting load and use team time for curriculum, teaching, assessment and professional problem-solving.",objectives:["Separate information-sharing from collaborative work","Use agendas with clear outcomes","Build teacher learning into meetings","Track actions without bureaucracy"],recommendedFor:["Department Lead","Aspiring leader"],modules:[
  {id:"dm1",type:"content",title:"Meetings should do work that email cannot",body:"If information can be read independently, a meeting is rarely the best place to read it aloud. High-value department meetings use shared time for decisions, curriculum planning, moderation, examining pupil work, rehearsal or solving instructional problems.",keyPoints:["Send routine notices asynchronously","State the decision/product required from each agenda item","Protect time for teaching/curriculum","Finish with owners and deadlines","Review recurring agenda items for value"]},
  {id:"dm2",type:"visual",title:"Meeting-value filter",layout:"flow",items:[{heading:"Inform?",text:"Could this be an email/document?",icon:"1"},{heading:"Discuss?",text:"Is collective judgement needed?",icon:"2"},{heading:"Create?",text:"Will the team produce something useful?",icon:"3"},{heading:"Practise?",text:"Can staff rehearse/moderate/learn together?",icon:"4"},{heading:"Act",text:"Who does what by when?",icon:"5"}]},
  {id:"dm3",type:"scenario",title:"Agenda scenario",prompt:"A 60-minute meeting has 18 information items and no time for curriculum discussion. What is the strongest redesign?",options:[{label:"Speak faster",feedback:"Speed does not change the low-value structure."},{label:"Move routine information to a written update and protect meeting time for decisions/teaching/curriculum work",feedback:"Shared time should be used for work requiring collaboration."},{label:"Extend every meeting to two hours",feedback:"Longer meetings do not automatically create more value."}]},
  {id:"dm4",type:"checklist",title:"Meeting audit",prompt:"Check your next agenda.",items:["Every item has a purpose/outcome","Routine notices have been removed where possible","At least one item improves curriculum/teaching/assessment","Discussion time is proportionate","Actions have clear owners","The meeting can finish on time"],completionText:"Meeting audit complete."},
  reflect("dm5","Which recurring department-meeting item could be moved out of the meeting to protect professional learning time?")
 ]
},
{
 id:"change-management-schools",title:"Change Management in Schools",category:"Leadership",duration:85,level:"Advanced",summary:"Implement school improvement through clear problems, manageable routines, staff support and review rather than repeated initiative launches.",objectives:["Diagnose implementation barriers","Build staff understanding and capability","Sequence change sustainably","Use implementation evidence to adapt"],recommendedFor:["Department Lead","CPD Lead","Leadership"],modules:[
  {id:"cm1",type:"content",title:"Implementation is not an announcement",body:"A new policy, curriculum or teaching strategy does not become embedded because it has been launched. Staff need clarity about the problem, the expected practice, why it matters, what support is available and how existing workload will change. Leaders should monitor implementation barriers as well as compliance.",keyPoints:["Define the problem before the solution","Reduce competing initiatives","Specify expected practice","Provide training/resources/rehearsal","Create feedback loops","Adapt implementation without abandoning the core aim"]},
  {id:"cm2",type:"visual",title:"Implementation stages",layout:"timeline",items:[{heading:"Explore",text:"Is this the right problem/approach?",icon:"1"},{heading:"Prepare",text:"Build clarity, capacity and resources.",icon:"2"},{heading:"Deliver",text:"Launch with support and manageable routines.",icon:"3"},{heading:"Embed",text:"Follow up, coach and remove barriers.",icon:"4"},{heading:"Sustain/review",text:"Keep what works and stop what does not.",icon:"5"}]},
  {id:"cm3",type:"scenario",title:"Initiative overload",prompt:"Staff are implementing several new systems inconsistently and report workload pressure. What is the strongest leadership move?",options:[{label:"Add another monitoring spreadsheet",feedback:"More monitoring may add workload without solving the implementation problem."},{label:"Prioritise the essential changes, pause lower-value work, clarify routines and provide targeted support",feedback:"Implementation improves when priorities and support are realistic."},{label:"Blame staff motivation",feedback:"Inconsistency may reflect unclear or overloaded implementation rather than motivation."}]},
  {id:"cm4",type:"activity",title:"Implementation plan",prompt:"Turn one proposed school/department change into an implementation sequence.",instructions:["Define the problem being solved.","Specify the key staff behaviour/routine.","List the support/resources needed.","Name one existing task that can be removed or simplified.","Set an implementation review measure."],placeholder:"Problem…\nRoutine…\nSupport…\nRemove…\nMeasure…",minimumCharacters:140},
  reflect("cm5","Which current initiative in your setting needs better implementation support rather than another reminder?")
 ]
},
{
 id:"staff-induction-school",title:"School Staff Induction Essentials",category:"Leadership",duration:90,level:"Foundation",summary:"Give new staff a structured introduction to safeguarding, behaviour, communication, IT, attendance, SEND, emergency procedures and professional expectations.",objectives:["Prioritise essential day-one information","Sequence induction over time","Check understanding rather than overload","Create clear routes for help"],recommendedFor:["New staff","ECT","Cover/Supply","Support staff","Leadership"],modules:[
  {id:"si1",type:"content",title:"Induction should reduce uncertainty",body:"New staff need critical safety and operational information immediately, but too much information on day one is easily forgotten. A strong induction distinguishes must-know-now procedures from information that can be revisited over the first weeks.",keyPoints:["Safeguarding and emergency routes first","Behaviour/attendance systems early","Approved communication and IT expectations","SEND/pupil information access","Named contacts for help","Planned follow-up rather than one-off briefing"]},
  {id:"si2",type:"visual",title:"Induction timeline",layout:"timeline",items:[{heading:"Before/Day 1",text:"Safeguarding, emergency, site access, conduct.",icon:"1"},{heading:"Week 1",text:"Behaviour, attendance, IT, routines, key contacts.",icon:"2"},{heading:"Weeks 2–4",text:"Curriculum, SEND, assessment, pastoral systems.",icon:"3"},{heading:"Half term",text:"Check confidence, gaps and support needs.",icon:"4"}]},
  {id:"si3",type:"checklist",title:"New-staff essentials",prompt:"Check the items every new staff member should be able to locate or explain.",items:["DSL/safeguarding reporting route","Emergency/fire/security procedures","Behaviour system","Attendance/register process","Approved communication systems","IT/cyber/data-protection expectations","SEND/pupil information route","First-aid arrangements","Who to contact for operational help"],completionText:"Induction essentials check complete."},
  {id:"si4",type:"activity",title:"Design a staged induction",prompt:"Create a simple induction sequence that avoids giving everything on day one.",instructions:["List the five must-know day-one items.","Choose the next five items for week one.","Set a follow-up check after two to four weeks.","Name the person/role responsible for each stage."],placeholder:"Day 1…\nWeek 1…\nFollow-up…\nOwners…",minimumCharacters:120},
  reflect("si5","Which important school procedure is currently learned by new staff only after something goes wrong?")
 ]
},
{
 id:"educational-visits-trip-safety",title:"Educational Visits & Trip Safety",category:"Safeguarding",duration:85,level:"Developing",summary:"Plan proportionate educational visits through clear purpose, supervision, safeguarding, medical/accessibility information, dynamic risk awareness and emergency arrangements.",objectives:["Distinguish routine and higher-planning visits","Use proportionate risk assessment","Plan supervision and safeguarding","Know emergency and communication arrangements"],recommendedFor:["Trip Lead","Teacher","Pastoral","Leadership"],modules:[
  {id:"ev1",type:"content",title:"Plan the visit around purpose and foreseeable risk",body:"Educational visits should have a clear educational purpose and proportionate planning. Routine visits may already be covered by school procedures, while activities or locations outside normal arrangements may need additional risk assessment and approval. Staff should follow the school's educational-visits policy and current DfE/local guidance.",keyPoints:["Use existing successful arrangements where appropriate","Identify significant foreseeable risks rather than every imaginable hazard","Plan supervision and meeting points","Include medical, SEND and accessibility needs","Know emergency contacts and escalation routes","Brief pupils and staff clearly"]},
  {id:"ev2",type:"visual",title:"Visit planning flow",layout:"flow",items:[{heading:"Purpose",text:"Why this visit and what will pupils do?",icon:"1"},{heading:"People",text:"Pupils, staffing, needs and supervision.",icon:"2"},{heading:"Place/activity",text:"Significant hazards and controls.",icon:"3"},{heading:"Emergency",text:"Contacts, meeting points and response plan.",icon:"4"},{heading:"Review",text:"Final changes/weather/attendance check.",icon:"5"}]},
  {id:"ev3",type:"scenario",title:"Last-minute change",prompt:"On arrival, part of the planned venue is closed and the group is offered an alternative activity not in the original plan. What is the strongest response?",options:[{label:"Accept automatically because the venue suggested it",feedback:"A new activity may change risks, supervision or accessibility."},{label:"Pause and dynamically assess whether the alternative fits school approval, supervision, pupil needs and risk controls before proceeding",feedback:"Material changes should be considered before the plan changes."},{label:"Let pupils choose individually",feedback:"The trip leader remains responsible for the school group's arrangements."}]},
  {id:"ev4",type:"checklist",title:"Pre-departure check",prompt:"Check the essentials before leaving school.",items:["Current register/headcount","Staff roles and supervision groups","Medical/medication arrangements","Emergency school/venue contacts","Travel/ticket arrangements","Meeting points and lost-pupil procedure","Accessibility/SEND adjustments","Weather/venue changes reviewed","Pupil briefing completed"],completionText:"Pre-departure visit check complete."},
  reflect("ev5","Which part of trip planning is most vulnerable to last-minute change, and what decision rule will help staff respond safely?")
 ]
},
{
 id:"first-aid-awareness-non-first-aiders",title:"First Aid Awareness for Non-First-Aiders",category:"Safeguarding",duration:45,level:"Foundation",summary:"Help all staff understand school first-aid arrangements, how to summon trained help and what information to provide without replacing certified first-aid training.",objectives:["Locate school first-aid arrangements","Know how to summon trained/emergency help","Protect the area and provide clear information","Understand role boundaries"],recommendedFor:["All staff"],modules:[
  {id:"fa1",type:"content",title:"Awareness is not first-aid certification",body:"All staff should know who the appointed first aiders are, how to contact them, where first-aid arrangements are located and how to call emergency services according to school procedures. This course does not teach clinical treatment and does not replace recognised first-aid training.",keyPoints:["Know the school's first-aid contact route","Get trained help promptly","Follow emergency procedures","Give clear location and incident information","Do not exceed your training","Record/report incidents through school systems"]},
  {id:"fa2",type:"visual",title:"Non-first-aider response",layout:"flow",items:[{heading:"Make area safe",text:"Avoid creating additional risk.",icon:"1"},{heading:"Call trained help",text:"Use school first-aid/emergency route.",icon:"2"},{heading:"Give clear information",text:"Location, person involved and what happened.",icon:"3"},{heading:"Follow instructions",text:"Support trained staff/emergency services.",icon:"4"},{heading:"Report",text:"Complete school incident procedures.",icon:"5"}]},
  {id:"fa3",type:"scenario",title:"Playground scenario",prompt:"A pupil becomes unwell and you are not first-aid trained. What should you prioritise?",options:[{label:"Attempt procedures you have not been trained to perform",feedback:"Staff should not exceed their training."},{label:"Summon the school's trained first-aid help promptly, keep the area safe and provide clear information",feedback:"This fits the role of a non-first-aider."},{label:"Leave the pupil alone while you finish another task",feedback:"A pupil needing help should not be abandoned."}]},
  {id:"fa4",type:"checklist",title:"Know your arrangements",prompt:"Check that you can answer these questions for your school/site.",items:["How do I contact a first aider?","Where is the nearest first-aid point/equipment?","How do I call emergency services from this site?","Who meets/directs emergency services?","How do I report an incident afterwards?","What changes on an off-site visit?"],completionText:"First-aid awareness check complete."},
  reflect("fa5","Which first-aid arrangement at your school would you need to locate faster in an emergency?")
 ]
},
{
 id:"science-laboratory-safety-awareness",title:"Science & Laboratory Safety Awareness",category:"Safeguarding",duration:70,level:"Developing",summary:"Strengthen safe science routines, risk-assessment awareness, supervision and incident response while keeping detailed hazardous-procedure guidance within approved school/CLEAPSS resources.",objectives:["Use approved risk assessments and practical procedures","Maintain safe supervision and routines","Know equipment/PPE expectations","Respond to incidents through school procedures"],recommendedFor:["Science Teacher","Science Technician","Cover/Supply","Leadership"],modules:[
  {id:"lab1",type:"content",title:"Use approved practical guidance",body:"Science practical work should follow the school's health-and-safety policy, approved risk assessments and specialist guidance such as the resources adopted by the school. Staff should not improvise hazardous procedures or substitute materials/equipment without considering how the change affects risk.",keyPoints:["Check the current approved practical/risk assessment","Brief pupils on significant controls","Use required PPE and safety equipment","Maintain appropriate supervision","Stop practical work if conditions change materially","Report incidents and near misses"]},
  {id:"lab2",type:"visual",title:"Safe practical cycle",layout:"flow",items:[{heading:"Plan",text:"Approved procedure and risk controls.",icon:"1"},{heading:"Prepare",text:"Room, equipment and PPE ready.",icon:"2"},{heading:"Brief",text:"Pupils know significant hazards/controls.",icon:"3"},{heading:"Supervise",text:"Monitor technique and changing conditions.",icon:"4"},{heading:"Close",text:"Safe shutdown, disposal and incident review.",icon:"5"}]},
  {id:"lab3",type:"scenario",title:"Unexpected substitution",prompt:"A planned practical resource is unavailable and someone suggests substituting another material/equipment setup that has not been checked. What is the strongest response?",options:[{label:"Use it immediately because the lesson has started",feedback:"Changes can alter risk and should not be improvised without appropriate assessment."},{label:"Pause and use approved guidance/risk assessment or choose a safe alternative activity",feedback:"Practical changes should remain within authorised safety arrangements."},{label:"Ask pupils to decide whether it seems safe",feedback:"Safety decisions remain a staff responsibility."}]},
  {id:"lab4",type:"checklist",title:"Practical readiness",prompt:"Check the preparation before a practical lesson.",items:["Approved procedure/risk assessment checked","Required PPE/safety equipment available","Equipment is suitable and in good condition","Pupil briefing points identified","Supervision/room layout is appropriate","Emergency/incident arrangements are known","Clear stop/cleanup procedure is planned"],completionText:"Science practical readiness check complete."},
  reflect("lab5","Which practical routine in your department most depends on pupils following a procedure consistently, and how is that routine explicitly taught?")
 ]
},
{
 id:"pe-safety-awareness",title:"PE & Physical Activity Safety Awareness",category:"Safeguarding",duration:60,level:"Developing",summary:"Use proportionate planning, equipment/space checks, progressive instruction and emergency arrangements to support safe participation in PE and school sport.",objectives:["Identify significant activity/environment risks","Use progressive teaching and supervision","Check equipment and spaces","Plan for medical needs and emergencies"],recommendedFor:["PE Teacher","Sports Coach","Cover/Supply","Leadership"],modules:[
  {id:"pe1",type:"content",title:"Safe participation is planned",body:"PE safety depends on the activity, environment, pupil needs, equipment and level of supervision. Staff should use school/subject policies, recognised governing-body guidance where applicable and approved risk assessments. Challenge can be progressive without exposing pupils to avoidable risk.",keyPoints:["Check space/surface/equipment","Know medical and SEND needs relevant to participation","Teach technique progressively","Maintain appropriate supervision","Adapt for environmental conditions","Know emergency and first-aid arrangements"]},
  {id:"pe2",type:"visual",title:"Activity readiness",layout:"flow",items:[{heading:"Environment",text:"Space, surface, weather and boundaries.",icon:"1"},{heading:"Equipment",text:"Condition and suitability.",icon:"2"},{heading:"Pupils",text:"Readiness, needs and grouping.",icon:"3"},{heading:"Instruction",text:"Progression and technique.",icon:"4"},{heading:"Emergency",text:"First aid and communication route.",icon:"5"}]},
  {id:"pe3",type:"scenario",title:"Environment change",prompt:"An outdoor surface becomes unsuitable during a lesson. What is the strongest response?",options:[{label:"Continue because the activity has already started",feedback:"Conditions should be reassessed when they change."},{label:"Pause, reassess the activity/environment and adapt or stop according to school guidance",feedback:"Dynamic risk awareness is part of safe supervision."},{label:"Let pupils decide individually whether to continue",feedback:"Staff retain responsibility for the school activity."}]},
  {id:"pe4",type:"checklist",title:"PE readiness check",prompt:"Check one activity before starting.",items:["Space/surface checked","Equipment checked","Medical/SEND information considered","Progression/instruction planned","Supervision/grouping appropriate","Environmental conditions checked","First-aid/emergency route known"],completionText:"PE readiness check complete."},
  reflect("pe5","Which environmental or supervision check should become a visible routine before your most common practical activity?")
 ]
},
{
 id:"dt-workshop-safety-awareness",title:"Design & Technology Workshop Safety Awareness",category:"Safeguarding",duration:70,level:"Developing",summary:"Build safe workshop routines around authorised equipment, supervision, PPE, machine/tool controls and incident reporting without replacing specialist competency training.",objectives:["Use authorised equipment and procedures","Maintain workshop supervision and access control","Understand PPE/guarding expectations","Know stop-work and incident arrangements"],recommendedFor:["D&T Teacher","Technician","Cover/Supply","Leadership"],modules:[
  {id:"dt1",type:"content",title:"Competence and authorisation come first",body:"Workshop equipment and processes should be used only where staff/pupils have the required training, authorisation and supervision under school procedures. This awareness course does not teach machine operation. Approved department risk assessments, manufacturer instructions and specialist training govern detailed use.",keyPoints:["Use only authorised equipment/processes","Check guarding/safety controls according to department procedure","Use required PPE","Maintain clear zones and supervision","Stop work when equipment/conditions are unsafe","Report faults and incidents promptly"]},
  {id:"dt2",type:"visual",title:"Workshop safety system",layout:"flow",items:[{heading:"Authorise",text:"Right person, training and supervision.",icon:"1"},{heading:"Inspect",text:"Workspace/equipment ready under procedure.",icon:"2"},{heading:"Brief",text:"Task-specific controls understood.",icon:"3"},{heading:"Supervise",text:"Safe zones and behaviour maintained.",icon:"4"},{heading:"Stop/report",text:"Faults or unsafe conditions acted on promptly.",icon:"5"}]},
  {id:"dt3",type:"scenario",title:"Equipment fault",prompt:"A piece of workshop equipment behaves unexpectedly during a lesson. What is the strongest response?",options:[{label:"Keep using it carefully until the lesson ends",feedback:"Unexpected equipment behaviour should not be ignored."},{label:"Stop use, secure/isolate it according to department procedure and report the fault",feedback:"Faulty equipment should be taken out of use through the authorised process."},{label:"Ask a pupil who knows the machine well to repair it",feedback:"Repairs should follow authorised competent procedures."}]},
  {id:"dt4",type:"checklist",title:"Workshop readiness",prompt:"Check the workshop before a practical session.",items:["Only authorised processes/equipment are planned","Workspace and access routes are clear","Required PPE is available","Equipment checks are complete under department procedure","Pupils understand task-specific controls","Supervision/positioning is planned","Fault/emergency reporting route is known"],completionText:"Workshop readiness check complete."},
  reflect("dt5","Which workshop routine would be safer if it became an explicit pupil checklist rather than an assumed habit?")
 ]
}
];
