import type { Course } from "./data";

type Brief = {
  id: string; parent: string; title: string; category: Course["category"]; minutes: 15 | 20;
  goal: string; read: string; case: string; choices: string[]; answer: number;
  feedback: string; question: string; options: string[]; correct: number;
  task: string; checklist: string[];
};

export const shortCourseBriefs: Brief[] = [
  { id: "short-safeguarding-disclosures", parent: "safeguarding-essentials", title: "Safeguarding: Responding to a Disclosure", category: "Safeguarding", minutes: 20,
    goal: "Listen safely and locate your school's current reporting route",
    read: "A disclosure may arrive in an ordinary conversation rather than a planned meeting. Your first task is to give the pupil a calm response and keep the safeguarding boundary clear. Listen without trying to establish a complete account yourself. Do not promise secrecy. Explain that you may need to share information with the people responsible for helping keep them safe. Use the current school safeguarding procedure, including its arrangements when the usual contact is unavailable. This short course is a rehearsal of your staff response, not a substitute for required safeguarding training or the current policy.",
    case: "A pupil starts to describe a worrying event, then says, 'Please don't tell anyone.' You have a lesson starting shortly. What should you do?",
    choices: ["Promise secrecy and ask for a full account", "Listen calmly, explain the sharing boundary and use the current safeguarding route promptly", "Wait for the pupil to repeat the concern tomorrow"], answer: 1,
    feedback: "A calm response and the proper reporting route protect the pupil without turning staff into investigators. The timetable is not a reason to set the concern aside.",
    question: "What should you check before you need to report a concern?", options: ["Which colleague is most curious", "Whether you can prove the concern", "The current reporting route and unavailable-contact arrangements"], correct: 2,
    task: "Write a fictional two-sentence response to a pupil and identify where you would find the current reporting procedure. Do not enter pupil details.", checklist: ["Locate the current safeguarding policy", "Identify the DSL/deputy route and alternative arrangements", "Rehearse a response that does not promise secrecy"] },
  { id: "short-factual-records", parent: "safeguarding-essentials", title: "Safeguarding: Factual Recording", category: "Safeguarding", minutes: 15,
    goal: "Separate a factual account from an interpretation",
    read: "A useful record lets the designated process understand the information you actually received. Preserve relevant timing, context and the source of the information. Distinguish direct observations and words from your interpretation. 'The pupil said they did not want to go home' is different from a conclusion about why. Do not build a private investigation or circulate the account informally. Use the school's approved recording and reporting system. A short, accurate account is more useful than a confident theory unsupported by what was observed.",
    case: "A fictional pupil says, 'I don't want to go home today.' Which opening note is most useful?",
    choices: ["The pupil said those words; record when, where and what you observed", "The family is clearly unsafe", "The pupil probably wants attention"], answer: 0,
    feedback: "The first note preserves the information. The other notes turn assumptions into facts. Record and report through current procedure rather than deciding the cause yourself.",
    question: "Which detail is an interpretation rather than a direct observation?", options: ["The conversation was at lunchtime", "The pupil was manipulating the adult", "The pupil said they felt worried"], correct: 1,
    task: "Rewrite 'The pupil was obviously lying because they wanted attention' as a factual record, using invented observations and explicitly labelling anything you cannot establish.", checklist: ["Facts and source are clear", "Relevant timing and context are recorded", "Assumptions are not presented as evidence"] },
  { id: "short-online-safety", parent: "online-safety", title: "Online Safety: Receiving a Concern", category: "Safeguarding", minutes: 20,
    goal: "Respond to an online concern without widening its circulation",
    read: "An online concern is still a concern about a pupil's safety and experience. Listen to the report and follow the school's safeguarding and online-safety arrangements. Do not ask pupils to forward concerning material around the staff team or put it into training notes. Evidence handling depends on the material and current procedure; get appropriate guidance rather than improvising. Separate what the pupil reported from what you have personally seen. Your role is a safe response and appropriate escalation, not a private search for the people involved.",
    case: "A pupil reports harmful messages in a group chat and offers to send screenshots to your personal phone. What is the strongest response?",
    choices: ["Ask the whole class to forward their screenshots", "Post the screenshots in the staff group", "Listen, avoid personal-device circulation and follow the approved reporting/evidence route"], answer: 2,
    feedback: "The approved process can guide appropriate handling. Wider or personal-device circulation can create further harm and privacy problems.",
    question: "What should an initial note distinguish?", options: ["What was reported and what you personally observed", "Popular and unpopular pupils", "Which app you dislike"], correct: 0,
    task: "Rehearse what you would say to the pupil and list the school procedure you would consult before handling any material.", checklist: ["Listen without blame", "Avoid unnecessary copying or circulation", "Use the current safeguarding/online-safety route"] },
  { id: "short-classroom-safety", parent: "health-safety-essentials-schools", title: "Health & Safety: A Classroom Risk Check", category: "Safeguarding", minutes: 20,
    goal: "Notice a real hazard and choose a proportionate response",
    read: "A classroom check should focus on real risks, not paperwork for its own sake. Look at the activity and the space people will use: access routes, equipment condition, storage and the needs of those present. Use existing school arrangements rather than inventing a parallel system. Specialist activities need the relevant risk assessment, equipment checks and trained guidance. If you cannot make an activity safe within your role and competence, pause it and seek the appropriate support. A tidy-looking room is not proof that every activity is safe.",
    case: "A cable crosses the route pupils use to reach equipment. The lesson is ready to start. What is the proportionate response?",
    choices: ["Tell pupils not to trip and start", "Remove or control the hazard safely, or pause the affected activity and report it through the school route", "Ignore it because nobody has fallen yet"], answer: 1,
    feedback: "Manage the actual hazard rather than relying on a warning. Use competent support if resolving it exceeds your role.",
    question: "When does a specialist practical activity need more than an ordinary classroom check?", options: ["Only after an accident", "Never if pupils are supervised", "When its equipment, substances or activity create specific risks"], correct: 2,
    task: "Describe an invented classroom hazard, who might be affected, the immediate control and who would review any unresolved risk.", checklist: ["Identify a specific hazard", "Choose a proportionate control within your competence", "Use the school's reporting and review arrangements"] },
  { id: "short-evacuation", parent: "fire-safety-emergency-evacuation", title: "Fire Safety: Know Your Evacuation Role", category: "Safeguarding", minutes: 15,
    goal: "Locate and rehearse your site-specific emergency responsibilities",
    read: "Emergency routines must come from the current arrangements for your site, not a generic diagram. Before an incident, know the alarm response, routes, assembly and accounting arrangements relevant to your role. Check how assistance for people who need it is planned. Do not improvise a firefighting role or return to an affected area to retrieve belongings. Use the school's trained and designated roles. This awareness refresher does not provide specialist fire-response training.",
    case: "You are covering in an unfamiliar room. Before pupils arrive, what should you prioritise?",
    choices: ["Check the site's evacuation instructions, routes and your accounting/assistance responsibilities", "Assume the route matches your usual classroom", "Wait for an alarm to ask pupils what normally happens"], answer: 0,
    feedback: "A cover arrangement should include the local emergency routine. Familiarise yourself before it is needed and ask for clarification where uncertain.",
    question: "Which information should direct an evacuation response?", options: ["A remembered routine from another school", "The current site-specific emergency arrangements", "The shortest-looking route regardless of instructions"], correct: 1,
    task: "Make a three-item induction question list for an unfamiliar room: route, accounting and planned assistance. Use no real personal details.", checklist: ["Know the local alarm response", "Know assembly/accounting arrangements", "Clarify your role in planned assistance"] },
  { id: "short-near-miss", parent: "accident-near-miss-riddor-awareness", title: "Safety: Reporting a Near Miss", category: "Safeguarding", minutes: 15,
    goal: "Capture a near miss so the risk can be reviewed",
    read: "A near miss can reveal a risk before someone is injured. Make the immediate situation safe within your role, get appropriate help, and use the school's incident-reporting arrangements. A useful report describes the event, conditions, timing and action taken without blaming or guessing. The appropriate designated person decides external reporting requirements; this course does not train staff to make specialist reporting decisions. A report should lead to learning about controls, not just a completed form.",
    case: "A shelf item falls beside a pupil without causing injury. What should follow the immediate safe response?",
    choices: ["Leave it unreported because nobody was hurt", "Wait for a second event", "Record and report the near miss, including the conditions and immediate action"], answer: 2,
    feedback: "The event gives useful risk information even without injury. Use the approved route so appropriate staff can review the controls.",
    question: "What makes a near-miss report useful?", options: ["A factual account and conditions that can inform prevention", "A guess about who deserves blame", "Only the fact that no one was injured"], correct: 0,
    task: "Write a fictional near-miss report in four lines: event, conditions, action and review needed.", checklist: ["Immediate safety addressed", "Event and context recorded factually", "Report reaches the designated school process"] },
  { id: "short-medical-plans", parent: "medical-conditions-schools", title: "Medical Conditions: Know the Agreed Plan", category: "Safeguarding", minutes: 20,
    goal: "Find the current support plan and recognise your role boundary",
    read: "Medical support should follow the pupil's current agreed plan and school procedures. Staff need to know what is relevant to their role, who is trained and what to do when help is needed. Do not infer treatment from a diagnosis, improvise medication arrangements or rely on an old message instead of current information. If instructions are unclear, obtain authorised clarification before taking on the task. Keep information on a need-to-know basis. This course provides awareness and planning practice, not medical advice or competency training.",
    case: "A colleague asks you to perform a medical-support task you have not been trained for, using instructions remembered from last term. What should you do?",
    choices: ["Copy what they remember", "Seek the current plan and the appropriate trained/authorised support rather than improvise", "Ask another pupil what usually happens"], answer: 1,
    feedback: "Current arrangements and appropriate competence matter. Use the school's support and emergency routes rather than inventing treatment.",
    question: "Which source should guide a pupil-specific medical-support routine?", options: ["A generic online checklist", "A colleague's memory", "The current agreed plan and school procedure"], correct: 2,
    task: "List three questions you would clarify before supervising an activity: relevant plan, trained support and emergency arrangements. Do not include pupil medical information.", checklist: ["Current plan available to appropriate staff", "Roles and training requirements clear", "Know where to obtain urgent help under school procedure"] },
  { id: "short-allergy-awareness", parent: "allergy-safety-schools-2026", title: "Allergy Safety: Plan Before the Activity", category: "Safeguarding", minutes: 20,
    goal: "Check allergy-related arrangements before changing an activity",
    read: "Changes to food, equipment, visitors or a trip can change the context of an agreed allergy plan. Check current arrangements with the appropriate school staff before the activity, including who is trained and how help will be obtained. Do not assume a small amount, previous tolerance or removal of a visible ingredient makes an exposure safe. This awareness course does not prescribe treatment or replace a pupil-specific plan, staff training or current emergency procedures. Keep any example in your CPD record fictional.",
    case: "A visitor adds an unplanned food-tasting activity. What is the strongest first move?",
    choices: ["Pause the change and check the current risk/support arrangements with appropriate school staff", "Proceed because only a small sample is offered", "Ask pupils to decide whether it is safe"], answer: 0,
    feedback: "An unplanned activity needs the appropriate checks. Do not substitute guesswork or pupil judgement for the agreed safety arrangements.",
    question: "What should happen when an activity changes?", options: ["Assume the old arrangements cover every change", "Check whether current plans and controls still fit", "Remove one visible ingredient and proceed"], correct: 1,
    task: "Create a fictional pre-activity check covering the change, the authorised information source and the trained/emergency support arrangements.", checklist: ["Check changes before proceeding", "Consult authorised current information", "Know the trained support and emergency route"] },
  { id: "short-school-security", parent: "school-security-emergency-awareness", title: "School Security: Responding to an Unfamiliar Visitor", category: "Safeguarding", minutes: 15,
    goal: "Use the site's visitor and security process safely",
    read: "A site-security concern should be handled through the school's current procedures. Know how visitors are expected to enter, identify themselves and obtain authorisation, and how staff summon help. Do not treat familiarity, confidence or an explanation as proof of authorisation. Equally, do not create a confrontation or leave supervised pupils to investigate. The appropriate response depends on the situation and the site's emergency arrangements. This course is awareness practice, not tactical security training.",
    case: "An unfamiliar adult asks you to let them through a controlled entrance because they are late. What should guide your response?",
    choices: ["Their confident manner", "Their promise that someone knows them", "The site's visitor/authorisation process and safe route to appropriate staff"], answer: 2,
    feedback: "Follow the approved access arrangements. Seek designated support without improvising a confrontation or bypassing controls.",
    question: "What establishes a visitor's authorisation?", options: ["The school's approved verification process", "Being in a hurry", "Knowing a member of staff's name"], correct: 0,
    task: "Rehearse a polite boundary statement and identify how you would contact the appropriate staff without leaving pupils unsupervised.", checklist: ["Know the visitor process", "Do not bypass access controls", "Know how to request designated help safely"] },
  { id: "short-data-handling", parent: "school-data-protection-gdpr", title: "Data Protection: Share Only What Is Needed", category: "Digital Teaching", minutes: 15,
    goal: "Check purpose, recipient and approved channel before sharing",
    read: "Before sharing staff or pupil information, ask why it is needed, who is authorised to receive it and which school-approved channel should be used. Removing a name may not remove identification if other details still point to a person. Avoid copying identifiable material into CPD notes or unapproved tools. If a possible data incident happens, use the school's reporting process promptly rather than quietly trying to hide or repair it alone. This refresher supports safe routines; it is not a legal assessment of every disclosure.",
    case: "You want feedback on a support plan from an unapproved online tool. You have removed the pupil's name but left distinctive details. What should you do?",
    choices: ["Upload it because the name is gone", "Use approved arrangements and a genuinely fictional/general example instead", "Add more details to improve the answer"], answer: 1,
    feedback: "A person may still be identifiable. Use approved data arrangements and avoid exposing unnecessary information.",
    question: "What should you check before sharing school information?", options: ["Whether the message is short", "Whether the recipient is friendly", "Purpose, authorised recipient, minimum information and approved channel"], correct: 2,
    task: "Turn an invented pupil-specific request into a general question that needs no personal data. Explain what you removed and why.", checklist: ["Purpose and recipient authorised", "Only necessary information used", "Approved channel and incident route known"] },
  { id: "short-adaptive-teaching", parent: "adaptive-teaching", title: "Adaptive Teaching: Remove One Barrier", category: "Teaching & Learning", minutes: 20,
    goal: "Choose and review a scaffold without lowering the learning goal",
    read: "Start with what the pupil understands and what the task asks them to do. A pupil may explain an idea but struggle to organise the written response. Choose a small scaffold that addresses that barrier, such as a visible sequence or a vocabulary prompt, while preserving the intended thinking. Look for accuracy and independence, not completion alone. Review the support: keep it if useful, adjust it if it misses the barrier and fade it when the pupil can manage without it.",
    case: "A pupil explains the science accurately but cannot organise a written explanation. Which first adaptation best fits that evidence?",
    choices: ["A short explanation structure linked to the same learning goal", "A different, easier topic", "An adult writes the answer"], answer: 0,
    feedback: "The scaffold addresses organisation while retaining the pupil's reasoning. Check whether it supports increasingly independent explanations.",
    question: "Which review evidence is strongest?", options: ["The page looks neat", "Accuracy and independence as well as completion", "The adult stayed beside the pupil"], correct: 1,
    task: "Name an invented task barrier, design a small scaffold and state the evidence that would justify fading it.", checklist: ["Barrier identified", "Learning goal retained", "Review accuracy and independence"] },
  { id: "short-calm-responses", parent: "de-escalation", title: "Behaviour: Rehearse a Calm Response", category: "Teaching & Learning", minutes: 20,
    goal: "Use a brief, predictable response within the school behaviour policy",
    read: "A calm response is a professional routine, not a guarantee that a situation will immediately settle. Use the school's agreed behaviour and safety arrangements. Keep language brief and clear, avoid a public argument and offer the appropriate next step. Consider the situation, known support needs and when designated help is required. Do not invent restraint or other specialist techniques from a training example. After the event, review what happened and plan follow-up through the proper school route.",
    case: "A pupil refuses a task loudly in front of peers. There is no immediate danger in this fictional example. Which first response best avoids a public argument?",
    choices: ["Debate every accusation in front of the class", "Raise your voice to match theirs", "Use a brief calm instruction and the agreed next step, seeking support as appropriate"], answer: 2,
    feedback: "A brief predictable response avoids feeding a public confrontation. Apply the current policy and safety arrangements; the example cannot determine every real situation.",
    question: "What should guide your response and escalation?", options: ["Current school policy, the context and agreed support/safety arrangements", "Winning the argument", "A technique copied from social media"], correct: 0,
    task: "Write a calm opening line, an agreed next-step prompt and the point at which you would request designated support.", checklist: ["Brief clear language", "Appropriate policy-based next step", "Follow-up and support route identified"] },
  { id: "short-retrieval", parent: "retrieval-practice", title: "Retrieval: Questions Worth Answering", category: "Teaching & Learning", minutes: 15,
    goal: "Write a retrieval prompt that requires recall before feedback",
    read: "Retrieval needs an attempt to bring knowledge to mind. A card labelled 'Key idea 1' gives no clear task, while immediately revealing the back removes the recall attempt. Write an answerable question tied to important knowledge. Ask pupils to respond before they check; then make the correction useful. Include older as well as recent knowledge where appropriate. Keep the routine low stakes and use errors to decide what needs another explanation or practice opportunity.",
    case: "Pupils flip each flashcard without attempting an answer. What useful change would you make?",
    choices: ["Add decorative icons", "Require a brief spoken or written answer before reveal, then correct errors", "Make the back visible at all times"], answer: 1,
    feedback: "The answer attempt turns viewing into retrieval. Prompt design and feedback matter more than card appearance.",
    question: "Which card front gives a usable retrieval task?", options: ["Objective 2", "Important idea", "What makes this task retrieval rather than rereading?"], correct: 2,
    task: "Write three answerable questions for an invented lesson, each with an answer and a correction for one likely error.", checklist: ["Question is explicit", "Answer attempt comes before reveal", "Feedback corrects an important error"] },
  { id: "short-understanding-check", parent: "checking-for-understanding", title: "Assessment: Check Everyone's Thinking", category: "Teaching & Learning", minutes: 20,
    goal: "Use a check whose result changes the next teaching move",
    read: "A useful understanding check is designed before you ask it. Choose a question that distinguishes an important misconception from secure reasoning. Use an accessible routine that gives you evidence from more than the quickest volunteers. Decide what pattern would lead you to reteach, model a step or move on. Participation alone is not the same as understanding: consider what the responses show about the idea. Keep the check focused enough to interpret and act on.",
    case: "Two confident volunteers answer correctly, while you have no responses from the rest of the class. What would improve your next decision?",
    choices: ["Use an accessible whole-class response to a diagnostic question and inspect the pattern", "Assume the class is secure", "Ask the same volunteers to explain again"], answer: 0,
    feedback: "Broader responses reduce the risk of deciding from a small, unrepresentative sample. The next step should respond to what the answers reveal.",
    question: "What should you plan alongside a hinge question?", options: ["Which pupil is most confident", "How different response patterns will change your next move", "How to collect scores without looking at answers"], correct: 1,
    task: "Create a question with one plausible misconception and write your next move for secure, mixed and mostly incorrect responses.", checklist: ["Important idea tested", "Accessible participation planned", "Next response linked to evidence"] },
  { id: "short-workload", parent: "staff-wellbeing", title: "Workload: One Sustainable Routine", category: "Wellbeing", minutes: 15,
    goal: "Test one workload change without shifting the burden to someone else",
    read: "A workload improvement needs a specific problem. Identify a recurring task, who needs its output and what value it provides. Consider simplifying, sharing or stopping low-value duplication through the appropriate team agreement. Check that a change does not simply move the work to a colleague or remove important support. Trial a small change and review time, quality and team experience. Personal efficiency can help, but it cannot resolve every structural issue; use the appropriate leadership or support route where needed.",
    case: "The team copies identical information into two tracking sheets. What is a useful first step?",
    choices: ["Ask the newest colleague to do both", "Work faster at home", "Clarify who uses each output and agree a small trial to remove unnecessary duplication"], answer: 2,
    feedback: "Start with purpose and an agreed trial. Check the information still reaches those who need it and that workload is not simply transferred.",
    question: "What should a workload trial review?", options: ["Time saved, output quality and effects on others", "Only how fast one person works", "Whether the new routine looks impressive"], correct: 0,
    task: "Describe one fictional duplicated task, a team-agreed change and the evidence you would review after a short trial.", checklist: ["Problem and purpose clear", "Change agreed through the right route", "Time, quality and impact on others reviewed"] },
];

export const shortCourseParents = Object.fromEntries(shortCourseBriefs.map(b => [b.id, b.parent]));
export const SHORT_COURSE_BOUNDARY = "Focused awareness/practice only. Follow current school policy and pupil-specific plans; this is not statutory, specialist or competency training. Never enter real pupil or confidential staff information.";

export const shortCourses: Course[] = shortCourseBriefs.map(b => ({
  id: b.id, title: b.title, category: b.category, duration: b.minutes, level: "Foundation",
  summary: b.goal + ". A linked, focused short course.", objectives: [b.goal, "Choose a proportionate response in a fictional situation", "Identify one policy-aligned action for practice"], recommendedFor: ["All staff"],
  modules: [
    { id: b.id + "-read", type: "content", title: "The idea and its boundary", body: b.read + "\n\n" + SHORT_COURSE_BOUNDARY, keyPoints: b.checklist },
    { id: b.id + "-check", type: "quiz", title: "Retrieve the key idea", question: b.question, options: b.options, answer: b.correct, feedback: b.feedback },
    { id: b.id + "-case", type: "scenario", title: "Choose a response", prompt: b.case, options: b.choices.map((label, i) => ({ label, feedback: i === b.answer ? b.feedback : "Compare this with the agreed principle: " + b.feedback })) },
    { id: b.id + "-rehearse", type: "activity", title: "Rehearse your next move", prompt: b.task, instructions: ["Use an invented or general context, not personal information.", "Explain your action and why it fits the evidence.", "Identify a policy, plan or review step that would guide real practice."], minimumCharacters: 40 },
    { id: b.id + "-review", type: "checklist", title: "Before you use it", prompt: "Review these steps and confirm you know how to apply them in your role.", items: b.checklist },
    { id: b.id + "-exit", type: "quiz", title: "Exit decision", question: b.case + " Which response best follows the principle?", options: b.choices, answer: b.answer, feedback: b.feedback },
    { id: b.id + "-commit", type: "reflection", title: "One practical commitment", prompt: "Name one specific action from this course, when you will use it and what you will check. Keep the example fictional or general." },
  ],
}));

export const shortCourseBudgets = (minutes: number) => minutes === 15 ? [3, 1, 2, 4, 1, 1, 3] : [4, 2, 3, 5, 1, 2, 3];

