export type SubjectCpdProfile = {
  id: string;
  title: string;
  audience: string;
  questioning: string;
  modelling: string;
  retrieval: string;
  feedback: string;
  application: string;
  recommendedCourseIds: string[];
};

export const subjectCpdProfiles: SubjectCpdProfile[] = [
  { id:"science", title:"Science", audience:"Science teachers and technicians supporting learning", questioning:"Use diagnostic questions that separate common misconceptions, then require every pupil to commit to an answer before discussion.", modelling:"Model scientific reasoning explicitly: identify variables, choose a relationship, substitute with units, then evaluate whether the result is physically sensible.", retrieval:"Mix equations, definitions, practical-method decisions and older prerequisite knowledge rather than retrieving only last lesson's facts.", feedback:"Comment on the scientific decision or reasoning step that will improve the next response, not simply presentation or effort.", application:"Choose one upcoming practical or calculation and identify the exact misconception you want a hinge question to expose.", recommendedCourseIds:["effective-questioning","checking-for-understanding","worked-examples-modelling","retrieval-practice","effective-feedback"] },
  { id:"mathematics", title:"Mathematics", audience:"Mathematics teachers", questioning:"Use carefully selected examples and non-examples to reveal whether pupils understand the mathematical structure rather than a memorised procedure.", modelling:"Think aloud through decisions between steps, including why a representation or operation is appropriate before carrying out the calculation.", retrieval:"Retrieve foundational facts and procedures that reduce working-memory demand in the new problem, then connect them to mixed problem types.", feedback:"Identify the first incorrect mathematical decision and prompt a correction that preserves as much pupil thinking as possible.", application:"Take one worked example and mark where you will pause, question and fade support before independent practice.", recommendedCourseIds:["worked-examples-modelling","checking-for-understanding","effective-explanations","retrieval-practice","cognitive-load-theory"] },
  { id:"english", title:"English", audience:"English and literacy teachers", questioning:"Move from comprehension to interpretation by asking pupils to justify claims with precise textual evidence and compare plausible readings.", modelling:"Model the invisible decisions behind analytical or creative writing, including selecting evidence, shaping a sentence and revising for effect.", retrieval:"Retrieve vocabulary, quotations, genre conventions and prior conceptual knowledge before asking pupils to use them in a new interpretation.", feedback:"Give a small, transferable writing target that can be applied in the next paragraph rather than correcting every weakness at once.", application:"Select one paragraph task and create a model that exposes the decisions an expert writer makes at each stage.", recommendedCourseIds:["disciplinary-literacy","effective-questioning","worked-examples-modelling","effective-feedback","metacognition-self-regulation"] },
  { id:"humanities", title:"Humanities", audience:"History, geography and related humanities teachers", questioning:"Use questions that distinguish factual recall from causal, comparative and evaluative reasoning, then probe the evidence behind claims.", modelling:"Show how an expert moves from sources or data to a supported conclusion, making disciplinary criteria visible.", retrieval:"Combine key factual knowledge with chronology, location, concepts and previously studied case examples that support current reasoning.", feedback:"Focus feedback on how evidence is selected, connected and evaluated within the discipline.", application:"Choose one extended-response question and map the evidence pupils need before they can make the required disciplinary judgement.", recommendedCourseIds:["disciplinary-literacy","curriculum-sequencing","effective-questioning","effective-explanations","effective-feedback"] },
  { id:"languages", title:"Modern Languages", audience:"Language teachers", questioning:"Use rapid whole-class checks for vocabulary and structures, then extend into spontaneous use so recall is not mistaken for communicative competence.", modelling:"Model pronunciation, sentence construction and repair strategies, gradually reducing prompts as pupils gain fluency.", retrieval:"Space vocabulary and grammar across topics and require productive recall, not just recognition.", feedback:"Prioritise errors that most affect meaning or the current language focus, then give pupils an immediate chance to improve the utterance or sentence.", application:"Choose one language structure and plan the progression from model to guided manipulation to independent use.", recommendedCourseIds:["retrieval-practice","worked-examples-modelling","effective-feedback","checking-for-understanding","cognitive-load-theory"] },
  { id:"pe", title:"Physical Education", audience:"PE teachers and sports staff", questioning:"Pause purposeful moments to ask pupils to identify tactical or technical decisions, not only describe what happened.", modelling:"Demonstrate a movement with a small number of observable cues and use comparison or replay where appropriate before practice.", retrieval:"Retrieve rules, tactical principles, health knowledge and technique cues across practical contexts.", feedback:"Keep feedback brief and actionable during performance, then allow immediate repetition so pupils can test the change.", application:"Choose one practical skill and define the two or three cues pupils should attend to during deliberate practice.", recommendedCourseIds:["effective-feedback","worked-examples-modelling","effective-questioning","metacognition-self-regulation","assessment-for-learning"] },
  { id:"art-design", title:"Art & Design", audience:"Art, design and technology teachers", questioning:"Use critique questions that make choices about purpose, process and effect explicit while preserving legitimate creative variation.", modelling:"Demonstrate technique and decision-making separately: show the process, then explain how an artist or designer chooses when to use it.", retrieval:"Retrieve vocabulary, material properties, processes and artist/designer references that pupils can apply in practical work.", feedback:"Frame critique around intention, evidence in the work and one productive next experiment rather than imposing a single preferred outcome.", application:"Select one technique and plan a demonstration followed by a constrained experiment in which pupils make their own design decision.", recommendedCourseIds:["effective-feedback","worked-examples-modelling","effective-explanations","metacognition-self-regulation","adaptive-teaching"] },
  { id:"primary", title:"Primary", audience:"Primary teachers and teaching assistants", questioning:"Use simple whole-class response routines to sample every pupil and distinguish secure understanding from confident volunteering.", modelling:"Break complex tasks into visible steps while continuing to narrate the thinking that links each step to the learning goal.", retrieval:"Build short, spaced retrieval across reading, number, vocabulary and topic knowledge while keeping the activity low stakes.", feedback:"Give age-appropriate, specific next actions and build time for pupils to use them immediately.", application:"Choose one lesson next week and identify where you will check everyone, re-model if needed and then fade support.", recommendedCourseIds:["rosenshine-principles","effective-questioning","retrieval-practice","adaptive-teaching","assessment-for-learning"] },
];

export function subjectCpdById(id: string) {
  return subjectCpdProfiles.find(profile => profile.id === id) || subjectCpdProfiles[0];
}
