"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { courses } from "@/lib/catalogue";
import { buildPersonalPathway } from "@/lib/developmentIntelligence";
import { getSupabaseBrowserClient } from "@/lib/supabase";

type Plan={id:string;role_focus:string;goal:string;selected_course_ids:string[];rationale:Record<string,string>;target_completion:string|null;status:string;created_at:string};
const ROLES=["ECT","Teacher","TA","Pastoral","Middle Leader","SLT","SEND","Safeguarding"];

export default function PersonalPathwayPage(){
  const [userId,setUserId]=useState("");const [completed,setCompleted]=useState<string[]>([]);const [plans,setPlans]=useState<Plan[]>([]);const [preview,setPreview]=useState<ReturnType<typeof buildPersonalPathway>|null>(null);const [message,setMessage]=useState("");const [loading,setLoading]=useState(true);
  const courseMap=useMemo(()=>new Map(courses.map(c=>[c.id,c])),[]);
  useEffect(()=>{const supabase=getSupabaseBrowserClient();(async()=>{const {data:auth}=await supabase.auth.getUser();if(!auth.user){window.location.href="/auth?next=/pathways/personal";return;}setUserId(auth.user.id);const [progress,saved]=await Promise.all([supabase.from("course_progress").select("course_id").eq("user_id",auth.user.id).not("completed_at","is",null),supabase.from("personal_pathway_plans").select("id,role_focus,goal,selected_course_ids,rationale,target_completion,status,created_at").eq("user_id",auth.user.id).order("created_at",{ascending:false}).limit(8)]);if(progress.error)setMessage(progress.error.message);if(saved.error)setMessage(saved.error.message);setCompleted((progress.data||[]).map((r:{course_id:string})=>r.course_id));setPlans((saved.data||[]) as Plan[]);setLoading(false);})();},[]);
  function build(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);setPreview(buildPersonalPathway(String(form.get("role")||"Teacher"),String(form.get("goal")||""),completed));}
  async function save(){if(!preview||!userId)return;const target=new Date();target.setMonth(target.getMonth()+3);const payload={user_id:userId,role_focus:preview.role,goal:preview.goal,selected_course_ids:preview.courseIds,rationale:preview.rationale,target_completion:target.toISOString().slice(0,10),status:"active"};const supabase=getSupabaseBrowserClient();const {data,error}=await supabase.from("personal_pathway_plans").insert(payload).select("id,role_focus,goal,selected_course_ids,rationale,target_completion,status,created_at").single();if(error){setMessage(error.message);return;}setPlans(prev=>[data as Plan,...prev].slice(0,8));setMessage("Personal pathway saved.");}
  if(loading)return <main className="stagePage"><div className="stageCard">Building pathway tools…</div></main>;
  return <main className="stagePage"><section className="stageHero"><span className="eyebrow">PERSONALISED DEVELOPMENT PATHWAY</span><h1>Build a role-specific CPD journey around one real goal.</h1><p>The pathway builder uses your role, development goal and completed learning to select a focused sequence rather than sending everyone through the same course list.</p><div className="stageHeroActions"><a className="secondary phaseLinkButton" href="/pathways">Curated pathways</a><a className="secondary phaseLinkButton" href="/ai-coach">AI CPD Coach</a></div></section>{message&&<div className="phaseNotice">{message}</div>}
    <section className="stageGrid"><div className="stageCard stageSpan5"><span className="eyebrow">BUILD YOUR ROUTE</span><h2>Role + goal</h2><form className="stageForm" onSubmit={build}><label>Role focus<select name="role">{ROLES.map(r=><option key={r}>{r}</option>)}</select></label><label>Your development goal<textarea required name="goal" rows={4} placeholder="e.g. Strengthen adaptive teaching while keeping pupils independent"/></label><button className="primary">Build personalised pathway</button></form></div><div className="stageCard stageSpan7"><span className="eyebrow">RECOMMENDED SEQUENCE</span><h2>{preview?`${preview.courseIds.length} focused courses`:"Your pathway will appear here"}</h2>{preview?<><div className="featurePathwayTimeline">{preview.courseIds.map((id,index)=>{const c=courseMap.get(id);return <div key={id}><span>{index+1}</span><div><strong>{c?.title||id}</strong><p>{preview.rationale[id]||"Recommended for this goal."}</p><small>{c?.duration||0} min · {c?.category||"CPD"}</small></div></div>})}</div><button className="primary" onClick={save}>Save this pathway</button></>:<div className="emptyCompact">Choose a role and describe the outcome you want to improve.</div>}</div></section>
    <section className="stageCard"><span className="eyebrow">SAVED PERSONAL PATHWAYS</span><h2>Your development plans</h2><div className="stageList">{plans.map(p=><div className="stageRow" key={p.id}><div className="stageRowMain"><strong>{p.role_focus}: {p.goal}</strong><span>{p.selected_course_ids.length} courses · target {p.target_completion?new Date(p.target_completion).toLocaleDateString("en-GB"):"not set"}</span><small>{p.selected_course_ids.map(id=>courseMap.get(id)?.title).filter(Boolean).slice(0,3).join(" · ")}</small></div><span className="stageBadge good">{p.status}</span></div>)}{!plans.length&&<div className="emptyCompact">No personalised pathways saved yet.</div>}</div></section>
  </main>;
}
