"use client";

import { useEffect, useMemo, useState } from "react";
import { getSupabaseBrowserClient } from "@/lib/supabase";

type Reminder={id:string;kind:string;title:string;detail:string;date?:string|null;severity:"overdue"|"soon"|"info";href:string};
type Requirement={id:string;title:string;mandatory:boolean;active:boolean};
type TrainingRecord={requirement_id:string;completed_at:string;expires_at:string|null};
type Assignment={id:string;title_snapshot:string;due_date:string|null;mandatory:boolean;status:string};
type Policy={id:string;title:string;version:string;mandatory:boolean;active:boolean;review_date:string|null};
type Ack={policy_id:string;policy_version:string};
type Objective={id:string;title:string;review_date:string|null;status:string};
type ActionPlan={id:string;title:string;review_date:string|null;status:string};
type Onboarding={programme_id:string;status:string};
type Programme={id:string;title:string};
type Booking={session_id:string;status:string};
type Session={id:string;title:string;starts_at:string;location:string};

export default function RemindersPage(){
  const [items,setItems]=useState<Reminder[]>([]);const [loading,setLoading]=useState(true);const [message,setMessage]=useState("");
  useEffect(()=>{let live=true;(async()=>{const c=getSupabaseBrowserClient();const {data:auth}=await c.auth.getUser();if(!auth.user){window.location.href="/auth?next=/reminders";return;}const uid=auth.user.id;const results=await Promise.all([
    c.from("training_requirements").select("id,title,mandatory,active").eq("active",true),
    c.from("training_records").select("requirement_id,completed_at,expires_at").eq("user_id",uid),
    c.from("cpd_assignments").select("id,title_snapshot,due_date,mandatory,status").eq("assigned_to",uid),
    c.from("school_policies").select("id,title,version,mandatory,active,review_date").eq("active",true),
    c.from("policy_acknowledgements").select("policy_id,policy_version").eq("user_id",uid),
    c.from("appraisal_objectives").select("id,title,review_date,status").eq("user_id",uid),
    c.from("action_plans").select("id,title,review_date,status").eq("user_id",uid),
    c.from("onboarding_assignments").select("programme_id,status").eq("user_id",uid),
    c.from("onboarding_programmes").select("id,title").eq("active",true),
    c.from("inset_bookings").select("session_id,status").eq("user_id",uid).eq("status","booked"),
    c.from("inset_sessions").select("id,title,starts_at,location").gte("starts_at",new Date().toISOString()).order("starts_at"),
  ]);if(!live)return;const errors=results.map(r=>r.error?.message).filter(Boolean);if(errors.length)setMessage(errors.join(" · "));const reminders=buildReminders((results[0].data||[]) as Requirement[],(results[1].data||[]) as TrainingRecord[],(results[2].data||[]) as Assignment[],(results[3].data||[]) as Policy[],(results[4].data||[]) as Ack[],(results[5].data||[]) as Objective[],(results[6].data||[]) as ActionPlan[],(results[7].data||[]) as Onboarding[],(results[8].data||[]) as Programme[],(results[9].data||[]) as Booking[],(results[10].data||[]) as Session[]);setItems(reminders);setLoading(false);})();return()=>{live=false};},[]);
  const groups=useMemo(()=>({overdue:items.filter(i=>i.severity==="overdue"),soon:items.filter(i=>i.severity==="soon"),info:items.filter(i=>i.severity==="info")}),[items]);
  if(loading)return <main className="stagePage"><div className="stageCard">Checking your CPD reminders…</div></main>;
  return <main className="stagePage remindersPage"><section className="stageHero remindersHero"><span className="eyebrow">AUTOMATIC CPD REMINDERS</span><h1>Your next actions in one place.</h1><p>This list is calculated from your live school records each time you open it—mandatory training, policy sign-off, assigned CPD, appraisal reviews, implementation follow-ups, onboarding and booked INSET sessions.</p></section>{message&&<div className="phaseNotice">{message}</div>}<section className="stageStatGrid"><div className="stageStat"><strong>{groups.overdue.length}</strong><span>overdue / expired</span></div><div className="stageStat"><strong>{groups.soon.length}</strong><span>due soon</span></div><div className="stageStat"><strong>{groups.info.length}</strong><span>upcoming</span></div><div className="stageStat"><strong>{items.length}</strong><span>total actions</span></div></section>{items.length===0?<section className="stageCard reminderClear"><div>✓</div><h2>You’re up to date.</h2><p>No current CPD, policy, onboarding, appraisal or INSET reminders need your attention.</p></section>:<section className="reminderColumns"><ReminderGroup title="Needs attention" items={groups.overdue}/><ReminderGroup title="Due soon" items={groups.soon}/><ReminderGroup title="Coming up" items={groups.info}/></section>}<section className="stageCard reminderNote"><strong>How reminders work</strong><p>These are in-app reminders based on existing school records; they do not send email or SMS yet. Nothing here creates a separate shadow record of safeguarding or pupil information.</p></section></main>;
}
function ReminderGroup({title,items}:{title:string;items:Reminder[]}){if(!items.length)return null;return <section className="stageCard"><span className="eyebrow">{title.toUpperCase()}</span><div className="reminderList">{items.map(i=><a className={`reminderCard ${i.severity}`} href={i.href} key={i.id}><span className="reminderKind">{i.kind}</span><div><strong>{i.title}</strong><p>{i.detail}</p></div>{i.date&&<time>{formatDate(i.date)}</time>}<b>→</b></a>)}</div></section>}
function buildReminders(reqs:Requirement[],records:TrainingRecord[],assignments:Assignment[],policies:Policy[],acks:Ack[],objectives:Objective[],plans:ActionPlan[],onboarding:Onboarding[],programmes:Programme[],bookings:Booking[],sessions:Session[]):Reminder[]{const out:Reminder[]=[];const today=startOfDay(new Date());const in30=addDays(today,30);const in14=addDays(today,14);const rec=new Map(records.map(r=>[r.requirement_id,r]));for(const r of reqs.filter(x=>x.mandatory)){const record=rec.get(r.id);if(!record){out.push({id:`training-missing-${r.id}`,kind:"Mandatory training",title:r.title,detail:"No valid completion is recorded for this mandatory requirement.",severity:"overdue",href:"/training"});continue;}if(record.expires_at){const exp=new Date(record.expires_at);if(exp<today)out.push({id:`training-exp-${r.id}`,kind:"Training renewal",title:r.title,detail:"This training record has expired and needs renewal.",date:record.expires_at,severity:"overdue",href:"/training"});else if(exp<=in30)out.push({id:`training-soon-${r.id}`,kind:"Training renewal",title:r.title,detail:"This mandatory training expires within 30 days.",date:record.expires_at,severity:"soon",href:"/training"});}}
for(const a of assignments.filter(x=>x.status!=="completed")){const sev=dueSeverity(a.due_date,today,in30);out.push({id:`assignment-${a.id}`,kind:a.mandatory?"Assigned mandatory CPD":"Assigned CPD",title:a.title_snapshot,detail:a.due_date?`Complete this assignment by ${formatDate(a.due_date)}.`:"A CPD activity has been assigned to you.",date:a.due_date,severity:sev,href:"/training"});}
const ackMap=new Map(acks.map(a=>[a.policy_id,a.policy_version]));for(const p of policies.filter(x=>x.mandatory)){if(ackMap.get(p.id)!==p.version)out.push({id:`policy-${p.id}`,kind:"Policy acknowledgement",title:p.title,detail:`Read and acknowledge version ${p.version}.`,date:p.review_date,severity:"soon",href:"/school-hub"});}
for(const o of objectives.filter(x=>!["achieved","closed"].includes(x.status))){const reviewDate=o.review_date;if(!reviewDate)continue;const sev=dueSeverity(reviewDate,today,in30);if(sev!=="info"||new Date(reviewDate)<=in30)out.push({id:`objective-${o.id}`,kind:"Appraisal review",title:o.title,detail:"Your professional objective is approaching its review date.",date:reviewDate,severity:sev,href:"/school-hub"});}
for(const p of plans.filter(x=>!["completed","closed"].includes(x.status))){const reviewDate=p.review_date;if(!reviewDate)continue;const sev=dueSeverity(reviewDate,today,in30);if(new Date(reviewDate)<=in30)out.push({id:`action-${p.id}`,kind:"Implementation follow-up",title:p.title,detail:"Review the evidence and decide what to keep, adapt or stop.",date:reviewDate,severity:sev,href:"/actions"});}
const prog=new Map(programmes.map(p=>[p.id,p.title]));for(const a of onboarding.filter(x=>x.status!=="completed"))out.push({id:`onboarding-${a.programme_id}`,kind:"Onboarding",title:prog.get(a.programme_id)||"Onboarding programme",detail:"Continue your assigned induction/development checklist.",severity:"info",href:"/school-hub"});
const booked=new Set(bookings.map(b=>b.session_id));for(const s of sessions.filter(x=>booked.has(x.id)&&new Date(x.starts_at)<=in14))out.push({id:`inset-${s.id}`,kind:"INSET booking",title:s.title,detail:`Booked session${s.location?` · ${s.location}`:""}.`,date:s.starts_at,severity:"info",href:"/school-hub"});
return out.sort((a,b)=>rank(a.severity)-rank(b.severity)||new Date(a.date||"2999-01-01").getTime()-new Date(b.date||"2999-01-01").getTime());}
function dueSeverity(v:string|null,today:Date,in30:Date):"overdue"|"soon"|"info"{if(!v)return"info";const d=new Date(v);if(d<today)return"overdue";if(d<=in30)return"soon";return"info"}function rank(s:string){return s==="overdue"?0:s==="soon"?1:2}function startOfDay(d:Date){return new Date(d.getFullYear(),d.getMonth(),d.getDate())}function addDays(d:Date,n:number){return new Date(d.getTime()+n*86400000)}function formatDate(v:string){return new Date(v).toLocaleDateString("en-GB",{day:"numeric",month:"short",year:"numeric"})}
