"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { courses } from "@/lib/catalogue";
import { getSupabaseBrowserClient } from "@/lib/supabase";

type Profile={id:string;role:string;department:string;organisation_id:string|null};
type Plan={id:string;organisation_id:string;department:string;academic_year:string;title:string;priorities:string[];target_hours:number;status:"draft"|"active"|"complete"|"archived";created_by:string;created_at:string;updated_at:string};
type Action={id:string;plan_id:string;title:string;owner_label:string;due_date:string|null;linked_course_id:string|null;evidence_expected:string;status:"planned"|"in_progress"|"complete"|"cancelled";notes:string;created_by:string};
type Gap={department:string;requirement_id:string;requirement_title:string;required_staff:number;current_staff:number;due_soon:number;expired:number;missing:number};

export default function DepartmentCpdPage(){
  const [profile,setProfile]=useState<Profile|null>(null);const [plans,setPlans]=useState<Plan[]>([]);const [actions,setActions]=useState<Action[]>([]);const [gaps,setGaps]=useState<Gap[]>([]);const [loading,setLoading]=useState(true);const [message,setMessage]=useState("");
  useEffect(()=>{let live=true;(async()=>{const c=getSupabaseBrowserClient();const {data:auth}=await c.auth.getUser();if(!auth.user){window.location.href="/auth?next=/department-cpd";return;}const {data:p,error:pe}=await c.from("staff_profiles").select("id,role,department,organisation_id").eq("id",auth.user.id).single();if(!live)return;if(pe||!p){setMessage(pe?.message||"Unable to load profile.");setLoading(false);return;}const me=p as Profile;setProfile(me);if(!["Department Lead","CPD Lead","Admin"].includes(me.role)){setLoading(false);return;}const [pl,ac,gap]=await Promise.all([c.from("department_cpd_plans").select("id,organisation_id,department,academic_year,title,priorities,target_hours,status,created_by,created_at,updated_at").order("academic_year",{ascending:false}).order("department"),c.from("department_cpd_actions").select("id,plan_id,title,owner_label,due_date,linked_course_id,evidence_expected,status,notes,created_by").order("due_date",{ascending:true}),c.rpc("department_training_gap")]);if(!live)return;const errors=[pl.error,ac.error,gap.error].filter(Boolean);if(errors.length)setMessage(errors.map(e=>e?.message).join(" · "));setPlans((pl.data||[]) as Plan[]);setActions((ac.data||[]) as Action[]);setGaps((gap.data||[]) as Gap[]);setLoading(false);})();return()=>{live=false};},[]);
  const canManage=Boolean(profile&&["Department Lead","CPD Lead","Admin"].includes(profile.role));const wholeSchool=Boolean(profile&&["CPD Lead","Admin"].includes(profile.role));
  const departmentOptions=useMemo(()=>[...new Set([profile?.department||"",...plans.map(p=>p.department),...gaps.map(g=>g.department)].filter(Boolean))].sort(),[profile?.department,plans,gaps]);
  const activePlans=plans.filter(p=>p.status==="active");const openActions=actions.filter(a=>!["complete","cancelled"].includes(a.status));const gapMissing=gaps.reduce((sum,g)=>sum+Number(g.missing||0),0);const gapRequired=gaps.reduce((sum,g)=>sum+Number(g.required_staff||0),0);

  async function createPlan(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!profile?.organisation_id)return;const formEl=e.currentTarget,fd=new FormData(formEl),c=getSupabaseBrowserClient();const department=wholeSchool?String(fd.get("department")||"").trim():profile.department;if(!department){setMessage("A department is required.");return;}const priorities=String(fd.get("priorities")||"").split(/\n|,/).map(x=>x.trim()).filter(Boolean);const {data,error}=await c.from("department_cpd_plans").insert({organisation_id:profile.organisation_id,department,academic_year:String(fd.get("academic_year")||"2026/27").trim(),title:String(fd.get("title")||"").trim(),priorities,target_hours:Number(fd.get("target_hours")||10),status:String(fd.get("status")||"draft"),created_by:profile.id}).select("id,organisation_id,department,academic_year,title,priorities,target_hours,status,created_by,created_at,updated_at").single();if(error){setMessage(error.message);return;}setPlans(prev=>[data as Plan,...prev]);formEl.reset();setMessage("Department CPD plan created.");}
  async function createAction(e:FormEvent<HTMLFormElement>,plan:Plan){e.preventDefault();if(!profile)return;const formEl=e.currentTarget,fd=new FormData(formEl),c=getSupabaseBrowserClient();const {data,error}=await c.from("department_cpd_actions").insert({plan_id:plan.id,title:String(fd.get("title")||"").trim(),owner_label:String(fd.get("owner_label")||"").trim(),due_date:String(fd.get("due_date")||"")||null,linked_course_id:String(fd.get("linked_course_id")||"")||null,evidence_expected:String(fd.get("evidence_expected")||"").trim(),notes:String(fd.get("notes")||"").trim(),created_by:profile.id}).select("id,plan_id,title,owner_label,due_date,linked_course_id,evidence_expected,status,notes,created_by").single();if(error){setMessage(error.message);return;}setActions(prev=>[...prev,data as Action]);formEl.reset();setMessage("Department CPD action added.");}
  async function changeAction(action:Action,status:Action["status"]){const c=getSupabaseBrowserClient();const {error}=await c.from("department_cpd_actions").update({status,updated_at:new Date().toISOString()}).eq("id",action.id);if(error){setMessage(error.message);return;}setActions(prev=>prev.map(a=>a.id===action.id?{...a,status}:a));}
  async function changePlan(plan:Plan,status:Plan["status"]){const c=getSupabaseBrowserClient();const {error}=await c.from("department_cpd_plans").update({status,updated_at:new Date().toISOString()}).eq("id",plan.id);if(error){setMessage(error.message);return;}setPlans(prev=>prev.map(p=>p.id===plan.id?{...p,status}:p));}

  if(loading)return <main className="stagePage"><div className="stageCard">Loading department CPD planning…</div></main>;
  if(!profile||!["Department Lead","CPD Lead","Admin"].includes(profile.role))return <main className="stagePage"><section className="stageHero"><span className="eyebrow">DEPARTMENT CPD</span><h1>Leadership access required.</h1><p>Department plans and aggregate compliance information are available to Department Leads, CPD Leads and Admins.</p></section></main>;
  return <main className="stagePage departmentCpdPage"><section className="stageHero departmentCpdHero"><span className="eyebrow">DEPARTMENT CPD PLANNING</span><h1>{wholeSchool?"Plan development across departments.":`${profile.department||"Department"} professional development plan`}</h1><p>Turn department priorities into a small number of CPD actions, link useful courses, define expected evidence, and keep mandatory-training gaps visible without exposing private staff reflections.</p></section>{message&&<div className="phaseNotice">{message}</div>}
    <section className="stageStatGrid"><div className="stageStat"><strong>{activePlans.length}</strong><span>active department plans</span></div><div className="stageStat"><strong>{openActions.length}</strong><span>open CPD actions</span></div><div className="stageStat"><strong>{gapMissing}</strong><span>training gaps</span></div><div className="stageStat"><strong>{gapRequired?Math.round(((gapRequired-gapMissing)/gapRequired)*100):100}%</strong><span>mandatory training current</span></div></section>

    {canManage&&<details className="stageDetails" open={!plans.length}><summary>Create department CPD plan</summary><form className="stageForm departmentPlanForm" onSubmit={createPlan}><div className="stageFormGrid">{wholeSchool&&<label>Department<input required name="department" list="department-list" placeholder="e.g. Science"/><datalist id="department-list">{departmentOptions.map(d=><option key={d} value={d}/>)}</datalist></label>}<label>Academic year<input required name="academic_year" defaultValue="2026/27"/></label><label className="full">Plan title<input required name="title" placeholder="e.g. Science teaching & assessment plan"/></label><label className="full">Priorities<textarea required name="priorities" rows={3} placeholder="One per line: Improve checking for understanding&#10;Strengthen extended-response modelling"/></label><label>Target CPD hours<input type="number" min="0" step="0.5" name="target_hours" defaultValue="10"/></label><label>Status<select name="status" defaultValue="active"><option value="draft">Draft</option><option value="active">Active</option></select></label></div><button className="primary">Create plan</button></form></details>}

    <section className="departmentPlanGrid">{plans.map(plan=>{const planActions=actions.filter(a=>a.plan_id===plan.id);return <article className={`stageCard departmentPlan ${plan.status}`} key={plan.id}><header><div><span>{plan.department} · {plan.academic_year}</span><h2>{plan.title}</h2></div><select value={plan.status} onChange={e=>changePlan(plan,e.target.value as Plan["status"])}><option value="draft">Draft</option><option value="active">Active</option><option value="complete">Complete</option><option value="archived">Archived</option></select></header><div className="departmentPriorities">{plan.priorities.map((p,i)=><span key={`${p}-${i}`}>{p}</span>)}</div><div className="departmentPlanMeta"><span><b>{plan.target_hours}</b> target hours</span><span><b>{planActions.filter(a=>a.status==="complete").length}/{planActions.length}</b> actions complete</span></div><div className="departmentActions">{planActions.map(a=><div key={a.id}><div><strong>{a.title}</strong><span>{a.owner_label||"Department team"}{a.due_date?` · due ${formatDate(a.due_date)}`:""}</span>{a.evidence_expected&&<small>Evidence: {a.evidence_expected}</small>}</div><select value={a.status} onChange={e=>changeAction(a,e.target.value as Action["status"])}><option value="planned">Planned</option><option value="in_progress">In progress</option><option value="complete">Complete</option><option value="cancelled">Cancelled</option></select></div>)}{!planActions.length&&<p className="muted">No actions added yet.</p>}</div><details className="departmentActionAdd"><summary>Add action</summary><form onSubmit={e=>createAction(e,plan)}><label>Action<input required name="title"/></label><label>Owner / team<input name="owner_label" placeholder="e.g. All Science staff"/></label><label>Due date<input name="due_date" type="date"/></label><label>Linked course<select name="linked_course_id"><option value="">None</option>{courses.map(c=><option value={c.id} key={c.id}>{c.title}</option>)}</select></label><label className="wide">Expected evidence<input name="evidence_expected" placeholder="e.g. work sample + department moderation discussion"/></label><label className="wide">Notes<textarea name="notes" rows={2}/></label><button className="primary">Add action</button></form></details></article>})}{!plans.length&&<div className="stageCard"><h2>No department CPD plans yet</h2><p>Create the first plan above. Keep priorities limited enough that staff can actually implement and revisit them.</p></div>}</section>

    <section className="stageCard trainingGapCard"><span className="eyebrow">MANDATORY TRAINING GAP OVERVIEW</span><h2>Where compliance needs attention</h2><p className="muted">This is calculated from active mandatory requirements, their configured audiences and current/expiry records. It does not use CPD reflections or observation notes.</p><div className="trainingGapTable"><div className="trainingGapHead"><span>Department / requirement</span><span>Current</span><span>Due soon</span><span>Expired</span><span>Gap</span></div>{gaps.map(g=>{const pct=g.required_staff?Math.round((g.current_staff/g.required_staff)*100):100;return <div className={`trainingGapRow ${g.missing>0?"attention":"good"}`} key={`${g.department}-${g.requirement_id}`}><div><strong>{g.department}</strong><span>{g.requirement_title}</span><progress max="100" value={pct}/></div><span>{g.current_staff}/{g.required_staff}</span><span>{g.due_soon}</span><span>{g.expired}</span><b>{g.missing}</b></div>})}{!gaps.length&&<div className="emptyCompact">No applicable mandatory training requirements are configured for the visible department scope.</div>}</div></section>
  </main>;
}
function formatDate(v:string){return new Date(`${v}T12:00:00`).toLocaleDateString("en-GB",{day:"numeric",month:"short",year:"numeric"});}
