"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { courses } from "@/lib/catalogue";
import { suggestFromLearningWalk } from "@/lib/developmentIntelligence";
import { getSupabaseBrowserClient } from "@/lib/supabase";

type Profile={id:string;role:string;department:string;organisation_id:string|null;site_id:string|null};
type Priority={id:string;title:string};
type Walk={id:string;observed_on:string;department:string;focus:string;strengths:string[];development_points:string[];signals:Record<string,boolean>;recommended_course_ids:string[];created_by:string;shared_for_aggregate:boolean};

const SIGNALS:[string,string][]=[
  ["checking_understanding","Checking for understanding"],["challenge","Challenge & adaptation"],["participation","Participation"],["independence","Pupil independence"],["behaviour_climate","Behaviour & climate"],["SEND_access","SEND access"],["retrieval","Retrieval"],["feedback","Feedback"],["literacy","Literacy/oracy"]
];

export default function LearningWalksPage(){
  const [profile,setProfile]=useState<Profile|null>(null); const [priorities,setPriorities]=useState<Priority[]>([]); const [walks,setWalks]=useState<Walk[]>([]); const [message,setMessage]=useState(""); const [loading,setLoading]=useState(true);
  const courseMap=useMemo(()=>new Map(courses.map(c=>[c.id,c])),[]);
  useEffect(()=>{const supabase=getSupabaseBrowserClient();(async()=>{const {data:auth}=await supabase.auth.getUser();if(!auth.user){window.location.href="/auth?next=/learning-walks";return;}const {data:p,error:pe}=await supabase.from("staff_profiles").select("id,role,department,organisation_id,site_id").eq("id",auth.user.id).single();if(pe||!p){setMessage(pe?.message||"Unable to load profile.");setLoading(false);return;}const me=p as Profile;setProfile(me);const [pr,lw]=await Promise.all([supabase.from("improvement_priorities").select("id,title").eq("active",true).order("title"),supabase.from("learning_walks").select("id,observed_on,department,focus,strengths,development_points,signals,recommended_course_ids,created_by,shared_for_aggregate").order("observed_on",{ascending:false}).limit(80)]);if(pr.error)setMessage(pr.error.message);if(lw.error)setMessage(lw.error.message);setPriorities((pr.data||[]) as Priority[]);setWalks((lw.data||[]) as Walk[]);setLoading(false);})();},[]);
  const leader=Boolean(profile&&["Department Lead","CPD Lead","Admin"].includes(profile.role));
  const ownWalks=walks.filter(w=>w.created_by===profile?.id); const aggregateWalks=leader?walks.filter(w=>w.shared_for_aggregate):[];
  const signalCounts=useMemo(()=>Object.fromEntries(SIGNALS.map(([key])=>[key,aggregateWalks.filter(w=>Boolean(w.signals?.[key])).length])),[aggregateWalks]);

  async function saveWalk(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!profile)return;const formEl=e.currentTarget;const form=new FormData(formEl);const focus=String(form.get("focus")||"").trim();const development=String(form.get("development_points")||"").split("\n").map(v=>v.trim()).filter(Boolean);const strengths=String(form.get("strengths")||"").split("\n").map(v=>v.trim()).filter(Boolean);const selectedSignals=SIGNALS.filter(([key])=>form.get(key)==="on").map(([key])=>key);const suggestions=suggestFromLearningWalk(focus,selectedSignals,development);const payload={organisation_id:profile.organisation_id,site_id:profile.site_id,created_by:profile.id,observed_on:String(form.get("observed_on")||new Date().toISOString().slice(0,10)),department:String(form.get("department")||profile.department||""),focus,evidence_notes:String(form.get("evidence_notes")||""),strengths,development_points:development,signals:Object.fromEntries(selectedSignals.map(k=>[k,true])),priority_id:String(form.get("priority_id")||"")||null,recommended_course_ids:suggestions.map(s=>s.course.id),shared_for_aggregate:Boolean(form.get("shared_for_aggregate"))};const supabase=getSupabaseBrowserClient();const {data,error}=await supabase.from("learning_walks").insert(payload).select("id,observed_on,department,focus,strengths,development_points,signals,recommended_course_ids,created_by,shared_for_aggregate").single();if(error){setMessage(error.message);return;}setWalks(prev=>[data as Walk,...prev]);formEl.reset();setMessage(`Learning walk saved. ${suggestions.length} CPD suggestions linked automatically.`);}

  if(loading)return <main className="stagePage"><div className="stageCard">Loading learning walks…</div></main>;
  return <main className="stagePage">
    <section className="stageHero"><span className="eyebrow">LEARNING WALKS · DEVELOPMENT, NOT RANKING</span><h1>Capture patterns quickly and turn them into useful CPD.</h1><p>This mobile-first tool records observable evidence and school-wide patterns without scoring or ranking individual teachers. CPD suggestions are generated from the focus, signals and development points you record.</p><div className="stageHeroActions"><a className="secondary phaseLinkButton" href="/improvement">School improvement</a><a className="secondary phaseLinkButton" href="/coach">CPD Coach</a></div></section>
    {message&&<div className="phaseNotice">{message}</div>}
    <section className="stageGrid"><div className="stageSpan7"><details className="stageDetails" open><summary>Record a learning walk</summary><form className="stageForm" onSubmit={saveWalk}><div className="stageFormGrid">
      <label>Date<input name="observed_on" type="date" defaultValue={new Date().toISOString().slice(0,10)}/></label><label>Department<input name="department" defaultValue={profile?.department||""}/></label><label className="full">Focus<input required name="focus" placeholder="e.g. How consistently are pupils checking their understanding?"/></label><label>Linked school priority<select name="priority_id"><option value="">None</option>{priorities.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label><label className="inlineCheck"><input name="shared_for_aggregate" type="checkbox" defaultChecked/>Include anonymously in school pattern view</label><fieldset className="full featureSignalGrid"><legend>What did you notice?</legend>{SIGNALS.map(([key,label])=><label className="inlineCheck" key={key}><input name={key} type="checkbox"/>{label}</label>)}</fieldset><label className="full">Observable evidence<textarea name="evidence_notes" rows={3} placeholder="Describe what pupils were doing, saying or producing. Avoid evaluative labels."/></label><label className="full">Strengths — one per line<textarea name="strengths" rows={3}/></label><label className="full">Development points — one per line<textarea name="development_points" rows={3}/></label></div><button className="primary">Save walk & suggest CPD</button></form></details></div>
      <aside className="stageCard stageSpan5"><span className="eyebrow">YOUR RECENT WALKS</span><h2>{ownWalks.length} recorded</h2><div className="stageList">{ownWalks.slice(0,5).map(w=><div className="stageRow" key={w.id}><div className="stageRowMain"><strong>{w.focus}</strong><span>{w.department||"Whole school"} · {new Date(w.observed_on).toLocaleDateString("en-GB")}</span><small>{w.recommended_course_ids.slice(0,2).map(id=>courseMap.get(id)?.title).filter(Boolean).join(" · ")||"No linked course"}</small></div></div>)}{!ownWalks.length&&<div className="emptyCompact">No learning walks yet.</div>}</div></aside>
    </section>
    {leader&&<section className="stageCard"><span className="eyebrow">AGGREGATE PATTERNS</span><h2>What is appearing across shared walks</h2><p className="muted">This is a pattern view, not a staff leaderboard. Individual teacher names are not collected by the learning-walk form.</p><div className="featureSignalSummary">{SIGNALS.map(([key,label])=><div key={key}><strong>{signalCounts[key]||0}</strong><span>{label}</span></div>)}</div></section>}
  </main>;
}
