"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { courses } from "@/lib/catalogue";
import { getSupabaseBrowserClient } from "@/lib/supabase";

type Profile={id:string;role:string;organisation_id:string|null};
type Plan={id:string;organisation_id:string;academic_year:string;title:string;priorities:string[];target_hours:number;status:"draft"|"active"|"closed";created_at:string};
type Action={id:string;plan_id:string;title:string;owner_label:string;due_date:string|null;status:"planned"|"in_progress"|"completed"|"cancelled";linked_course_id:string|null;evidence_expected:string;notes:string};
type Review={id:string;organisation_id:string;course_id:string;course_title:string;quality_rating:number|null;accuracy_status:"review_due"|"checked"|"needs_update";accessibility_status:"review_due"|"checked"|"needs_update";notes:string;reviewed_at:string;next_review_date:string|null};
type Audit={id:number;entity_type:string;entity_id:string;action:string;summary:{title?:string};occurred_at:string};

export default function QualityPage(){
  const [profile,setProfile]=useState<Profile|null>(null);const [plans,setPlans]=useState<Plan[]>([]);const [actions,setActions]=useState<Action[]>([]);const [reviews,setReviews]=useState<Review[]>([]);const [audit,setAudit]=useState<Audit[]>([]);const [loading,setLoading]=useState(true);const [message,setMessage]=useState("");
  const admin=Boolean(profile&&["CPD Lead","Admin"].includes(profile.role));

  useEffect(()=>{const supabase=getSupabaseBrowserClient();let alive=true;(async()=>{const {data:auth}=await supabase.auth.getUser();if(!auth.user){window.location.href="/auth?next=/quality";return;}const {data:p,error}=await supabase.from("staff_profiles").select("id,role,organisation_id").eq("id",auth.user.id).single();if(!alive)return;if(error||!p){setMessage(error?.message||"Unable to load profile.");setLoading(false);return;}setProfile(p as Profile);if(!p.organisation_id){setLoading(false);return;}const orgId=p.organisation_id;const [pl,ac,rv]=await Promise.all([supabase.from("annual_cpd_plans").select("id,organisation_id,academic_year,title,priorities,target_hours,status,created_at").eq("organisation_id",orgId).order("academic_year",{ascending:false}),supabase.from("annual_cpd_actions").select("id,plan_id,title,owner_label,due_date,status,linked_course_id,evidence_expected,notes").order("due_date",{ascending:true}),supabase.from("course_quality_reviews").select("id,organisation_id,course_id,course_title,quality_rating,accuracy_status,accessibility_status,notes,reviewed_at,next_review_date").eq("organisation_id",orgId).order("next_review_date",{ascending:true})]);if(pl.error||ac.error||rv.error)setMessage([pl.error?.message,ac.error?.message,rv.error?.message].filter(Boolean).join(" · "));setPlans((pl.data||[]) as Plan[]);setActions((ac.data||[]) as Action[]);setReviews((rv.data||[]) as Review[]);if(["CPD Lead","Admin"].includes(p.role)){const {data:logs}=await supabase.from("cpd_audit_log").select("id,entity_type,entity_id,action,summary,occurred_at").eq("organisation_id",orgId).order("occurred_at",{ascending:false}).limit(40);setAudit((logs||[]) as Audit[]);}setLoading(false);})();return()=>{alive=false;};},[]);

  const currentPlan=plans.find(p=>p.status==="active")||plans[0]||null;const currentActions=useMemo(()=>currentPlan?actions.filter(a=>a.plan_id===currentPlan.id):[],[actions,currentPlan]);const overdue=currentActions.filter(a=>a.due_date&&new Date(a.due_date).getTime()<Date.now()&&!['completed','cancelled'].includes(a.status)).length;const reviewDue=reviews.filter(r=>!r.next_review_date||new Date(r.next_review_date).getTime()<=Date.now()||r.accuracy_status!=="checked"||r.accessibility_status!=="checked").length;

  async function createPlan(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!profile?.organisation_id)return;const formEl=e.currentTarget;const fd=new FormData(formEl);const client=getSupabaseBrowserClient();const {data,error}=await client.from("annual_cpd_plans").insert({organisation_id:profile.organisation_id,academic_year:String(fd.get("academic_year")||""),title:String(fd.get("title")||"Annual CPD Plan"),priorities:String(fd.get("priorities")||"").split("\n").map(x=>x.trim()).filter(Boolean),target_hours:Number(fd.get("target_hours")||20),status:String(fd.get("status")||"draft"),created_by:profile.id}).select("id,organisation_id,academic_year,title,priorities,target_hours,status,created_at").single();if(error)setMessage(error.message);else{setPlans(prev=>[data as Plan,...prev]);formEl.reset();setMessage("Annual CPD plan created.");}}
  async function createAction(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!currentPlan)return;const formEl=e.currentTarget;const fd=new FormData(formEl);const client=getSupabaseBrowserClient();const {data,error}=await client.from("annual_cpd_actions").insert({plan_id:currentPlan.id,title:String(fd.get("title")||""),owner_label:String(fd.get("owner_label")||""),due_date:String(fd.get("due_date")||"")||null,linked_course_id:String(fd.get("linked_course_id")||"")||null,evidence_expected:String(fd.get("evidence_expected")||""),notes:String(fd.get("notes")||"")}).select("id,plan_id,title,owner_label,due_date,status,linked_course_id,evidence_expected,notes").single();if(error)setMessage(error.message);else{setActions(prev=>[...prev,data as Action]);formEl.reset();setMessage("Plan action added.");}}
  async function updateAction(id:string,status:Action["status"]){const client=getSupabaseBrowserClient();const {error}=await client.from("annual_cpd_actions").update({status,updated_at:new Date().toISOString()}).eq("id",id);if(error)setMessage(error.message);else setActions(prev=>prev.map(a=>a.id===id?{...a,status}:a));}
  async function saveReview(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!profile?.organisation_id)return;const fd=new FormData(e.currentTarget);const courseId=String(fd.get("course_id")||"");const course=courses.find(c=>c.id===courseId);if(!course){setMessage("Choose a course to review.");return;}const client=getSupabaseBrowserClient();const payload={organisation_id:profile.organisation_id,course_id:course.id,course_title:course.title,quality_rating:Number(fd.get("quality_rating")||0)||null,accuracy_status:String(fd.get("accuracy_status")||"review_due"),accessibility_status:String(fd.get("accessibility_status")||"review_due"),notes:String(fd.get("notes")||""),reviewed_by:profile.id,reviewed_at:new Date().toISOString(),next_review_date:String(fd.get("next_review_date")||"")||null};const {data,error}=await client.from("course_quality_reviews").upsert(payload,{onConflict:"organisation_id,course_id"}).select("id,organisation_id,course_id,course_title,quality_rating,accuracy_status,accessibility_status,notes,reviewed_at,next_review_date").single();if(error)setMessage(error.message);else{setReviews(prev=>[...(prev.filter(r=>r.course_id!==course.id)),data as Review].sort((a,b)=>String(a.next_review_date||'9999').localeCompare(String(b.next_review_date||'9999'))));setMessage("Course quality review saved.");}}

  if(loading)return <main className="stagePage"><div className="stageCard">Loading annual CPD quality dashboard…</div></main>;
  if(!profile?.organisation_id)return <main className="stagePage"><section className="stageCard"><span className="eyebrow">STAGE 14</span><h1>Organisation setup required</h1><p>Create or join your school/trust organisation before using annual planning and QA.</p><a className="primary phaseLinkButton" href="/organisation">Open organisation setup</a></section></main>;

  return <main className="stagePage"><section className="stageHero"><span className="eyebrow">STAGE 14 · ANNUAL CPD & QUALITY ASSURANCE</span><h1>Plan the year, review quality and keep an audit trail.</h1><p>Turn school priorities into trackable CPD actions, schedule course reviews and keep a transparent record of major CPD administration changes.</p><div className="stageHeroActions"><a className="secondary phaseLinkButton" href="/organisation">Organisation settings</a></div></section>{message&&<div className="phaseNotice">{message}</div>}
    <section className="stageStatGrid"><div className="stageStat"><strong>{currentPlan?.academic_year||"—"}</strong><span>current plan</span></div><div className="stageStat"><strong>{currentActions.filter(a=>a.status==="completed").length}/{currentActions.length}</strong><span>actions complete</span></div><div className="stageStat"><strong>{overdue}</strong><span>overdue actions</span></div><div className="stageStat"><strong>{reviewDue}</strong><span>course reviews due</span></div></section>
    <section className="stageGrid"><div className="stageCard stageSpan7"><span className="eyebrow">ANNUAL PLAN</span><h2>{currentPlan?.title||"No annual plan yet"}</h2>{currentPlan?<><div className="priorityPills">{currentPlan.priorities.map((p,i)=><span className="stageBadge" key={i}>{p}</span>)}</div><div className="stageList">{currentActions.map(a=><div className="stageRow" key={a.id}><div className="stageRowMain"><strong>{a.title}</strong><span>{a.owner_label||"No owner"}{a.due_date?` · due ${new Date(a.due_date).toLocaleDateString('en-GB')}`:""}</span><small>{a.evidence_expected||"No evidence expectation recorded"}</small></div><select value={a.status} disabled={!admin} onChange={e=>updateAction(a.id,e.target.value as Action["status"])}><option value="planned">planned</option><option value="in_progress">in progress</option><option value="completed">completed</option><option value="cancelled">cancelled</option></select></div>)}</div></>:<p>Create the school’s annual CPD plan to start tracking priorities and implementation.</p>}</div>{admin&&<div className="stageCard stageSpan5"><span className="eyebrow">PLAN BUILDER</span><h2>{currentPlan?"Add an action":"Create annual plan"}</h2>{currentPlan?<form className="stageForm" onSubmit={createAction}><label>Action title<input required name="title"/></label><label>Owner / team<input name="owner_label"/></label><label>Due date<input type="date" name="due_date"/></label><label>Linked course<select name="linked_course_id"><option value="">None</option>{courses.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label><label>Expected evidence<textarea name="evidence_expected" rows={3}/></label><label>Notes<textarea name="notes" rows={2}/></label><button className="primary">Add action</button></form>:<form className="stageForm" onSubmit={createPlan}><label>Academic year<input required name="academic_year" defaultValue="2026/27"/></label><label>Plan title<input required name="title" defaultValue="Whole-school CPD Plan"/></label><label>Priority areas<textarea name="priorities" rows={5} placeholder={"One priority per line\nAdaptive teaching\nLiteracy\nQuestioning"}/></label><label>Target CPD hours<input name="target_hours" type="number" min="0" step="0.5" defaultValue="20"/></label><label>Status<select name="status" defaultValue="active"><option value="draft">draft</option><option value="active">active</option></select></label><button className="primary">Create annual plan</button></form>}</div>}</section>
    <section className="stageGrid"><div className="stageCard stageSpan7"><span className="eyebrow">COURSE QA</span><h2>Accuracy, accessibility and review dates</h2><div className="stageList">{reviews.map(r=><div className="stageRow" key={r.id}><div className="stageRowMain"><strong>{r.course_title}</strong><span>{r.quality_rating?`${r.quality_rating}/5 quality · `:""}{r.accuracy_status} accuracy · {r.accessibility_status} accessibility</span><small>{r.next_review_date?`Next review ${new Date(r.next_review_date).toLocaleDateString('en-GB')}`:"No next-review date"}</small></div><span className={`stageBadge ${r.accuracy_status==="checked"&&r.accessibility_status==="checked"?"good":"warn"}`}>{r.accuracy_status==="checked"&&r.accessibility_status==="checked"?"checked":"review"}</span></div>)}{!reviews.length&&<div className="emptyCompact">No course quality reviews recorded yet.</div>}</div></div>{admin&&<div className="stageCard stageSpan5"><span className="eyebrow">QUALITY REVIEW</span><h2>Review a course</h2><form className="stageForm" onSubmit={saveReview}><label>Course<select required name="course_id"><option value="">Choose…</option>{courses.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label><label>Quality rating<select name="quality_rating" defaultValue="4"><option value="">Not rated</option>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n}/5</option>)}</select></label><label>Accuracy<select name="accuracy_status" defaultValue="checked"><option value="checked">checked</option><option value="needs_update">needs update</option><option value="review_due">review due</option></select></label><label>Accessibility<select name="accessibility_status" defaultValue="checked"><option value="checked">checked</option><option value="needs_update">needs update</option><option value="review_due">review due</option></select></label><label>Next review<input type="date" name="next_review_date"/></label><label>Notes<textarea name="notes" rows={3}/></label><button className="primary">Save review</button></form></div>}</section>
    {admin&&<section className="stageCard"><span className="eyebrow">AUDIT TRAIL</span><h2>Recent CPD administration changes</h2><div className="stageList">{audit.map(row=><div className="stageRow" key={row.id}><div className="stageRowMain"><strong>{row.summary?.title||row.entity_type}</strong><span>{row.action} · {row.entity_type}</span><small>{new Date(row.occurred_at).toLocaleString('en-GB')}</small></div></div>)}{!audit.length&&<div className="emptyCompact">No audited changes yet.</div>}</div></section>}
  </main>;
}
