"use client";

import { useEffect, useMemo, useState } from "react";
import { courses } from "@/lib/catalogue";
import { getSupabaseBrowserClient } from "@/lib/supabase";
import { addDays, formatWorkflowDate, getInductionTemplate, type InductionRole } from "@/lib/schoolWorkflows";

type Profile={id:string;full_name:string;role:string;department:string;organisation_id:string|null};
type Assignment={id:string;organisation_id:string;user_id:string;role_focus:string;start_date:string;target_date:string|null;mentor_id:string|null;status:string;created_by:string;created_at:string};
type Task={id:string;assignment_id:string;title:string;description:string;task_type:string;linked_course_id:string|null;linked_policy_id:string|null;due_date:string|null;status:string;completed_at:string|null;staff_note:string;sort_order:number};
type Progress={course_id:string;completed_at:string|null};
const roles:InductionRole[]=["ECT","Teacher","Teaching Assistant","Pastoral","Middle Leader","Support Staff"];

export default function InductionPage(){
  const [me,setMe]=useState<Profile|null>(null);const [staff,setStaff]=useState<Profile[]>([]);const [assignments,setAssignments]=useState<Assignment[]>([]);const [tasks,setTasks]=useState<Task[]>([]);const [progress,setProgress]=useState<Progress[]>([]);const [loading,setLoading]=useState(true);const [notice,setNotice]=useState("");
  const [newUser,setNewUser]=useState("");const [newRole,setNewRole]=useState<InductionRole>("Teacher");const [startDate,setStartDate]=useState(new Date().toISOString().slice(0,10));const [targetDate,setTargetDate]=useState(addDays(new Date(),60));const [mentor,setMentor]=useState("");
  const isAdmin=Boolean(me&&["CPD Lead","Admin"].includes(me.role));

  async function load(){
    const client=getSupabaseBrowserClient();const {data:auth}=await client.auth.getUser();if(!auth.user){window.location.href="/auth?next=/induction";return;}
    const {data:profile,error:pe}=await client.from("staff_profiles").select("id,full_name,role,department,organisation_id").eq("id",auth.user.id).maybeSingle();const p=(profile||null) as Profile|null;setMe(p);
    const admin=Boolean(p&&["CPD Lead","Admin"].includes(p.role));
    const [a,t,pr,s]=await Promise.all([
      client.from("staff_induction_assignments").select("*").order("created_at",{ascending:false}),
      client.from("staff_induction_tasks").select("*").order("sort_order"),
      client.from("staff_development_course_progress").select("course_id,completed_at").eq("user_id",auth.user.id),
      admin&&p?.organisation_id?client.from("staff_profiles").select("id,full_name,role,department,organisation_id").eq("organisation_id",p.organisation_id).order("full_name"):Promise.resolve({data:p?[p]:[],error:null}),
    ]);
    setAssignments((a.data||[]) as Assignment[]);setTasks((t.data||[]) as Task[]);setProgress((pr.data||[]) as Progress[]);setStaff((s.data||[]) as Profile[]);if(!newUser&&admin&&(s.data||[])[0])setNewUser((s.data||[])[0].id);setNotice([pe,a.error,t.error,pr.error,s.error].filter(Boolean).map(x=>x!.message).join(" · "));setLoading(false);
  }
  useEffect(()=>{void load();},[]);
  const completedCourses=new Set(progress.filter(p=>p.completed_at).map(p=>p.course_id));
  const myAssignments=assignments.filter(a=>a.user_id===me?.id||a.mentor_id===me?.id);const active=myAssignments.find(a=>a.user_id===me?.id&&a.status==="active")||myAssignments.find(a=>a.user_id===me?.id);
  const myTasks=active?tasks.filter(t=>t.assignment_id===active.id):[];
  const doneCount=myTasks.filter(t=>t.status==="completed"||(t.task_type==="course"&&t.linked_course_id&&completedCourses.has(t.linked_course_id))).length;
  const progressPercent=myTasks.length?Math.round(doneCount/myTasks.length*100):0;
  const nextTask=myTasks.find(t=>!(t.status==="completed"||(t.task_type==="course"&&t.linked_course_id&&completedCourses.has(t.linked_course_id))));
  const adminAssignments=useMemo(()=>assignments.filter(a=>a.user_id!==me?.id||isAdmin),[assignments,me,isAdmin]);

  async function updateTask(task:Task,status:string){
    const client=getSupabaseBrowserClient();const {error}=await client.from("staff_induction_tasks").update({status,completed_at:status==="completed"?new Date().toISOString():null,updated_at:new Date().toISOString()}).eq("id",task.id);if(error)return setNotice(error.message);await load();
  }
  async function saveTaskNote(task:Task,note:string){const client=getSupabaseBrowserClient();const {error}=await client.from("staff_induction_tasks").update({staff_note:note,updated_at:new Date().toISOString()}).eq("id",task.id);if(error)setNotice(error.message);}
  async function createInduction(){
    if(!isAdmin||!me?.organisation_id||!newUser)return;const client=getSupabaseBrowserClient();const {data:assignment,error}=await client.from("staff_induction_assignments").insert({organisation_id:me.organisation_id,user_id:newUser,role_focus:newRole,start_date:startDate,target_date:targetDate||null,mentor_id:mentor||null,status:"active",created_by:me.id}).select("id").single();if(error)return setNotice(error.message);
    const template=getInductionTemplate(newRole);const rows=template.map((item,index)=>{const course=item.courseKeyword?courses.find(c=>`${c.title} ${c.summary}`.toLowerCase().includes(item.courseKeyword!.toLowerCase())):null;return {assignment_id:assignment.id,title:item.title,description:item.description,task_type:item.taskType,linked_course_id:course?.id||null,linked_policy_id:null,due_date:addDays(startDate,item.dueOffsetDays),status:"pending",completed_at:null,staff_note:"",sort_order:index+1,created_by:me.id};});const {error:taskError}=await client.from("staff_induction_tasks").insert(rows);if(taskError)return setNotice(taskError.message);setNotice("Induction pathway created and tasks assigned.");await load();
  }
  async function updateAssignment(a:Assignment,status:string){const client=getSupabaseBrowserClient();const {error}=await client.from("staff_induction_assignments").update({status,updated_at:new Date().toISOString()}).eq("id",a.id);if(error)return setNotice(error.message);await load();}

  if(loading)return <main className="stagePage"><div className="stageCard">Loading induction hub…</div></main>;
  return <main className="stagePage schoolWorkflowPage"><section className="stageHero workflowHero"><span className="eyebrow">NEW STAFF INDUCTION</span><h1>A role-based onboarding pathway that connects policies, CPD and people.</h1><p>Give new staff a clear sequence for safeguarding, school systems, role-specific learning, mentor meetings and early review without creating another spreadsheet.</p><div className="stageHeroActions"><a className="primary phaseLinkButton" href="/knowledge-base">School Knowledge</a><a className="secondary phaseLinkButton" href="/compliance">Mandatory training</a><a className="secondary phaseLinkButton" href="/dashboard">Dashboard</a></div></section>{notice&&<div className="phaseNotice">{notice}</div>}
    <section className="workflowStats"><div><strong>{active?progressPercent:0}%</strong><span>my induction progress</span></div><div><strong>{myTasks.length}</strong><span>assigned induction tasks</span></div><div><strong>{doneCount}</strong><span>completed</span></div><div><strong>{active?.target_date?formatWorkflowDate(active.target_date):"—"}</strong><span>target completion</span></div></section>
    <section className="stageGrid"><article className="stageCard stageSpan8"><span className="eyebrow">MY INDUCTION</span><h2>{active?`${active.role_focus} induction`:"No active induction"}</h2>{active?<><div className="workflowProgress"><span style={{width:`${progressPercent}%`}}/></div>{nextTask&&<div className="workflowNext"><span>NEXT</span><strong>{nextTask.title}</strong><p>{nextTask.description}</p></div>}<div className="stageList">{myTasks.map(task=>{const courseDone=Boolean(task.task_type==="course"&&task.linked_course_id&&completedCourses.has(task.linked_course_id));const done=task.status==="completed"||courseDone;return <div className="workflowTask" key={task.id}><div className={`workflowTaskIcon ${done?"done":""}`}>{done?"✓":"○"}</div><div className="workflowTaskMain"><strong>{task.title}</strong><p>{task.description}</p><small>{task.due_date?`Due ${formatWorkflowDate(task.due_date)}`:"No due date"}{courseDone?" · CPD completion detected":""}</small><textarea defaultValue={task.staff_note} placeholder="Optional induction note" onBlur={e=>saveTaskNote(task,e.target.value)}/></div><div className="workflowTaskActions">{task.task_type==="course"&&task.linked_course_id&&<a className="secondary phaseLinkButton" href={`/cpd?course=${encodeURIComponent(task.linked_course_id)}`}>Open CPD</a>}{task.task_type==="policy"&&<a className="secondary phaseLinkButton" href="/knowledge-base">Open policies</a>}{!done&&<button className="primary" onClick={()=>updateTask(task,"completed")}>Complete</button>}{done&&task.status==="completed"&&<button className="secondary" onClick={()=>updateTask(task,"pending")}>Reopen</button>}</div></div>})}</div></>:<div className="emptyCompact">Your school has not assigned an induction pathway yet.</div>}</article>
      <aside className="stageCard stageSpan4"><span className="eyebrow">INDUCTION SUPPORT</span><h2>What good onboarding covers</h2><div className="workflowChecklist"><div>Safeguarding and reporting routes</div><div>Current school policies</div><div>Systems and day-to-day routines</div><div>Role-specific professional learning</div><div>Named mentor/line-manager contact</div><div>30–60 day review and next target</div></div>{active?.mentor_id&&<p className="workflowPrivacy">A mentor is linked to this pathway and can see its task progress.</p>}</aside></section>
    {isAdmin&&<><section className="stageGrid"><article className="stageCard stageSpan5"><span className="eyebrow">ASSIGN INDUCTION</span><h2>Create a role-based pathway</h2><div className="workflowForm"><select value={newUser} onChange={e=>setNewUser(e.target.value)}>{staff.map(person=><option key={person.id} value={person.id}>{person.full_name} · {person.department}</option>)}</select><select value={newRole} onChange={e=>setNewRole(e.target.value as InductionRole)}>{roles.map(role=><option key={role}>{role}</option>)}</select><label>Start date<input type="date" value={startDate} onChange={e=>{setStartDate(e.target.value);setTargetDate(addDays(e.target.value,60))}}/></label><label>Target date<input type="date" value={targetDate} onChange={e=>setTargetDate(e.target.value)}/></label><select value={mentor} onChange={e=>setMentor(e.target.value)}><option value="">No mentor selected</option>{staff.filter(person=>person.id!==newUser).map(person=><option key={person.id} value={person.id}>{person.full_name}</option>)}</select><button className="primary" onClick={createInduction}>Create induction</button></div></article><article className="stageCard stageSpan7"><span className="eyebrow">INDUCTION OVERVIEW</span><h2>Current new-staff pathways</h2><div className="stageList">{adminAssignments.map(a=>{const aTasks=tasks.filter(t=>t.assignment_id===a.id);const done=aTasks.filter(t=>t.status==="completed").length;const person=staff.find(s=>s.id===a.user_id);return <div className="stageRow" key={a.id}><div className="stageRowMain"><strong>{person?.full_name||"Staff member"} · {a.role_focus}</strong><span>{done}/{aTasks.length} tasks complete · {a.status}</span><small>{a.target_date?`Target ${formatWorkflowDate(a.target_date)}`:"No target date"}</small></div>{a.status==="active"&&<button className="secondary" onClick={()=>updateAssignment(a,"completed")}>Sign off</button>}</div>})}{!adminAssignments.length&&<div className="emptyCompact">No induction pathways have been assigned yet.</div>}</div></article></section></>}
  </main>;
}
