"use client";

import { useEffect, useMemo, useState } from "react";
import { courses } from "@/lib/catalogue";
import { getSupabaseBrowserClient } from "@/lib/supabase";
import { formatWorkflowDate } from "@/lib/schoolWorkflows";

type Profile={id:string;full_name:string;role:string;department:string;organisation_id:string|null};
type Plan={id:string;organisation_id:string;department:string;academic_year:string;title:string;priorities:string[];target_hours:number;status:string;created_by:string;created_at:string};
type Action={id:string;plan_id:string;title:string;owner_label:string;due_date:string|null;linked_course_id:string|null;evidence_expected:string;status:string;notes:string;created_by:string};
type Walk={id:string;department:string;observed_on:string;focus:string;strengths:string[];development_points:string[];signals:Record<string,unknown>;recommended_course_ids:string[];shared_for_aggregate:boolean};
type Impact={id:string;user_id:string;source_title:string;review_stage:string;implementation_status:string|null;evidence_type:string;impact_note:string;shared_with_leadership:boolean;reviewed_at:string|null};

export default function DepartmentsPage(){
  const [me,setMe]=useState<Profile|null>(null);const [plans,setPlans]=useState<Plan[]>([]);const [actions,setActions]=useState<Action[]>([]);const [walks,setWalks]=useState<Walk[]>([]);const [impact,setImpact]=useState<Impact[]>([]);const [staff,setStaff]=useState<Profile[]>([]);const [loading,setLoading]=useState(true);const [notice,setNotice]=useState("");
  const [title,setTitle]=useState("");const [year,setYear]=useState("2026/27");const [priorities,setPriorities]=useState("");const [targetHours,setTargetHours]=useState("10");const [selectedPlan,setSelectedPlan]=useState("");const [actionTitle,setActionTitle]=useState("");const [owner,setOwner]=useState("");const [dueDate,setDueDate]=useState("");const [courseId,setCourseId]=useState("");const [evidenceExpected,setEvidenceExpected]=useState("");
  const canManage=Boolean(me&&["Department Lead","CPD Lead","Admin"].includes(me.role));const isOrgAdmin=Boolean(me&&["CPD Lead","Admin"].includes(me.role));

  async function load(){
    const client=getSupabaseBrowserClient();const {data:auth}=await client.auth.getUser();if(!auth.user){window.location.href="/auth?next=/departments";return;}
    const {data:profile,error:pe}=await client.from("staff_profiles").select("id,full_name,role,department,organisation_id").eq("id",auth.user.id).maybeSingle();const p=(profile||null) as Profile|null;setMe(p);setOwner(p?.full_name||"");
    const [pl,ac,lw,im,sp]=await Promise.all([
      client.from("department_cpd_plans").select("*").order("created_at",{ascending:false}),
      client.from("department_cpd_actions").select("*").order("due_date",{ascending:true}),
      client.from("learning_walks").select("id,department,observed_on,focus,strengths,development_points,signals,recommended_course_ids,shared_for_aggregate").eq("shared_for_aggregate",true).order("observed_on",{ascending:false}),
      client.from("cpd_impact_reviews").select("id,user_id,source_title,review_stage,implementation_status,evidence_type,impact_note,shared_with_leadership,reviewed_at").eq("shared_with_leadership",true).not("reviewed_at","is",null).order("reviewed_at",{ascending:false}),
      p&&["CPD Lead","Admin"].includes(p.role)&&p.organisation_id?client.from("staff_profiles").select("id,full_name,role,department,organisation_id").eq("organisation_id",p.organisation_id):Promise.resolve({data:[],error:null}),
    ]);
    setPlans((pl.data||[]) as Plan[]);setActions((ac.data||[]) as Action[]);setWalks((lw.data||[]) as Walk[]);setImpact((im.data||[]) as Impact[]);setStaff((sp.data||[]) as Profile[]);if(!selectedPlan&&(pl.data||[])[0])setSelectedPlan((pl.data||[])[0].id);setNotice([pe,pl.error,ac.error,lw.error,im.error,sp.error].filter(Boolean).map(x=>x!.message).join(" · "));setLoading(false);
  }
  useEffect(()=>{void load();},[]);
  const department=me?.department||"Whole school";
  const departmentPlans=plans.filter(p=>isOrgAdmin?true:p.department===department);const activePlan=departmentPlans.find(p=>p.id===selectedPlan)||departmentPlans[0];const planActions=activePlan?actions.filter(a=>a.plan_id===activePlan.id):[];
  const departmentWalks=walks.filter(w=>w.department===department);
  const developmentThemes=useMemo(()=>frequency(departmentWalks.flatMap(w=>w.development_points)).slice(0,5),[departmentWalks]);
  const strengths=useMemo(()=>frequency(departmentWalks.flatMap(w=>w.strengths)).slice(0,5),[departmentWalks]);
  const recommendedIds=useMemo(()=>frequency(departmentWalks.flatMap(w=>w.recommended_course_ids)).slice(0,5),[departmentWalks]);
  const filteredImpact=useMemo(()=>{
    if(!isOrgAdmin)return impact;
    const ids=new Set(staff.filter(s=>s.department===department).map(s=>s.id));return impact.filter(i=>ids.has(i.user_id));
  },[impact,staff,isOrgAdmin,department]);
  const implementation=frequency(filteredImpact.map(i=>i.implementation_status||"not recorded"));

  async function createPlan(){
    if(!canManage||!me?.organisation_id||!title.trim())return;const client=getSupabaseBrowserClient();const {error}=await client.from("department_cpd_plans").insert({organisation_id:me.organisation_id,department,title:title.trim(),academic_year:year.trim(),priorities:priorities.split(/\n|,/).map(v=>v.trim()).filter(Boolean),target_hours:Number(targetHours)||0,status:"active",created_by:me.id});if(error)return setNotice(error.message);setTitle("");setPriorities("");setNotice("Department development plan created.");await load();
  }
  async function addAction(){
    if(!canManage||!me||!selectedPlan||!actionTitle.trim())return setNotice("Choose a plan and add an action title.");const client=getSupabaseBrowserClient();const {error}=await client.from("department_cpd_actions").insert({plan_id:selectedPlan,title:actionTitle.trim(),owner_label:owner.trim()||"Department team",due_date:dueDate||null,linked_course_id:courseId||null,evidence_expected:evidenceExpected.trim()||"Evidence that the agreed action has been implemented and reviewed.",status:"planned",notes:"",created_by:me.id});if(error)return setNotice(error.message);setActionTitle("");setDueDate("");setCourseId("");setEvidenceExpected("");setNotice("Department action added.");await load();
  }
  async function updateAction(action:Action,status:string){const client=getSupabaseBrowserClient();const {error}=await client.from("department_cpd_actions").update({status,updated_at:new Date().toISOString()}).eq("id",action.id);if(error)return setNotice(error.message);await load();}

  if(loading)return <main className="stagePage"><div className="stageCard">Loading department hub…</div></main>;
  return <main className="stagePage schoolWorkflowPage"><section className="stageHero workflowHero"><span className="eyebrow">DEPARTMENT DEVELOPMENT HUB</span><h1>{department} development in one place.</h1><p>Connect department priorities, CPD actions, learning-walk themes and shared implementation evidence without creating individual teacher scores.</p><div className="stageHeroActions"><a className="primary phaseLinkButton" href="/learning-walks">Learning Walks</a><a className="secondary phaseLinkButton" href="/improvement/programmes">Improvement → CPD</a><a className="secondary phaseLinkButton" href="/facilitator">Facilitator packs</a></div></section>{notice&&<div className="phaseNotice">{notice}</div>}
    <section className="workflowStats"><div><strong>{departmentPlans.length}</strong><span>development plans</span></div><div><strong>{planActions.filter(a=>a.status!=="complete").length}</strong><span>open actions</span></div><div><strong>{departmentWalks.length}</strong><span>shared learning walks</span></div><div><strong>{filteredImpact.length}</strong><span>shared impact reviews</span></div></section>
    <section className="stageGrid"><article className="stageCard stageSpan8"><span className="eyebrow">DEPARTMENT PLAN</span><div className="workflowHeadingRow"><div><h2>{activePlan?.title||"No department development plan"}</h2>{activePlan&&<p>{activePlan.academic_year} · target {activePlan.target_hours} CPD hours</p>}</div>{departmentPlans.length>1&&<select value={activePlan?.id||""} onChange={e=>setSelectedPlan(e.target.value)}>{departmentPlans.map(p=><option key={p.id} value={p.id}>{p.department} · {p.title}</option>)}</select>}</div>{activePlan?<><div className="workflowPills">{activePlan.priorities.map(priority=><span key={priority}>{priority}</span>)}</div><div className="stageList">{planActions.map(action=><div className="stageRow" key={action.id}><div className="stageRowMain"><strong>{action.title}</strong><span>{action.owner_label}{action.due_date?` · due ${formatWorkflowDate(action.due_date)}`:""}</span><small>Evidence: {action.evidence_expected}</small></div><span className={`stageBadge ${action.status==="complete"?"good":action.status==="in_progress"?"warn":""}`}>{action.status.replace("_"," ")}</span>{action.linked_course_id&&<a className="secondary phaseLinkButton" href={`/cpd?course=${encodeURIComponent(action.linked_course_id)}`}>Open CPD</a>}{canManage&&action.status!=="complete"&&<button className="secondary" onClick={()=>updateAction(action,action.status==="planned"?"in_progress":"complete")}>{action.status==="planned"?"Start":"Complete"}</button>}</div>)}{!planActions.length&&<div className="emptyCompact">No actions have been added yet.</div>}</div></>:<div className="emptyCompact">A Department Lead or CPD Lead can create the first plan below.</div>}</article>
      <aside className="stageCard stageSpan4"><span className="eyebrow">DEVELOPMENT SIGNALS</span><h2>What shared evidence is suggesting</h2><h3>Common strengths</h3><div className="workflowThemeList">{strengths.map(([label,count])=><div key={label}><span>{label}</span><b>{count}</b></div>)}{!strengths.length&&<p>No shared learning-walk strengths yet.</p>}</div><h3>Development themes</h3><div className="workflowThemeList">{developmentThemes.map(([label,count])=><div key={label}><span>{label}</span><b>{count}</b></div>)}{!developmentThemes.length&&<p>No shared development themes yet.</p>}</div></aside></section>
    <section className="stageGrid"><article className="stageCard stageSpan6"><span className="eyebrow">CPD RECOMMENDATIONS</span><h2>Courses appearing in learning-walk follow-up</h2><div className="stageList">{recommendedIds.map(([id,count])=>{const course=courses.find(c=>c.id===id);return <div className="stageRow" key={id}><div className="stageRowMain"><strong>{course?.title||id}</strong><span>Recommended from {count} shared learning-walk record{count===1?"":"s"}</span></div><a className="secondary phaseLinkButton" href={`/cpd?course=${encodeURIComponent(id)}`}>Open</a></div>})}{!recommendedIds.length&&<div className="emptyCompact">No course recommendations have emerged yet.</div>}</div></article><article className="stageCard stageSpan6"><span className="eyebrow">IMPLEMENTATION IMPACT</span><h2>Shared Phase 6 follow-through</h2><p className="workflowPrivacy">Only impact reviews staff chose to share with leadership are included. The hub shows patterns, not individual names or rankings.</p><div className="workflowThemeList">{implementation.map(([label,count])=><div key={label}><span>{label.replace("_"," ")}</span><b>{count}</b></div>)}{!implementation.length&&<p>No shared implementation reviews yet.</p>}</div></article></section>
    {canManage&&<section className="stageGrid"><article className="stageCard stageSpan5"><span className="eyebrow">NEW DEPARTMENT PLAN</span><h2>Set the development direction</h2><div className="workflowForm"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Plan title"/><input value={year} onChange={e=>setYear(e.target.value)} placeholder="Academic year"/><textarea value={priorities} onChange={e=>setPriorities(e.target.value)} placeholder="Priorities, separated by commas or new lines"/><label>Target CPD hours<input type="number" min="0" value={targetHours} onChange={e=>setTargetHours(e.target.value)}/></label><button className="primary" onClick={createPlan}>Create plan</button></div></article><article className="stageCard stageSpan7"><span className="eyebrow">ADD ACTION</span><h2>Turn the plan into practical work</h2><div className="workflowForm"><select value={selectedPlan} onChange={e=>setSelectedPlan(e.target.value)}><option value="">Choose plan</option>{departmentPlans.map(p=><option value={p.id} key={p.id}>{p.title}</option>)}</select><input value={actionTitle} onChange={e=>setActionTitle(e.target.value)} placeholder="Action"/><input value={owner} onChange={e=>setOwner(e.target.value)} placeholder="Owner / team"/><input type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)}/><select value={courseId} onChange={e=>setCourseId(e.target.value)}><option value="">Optional linked CPD</option>{courses.map(c=><option value={c.id} key={c.id}>{c.title}</option>)}</select><textarea value={evidenceExpected} onChange={e=>setEvidenceExpected(e.target.value)} placeholder="What evidence should the department review?"/><button className="primary" onClick={addAction}>Add action</button></div></article></section>}
  </main>;
}

function frequency(values:string[]):[string,number][]{const map=new Map<string,number>();values.filter(Boolean).forEach(value=>map.set(value,(map.get(value)||0)+1));return [...map.entries()].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]));}
