"use client";

import { useEffect, useMemo, useState } from "react";
import { courses } from "@/lib/catalogue";
import { microCpdUnits } from "@/lib/microCpd";
import { getSupabaseBrowserClient } from "@/lib/supabase";

type Profile={id:string;role:string;organisation_id:string|null;department:string};
type ImpactReview={id:string;source_type:"course"|"micro_cpd"|"external_cpd"|"action_plan";source_id:string;source_title:string;review_stage:"4_week"|"8_week"|"12_week"|"custom";due_on:string;reviewed_at:string|null;implementation_status:"not_started"|"trying"|"embedded"|"adapted"|"stopped"|null;confidence:number|null;evidence_type:string;impact_note:string;next_step:string;shared_with_leadership:boolean};
type CourseProgress={course_id:string;completed_at:string};
type MicroProgress={unit_id:string;completed_at:string};
type ExternalCpd={id:string;title:string;occurred_on:string};
type ActionPlan={id:string;title:string;start_date:string;status:string};
type Candidate={type:ImpactReview["source_type"];id:string;title:string;date:string};
type Aggregate={eligible:boolean;distinct_staff:number;total_reviews:number;reviewed:number;due_or_overdue:number;not_started:number;trying:number;embedded:number;adapted:number;stopped:number;average_confidence:number|null};
type Draft={status:NonNullable<ImpactReview["implementation_status"]>;confidence:number;evidence:string;note:string;next:string;share:boolean};

const stages:{id:ImpactReview["review_stage"];label:string;days:number}[]=[{id:"4_week",label:"4 weeks",days:28},{id:"8_week",label:"8 weeks",days:56},{id:"12_week",label:"12 weeks",days:84}];

export default function ImpactPage(){
  const [profile,setProfile]=useState<Profile|null>(null);const [reviews,setReviews]=useState<ImpactReview[]>([]);const [candidates,setCandidates]=useState<Candidate[]>([]);const [drafts,setDrafts]=useState<Record<string,Draft>>({});const [aggregate,setAggregate]=useState<Aggregate|null>(null);const [loading,setLoading]=useState(true);const [message,setMessage]=useState("");const [busy,setBusy]=useState("");
  useEffect(()=>{let live=true;(async()=>{const c=getSupabaseBrowserClient();const {data:auth}=await c.auth.getUser();if(!auth.user){window.location.href="/auth?next=/impact";return;}const {data:p,error:pe}=await c.from("staff_profiles").select("id,role,organisation_id,department").eq("id",auth.user.id).single();if(!live)return;if(pe||!p){setMessage(pe?.message||"Unable to load profile.");setLoading(false);return;}setProfile(p as Profile);const [r,cp,mp,ex,ap]=await Promise.all([
    c.from("cpd_impact_reviews").select("id,source_type,source_id,source_title,review_stage,due_on,reviewed_at,implementation_status,confidence,evidence_type,impact_note,next_step,shared_with_leadership").eq("user_id",auth.user.id).order("due_on"),
    c.from("course_progress").select("course_id,completed_at").eq("user_id",auth.user.id).not("completed_at","is",null).order("completed_at",{ascending:false}),
    c.from("micro_cpd_progress").select("unit_id,completed_at").eq("user_id",auth.user.id).order("completed_at",{ascending:false}),
    c.from("external_cpd_records").select("id,title,occurred_on").eq("user_id",auth.user.id).order("occurred_on",{ascending:false}),
    c.from("action_plans").select("id,title,start_date,status").eq("user_id",auth.user.id).order("start_date",{ascending:false}),
  ]);if(!live)return;const errors=[r.error,cp.error,mp.error,ex.error,ap.error].filter(Boolean);if(errors.length)setMessage(errors.map(e=>e?.message).join(" · "));const reviewRows=(r.data||[]) as ImpactReview[];setReviews(reviewRows);setDrafts(Object.fromEntries(reviewRows.map(row=>[row.id,toDraft(row)])));const courseMap=new Map(courses.map(x=>[x.id,x.title]));const microMap=new Map(microCpdUnits.map(x=>[x.id,x.title]));const nextCandidates:Candidate[]=[...((cp.data||[]) as CourseProgress[]).map(x=>({type:"course" as const,id:x.course_id,title:courseMap.get(x.course_id)||x.course_id,date:x.completed_at})),...((mp.data||[]) as MicroProgress[]).map(x=>({type:"micro_cpd" as const,id:x.unit_id,title:microMap.get(x.unit_id)||x.unit_id,date:x.completed_at})),...((ex.data||[]) as ExternalCpd[]).map(x=>({type:"external_cpd" as const,id:x.id,title:x.title,date:x.occurred_on})),...((ap.data||[]) as ActionPlan[]).filter(x=>x.status!=="planned").map(x=>({type:"action_plan" as const,id:x.id,title:x.title,date:x.start_date}))].sort((a,b)=>new Date(b.date).getTime()-new Date(a.date).getTime());setCandidates(nextCandidates.slice(0,30));if(["Department Lead","CPD Lead","Admin"].includes(p.role)){const {data,error}=await c.rpc("cpd_impact_aggregate");if(error)setMessage(prev=>[prev,error.message].filter(Boolean).join(" · "));else if(Array.isArray(data)&&data[0])setAggregate(data[0] as Aggregate);}setLoading(false);})();return()=>{live=false};},[]);

  const reviewKeys=useMemo(()=>new Set(reviews.map(r=>`${r.source_type}:${r.source_id}:${r.review_stage}`)),[reviews]);
  const pending=useMemo(()=>reviews.filter(r=>!r.reviewed_at).sort((a,b)=>a.due_on.localeCompare(b.due_on)),[reviews]);
  const history=useMemo(()=>reviews.filter(r=>r.reviewed_at).sort((a,b)=>(b.reviewed_at||"").localeCompare(a.reviewed_at||"")),[reviews]);
  const dueCount=pending.filter(r=>new Date(`${r.due_on}T23:59:59`).getTime()<Date.now()).length;

  async function schedule(candidate:Candidate){if(!profile)return;const missing=stages.filter(s=>!reviewKeys.has(`${candidate.type}:${candidate.id}:${s.id}`));if(!missing.length){setMessage("The 4, 8 and 12 week reviews are already scheduled for this CPD activity.");return;}setBusy(`schedule-${candidate.type}-${candidate.id}`);const c=getSupabaseBrowserClient();const rows=missing.map(stage=>({user_id:profile.id,organisation_id:profile.organisation_id,source_type:candidate.type,source_id:candidate.id,source_title:candidate.title,review_stage:stage.id,due_on:addDays(candidate.date,stage.days)}));const {data,error}=await c.from("cpd_impact_reviews").insert(rows).select("id,source_type,source_id,source_title,review_stage,due_on,reviewed_at,implementation_status,confidence,evidence_type,impact_note,next_step,shared_with_leadership");setBusy("");if(error){setMessage(error.message);return;}const created=(data||[]) as ImpactReview[];setReviews(prev=>[...prev,...created]);setDrafts(prev=>({...prev,...Object.fromEntries(created.map(row=>[row.id,toDraft(row)]))}));setMessage(`Scheduled ${missing.length} impact review${missing.length===1?"":"s"} for ${candidate.title}.`);}

  async function saveReview(review:ImpactReview){const draft=drafts[review.id];if(!draft)return;if(draft.note.trim().length<12){setMessage("Add a short impact note before saving the review.");return;}setBusy(review.id);const c=getSupabaseBrowserClient();const patch={implementation_status:draft.status,confidence:draft.confidence,evidence_type:draft.evidence,impact_note:draft.note.trim(),next_step:draft.next.trim(),shared_with_leadership:draft.share,reviewed_at:new Date().toISOString(),updated_at:new Date().toISOString()};const {data,error}=await c.from("cpd_impact_reviews").update(patch).eq("id",review.id).select("id,source_type,source_id,source_title,review_stage,due_on,reviewed_at,implementation_status,confidence,evidence_type,impact_note,next_step,shared_with_leadership").single();setBusy("");if(error){setMessage(error.message);return;}setReviews(prev=>prev.map(r=>r.id===review.id?data as ImpactReview:r));setMessage("Impact review saved to your private CPD record.");}

  function updateDraft(id:string,patch:Partial<Draft>){setDrafts(prev=>({...prev,[id]:{...prev[id],...patch}}));}

  if(loading)return <main className="stagePage"><div className="stageCard">Loading CPD impact reviews…</div></main>;
  return <main className="stagePage impactPage"><section className="stageHero impactHero"><span className="eyebrow">CPD IMPACT · 4 / 8 / 12 WEEK REVIEW</span><h1>Track what changed after the training.</h1><p>Schedule follow-ups from completed courses, Micro-CPD, external development or action plans. Your impact note stays private; leadership analytics use aggregate patterns only and require at least three staff in the cohort.</p></section>{message&&<div className="phaseNotice">{message}</div>}
    <section className="stageStatGrid"><div className="stageStat"><strong>{pending.length}</strong><span>reviews scheduled</span></div><div className="stageStat"><strong>{dueCount}</strong><span>due / overdue</span></div><div className="stageStat"><strong>{history.length}</strong><span>reviews completed</span></div><div className="stageStat"><strong>{reviews.filter(r=>r.shared_with_leadership).length}</strong><span>explicitly shared</span></div></section>

    <section className="stageCard"><span className="eyebrow">TRACK RECENT CPD</span><h2>Schedule follow-up checkpoints</h2><p className="impactIntro">Choose CPD where you actually intended to change practice. The app creates review checkpoints 4, 8 and 12 weeks from the original activity date.</p><div className="impactCandidates">{candidates.map(item=>{const scheduled=stages.filter(s=>reviewKeys.has(`${item.type}:${item.id}:${s.id}`)).length;return <div key={`${item.type}-${item.id}`}><div><span>{labelSource(item.type)} · {formatDate(item.date)}</span><strong>{item.title}</strong><small>{scheduled}/3 checkpoints scheduled</small></div><button className={scheduled===3?"secondary":"primary"} disabled={scheduled===3||busy===`schedule-${item.type}-${item.id}`} onClick={()=>schedule(item)}>{scheduled===3?"Scheduled":busy?"Scheduling…":"Schedule 4/8/12 weeks"}</button></div>})}{!candidates.length&&<div className="emptyCompact">Complete a course, Micro-CPD unit, external CPD record or active action plan to start impact tracking.</div>}</div></section>

    <section className="stageCard"><span className="eyebrow">YOUR REVIEW QUEUE</span><h2>What happened when you tried it?</h2><div className="impactReviewList">{pending.map(review=>{const draft=drafts[review.id]||toDraft(review);const overdue=new Date(`${review.due_on}T23:59:59`).getTime()<Date.now();return <details className={`impactReview ${overdue?"overdue":""}`} key={review.id} open={overdue}><summary><div><span>{stageLabel(review.review_stage)} · due {formatDate(review.due_on)}</span><strong>{review.source_title}</strong></div><b>{overdue?"Due now":"Scheduled"}</b></summary><div className="impactForm"><label>Implementation status<select value={draft.status} onChange={e=>updateDraft(review.id,{status:e.target.value as Draft["status"]})}><option value="not_started">Not started</option><option value="trying">Trying it</option><option value="embedded">Embedded in practice</option><option value="adapted">Adapted after testing</option><option value="stopped">Stopped / not useful here</option></select></label><label>Confidence now · {draft.confidence}/5<input type="range" min="1" max="5" value={draft.confidence} onChange={e=>updateDraft(review.id,{confidence:Number(e.target.value)})}/></label><label>Evidence used<select value={draft.evidence} onChange={e=>updateDraft(review.id,{evidence:e.target.value})}><option value="none">No formal evidence</option><option value="pupil_work">Pupil work</option><option value="assessment">Assessment evidence</option><option value="observation">Observation / coaching</option><option value="feedback">Pupil / colleague feedback</option><option value="self_reflection">Professional reflection</option><option value="other">Other</option></select></label><label className="full">What changed?<textarea rows={3} value={draft.note} onChange={e=>updateDraft(review.id,{note:e.target.value})} placeholder="Briefly describe what you noticed in practice…"/></label><label className="full">Next step<textarea rows={2} value={draft.next} onChange={e=>updateDraft(review.id,{next:e.target.value})} placeholder="Keep, adapt, revisit or stop?"/></label><label className="full impactShare"><input type="checkbox" checked={draft.share} onChange={e=>updateDraft(review.id,{share:e.target.checked})}/>Allow authorised CPD leadership to know this review was explicitly shared. Private impact-note text is not included in the aggregate dashboard.</label><button className="primary" disabled={busy===review.id} onClick={()=>saveReview(review)}>{busy===review.id?"Saving…":"Save impact review"}</button></div></details>})}{!pending.length&&<div className="emptyCompact">No impact reviews are waiting. Schedule one from recent CPD above.</div>}</div></section>

    {profile&&["Department Lead","CPD Lead","Admin"].includes(profile.role)&&<section className="stageCard impactLeadership"><span className="eyebrow">AGGREGATE LEADERSHIP VIEW</span><h2>Implementation patterns, not staff scores</h2>{aggregate?.eligible?<><div className="impactAggregateStats"><div><strong>{aggregate.distinct_staff}</strong><span>staff represented</span></div><div><strong>{aggregate.reviewed}</strong><span>reviews completed</span></div><div><strong>{aggregate.due_or_overdue}</strong><span>due / overdue</span></div><div><strong>{aggregate.average_confidence??"—"}</strong><span>average confidence</span></div></div><div className="impactStatusBars">{(["not_started","trying","embedded","adapted","stopped"] as const).map(key=><div key={key}><span>{statusLabel(key)}</span><progress max={Math.max(1,aggregate.reviewed)} value={aggregate[key]}/><b>{aggregate[key]}</b></div>)}</div></>:<div className="impactPrivacyGate"><strong>Aggregate view hidden until at least three staff are represented.</strong><p>This threshold reduces the chance that an individual staff member's implementation status can be inferred from a small cohort.</p></div>}</section>}

    {history.length>0&&<section className="stageCard"><span className="eyebrow">REVIEW HISTORY</span><h2>Your completed impact checks</h2><div className="impactHistory">{history.slice(0,12).map(r=><div key={r.id}><div><strong>{r.source_title}</strong><span>{stageLabel(r.review_stage)} · {statusLabel(r.implementation_status||"not_started")}</span></div><p>{r.impact_note}</p><small>{r.reviewed_at?formatDate(r.reviewed_at):formatDate(r.due_on)}{r.shared_with_leadership?" · explicitly shared":" · private"}</small></div>)}</div></section>}

    <section className="stageCard impactBoundary"><strong>Impact is contextual.</strong><p>This dashboard records professional implementation and evidence chosen by staff. It does not calculate a teacher-quality score, rank staff, or claim that a single CPD activity caused pupil outcomes.</p></section>
  </main>;
}

function toDraft(r:ImpactReview):Draft{return {status:r.implementation_status||"trying",confidence:r.confidence||3,evidence:r.evidence_type||"none",note:r.impact_note||"",next:r.next_step||"",share:r.shared_with_leadership};}
function addDays(value:string,days:number){const d=new Date(value.length===10?`${value}T12:00:00Z`:value);d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10);}
function formatDate(value:string){return new Date(value.length===10?`${value}T12:00:00`:value).toLocaleDateString("en-GB",{day:"numeric",month:"short",year:"numeric"});}
function labelSource(type:Candidate["type"]){return type==="course"?"Course":type==="micro_cpd"?"Micro-CPD":type==="external_cpd"?"External CPD":"Action plan";}
function stageLabel(stage:ImpactReview["review_stage"]){return stage==="4_week"?"4-week review":stage==="8_week"?"8-week review":stage==="12_week"?"12-week review":"Custom review";}
function statusLabel(status:NonNullable<ImpactReview["implementation_status"]>){return status==="not_started"?"Not started":status==="trying"?"Trying":status==="embedded"?"Embedded":status==="adapted"?"Adapted":"Stopped";}
