"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { getSupabaseBrowserClient } from "@/lib/supabase";

type Profile={id:string;role:string;organisation_id:string|null};
type Site={id:string;name:string;code:string;active:boolean};
type Domain={domain:string;status:string};
type Row={id?:string;email:string;full_name:string;department:string;role:string;site_id:string|null;active:boolean;source:string};
type ImportRow={email:string;full_name:string;department:string;role:string;site_code:string};
const roles=["Staff","Department Lead","CPD Lead","Admin"];

export default function StaffSyncPage(){
  const [profile,setProfile]=useState<Profile|null>(null);const [sites,setSites]=useState<Site[]>([]);const [domains,setDomains]=useState<Domain[]>([]);const [rows,setRows]=useState<Row[]>([]);const [preview,setPreview]=useState<ImportRow[]>([]);const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);
  const admin=Boolean(profile&&profile.role==="Admin");
  useEffect(()=>{let live=true;(async()=>{const c=getSupabaseBrowserClient();const {data:auth}=await c.auth.getUser();if(!auth.user){window.location.href="/admin-login";return;}const {data:p,error}=await c.from("staff_profiles").select("id,role,organisation_id").eq("id",auth.user.id).single();if(!live)return;if(error||!p){setMessage(error?.message||"Unable to load profile.");setLoading(false);return;}setProfile(p as Profile);if(!p.organisation_id){setLoading(false);return;}const [s,d,r]=await Promise.all([c.from("school_sites").select("id,name,code,active").eq("organisation_id",p.organisation_id).eq("active",true).order("name"),c.from("organisation_domains").select("domain,status").eq("organisation_id",p.organisation_id),c.from("organisation_staff_directory").select("id,email,full_name,department,role,site_id,active,source").eq("organisation_id",p.organisation_id).order("email")]);if(!live)return;setSites((s.data||[]) as Site[]);setDomains((d.data||[]) as Domain[]);setRows((r.data||[]) as Row[]);setLoading(false);})();return()=>{live=false};},[]);

  async function addManual(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!profile?.organisation_id||!admin)return;const f=e.currentTarget,fd=new FormData(f),email=String(fd.get("email")||"").trim().toLowerCase();if(!allowedEmail(email)){setMessage("That email does not use one of this school's registered domains.");return;}const c=getSupabaseBrowserClient();setBusy(true);const {data,error}=await c.from("organisation_staff_directory").upsert({organisation_id:profile.organisation_id,email,full_name:String(fd.get("full_name")||"").trim(),department:String(fd.get("department")||"").trim(),role:String(fd.get("role")||"Staff"),site_id:String(fd.get("site_id")||"")||null,active:true,source:"manual",created_by:profile.id,updated_at:new Date().toISOString()},{onConflict:"organisation_id,email"}).select("id,email,full_name,department,role,site_id,active,source").single();setBusy(false);if(error){setMessage(error.message);return;}setRows(prev=>[...prev.filter(x=>x.email!==email),data as Row].sort((a,b)=>a.email.localeCompare(b.email)));f.reset();setMessage("Staff provisioning record saved. It will apply automatically when this person signs in.");}

  async function remove(id:string|undefined){if(!id||!admin)return;const c=getSupabaseBrowserClient();const {error}=await c.from("organisation_staff_directory").delete().eq("id",id);if(error)setMessage(error.message);else{setRows(prev=>prev.filter(r=>r.id!==id));setMessage("Provisioning record removed.");}}

  async function importCsv(){if(!profile?.organisation_id||!admin||!preview.length)return;const c=getSupabaseBrowserClient();setBusy(true);const invalid=preview.filter(r=>!allowedEmail(r.email)||!roles.includes(normaliseRole(r.role)));if(invalid.length){setBusy(false);setMessage(`${invalid.length} row(s) need fixing before import. Check school domain and role values.`);return;}const payload=preview.map(r=>({organisation_id:profile.organisation_id,email:r.email.toLowerCase(),full_name:r.full_name,department:r.department,role:normaliseRole(r.role),site_id:siteForCode(r.site_code)?.id||null,active:true,source:"csv",created_by:profile.id,updated_at:new Date().toISOString()}));const {data,error}=await c.from("organisation_staff_directory").upsert(payload,{onConflict:"organisation_id,email"}).select("id,email,full_name,department,role,site_id,active,source");setBusy(false);if(error){setMessage(error.message);return;}const imported=(data||[]) as Row[];setRows(prev=>{const emails=new Set(imported.map(r=>r.email));return [...prev.filter(r=>!emails.has(r.email)),...imported].sort((a,b)=>a.email.localeCompare(b.email));});setPreview([]);setMessage(`${imported.length} staff record(s) imported. Their school login will pick up these details automatically.`);}

  function readCsv(file:File){const reader=new FileReader();reader.onload=()=>{try{const parsed=parseCsv(String(reader.result||""));setPreview(parsed);setMessage(parsed.length?`Preview ready: ${parsed.length} staff row(s). Review before importing.`:"No staff rows found in the CSV.");}catch(e){setMessage(e instanceof Error?e.message:"Unable to read CSV.");}};reader.readAsText(file);}
  function allowedEmail(email:string){const domain=email.split("@")[1]?.toLowerCase();return Boolean(domain&&domains.some(d=>d.domain===domain&&["pending","verified"].includes(d.status)));}
  function siteForCode(code:string){return sites.find(s=>s.code.toLowerCase()===code.toLowerCase()||s.name.toLowerCase()===code.toLowerCase());}
  const verified=domains.filter(d=>d.status==="verified").map(d=>`@${d.domain}`);
  const stats=useMemo(()=>({total:rows.filter(r=>r.active).length,leaders:rows.filter(r=>r.active&&r.role!=="Staff").length,departments:new Set(rows.filter(r=>r.department).map(r=>r.department)).size}),[rows]);

  if(loading)return <main className="stagePage"><div className="stageCard">Loading staff sync…</div></main>;
  if(!admin)return <main className="stagePage"><section className="stageHero"><span className="eyebrow">STAFF SYNC</span><h1>School Admin access required.</h1><p>Pre-provisioning can assign elevated permissions, so this area is restricted to School Admin accounts.</p><div className="stageHeroActions"><a className="primary phaseLinkButton" href="/admin-login">Admin sign in</a></div></section></main>;
  if(!profile?.organisation_id)return <main className="stagePage"><section className="stageHero"><span className="eyebrow">STAFF SYNC</span><h1>Connect an organisation first.</h1></section></main>;

  return <main className="stagePage staffSyncPage"><section className="stageHero staffSyncHero"><span className="eyebrow">SCHOOL ADMIN · STAFF DIRECTORY</span><h1>Prepare staff before they sign in.</h1><p>Import a simple school staff list or add individuals manually. Staff do not need to be imported to create an account: anyone on the verified school domain can join as Staff automatically. Pre-provisioning is for department, site or higher-access setup.</p><div className="stageHeroActions"><a className="secondary phaseLinkButton" href="/staff-access">Manage existing staff</a><a className="secondary phaseLinkButton" href="/school-access">School domains</a></div></section>{message&&<div className="phaseNotice">{message}</div>}
    <section className="stageStatGrid"><div className="stageStat"><strong>{stats.total}</strong><span>provisioned staff</span></div><div className="stageStat"><strong>{stats.leaders}</strong><span>lead/admin roles</span></div><div className="stageStat"><strong>{stats.departments}</strong><span>departments</span></div><div className="stageStat"><strong>{verified.length}</strong><span>verified domains</span></div></section>
    <section className="stageGrid"><div className="stageCard stageSpan5"><span className="eyebrow">CSV IMPORT</span><h2>Upload staff directory</h2><p>Accepted columns: <code>email,full_name,department,role,site_code</code>. Role can be Staff, Department Lead, CPD Lead or Admin.</p><input className="staffCsvInput" type="file" accept=".csv,text/csv" onChange={e=>{const f=e.target.files?.[0];if(f)readCsv(f);}}/><a className="textButton" href={`data:text/csv;charset=utf-8,${encodeURIComponent("email,full_name,department,role,site_code\nteacher@school.org.uk,Example Teacher,Science,Staff,MAIN")}`} download="teaching-cpd-staff-template.csv">Download CSV template</a>{preview.length>0&&<><div className="staffImportPreview"><strong>Import preview</strong>{preview.slice(0,8).map((r,i)=><div key={`${r.email}-${i}`} className={allowedEmail(r.email)&&roles.includes(normaliseRole(r.role))?"":"invalid"}><span>{r.email}</span><span>{r.full_name||"—"}</span><span>{normaliseRole(r.role)}</span><span>{r.site_code||"Default site"}</span></div>)}{preview.length>8&&<small>+ {preview.length-8} more rows</small>}</div><button className="primary" disabled={busy} onClick={importCsv}>{busy?"Importing…":`Import ${preview.length} staff`}</button></>}</div>
      <div className="stageCard stageSpan7"><span className="eyebrow">MANUAL PROVISIONING</span><h2>Add or update one staff member</h2><form className="staffManualForm" onSubmit={addManual}><label>School email<input required type="email" name="email" placeholder={verified[0]?`name${verified[0]}`:"name@school.org.uk"}/></label><label>Full name<input name="full_name"/></label><label>Department<input name="department"/></label><label>Role<select name="role">{roles.map(r=><option key={r}>{r}</option>)}</select></label><label>Site<select name="site_id"><option value="">Default / first site</option>{sites.map(s=><option key={s.id} value={s.id}>{s.name} ({s.code})</option>)}</select></label><button className="primary" disabled={busy}>Save provisioning record</button></form><div className="staffDomainNote"><strong>Registered domains</strong><span>{domains.length?domains.map(d=>`@${d.domain} (${d.status})`).join(" · "):"No school domain registered yet."}</span></div></div></section>
    <section className="stageCard"><span className="eyebrow">PROVISIONED DIRECTORY</span><h2>Staff waiting / configured for school login</h2><div className="staffDirectoryTable"><div className="staffDirectoryHead"><span>Email</span><span>Name</span><span>Department</span><span>Role</span><span>Site</span><span/></div>{rows.map(r=><div key={r.id||r.email}><span>{r.email}</span><span>{r.full_name||"—"}</span><span>{r.department||"—"}</span><span>{r.role}</span><span>{sites.find(s=>s.id===r.site_id)?.code||"Default"}</span><button className="textButton" onClick={()=>remove(r.id)}>Remove</button></div>)}{!rows.length&&<p className="muted">No provisioning records yet. Staff can still join automatically from the verified school domain as Staff.</p>}</div></section>
  </main>;
}

function normaliseRole(value:string){const cleaned=(value||"Staff").trim().toLowerCase();if(cleaned==="department lead"||cleaned==="departmentlead")return "Department Lead";if(cleaned==="cpd lead"||cleaned==="cpdlead")return "CPD Lead";if(cleaned==="admin"||cleaned==="administrator")return "Admin";return cleaned==="staff"||cleaned==="teacher"||cleaned==="teaching assistant"?"Staff":value.trim();}
function parseCsv(text:string):ImportRow[]{const lines=text.replace(/^\uFEFF/,"").split(/\r?\n/).filter(l=>l.trim());if(!lines.length)return[];const matrix=lines.map(parseCsvLine);const headers=matrix[0].map(h=>h.trim().toLowerCase().replace(/\s+/g,"_"));const emailIndex=headers.indexOf("email");if(emailIndex<0)throw new Error("CSV must include an email column.");const idx=(name:string)=>headers.indexOf(name);return matrix.slice(1).map(cols=>({email:(cols[emailIndex]||"").trim().toLowerCase(),full_name:(cols[idx("full_name")]||cols[idx("name")]||"").trim(),department:(cols[idx("department")]||"").trim(),role:(cols[idx("role")]||"Staff").trim(),site_code:(cols[idx("site_code")]||cols[idx("site")]||"").trim()})).filter(r=>r.email);}
function parseCsvLine(line:string){const out:string[]=[];let current="",quoted=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'){if(quoted&&line[i+1]==='"'){current+='"';i++;}else quoted=!quoted;}else if(ch===","&&!quoted){out.push(current);current="";}else current+=ch;}out.push(current);return out;}
