"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { courses } from "@/lib/catalogue";
import { getSupabaseBrowserClient } from "@/lib/supabase";

type Tab = "overview"|"policies"|"appraisal"|"inset"|"onboarding"|"budget"|"resources"|"guidance"|"branding"|"reports";
type Profile={id:string;full_name:string;role:string;department:string;organisation_id:string|null};
type Org={id:string;name:string;academic_year:string;brand_name:string|null;logo_url:string|null;accent_color:string|null;secondary_color:string|null;support_email:string|null};
type Policy={id:string;title:string;category:string;version:string;summary:string;document_url:string|null;effective_date:string|null;review_date:string|null;mandatory:boolean;active:boolean};
type Ack={policy_id:string;user_id:string;policy_version:string;acknowledged_at:string};
type Standard={code:string;framework:string;title:string;summary:string;source_title:string;source_url:string;sort_order:number};
type Objective={id:string;user_id:string;title:string;description:string;success_criteria:string;standard_codes:string[];linked_course_ids:string[];review_date:string|null;status:string;shared_with_leadership:boolean};
type InsetDay={id:string;title:string;inset_date:string;theme:string;status:string};
type InsetSession={id:string;inset_day_id:string;title:string;description:string;starts_at:string;ends_at:string|null;location:string;capacity:number|null;audience:string;facilitator:string;linked_course_id:string|null};
type Booking={session_id:string;user_id:string;status:string;attendance_status:string};
type Programme={id:string;title:string;audience_role:string;description:string;course_ids:string[];mandatory_course_ids:string[];checklist:string[];active:boolean};
type Assignment={programme_id:string;user_id:string;checklist_complete:string[];status:string};
type Budget={id:string;academic_year:string;name:string;department:string|null;amount:number};
type Expense={id:string;budget_id:string;title:string;provider:string;training_cost:number;cover_cost:number;travel_cost:number;other_cost:number;occurred_on:string|null;status:string};
type Guidance={id:string;title:string;publisher:string;source_url:string;version_label:string;effective_date:string|null;last_verified_on:string;next_check_on:string|null;status:string};
type Resource={id:string;title:string;description:string;resource_url:string|null;category:string;linked_course_id:string|null;status:string;created_by:string};
type Staff={id:string;full_name:string;role:string;department:string};
type TrainingRequirement={id:string;title:string;mandatory:boolean;active:boolean};
type TrainingRecord={user_id:string;requirement_id:string;completed_at:string;expires_at:string|null};
type Priority={id:string;title:string;active:boolean};

const tabs:[Tab,string][]=[["overview","Overview"],["policies","Policies"],["appraisal","Standards & appraisal"],["inset","INSET"],["onboarding","Onboarding"],["budget","Budget"],["resources","Resources"],["guidance","Guidance"],["branding","Branding"],["reports","Reports"]];

export default function SchoolHubPage(){
  const [tab,setTab]=useState<Tab>("overview");
  const [profile,setProfile]=useState<Profile|null>(null); const [org,setOrg]=useState<Org|null>(null); const [staff,setStaff]=useState<Staff[]>([]);
  const [policies,setPolicies]=useState<Policy[]>([]); const [acks,setAcks]=useState<Ack[]>([]); const [standards,setStandards]=useState<Standard[]>([]); const [objectives,setObjectives]=useState<Objective[]>([]);
  const [insetDays,setInsetDays]=useState<InsetDay[]>([]); const [sessions,setSessions]=useState<InsetSession[]>([]); const [bookings,setBookings]=useState<Booking[]>([]);
  const [programmes,setProgrammes]=useState<Programme[]>([]); const [assignments,setAssignments]=useState<Assignment[]>([]); const [budgets,setBudgets]=useState<Budget[]>([]); const [expenses,setExpenses]=useState<Expense[]>([]);
  const [guidance,setGuidance]=useState<Guidance[]>([]); const [resources,setResources]=useState<Resource[]>([]); const [trainingRequirements,setTrainingRequirements]=useState<TrainingRequirement[]>([]); const [trainingRecords,setTrainingRecords]=useState<TrainingRecord[]>([]); const [priorities,setPriorities]=useState<Priority[]>([]);
  const [loading,setLoading]=useState(true); const [message,setMessage]=useState("");
  const admin=Boolean(profile&&["CPD Lead","Admin"].includes(profile.role));

  useEffect(()=>{let alive=true;(async()=>{const client=getSupabaseBrowserClient();const {data:auth}=await client.auth.getUser();if(!auth.user){window.location.href="/auth?next=/school-hub";return;}const {data:p,error}=await client.from("staff_profiles").select("id,full_name,role,department,organisation_id").eq("id",auth.user.id).single();if(!alive)return;if(error||!p){setMessage(error?.message||"Unable to load profile.");setLoading(false);return;}setProfile(p as Profile);if(!p.organisation_id){setLoading(false);return;}await reloadAll(p.organisation_id,p.role);if(alive)setLoading(false);})();return()=>{alive=false};},[]);

  async function reloadAll(orgId:string,role:string){const client=getSupabaseBrowserClient();const isAdmin=["CPD Lead","Admin"].includes(role);const base=await Promise.all([
    client.from("organisations").select("id,name,academic_year,brand_name,logo_url,accent_color,secondary_color,support_email").eq("id",orgId).single(),
    client.from("school_policies").select("id,title,category,version,summary,document_url,effective_date,review_date,mandatory,active").eq("organisation_id",orgId).order("category").order("title"),
    client.from("policy_acknowledgements").select("policy_id,user_id,policy_version,acknowledged_at"),
    client.from("professional_standards").select("code,framework,title,summary,source_title,source_url,sort_order").order("sort_order"),
    client.from("appraisal_objectives").select("id,user_id,title,description,success_criteria,standard_codes,linked_course_ids,review_date,status,shared_with_leadership").order("review_date"),
    client.from("inset_days").select("id,title,inset_date,theme,status").eq("organisation_id",orgId).order("inset_date"),
    client.from("inset_sessions").select("id,inset_day_id,title,description,starts_at,ends_at,location,capacity,audience,facilitator,linked_course_id").order("starts_at"),
    client.from("inset_bookings").select("session_id,user_id,status,attendance_status"),
    client.from("onboarding_programmes").select("id,title,audience_role,description,course_ids,mandatory_course_ids,checklist,active").eq("organisation_id",orgId).order("title"),
    client.from("onboarding_assignments").select("programme_id,user_id,checklist_complete,status"),
    client.from("system_guidance_sources").select("id,title,publisher,source_url,version_label,effective_date,last_verified_on,next_check_on,status").order("title"),
    client.from("school_resource_library").select("id,title,description,resource_url,category,linked_course_id,status,created_by").eq("organisation_id",orgId).order("title"),
    client.from("improvement_priorities").select("id,title,active").eq("organisation_id",orgId).eq("active",true),
  ]);
  if(base[0].data)setOrg(base[0].data as Org); setPolicies((base[1].data||[]) as Policy[]); setAcks((base[2].data||[]) as Ack[]); setStandards((base[3].data||[]) as Standard[]); setObjectives((base[4].data||[]) as Objective[]); setInsetDays((base[5].data||[]) as InsetDay[]); setSessions((base[6].data||[]) as InsetSession[]); setBookings((base[7].data||[]) as Booking[]); setProgrammes((base[8].data||[]) as Programme[]); setAssignments((base[9].data||[]) as Assignment[]); setGuidance((base[10].data||[]) as Guidance[]); setResources((base[11].data||[]) as Resource[]); setPriorities((base[12].data||[]) as Priority[]);
  if(isAdmin){const extra=await Promise.all([client.from("staff_profiles").select("id,full_name,role,department").eq("organisation_id",orgId).order("full_name"),client.from("cpd_budgets").select("id,academic_year,name,department,amount").eq("organisation_id",orgId).order("academic_year",{ascending:false}),client.from("cpd_expenses").select("id,budget_id,title,provider,training_cost,cover_cost,travel_cost,other_cost,occurred_on,status"),client.from("training_requirements").select("id,title,mandatory,active").eq("organisation_id",orgId),client.from("training_records").select("user_id,requirement_id,completed_at,expires_at")]);setStaff((extra[0].data||[]) as Staff[]);setBudgets((extra[1].data||[]) as Budget[]);setExpenses((extra[2].data||[]) as Expense[]);setTrainingRequirements((extra[3].data||[]) as TrainingRequirement[]);setTrainingRecords((extra[4].data||[]) as TrainingRecord[]);}
  }

  async function acknowledge(policy:Policy){if(!profile)return;const client=getSupabaseBrowserClient();const {data,error}=await client.from("policy_acknowledgements").upsert({policy_id:policy.id,user_id:profile.id,policy_version:policy.version,acknowledged_at:new Date().toISOString()},{onConflict:"policy_id,user_id"}).select("policy_id,user_id,policy_version,acknowledged_at").single();if(error)setMessage(error.message);else{setAcks(prev=>[...prev.filter(a=>!(a.policy_id===policy.id&&a.user_id===profile.id)),data as Ack]);setMessage("Policy acknowledgement recorded with date and version.");}}

  async function createPolicy(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!profile?.organisation_id||!admin)return;const f=e.currentTarget,fd=new FormData(f),client=getSupabaseBrowserClient();const {data,error}=await client.from("school_policies").insert({organisation_id:profile.organisation_id,title:String(fd.get("title")||"").trim(),category:String(fd.get("category")||"School policy"),version:String(fd.get("version")||"1.0"),summary:String(fd.get("summary")||""),document_url:String(fd.get("url")||"")||null,effective_date:String(fd.get("effective_date")||"")||null,review_date:String(fd.get("review_date")||"")||null,mandatory:fd.get("mandatory")==="on",created_by:profile.id}).select("id,title,category,version,summary,document_url,effective_date,review_date,mandatory,active").single();if(error)setMessage(error.message);else{setPolicies(prev=>[...prev,data as Policy]);f.reset();setMessage("Policy published to the school CPD hub.");}}

  async function createObjective(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!profile?.organisation_id)return;const f=e.currentTarget,fd=new FormData(f),client=getSupabaseBrowserClient();const codes=fd.getAll("standards").map(String);const course=String(fd.get("course")||"");const {data,error}=await client.from("appraisal_objectives").insert({organisation_id:profile.organisation_id,user_id:profile.id,title:String(fd.get("title")||"").trim(),description:String(fd.get("description")||""),success_criteria:String(fd.get("success")||""),standard_codes:codes,linked_course_ids:course?[course]:[],review_date:String(fd.get("review_date")||"")||null,shared_with_leadership:fd.get("shared")==="on",created_by:profile.id}).select("id,user_id,title,description,success_criteria,standard_codes,linked_course_ids,review_date,status,shared_with_leadership").single();if(error)setMessage(error.message);else{setObjectives(prev=>[...prev,data as Objective]);f.reset();setMessage("Professional objective saved.");}}

  async function createInsetDay(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!profile?.organisation_id||!admin)return;const f=e.currentTarget,fd=new FormData(f),client=getSupabaseBrowserClient();const {data,error}=await client.from("inset_days").insert({organisation_id:profile.organisation_id,title:String(fd.get("title")||""),inset_date:String(fd.get("date")||""),theme:String(fd.get("theme")||""),status:"open",created_by:profile.id}).select("id,title,inset_date,theme,status").single();if(error)setMessage(error.message);else{setInsetDays(prev=>[...prev,data as InsetDay]);f.reset();setMessage("INSET day created.");}}

  async function createInsetSession(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!admin)return;const f=e.currentTarget,fd=new FormData(f),client=getSupabaseBrowserClient();const {data,error}=await client.from("inset_sessions").insert({inset_day_id:String(fd.get("day")),title:String(fd.get("title")||""),description:String(fd.get("description")||""),starts_at:String(fd.get("starts_at")||""),ends_at:String(fd.get("ends_at")||"")||null,location:String(fd.get("location")||""),capacity:Number(fd.get("capacity")||0)||null,audience:String(fd.get("audience")||"All staff"),facilitator:String(fd.get("facilitator")||""),linked_course_id:String(fd.get("course")||"")||null}).select("id,inset_day_id,title,description,starts_at,ends_at,location,capacity,audience,facilitator,linked_course_id").single();if(error)setMessage(error.message);else{setSessions(prev=>[...prev,data as InsetSession].sort((a,b)=>a.starts_at.localeCompare(b.starts_at)));f.reset();setMessage("INSET session added.");}}

  async function bookSession(sessionId:string){if(!profile)return;const client=getSupabaseBrowserClient();const {data,error}=await client.from("inset_bookings").upsert({session_id:sessionId,user_id:profile.id,status:"booked"},{onConflict:"session_id,user_id"}).select("session_id,user_id,status,attendance_status").single();if(error)setMessage(error.message);else{setBookings(prev=>[...prev.filter(b=>!(b.session_id===sessionId&&b.user_id===profile.id)),data as Booking]);setMessage("INSET session booked.");}}

  async function assignProgramme(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!profile||!admin)return;const f=e.currentTarget,fd=new FormData(f),client=getSupabaseBrowserClient();const {data,error}=await client.from("onboarding_assignments").upsert({programme_id:String(fd.get("programme")),user_id:String(fd.get("user")),assigned_by:profile.id,status:"active"},{onConflict:"programme_id,user_id"}).select("programme_id,user_id,checklist_complete,status").single();if(error)setMessage(error.message);else{setAssignments(prev=>[...prev.filter(a=>!(a.programme_id===data.programme_id&&a.user_id===data.user_id)),data as Assignment]);setMessage("Onboarding programme assigned.");}}

  async function toggleChecklist(a:Assignment,item:string){if(!profile||a.user_id!==profile.id)return;const next=a.checklist_complete.includes(item)?a.checklist_complete.filter(x=>x!==item):[...a.checklist_complete,item];const p=programmes.find(x=>x.id===a.programme_id);const status=p&&p.checklist.every(x=>next.includes(x))?"completed":"active";const client=getSupabaseBrowserClient();const {error}=await client.from("onboarding_assignments").update({checklist_complete:next,status,completed_at:status==="completed"?new Date().toISOString():null}).eq("programme_id",a.programme_id).eq("user_id",a.user_id);if(error)setMessage(error.message);else setAssignments(prev=>prev.map(x=>x.programme_id===a.programme_id&&x.user_id===a.user_id?{...x,checklist_complete:next,status}:x));}

  async function createBudget(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!profile?.organisation_id||!admin)return;const f=e.currentTarget,fd=new FormData(f),client=getSupabaseBrowserClient();const {data,error}=await client.from("cpd_budgets").insert({organisation_id:profile.organisation_id,academic_year:String(fd.get("year")||org?.academic_year||""),name:String(fd.get("name")||""),department:String(fd.get("department")||"")||null,amount:Number(fd.get("amount")||0),created_by:profile.id}).select("id,academic_year,name,department,amount").single();if(error)setMessage(error.message);else{setBudgets(prev=>[...prev,data as Budget]);f.reset();setMessage("CPD budget created.");}}

  async function createExpense(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!profile||!admin)return;const f=e.currentTarget,fd=new FormData(f),client=getSupabaseBrowserClient();const {data,error}=await client.from("cpd_expenses").insert({budget_id:String(fd.get("budget")),title:String(fd.get("title")||""),provider:String(fd.get("provider")||""),training_cost:Number(fd.get("training")||0),cover_cost:Number(fd.get("cover")||0),travel_cost:Number(fd.get("travel")||0),other_cost:Number(fd.get("other")||0),occurred_on:String(fd.get("date")||"")||null,status:String(fd.get("status")||"planned"),created_by:profile.id}).select("id,budget_id,title,provider,training_cost,cover_cost,travel_cost,other_cost,occurred_on,status").single();if(error)setMessage(error.message);else{setExpenses(prev=>[...prev,data as Expense]);f.reset();setMessage("CPD cost recorded.");}}

  async function createResource(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!profile?.organisation_id||!admin)return;const f=e.currentTarget,fd=new FormData(f),client=getSupabaseBrowserClient();const {data,error}=await client.from("school_resource_library").insert({organisation_id:profile.organisation_id,title:String(fd.get("title")||""),description:String(fd.get("description")||""),resource_url:String(fd.get("url")||"")||null,category:String(fd.get("category")||"CPD resource"),linked_course_id:String(fd.get("course")||"")||null,status:"published",created_by:profile.id}).select("id,title,description,resource_url,category,linked_course_id,status,created_by").single();if(error)setMessage(error.message);else{setResources(prev=>[...prev,data as Resource]);f.reset();setMessage("Resource published.");}}

  async function saveBranding(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!org||!admin)return;const fd=new FormData(e.currentTarget),client=getSupabaseBrowserClient();const patch={brand_name:String(fd.get("brand_name")||"")||null,logo_url:String(fd.get("logo_url")||"")||null,accent_color:String(fd.get("accent")||"")||null,secondary_color:String(fd.get("secondary")||"")||null,support_email:String(fd.get("support_email")||"")||null};const {data,error}=await client.from("organisations").update(patch).eq("id",org.id).select("id,name,academic_year,brand_name,logo_url,accent_color,secondary_color,support_email").single();if(error)setMessage(error.message);else{setOrg(data as Org);setMessage("School branding saved. Refresh to apply the colour theme across the app.");}}

  const myAssignments=assignments.filter(a=>a.user_id===profile?.id); const myAcks=new Set(acks.filter(a=>a.user_id===profile?.id).map(a=>a.policy_id));
  const outstandingPolicies=policies.filter(p=>p.active&&p.mandatory&&!myAcks.has(p.id)); const myObjectives=objectives.filter(o=>o.user_id===profile?.id);
  const upcomingSessions=sessions.filter(s=>new Date(s.starts_at).getTime()>=Date.now()).slice(0,8);
  const totalBudget=budgets.reduce((s,b)=>s+Number(b.amount),0); const totalSpend=expenses.filter(e=>e.status!=="cancelled").reduce((s,e)=>s+Number(e.training_cost)+Number(e.cover_cost)+Number(e.travel_cost)+Number(e.other_cost),0);
  const activeReq=trainingRequirements.filter(r=>r.active&&r.mandatory); const now=Date.now(); const validTraining=trainingRecords.filter(r=>!r.expires_at||new Date(r.expires_at).getTime()>now);
  const policyCoverage=staff.length&&policies.filter(p=>p.active&&p.mandatory).length?Math.round(100*acks.filter(a=>policies.some(p=>p.id===a.policy_id&&p.active&&p.mandatory)).length/(staff.length*policies.filter(p=>p.active&&p.mandatory).length)):0;

  if(loading)return <main className="stagePage"><div className="stageCard">Loading school CPD hub…</div></main>;
  if(!profile)return <main className="stagePage"><div className="stageCard">Unable to load your staff account.</div></main>;
  if(!profile.organisation_id)return <main className="stagePage"><section className="stageHero"><span className="eyebrow">SCHOOL CPD HUB</span><h1>Connect your school first.</h1><p>The commercial school workspace becomes available after your account is linked to an organisation.</p><a className="primary phaseLinkButton" href="/organisation">Open organisation setup</a></section></main>;

  return <main className="stagePage schoolHubPage">
    <section className="stageHero schoolHubHero"><span className="eyebrow">SCHOOL CPD OPERATING SYSTEM</span><h1>{org?.brand_name||org?.name||"School CPD Hub"}</h1><p>Policies, professional standards, appraisal, INSET, onboarding, budgets, resources and evidence reporting in one school-scoped workspace.</p><div className="stageHeroActions"><a className="secondary phaseLinkButton" href="/training">Mandatory training</a><a className="secondary phaseLinkButton" href="/quality">Annual CPD & QA</a>{admin&&<a className="secondary phaseLinkButton" href="/school-access">School access</a>}</div></section>
    {message&&<div className="phaseNotice">{message}</div>}
    <div className="schoolSectionPicker">
      <label>School hub section<select value={tab} onChange={event=>setTab(event.target.value as Tab)}>
        <optgroup label="School essentials">{tabs.filter(([t])=>["overview","policies","resources","guidance"].includes(t)).map(([t,label])=><option key={t} value={t}>{label}</option>)}</optgroup>
        <optgroup label="Staff development">{tabs.filter(([t])=>["appraisal","inset","onboarding"].includes(t)).map(([t,label])=><option key={t} value={t}>{t==="onboarding"?"Staff induction":label}</option>)}</optgroup>
        {admin&&<optgroup label="Administration">{tabs.filter(([t])=>["budget","branding","reports"].includes(t)).map(([t,label])=><option key={t} value={t}>{t==="reports"?"Governance summary":label}</option>)}</optgroup>}
      </select></label>
      <p>Choose one section at a time. Policies and resources are grouped together; staff development and administration have their own sections.</p>
    </div>

    {tab==="overview"&&<><section className="stageStatGrid"><div className="stageStat"><strong>{outstandingPolicies.length}</strong><span>policies to acknowledge</span></div><div className="stageStat"><strong>{myObjectives.filter(o=>!["achieved","closed"].includes(o.status)).length}</strong><span>active objectives</span></div><div className="stageStat"><strong>{upcomingSessions.length}</strong><span>upcoming INSET sessions</span></div><div className="stageStat"><strong>{myAssignments.filter(a=>a.status!=="completed").length}</strong><span>onboarding programmes</span></div></section><section className="stageGrid"><div className="stageCard stageSpan6"><span className="eyebrow">YOUR ACTIONS</span><h2>What needs attention</h2><div className="hubActionList">{outstandingPolicies.slice(0,4).map(p=><button key={p.id} onClick={()=>setTab("policies")}><span>Policy</span><strong>{p.title}</strong><small>Version {p.version} requires acknowledgement</small></button>)}{myAssignments.filter(a=>a.status!=="completed").slice(0,3).map(a=><button key={a.programme_id} onClick={()=>setTab("onboarding")}><span>Onboarding</span><strong>{programmes.find(p=>p.id===a.programme_id)?.title||"Programme"}</strong><small>Continue your induction checklist</small></button>)}{!outstandingPolicies.length&&!myAssignments.filter(a=>a.status!=="completed").length&&<p className="muted">No immediate school-hub actions.</p>}</div></div><div className="stageCard stageSpan6"><span className="eyebrow">PROFESSIONAL DEVELOPMENT</span><h2>Connected development</h2><p>Your appraisal objectives can map to the Teachers’ Standards and directly link to CPD courses. Reflection/evidence remains private unless you explicitly share the objective with leadership.</p><div className="hubQuickLinks"><button onClick={()=>setTab("appraisal")}>Open standards & appraisal</button><a href="/improvement">School improvement priorities</a><a href="/actions">Implementation plans</a><a href="/portfolio">CPD evidence portfolio</a></div></div></section></>}

    {tab==="policies"&&<section className="stageGrid"><div className="stageCard stageSpan7"><span className="eyebrow">POLICY ACKNOWLEDGEMENT</span><h2>School policies and required reading</h2><div className="policyList">{policies.filter(p=>p.active).map(p=>{const ack=acks.find(a=>a.policy_id===p.id&&a.user_id===profile.id);return <article key={p.id} className={ack?"policyCard acknowledged":"policyCard"}><div className="policyCardHead"><div><span>{p.category}</span><h3>{p.title}</h3><small>Version {p.version}{p.effective_date?` · effective ${date(p.effective_date)}`:""}</small></div><b>{ack?"Acknowledged":p.mandatory?"Required":"Optional"}</b></div>{p.summary&&<p>{p.summary}</p>}<div className="policyActions">{p.document_url&&<a href={p.document_url} target="_blank" rel="noreferrer">Open document ↗</a>}{!ack&&<button className="primary" onClick={()=>acknowledge(p)}>I have read this version</button>}{ack&&<small>Recorded {dateTime(ack.acknowledged_at)}</small>}</div></article>})}</div></div>{admin&&<div className="stageCard stageSpan5"><span className="eyebrow">PUBLISH POLICY</span><h2>Add required reading</h2><form className="stageForm" onSubmit={createPolicy}><label>Title<input required name="title"/></label><label>Category<input name="category" defaultValue="School policy"/></label><label>Version<input name="version" defaultValue="1.0"/></label><label>Summary<textarea name="summary" rows={3}/></label><label>Document link<input name="url" type="url" placeholder="https://…"/></label><label>Effective date<input name="effective_date" type="date"/></label><label>Review date<input name="review_date" type="date"/></label><label className="inlineCheck"><input type="checkbox" name="mandatory" defaultChecked/> Require acknowledgement</label><button className="primary">Publish policy</button></form><div className="policyAdminSummary"><strong>{policyCoverage}%</strong><span>mandatory policy acknowledgement coverage</span></div></div>}</section>}

    {tab==="appraisal"&&<section className="stageGrid"><div className="stageCard stageSpan7"><span className="eyebrow">YOUR OBJECTIVES</span><h2>Professional standards & appraisal</h2><div className="objectiveList">{myObjectives.map(o=><article key={o.id}><div><strong>{o.title}</strong><span className={`stageBadge ${o.status==="achieved"?"good":""}`}>{o.status}</span></div><p>{o.description}</p>{o.success_criteria&&<small>Success evidence: {o.success_criteria}</small>}<div className="standardPills">{o.standard_codes.map(code=><span key={code}>{code}</span>)}</div>{o.linked_course_ids.map(id=><a key={id} href={`/?course=${encodeURIComponent(id)}`}>{courses.find(c=>c.id===id)?.title||id}</a>)}</article>)}{!myObjectives.length&&<p className="muted">No objectives yet. Add one using the planner.</p>}</div></div><div className="stageCard stageSpan5"><span className="eyebrow">OBJECTIVE PLANNER</span><h2>Connect appraisal to development</h2><form className="stageForm" onSubmit={createObjective}><label>Objective<input required name="title"/></label><label>What will change?<textarea name="description" rows={3}/></label><label>Success criteria<textarea name="success" rows={3}/></label><label>Review date<input type="date" name="review_date"/></label><label>Linked CPD course<select name="course"><option value="">No course yet</option>{courses.slice().sort((a,b)=>a.title.localeCompare(b.title)).map(c=><option value={c.id} key={c.id}>{c.title}</option>)}</select></label><fieldset className="standardsPicker"><legend>Relevant standards</legend>{standards.filter(s=>s.framework==="Teachers Standards").map(s=><label key={s.code}><input type="checkbox" name="standards" value={s.code}/><span><b>{s.code} · {s.title}</b><small>{s.summary}</small></span></label>)}</fieldset><label className="inlineCheck"><input type="checkbox" name="shared"/> Share this objective with CPD leadership</label><button className="primary">Save objective</button></form></div></section>}

    {tab==="inset"&&<><section className="stageGrid"><div className="stageCard stageSpan7"><span className="eyebrow">INSET SCHEDULE</span><h2>Upcoming sessions</h2><div className="insetSchedule">{sessions.map(s=>{const d=insetDays.find(x=>x.id===s.inset_day_id);const booked=bookings.some(b=>b.session_id===s.id&&b.user_id===profile.id&&b.status==="booked");return <article key={s.id}><time>{dateTime(s.starts_at)}</time><div><strong>{s.title}</strong><span>{d?.title||"INSET"} · {s.location||"Location TBC"} · {s.audience}</span><p>{s.description}</p>{s.linked_course_id&&<small>Linked CPD: {courses.find(c=>c.id===s.linked_course_id)?.title||s.linked_course_id}</small>}</div><button className={booked?"secondary":"primary"} disabled={booked} onClick={()=>bookSession(s.id)}>{booked?"Booked":"Book place"}</button></article>})}{!sessions.length&&<p className="muted">No INSET sessions have been published yet.</p>}</div></div>{admin&&<div className="stageCard stageSpan5"><span className="eyebrow">INSET BUILDER</span><h2>Create a day</h2><form className="stageForm" onSubmit={createInsetDay}><label>Day title<input required name="title" placeholder="Autumn INSET"/></label><label>Date<input required type="date" name="date"/></label><label>Theme<input name="theme"/></label><button className="primary">Create INSET day</button></form></div>}</section>{admin&&insetDays.length>0&&<section className="stageCard"><span className="eyebrow">SESSION BUILDER</span><h2>Add a workshop/session</h2><form className="hubFormGrid" onSubmit={createInsetSession}><label>INSET day<select name="day">{insetDays.map(d=><option key={d.id} value={d.id}>{d.title} · {date(d.inset_date)}</option>)}</select></label><label>Session title<input required name="title"/></label><label className="span2">Description<textarea name="description" rows={2}/></label><label>Starts<input required type="datetime-local" name="starts_at"/></label><label>Ends<input type="datetime-local" name="ends_at"/></label><label>Location<input name="location"/></label><label>Capacity<input type="number" min="1" name="capacity"/></label><label>Audience<input name="audience" defaultValue="All staff"/></label><label>Facilitator<input name="facilitator"/></label><label className="span2">Linked course<select name="course"><option value="">None</option>{courses.map(c=><option value={c.id} key={c.id}>{c.title}</option>)}</select></label><button className="primary span2">Add session</button></form></section>}</>}

    {tab==="onboarding"&&<section className="stageGrid"><div className="stageCard stageSpan7"><span className="eyebrow">YOUR ONBOARDING</span><h2>Structured role development</h2>{myAssignments.map(a=>{const p=programmes.find(x=>x.id===a.programme_id);if(!p)return null;return <article className="onboardingCard" key={a.programme_id}><div><h3>{p.title}</h3><span className={`stageBadge ${a.status==="completed"?"good":""}`}>{a.status}</span></div><p>{p.description}</p><div className="onboardingChecklist">{p.checklist.map(item=><button key={item} className={a.checklist_complete.includes(item)?"done":""} onClick={()=>toggleChecklist(a,item)}><span>{a.checklist_complete.includes(item)?"✓":"○"}</span>{item}</button>)}</div><div className="onboardingCourses">{p.course_ids.map(id=><a key={id} href={`/?course=${encodeURIComponent(id)}`}>{courses.find(c=>c.id===id)?.title||id}</a>)}</div></article>})}{!myAssignments.length&&<p className="muted">No onboarding programme is assigned to your account.</p>}</div>{admin&&<div className="stageCard stageSpan5"><span className="eyebrow">ASSIGN PROGRAMME</span><h2>New staff / ECT / TA pathways</h2><form className="stageForm" onSubmit={assignProgramme}><label>Programme<select required name="programme">{programmes.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label><label>Staff member<select required name="user">{staff.map(s=><option key={s.id} value={s.id}>{s.full_name||"Staff member"} · {s.department||s.role}</option>)}</select></label><button className="primary">Assign programme</button></form><div className="programmeAdminList">{programmes.map(p=><article key={p.id}><strong>{p.title}</strong><span>{p.audience_role}</span><small>{assignments.filter(a=>a.programme_id===p.id).length} assigned</small></article>)}</div></div>}</section>}

    {tab==="budget"&&admin&&<><section className="stageStatGrid"><div className="stageStat"><strong>{money(totalBudget)}</strong><span>allocated</span></div><div className="stageStat"><strong>{money(totalSpend)}</strong><span>planned/spent</span></div><div className="stageStat"><strong>{money(Math.max(0,totalBudget-totalSpend))}</strong><span>remaining</span></div><div className="stageStat"><strong>{expenses.length}</strong><span>cost records</span></div></section><section className="stageGrid"><div className="stageCard stageSpan6"><span className="eyebrow">BUDGETS</span><h2>CPD allocation</h2><div className="budgetList">{budgets.map(b=>{const spent=expenses.filter(e=>e.budget_id===b.id&&e.status!=="cancelled").reduce((s,e)=>s+Number(e.training_cost)+Number(e.cover_cost)+Number(e.travel_cost)+Number(e.other_cost),0);return <article key={b.id}><div><strong>{b.name}</strong><span>{b.academic_year}{b.department?` · ${b.department}`:""}</span></div><div><b>{money(spent)} / {money(Number(b.amount))}</b><progress max={Number(b.amount)||1} value={spent}/></div></article>})}</div><form className="stageForm compactForm" onSubmit={createBudget}><label>Name<input required name="name" placeholder="Whole-school CPD"/></label><label>Academic year<input name="year" defaultValue={org?.academic_year}/></label><label>Department<input name="department" placeholder="Optional"/></label><label>Allocation (£)<input required type="number" min="0" step="0.01" name="amount"/></label><button className="primary">Create budget</button></form></div><div className="stageCard stageSpan6"><span className="eyebrow">COST TRACKING</span><h2>Training, cover and travel</h2><form className="stageForm" onSubmit={createExpense}><label>Budget<select required name="budget">{budgets.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Training / activity<input required name="title"/></label><label>Provider<input name="provider"/></label><label>Training cost (£)<input type="number" min="0" step="0.01" name="training"/></label><label>Cover cost (£)<input type="number" min="0" step="0.01" name="cover"/></label><label>Travel cost (£)<input type="number" min="0" step="0.01" name="travel"/></label><label>Other cost (£)<input type="number" min="0" step="0.01" name="other"/></label><label>Date<input type="date" name="date"/></label><label>Status<select name="status"><option>planned</option><option>approved</option><option>spent</option><option>cancelled</option></select></label><button className="primary" disabled={!budgets.length}>Record cost</button></form></div></section></>}

    {tab==="resources"&&<section className="stageGrid"><div className="stageCard stageSpan7"><span className="eyebrow">SCHOOL RESOURCE BANK</span><h2>Shared CPD tools and exemplars</h2><div className="resourceGrid">{resources.filter(r=>r.status==="published").map(r=><article key={r.id}><span>{r.category}</span><strong>{r.title}</strong><p>{r.description}</p>{r.linked_course_id&&<small>Linked to {courses.find(c=>c.id===r.linked_course_id)?.title||r.linked_course_id}</small>}{r.resource_url&&<a href={r.resource_url} target="_blank" rel="noreferrer">Open resource ↗</a>}</article>)}</div></div>{admin&&<div className="stageCard stageSpan5"><span className="eyebrow">PUBLISH RESOURCE</span><h2>Add a school exemplar</h2><form className="stageForm" onSubmit={createResource}><label>Title<input required name="title"/></label><label>Category<input name="category" defaultValue="CPD resource"/></label><label>Description<textarea name="description" rows={3}/></label><label>Link<input type="url" name="url"/></label><label>Linked course<select name="course"><option value="">None</option>{courses.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label><button className="primary">Publish resource</button></form></div>}</section>}

    {tab==="guidance"&&<section className="stageCard"><span className="eyebrow">GUIDANCE FRESHNESS</span><h2>Authoritative references used by the CPD system</h2><p>This register helps CPD leads see which external guidance the platform is aligned to and when it should be checked again. It does not replace reading the underlying source.</p><div className="guidanceGrid">{guidance.map(g=>{const due=g.next_check_on&&new Date(g.next_check_on).getTime()<Date.now();return <article key={g.id} className={due?"reviewDue":""}><div><span className={`guidanceStatus ${due?"due":"current"}`}>{due?"Review due":g.status}</span><small>{g.publisher}</small></div><h3>{g.title}</h3><p>{g.version_label}</p><dl><div><dt>Last verified</dt><dd>{date(g.last_verified_on)}</dd></div><div><dt>Next check</dt><dd>{date(g.next_check_on)}</dd></div></dl><a href={g.source_url} target="_blank" rel="noreferrer">Open official source ↗</a></article>})}</div></section>}

    {tab==="branding"&&admin&&<section className="stageGrid"><div className="stageCard stageSpan6"><span className="eyebrow">WHITE-LABEL SETTINGS</span><h2>School branding</h2><form className="stageForm" onSubmit={saveBranding}><label>Display name<input name="brand_name" defaultValue={org?.brand_name||""}/></label><label>Logo URL<input type="url" name="logo_url" defaultValue={org?.logo_url||""}/></label><label>Primary colour<input name="accent" pattern="^#[0-9A-Fa-f]{6}$" placeholder="#0F766E" defaultValue={org?.accent_color||""}/></label><label>Secondary colour<input name="secondary" pattern="^#[0-9A-Fa-f]{6}$" placeholder="#115E59" defaultValue={org?.secondary_color||""}/></label><label>Support email<input type="email" name="support_email" defaultValue={org?.support_email||""}/></label><button className="primary">Save branding</button></form></div><div className="stageCard stageSpan6 brandPreview" style={{"--preview-accent":org?.accent_color||"#0f766e"} as React.CSSProperties}><span className="eyebrow">PREVIEW</span>{org?.logo_url&&<img src={org.logo_url} alt="School logo preview"/>}<h2>{org?.brand_name||org?.name}</h2><p>Professional Learning Hub</p><button>Example action</button></div></section>}

    {tab==="reports"&&admin&&<section className="stageCard governanceReport"><div className="reportHeader"><div><span className="eyebrow">GOVERNANCE / INSPECTION EVIDENCE SUMMARY</span><h2>{org?.brand_name||org?.name} · {org?.academic_year}</h2><p>A live evidence summary of CPD systems and participation. This is an evidence pack, not a claim of inspection compliance or pupil impact.</p></div><button className="primary noPrint" onClick={()=>window.print()}>Print / Save PDF</button></div><div className="reportMetrics"><div><strong>{staff.length}</strong><span>staff accounts</span></div><div><strong>{activeReq.length}</strong><span>active mandatory requirements</span></div><div><strong>{validTraining.length}</strong><span>valid training records</span></div><div><strong>{policyCoverage}%</strong><span>mandatory policy acknowledgement</span></div><div><strong>{insetDays.length}</strong><span>INSET days planned</span></div><div><strong>{priorities.length}</strong><span>active improvement priorities</span></div></div><section><h3>Safeguarding & policy systems</h3><p>{policies.filter(p=>p.active&&p.mandatory).length} mandatory policy/read-and-acknowledge items are currently active. The guidance register includes {guidance.length} authoritative sources with review dates.</p></section><section><h3>Professional development</h3><p>{objectives.length} professional objectives are recorded in the organisation-visible dataset, with staff-controlled sharing for appraisal objectives. {programmes.length} onboarding programmes are available.</p></section><section><h3>INSET and implementation</h3><p>{insetDays.length} INSET days and {sessions.length} sessions are recorded. Staff can book sessions and connect workshops to CPD courses and live-session activities.</p></section><section><h3>CPD investment</h3><p>{money(totalBudget)} is allocated across recorded CPD budgets and {money(totalSpend)} is currently planned/approved/spent, including training, cover and travel costs.</p></section><section><h3>Current official-reference checks</h3><ul>{guidance.map(g=><li key={g.id}><strong>{g.title}</strong> — {g.version_label}; last checked {date(g.last_verified_on)}</li>)}</ul></section><footer>Generated {new Date().toLocaleString("en-GB")} from Teaching CPD Hub live records.</footer></section>}
  </main>;
}

function date(v:string|null){return v?new Date(v).toLocaleDateString("en-GB"):"—"} function dateTime(v:string){return new Date(v).toLocaleString("en-GB",{dateStyle:"medium",timeStyle:"short"})} function money(v:number){return new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP",maximumFractionDigits:0}).format(v)}
