"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { getSupabaseBrowserClient } from "@/lib/supabase";

type Profile={id:string;full_name:string;role:string;department:string;organisation_id:string|null;site_id:string|null};
type Organisation={id:string;name:string;slug:string;trust_name:string;academic_year:string;timezone:string;default_cpd_hours:number;join_code:string;created_at:string};
type Site={id:string;organisation_id:string;name:string;code:string;active:boolean};
type Membership={organisation_id:string;user_id:string;site_id:string|null;member_role:"member"|"site_lead"|"org_admin";active:boolean;joined_at:string};
type Staff={id:string;full_name:string;role:string;department:string;site_id:string|null};

export default function OrganisationPage(){
  const [profile,setProfile]=useState<Profile|null>(null);const [org,setOrg]=useState<Organisation|null>(null);const [sites,setSites]=useState<Site[]>([]);const [members,setMembers]=useState<Membership[]>([]);const [staff,setStaff]=useState<Staff[]>([]);const [loading,setLoading]=useState(true);const [message,setMessage]=useState("");
  const admin=Boolean(profile&&["CPD Lead","Admin"].includes(profile.role));

  useEffect(()=>{const supabase=getSupabaseBrowserClient();let alive=true;(async()=>{const {data:auth}=await supabase.auth.getUser();if(!auth.user){window.location.href="/auth?next=/organisation";return;}const {data:p,error}=await supabase.from("staff_profiles").select("id,full_name,role,department,organisation_id,site_id").eq("id",auth.user.id).single();if(!alive)return;if(error||!p){setMessage(error?.message||"Unable to load profile.");setLoading(false);return;}setProfile(p as Profile);if(p.organisation_id)await loadOrg(p.organisation_id,p.role);setLoading(false);})();async function loadOrg(orgId:string,role:string){const client=getSupabaseBrowserClient();const [o,s,m]=await Promise.all([client.from("organisations").select("id,name,slug,trust_name,academic_year,timezone,default_cpd_hours,join_code,created_at").eq("id",orgId).single(),client.from("school_sites").select("id,organisation_id,name,code,active").eq("organisation_id",orgId).order("name"),client.from("organisation_memberships").select("organisation_id,user_id,site_id,member_role,active,joined_at").eq("organisation_id",orgId)]);if(o.error||s.error||m.error)setMessage([o.error?.message,s.error?.message,m.error?.message].filter(Boolean).join(" · "));if(o.data)setOrg(o.data as Organisation);setSites((s.data||[]) as Site[]);setMembers((m.data||[]) as Membership[]);if(["CPD Lead","Admin"].includes(role)){const {data:rows}=await client.from("staff_profiles").select("id,full_name,role,department,site_id").eq("organisation_id",orgId).order("full_name");setStaff((rows||[]) as Staff[]);}}return()=>{alive=false;};},[]);

  const staffMap=useMemo(()=>new Map(staff.map(s=>[s.id,s])),[staff]);

  async function bootstrap(e:FormEvent<HTMLFormElement>){e.preventDefault();const formEl=e.currentTarget;const fd=new FormData(formEl);const client=getSupabaseBrowserClient();const {data,error}=await client.rpc("bootstrap_organisation",{p_name:String(fd.get("name")||""),p_slug:String(fd.get("slug")||""),p_academic_year:String(fd.get("academic_year")||"2026/27"),p_site_name:String(fd.get("site_name")||"")});if(error){setMessage(error.message);return;}setMessage("Organisation created. Reloading settings…");if(data)window.location.reload();}
  async function join(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);const client=getSupabaseBrowserClient();const {data,error}=await client.rpc("join_organisation",{p_code:String(fd.get("code")||"")});if(error){setMessage(error.message);return;}if(data)window.location.reload();}
  async function saveSettings(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!org)return;const fd=new FormData(e.currentTarget);const client=getSupabaseBrowserClient();const patch={name:String(fd.get("name")||""),trust_name:String(fd.get("trust_name")||""),academic_year:String(fd.get("academic_year")||""),timezone:String(fd.get("timezone")||"Europe/London"),default_cpd_hours:Number(fd.get("default_cpd_hours")||20),updated_at:new Date().toISOString()};const {data,error}=await client.from("organisations").update(patch).eq("id",org.id).select().single();if(error)setMessage(error.message);else{setOrg(data as Organisation);setMessage("Organisation settings saved.");}}
  async function createSite(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!org||!profile)return;const formEl=e.currentTarget;const fd=new FormData(formEl);const client=getSupabaseBrowserClient();const {data,error}=await client.from("school_sites").insert({organisation_id:org.id,name:String(fd.get("name")||""),code:String(fd.get("code")||"").toUpperCase(),created_by:profile.id}).select("id,organisation_id,name,code,active").single();if(error)setMessage(error.message);else{setSites(prev=>[...prev,data as Site].sort((a,b)=>a.name.localeCompare(b.name)));formEl.reset();setMessage("School site added.");}}
  async function rotateCode(){if(!org)return;const next=Math.random().toString(36).slice(2,10).toUpperCase();const client=getSupabaseBrowserClient();const {data,error}=await client.from("organisations").update({join_code:next,updated_at:new Date().toISOString()}).eq("id",org.id).select().single();if(error)setMessage(error.message);else{setOrg(data as Organisation);setMessage("Join code rotated. The previous code no longer works.");}}
  async function changeMemberSite(userId:string,siteId:string){if(!org)return;const client=getSupabaseBrowserClient();const {error}=await client.from("organisation_memberships").update({site_id:siteId||null}).eq("organisation_id",org.id).eq("user_id",userId);if(error)setMessage(error.message);else{setMembers(prev=>prev.map(m=>m.user_id===userId?{...m,site_id:siteId||null}:m));setMessage("Member site updated.");}}

  if(loading)return <main className="stagePage"><div className="stageCard">Loading organisation settings…</div></main>;
  if(!profile)return <main className="stagePage"><div className="stageCard">Unable to load your staff profile.</div></main>;

  if(!profile.organisation_id)return <main className="stagePage"><section className="stageHero"><span className="eyebrow">STAGE 13 · ORGANISATION SETUP</span><h1>Connect this CPD account to your school or trust.</h1><p>Use an organisation join code, or create the organisation if you are the CPD Lead/Admin setting up the platform.</p></section>{message&&<div className="phaseNotice">{message}</div>}<section className="stageGrid"><div className="stageCard stageSpan6"><h2>Join an existing organisation</h2><form className="stageForm" onSubmit={join}><label>Organisation join code<input required name="code" placeholder="e.g. A7K9P2QM"/></label><button className="primary">Join organisation</button></form></div>{admin&&<div className="stageCard stageSpan6"><h2>Create organisation</h2><form className="stageForm" onSubmit={bootstrap}><label>Organisation / school name<input required name="name"/></label><label>Short slug<input required name="slug" placeholder="adcote-school"/></label><label>Academic year<input name="academic_year" defaultValue="2026/27"/></label><label>Main site name<input name="site_name" placeholder="Main school"/></label><button className="primary">Create organisation</button></form></div>}</section></main>;

  return <main className="stagePage"><section className="stageHero"><span className="eyebrow">STAGE 13 · SCHOOL / TRUST MODE</span><h1>{org?.name||"Organisation"}</h1><p>Organisation settings and school sites keep staff-facing administration scoped to the correct school or trust.</p><div className="stageHeroActions"><a className="secondary phaseLinkButton" href="/quality">Annual CPD & QA</a></div></section>{message&&<div className="phaseNotice">{message}</div>}
    <section className="stageStatGrid"><div className="stageStat"><strong>{sites.length}</strong><span>school sites</span></div><div className="stageStat"><strong>{members.length}</strong><span>members</span></div><div className="stageStat"><strong>{org?.academic_year||"—"}</strong><span>academic year</span></div><div className="stageStat"><strong>{org?.default_cpd_hours||0}</strong><span>target CPD hours</span></div></section>
    <section className="stageGrid"><div className="stageCard stageSpan6"><span className="eyebrow">ORGANISATION</span><h2>Current settings</h2>{org&&<form className="stageForm" onSubmit={saveSettings}><label>Name<input name="name" defaultValue={org.name} disabled={!admin}/></label><label>Trust / group name<input name="trust_name" defaultValue={org.trust_name} disabled={!admin}/></label><label>Academic year<input name="academic_year" defaultValue={org.academic_year} disabled={!admin}/></label><label>Timezone<input name="timezone" defaultValue={org.timezone} disabled={!admin}/></label><label>Target CPD hours<input name="default_cpd_hours" type="number" min="0" step="0.5" defaultValue={org.default_cpd_hours} disabled={!admin}/></label>{admin&&<button className="primary">Save settings</button>}</form>}</div><div className="stageCard stageSpan6"><span className="eyebrow">JOIN CODE</span><h2>Staff onboarding</h2><p>Share this code only with staff who should join this organisation.</p><div className="orgJoinCode">{org?.join_code||"—"}</div>{admin&&<button className="secondary" onClick={rotateCode}>Rotate code</button>}</div></section>
    <section className="stageGrid"><div className="stageCard stageSpan5"><span className="eyebrow">SITES</span><h2>School sites</h2><div className="stageList">{sites.map(s=><div className="stageRow" key={s.id}><div className="stageRowMain"><strong>{s.name}</strong><span>{s.code}</span></div><span className={`stageBadge ${s.active?"good":""}`}>{s.active?"active":"inactive"}</span></div>)}</div>{admin&&<form className="stageForm compactForm" onSubmit={createSite}><label>Site name<input required name="name"/></label><label>Code<input required name="code" maxLength={12}/></label><button className="primary">Add site</button></form>}</div><div className="stageCard stageSpan7"><span className="eyebrow">MEMBERS</span><h2>Organisation membership</h2>{admin?<div className="stageList">{members.map(m=>{const s=staffMap.get(m.user_id);return <div className="stageRow" key={m.user_id}><div className="stageRowMain"><strong>{s?.full_name||"Staff member"}</strong><span>{s?.role||m.member_role} · {s?.department||"No department"}</span></div><select value={m.site_id||""} onChange={e=>changeMemberSite(m.user_id,e.target.value)}><option value="">No site</option>{sites.map(site=><option key={site.id} value={site.id}>{site.name}</option>)}</select></div>})}</div>:<p>Your account is connected to this organisation. Member details are visible to authorised CPD administrators only.</p>}</div></section>
  </main>;
}
