"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { getSupabaseBrowserClient } from "@/lib/supabase";
import { resolveStaffAccess } from "@/lib/rolePermissions";

type Area = "student_support"|"interventions"|"pastoral"|"staff_progress"|"timetable_leadership";
type Level = "none"|"view"|"manage";
type Staff = {user_id:string;display_name:string;role:string|null;department:string|null;job_title:string|null;email:string|null};
type Grant = {id:string;organization_id:string;user_id:string;area:Area;access_level:"view"|"manage";assigned_by:string};
const areas:{id:Area;label:string;description:string;manage:string}[]=[
 {id:"student_support",label:"Student support profiles",description:"General pupil support profiles and support overview.",manage:"Create and edit general support profiles."},
 {id:"interventions",label:"Interventions & review evidence",description:"Intervention strategies, evidence and review information.",manage:"Create, edit and close interventions."},
 {id:"pastoral",label:"Pastoral / regulation check-ins",description:"General pastoral and regulation check-in records.",manage:"Create, edit and remove check-ins."},
 {id:"staff_progress",label:"Staff CPD progress reporting",description:"Completion and implementation status for other staff.",manage:"Reporting is read-only; Manage is treated as view."},
 {id:"timetable_leadership",label:"Timetable leadership analytics",description:"Whole-school workload and timetable leadership reporting.",manage:"Reserved for timetable administration workflows."},
];
const key=(user:string,area:Area)=>`${user}:${area}`;

export default function DataAccessPage(){
 const client=getSupabaseBrowserClient();
 const [loading,setLoading]=useState(true),[message,setMessage]=useState(""),[orgId,setOrgId]=useState(""),[me,setMe]=useState(""),[allowed,setAllowed]=useState(false),[staff,setStaff]=useState<Staff[]>([]),[grants,setGrants]=useState<Grant[]>([]),[busy,setBusy]=useState("");
 const [query,setQuery]=useState("");
 useEffect(()=>{let live=true;(async()=>{const {data:auth}=await client.auth.getUser();if(!auth.user){window.location.replace("/auth?next=/admin-centre/data-access");return;}const access=await resolveStaffAccess(client,auth.user);if(!live)return;setMe(auth.user.id);if(access.role!=="administrator"||!access.organizationId){setLoading(false);return;}setAllowed(true);setOrgId(access.organizationId);const [people,rights]=await Promise.all([client.from("staff_directory_entries").select("user_id,display_name,role,department,job_title,email").eq("organization_id",access.organizationId).order("display_name"),client.from("staff_development_access_grants").select("id,organization_id,user_id,area,access_level,assigned_by").eq("organization_id",access.organizationId)]);if(!live)return;if(people.error||rights.error)setMessage(people.error?.message||rights.error?.message||"");setStaff((people.data||[]) as Staff[]);setGrants((rights.data||[]) as Grant[]);setLoading(false);})().catch(error=>{if(live){setMessage(error instanceof Error?error.message:"Could not load access controls.");setLoading(false);}});return()=>{live=false};},[]);
 const rights=useMemo(()=>new Map(grants.map(g=>[key(g.user_id,g.area),g.access_level as Level])),[grants]);
 const visible=useMemo(()=>staff.filter(person=>`${person.display_name} ${person.email||""} ${person.department||""} ${person.role||""}`.toLowerCase().includes(query.toLowerCase())),[staff,query]);
 async function setLevel(person:Staff,area:Area,level:Level){if(!allowed||!orgId)return;const id=key(person.user_id,area);setBusy(id);setMessage("");try{if(level==="none"){const {error}=await client.from("staff_development_access_grants").delete().eq("organization_id",orgId).eq("user_id",person.user_id).eq("area",area);if(error)throw error;setGrants(prev=>prev.filter(g=>!(g.user_id===person.user_id&&g.area===area)));}else{const value=level==="manage"&&area==="staff_progress"?"view":level;const payload={organization_id:orgId,user_id:person.user_id,area,access_level:value,assigned_by:me,updated_at:new Date().toISOString()};const {data,error}=await client.from("staff_development_access_grants").upsert(payload,{onConflict:"organization_id,user_id,area"}).select("id,organization_id,user_id,area,access_level,assigned_by").single();if(error)throw error;setGrants(prev=>[...prev.filter(g=>!(g.user_id===person.user_id&&g.area===area)),data as Grant]);}setMessage(`${person.display_name} access updated.`);}catch(error){setMessage(error instanceof Error?error.message:"Access could not be updated.");}finally{setBusy("");}}
 if(loading)return <main className="stagePage"><section className="stageCard">Loading sensitive-data access controls…</section></main>;
 if(!allowed)return <main className="stagePage"><section className="stageHero"><span className="eyebrow">SCHOOL ADMIN · DATA ACCESS</span><h1>School Administrator access required</h1><p>Only a school owner/Administrator can decide who receives access to sensitive general school information. Platform administrators do not automatically receive these permissions.</p><div className="stageHeroActions"><Link className="secondary phaseLinkButton" href="/admin-centre">Admin Centre</Link></div></section></main>;
 return <main className="stagePage">
  <section className="stageHero"><span className="eyebrow">SCHOOL ADMIN · LEAST-PRIVILEGE ACCESS</span><h1>Choose exactly who can see sensitive information.</h1><p>Ordinary leadership titles no longer automatically unlock these records. Grant access only where a staff member needs it for their role, and review the matrix regularly.</p><div className="stageHeroActions"><Link className="secondary phaseLinkButton" href="/admin-centre">← Admin Centre</Link><Link className="secondary phaseLinkButton" href="/staff-access">Staff roles</Link></div></section>
  {message&&<div className="phaseNotice">{message}</div>}
  <section className="stageCard"><span className="eyebrow">STRICTER AREAS STAY SEPARATE</span><h2>SEND/EAL and safeguarding are not controlled by this general matrix</h2><p>Those areas keep their own stricter role assignments and access checks. Giving someone Student Support or Pastoral access here does not grant SEND/EAL case access or safeguarding permissions.</p></section>
  <section className="stageCard"><div className="staffAccessHeading"><div><span className="eyebrow">SENSITIVE AREA PERMISSIONS</span><h2>Staff access matrix</h2></div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search staff…"/></div><div style={{overflowX:"auto"}}><table className="ops-table" style={{minWidth:1050,width:"100%"}}><thead><tr><th>Staff member</th>{areas.map(area=><th key={area.id}><strong>{area.label}</strong><br/><small>{area.description}</small></th>)}</tr></thead><tbody>{visible.map(person=><tr key={person.user_id}><td><strong>{person.display_name}</strong><br/><small>{person.department||person.job_title||person.role||"Staff"}{person.email?` · ${person.email}`:""}</small></td>{areas.map(area=>{const value=rights.get(key(person.user_id,area.id))||"none";const id=key(person.user_id,area.id);return <td key={area.id}><select aria-label={`${person.display_name} ${area.label}`} value={value} disabled={busy===id} onChange={e=>void setLevel(person,area.id,e.target.value as Level)}><option value="none">No access</option><option value="view">View</option><option value="manage">Manage</option></select><br/><small>{value==="manage"?area.manage:value==="view"?"Can view authorised records.":"Not authorised."}</small></td>})}</tr>)}{!visible.length&&<tr><td colSpan={areas.length+1}>No staff matched your search.</td></tr>}</tbody></table></div></section>
  <section className="stageCard"><span className="eyebrow">REVIEW ROUTINE</span><h2>Recommended checks</h2><p>Review privileged access after role changes, staff departures and at least termly. Disable leavers promptly. Keep sensitive narrative in the correct restricted area rather than copying it into general notes, notices or resources.</p></section>
 </main>;
}
