"use client";

import { useEffect, useMemo, useState } from "react";
import { microCpdUnits } from "@/lib/microCpd";
import { getSupabaseBrowserClient } from "@/lib/supabase";

type Progress={unit_id:string;reflection:string;completed_at:string};

export default function MicroCpdPage(){
  const [progress,setProgress]=useState<Record<string,Progress>>({});const [open,setOpen]=useState<string|null>(null);const [answers,setAnswers]=useState<Record<string,number>>({});const [reflections,setReflections]=useState<Record<string,string>>({});const [message,setMessage]=useState("");const [loading,setLoading]=useState(true);const [category,setCategory]=useState("All");
  useEffect(()=>{let live=true;(async()=>{const c=getSupabaseBrowserClient();const {data:auth}=await c.auth.getUser();if(!auth.user){window.location.href="/auth?next=/micro-cpd";return;}const {data,error}=await c.from("micro_cpd_progress").select("unit_id,reflection,completed_at").eq("user_id",auth.user.id);if(!live)return;if(error)setMessage(error.message);const next:Record<string,Progress>={};for(const row of data||[])next[row.unit_id]=row as Progress;setProgress(next);setReflections(Object.fromEntries(Object.values(next).map(row=>[row.unit_id,row.reflection])));setLoading(false);})();return()=>{live=false};},[]);
  const categories=useMemo(()=>["All",...new Set(microCpdUnits.map(u=>u.category))],[]);const units=category==="All"?microCpdUnits:microCpdUnits.filter(u=>u.category===category);const completed=Object.keys(progress).length;const minutes=microCpdUnits.filter(u=>progress[u.id]).reduce((sum,u)=>sum+u.minutes,0);
  async function complete(unitId:string){const unit=microCpdUnits.find(u=>u.id===unitId);if(!unit)return;if(answers[unitId]!==unit.answer){setMessage("Complete the quick check correctly before saving this micro-CPD unit.");return;}const reflection=(reflections[unitId]||"").trim();if(reflection.length<12){setMessage("Add a short commitment to practice before completing the unit.");return;}const c=getSupabaseBrowserClient();const {data:auth}=await c.auth.getUser();if(!auth.user)return;const {data,error}=await c.from("micro_cpd_progress").upsert({user_id:auth.user.id,unit_id:unitId,reflection,completed_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:"user_id,unit_id"}).select("unit_id,reflection,completed_at").single();if(error){setMessage(error.message);return;}setProgress(prev=>({...prev,[unitId]:data as Progress}));setMessage(`Saved: ${unit.title}`);}
  if(loading)return <main className="stagePage"><div className="stageCard">Loading micro-CPD…</div></main>;
  return <main className="stagePage microCpdPage"><section className="stageHero microCpdHero"><span className="eyebrow">MICRO-CPD · 5–10 MINUTES</span><h1>One useful idea. One quick practice. One action to try.</h1><p>Use these when a full course is too much for the time available. Each unit is deliberately narrow and ends with a practical commitment rather than a long assessment.</p></section>{message&&<div className="phaseNotice">{message}</div>}
    <section className="stageStatGrid"><div className="stageStat"><strong>{completed}</strong><span>micro-units completed</span></div><div className="stageStat"><strong>{minutes}</strong><span>minutes completed</span></div><div className="stageStat"><strong>{microCpdUnits.length-completed}</strong><span>units available</span></div><div className="stageStat"><strong>{categories.length-1}</strong><span>development themes</span></div></section>
    <section className="stageCard microFilter"><div><span className="eyebrow">FILTER</span><h2>Choose a development theme</h2></div><select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select></section>
    <section className="microGrid">{units.map(unit=>{const done=Boolean(progress[unit.id]);const answer=answers[unit.id];const answered=answer!==undefined;return <article className={`stageCard microCard ${done?"done":""}`} key={unit.id}><header><div><span className="microMinutes">{unit.minutes} min</span><span className="microCategory">{unit.category}</span></div>{done&&<b>✓ completed</b>}</header><h2>{unit.title}</h2><p>{unit.idea}</p><button className="secondary" onClick={()=>setOpen(open===unit.id?null:unit.id)}>{open===unit.id?"Close unit":done?"Review unit":"Start micro-CPD"}</button>{open===unit.id&&<div className="microBody"><div className="microFlow">{unit.visual.map((step,i)=><div key={step.heading}><span>{i+1}</span><strong>{step.heading}</strong><p>{step.text}</p></div>)}</div><section className="microPractice"><span className="eyebrow">TRY IT</span><p>{unit.tryIt}</p></section><section className="microCheck"><span className="eyebrow">QUICK CHECK</span><strong>{unit.question}</strong><div>{unit.options.map((option,i)=><label className={answered&&i===unit.answer?"correct":answered&&i===answer?"wrong":""} key={option}><input type="radio" name={`answer-${unit.id}`} checked={answer===i} onChange={()=>setAnswers(prev=>({...prev,[unit.id]:i}))}/><span>{option}</span></label>)}</div>{answered&&<p className={answer===unit.answer?"checkFeedback good":"checkFeedback"}>{answer===unit.answer?unit.feedback:"Not quite. Re-read the idea and try the check again."}</p>}</section><section className="microCommit"><span className="eyebrow">COMMIT TO PRACTICE</span><label>{unit.commitPrompt}<textarea rows={3} value={reflections[unit.id]||""} onChange={e=>setReflections(prev=>({...prev,[unit.id]:e.target.value}))} placeholder="Write one specific action you will try…"/></label><button className="primary" onClick={()=>complete(unit.id)}>{done?"Update reflection":"Complete micro-CPD"}</button>{done&&<small>Last saved {new Date(progress[unit.id].completed_at).toLocaleDateString("en-GB")}</small>}</section></div>}</article>})}</section>
    <section className="stageCard microBoundary"><strong>Micro-CPD is a prompt for practice, not proof of impact.</strong><p>Completion records that you engaged with the unit. Use an action plan, coaching cycle, portfolio evidence or later reflection if you want to evaluate whether the change improved practice.</p><div className="stageHeroActions"><a className="secondary phaseLinkButton" href="/actions">Action plans</a><a className="secondary phaseLinkButton" href="/portfolio">Portfolio</a></div></section>
  </main>;
}
