"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { getSupabaseBrowserClient } from "@/lib/supabase";

type Doc = { id:string; organization_id:string; created_by:string; title:string; category:string; source_type:"text"|"file"; source_name:string|null; storage_path:string|null; content:string; summary:string; tags:string[]; status:string; updated_at:string };
type Profile = { id:string; full_name:string; role:string; organisation_id:string|null };
type Citation = { index:number; id:string; title:string };

const categories=["Policy","Safeguarding","SEND","Behaviour","Teaching & Learning","Staff Handbook","Curriculum","Operations","Wellbeing","Other"];

async function authHeaders(extra:Record<string,string>={}){
  const client=getSupabaseBrowserClient();
  const {data}=await client.auth.getSession();
  const token=data.session?.access_token;
  if(!token)throw new Error("Your session has expired. Sign in again.");
  return {...extra,Authorization:`Bearer ${token}`};
}

export default function KnowledgeBasePage(){
  const [profile,setProfile]=useState<Profile|null>(null); const [orgId,setOrgId]=useState(""); const [docs,setDocs]=useState<Doc[]>([]); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
  const [question,setQuestion]=useState(""); const [answer,setAnswer]=useState(""); const [citations,setCitations]=useState<Citation[]>([]); const [mode,setMode]=useState("");
  const leader=useMemo(()=>Boolean(profile&&["Admin","CPD Lead","Department Lead"].includes(profile.role)),[profile]);

  useEffect(()=>{const client=getSupabaseBrowserClient();let active=true;(async()=>{const {data:auth}=await client.auth.getUser();if(!auth.user){window.location.href="/auth?next=/knowledge-base";return;}const {data:p}=await client.from("staff_profiles").select("id,full_name,role,organisation_id").eq("id",auth.user.id).maybeSingle();let oid=String(p?.organisation_id||"");if(!oid){const {data:m}=await client.from("school_organization_members").select("organization_id").eq("user_id",auth.user.id).limit(1).maybeSingle();oid=String(m?.organization_id||"");}if(!active)return;setProfile((p||{id:auth.user.id,full_name:"Staff member",role:"Staff",organisation_id:oid||null}) as Profile);setOrgId(oid);if(oid){const {data,error}=await client.from("school_knowledge_documents").select("id,organization_id,created_by,title,category,source_type,source_name,storage_path,content,summary,tags,status,updated_at").eq("organization_id",oid).eq("status","active").order("updated_at",{ascending:false});if(error)setMessage(error.message);setDocs((data||[]) as Doc[]);}setLoading(false);})();return()=>{active=false};},[]);

  async function addText(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!profile||!orgId)return;const form=new FormData(e.currentTarget);const title=String(form.get("title")||"").trim();const content=String(form.get("content")||"").trim();if(title.length<3||content.length<30){setMessage("Add a clear title and at least a short section of useful text.");return;}setBusy(true);const client=getSupabaseBrowserClient();const {data,error}=await client.from("school_knowledge_documents").insert({organization_id:orgId,created_by:profile.id,title,category:String(form.get("category")||"General"),source_type:"text",content,summary:String(form.get("summary")||"").trim()||content.slice(0,350),tags:String(form.get("tags")||"").split(",").map(x=>x.trim()).filter(Boolean).slice(0,8)}).select("id,organization_id,created_by,title,category,source_type,source_name,storage_path,content,summary,tags,status,updated_at").single();setBusy(false);if(error||!data){setMessage(error?.message||"Could not save the knowledge source.");return;}setDocs(prev=>[data as Doc,...prev]);e.currentTarget.reset();setMessage("Knowledge source added.");}

  async function uploadFile(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!profile||!orgId)return;const form=new FormData(e.currentTarget);const file=form.get("file");if(!(file instanceof File)||!file.size){setMessage("Choose a PDF, DOCX, TXT or Markdown file.");return;}setBusy(true);try{const extraction=new FormData();extraction.append("file",file);const headers=await authHeaders();const response=await fetch("/api/knowledge-base/extract",{method:"POST",headers,body:extraction});if(response.status===401){window.location.href="/auth?next=/knowledge-base";return;}const extracted=await response.json().catch(()=>({error:"The document could not be read."}));if(!response.ok){setMessage(String(extracted.error||"The document could not be read."));return;}const client=getSupabaseBrowserClient();const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"-");const path=`${orgId}/${crypto.randomUUID()}/${safe}`;const upload=await client.storage.from("school-knowledge").upload(path,file,{upsert:false,contentType:file.type});if(upload.error){setMessage(upload.error.message);return;}const {data,error}=await client.from("school_knowledge_documents").insert({organization_id:orgId,created_by:profile.id,title:String(form.get("title")||"").trim()||file.name.replace(/\.[^.]+$/,""),category:String(form.get("category")||"General"),source_type:"file",source_name:file.name,storage_path:path,content:String(extracted.content||""),summary:String(extracted.summary||""),tags:Array.isArray(extracted.tags)?extracted.tags:[]}).select("id,organization_id,created_by,title,category,source_type,source_name,storage_path,content,summary,tags,status,updated_at").single();if(error||!data){setMessage(error?.message||"The file uploaded but its knowledge record could not be saved.");return;}setDocs(prev=>[data as Doc,...prev]);e.currentTarget.reset();setMessage("Document uploaded, extracted and added to the school knowledge base.");}catch(error){setMessage(error instanceof Error?error.message:"The document could not be read.");}finally{setBusy(false);}}

  async function ask(e:FormEvent<HTMLFormElement>){e.preventDefault();const q=question.trim();if(q.length<3)return;setBusy(true);setAnswer("");setCitations([]);try{const client=getSupabaseBrowserClient();const {data,error}=await client.rpc("search_school_knowledge",{p_query:q,p_limit:6});if(error){setMessage(error.message);return;}const sources=(data||[]) as Array<{id:string;title:string;category:string;summary:string;content:string}>;const headers=await authHeaders({"Content-Type":"application/json"});const response=await fetch("/api/knowledge-base/ask",{method:"POST",headers,body:JSON.stringify({question:q,sources})});if(response.status===401){window.location.href="/auth?next=/knowledge-base";return;}const result=await response.json().catch(()=>({text:"Unable to answer right now.",citations:[]}));setAnswer(String(result.text||"Unable to answer right now."));setCitations(Array.isArray(result.citations)?result.citations:[]);setMode(String(result.mode||""));}catch(error){setMessage(error instanceof Error?error.message:"Unable to answer right now.");}finally{setBusy(false);}}

  async function openSource(doc:Doc){if(!doc.storage_path)return;const client=getSupabaseBrowserClient();const {data,error}=await client.storage.from("school-knowledge").createSignedUrl(doc.storage_path,300);if(error||!data?.signedUrl){setMessage(error?.message||"Could not open the source file.");return;}window.open(data.signedUrl,"_blank","noopener,noreferrer");}
  async function archive(doc:Doc){const client=getSupabaseBrowserClient();const {error}=await client.from("school_knowledge_documents").update({status:"archived",updated_at:new Date().toISOString()}).eq("id",doc.id);if(error){setMessage(error.message);return;}setDocs(prev=>prev.filter(item=>item.id!==doc.id));setMessage("Source archived.");}

  if(loading)return <main className="stagePage"><div className="stageCard">Loading school knowledge…</div></main>;
  if(!orgId)return <main className="stagePage"><section className="stageCard"><h1>Join or create a school first</h1><p>The knowledge base is separated by school organisation so documents are never shared across schools.</p></section></main>;
  return <main className="stagePage aiPlatformPage">
    <section className="stageHero aiKnowledgeHero"><span className="eyebrow">SCHOOL KNOWLEDGE + GEMINI</span><h1>Ask your school documents, not the open internet.</h1><p>Policies, handbooks and guidance stay inside your school workspace. Gemini answers from the relevant sources and cites them by number instead of inventing school procedures.</p><div className="stageHeroActions"><a className="primary phaseLinkButton" href="/ai-course-builder">Build CPD from these sources</a><a className="secondary phaseLinkButton" href="/dashboard">Staff dashboard</a></div></section>
    {message&&<div className="phaseNotice">{message}</div>}
    <section className="stageGrid"><article className="stageCard stageSpan8"><span className="eyebrow">ASK THE SCHOOL</span><h2>School knowledge assistant</h2><form className="knowledgeAsk" onSubmit={ask}><textarea value={question} onChange={e=>setQuestion(e.target.value)} rows={3} placeholder="e.g. What does our behaviour policy say staff should do after repeated low-level disruption?"/><button className="primary" disabled={busy||question.trim().length<3}>{busy?"Searching…":"Ask Gemini"}</button></form>{answer&&<div className="knowledgeAnswer"><div className="phaseActions"><span className="stageBadge">{mode==="gemini"?"Gemini + school sources":"Source mode"}</span></div><p>{answer}</p>{citations.length>0&&<div className="knowledgeCitations">{citations.map(c=><span key={c.id}>[{c.index}] {c.title}</span>)}</div>}</div>}</article><aside className="stageCard stageSpan4"><span className="eyebrow">KNOWLEDGE COVERAGE</span><h2>{docs.length} active sources</h2><p>{new Set(docs.map(d=>d.category)).size} categories represented.</p><div className="knowledgeTags">{[...new Set(docs.flatMap(d=>d.tags||[]))].slice(0,12).map(tag=><span key={tag}>{tag}</span>)}</div><p className="muted">For safeguarding or safety questions, the current approved policy and designated lead remain authoritative.</p></aside></section>

    {leader&&<section className="stageGrid"><details className="stageCard stageSpan6"><summary><strong>Add pasted knowledge</strong></summary><form className="stageForm" onSubmit={addText}><label>Title<input name="title" required/></label><label>Category<select name="category">{categories.map(x=><option key={x}>{x}</option>)}</select></label><label className="full">Optional summary<textarea name="summary" rows={2}/></label><label className="full">Document text<textarea name="content" rows={10} required placeholder="Paste the approved policy/guidance text here…"/></label><label className="full">Tags<input name="tags" placeholder="behaviour, sanctions, classroom"/></label><button className="primary" disabled={busy}>Add to knowledge base</button></form></details><details className="stageCard stageSpan6"><summary><strong>Upload a document</strong></summary><form className="stageForm" onSubmit={uploadFile}><label>Optional display title<input name="title"/></label><label>Category<select name="category">{categories.map(x=><option key={x}>{x}</option>)}</select></label><label className="full">PDF, DOCX, TXT or Markdown<input name="file" type="file" accept=".pdf,.docx,.txt,.md,application/pdf,text/plain,text/markdown,application/vnd.openxmlformats-officedocument.wordprocessingml.document" required/></label><p className="muted">Gemini extracts documents up to 3 MB. The original file is stored privately in your school knowledge bucket.</p><button className="primary" disabled={busy}>{busy?"Processing…":"Upload and extract"}</button></form></details></section>}

    <section className="stageCard"><span className="eyebrow">SOURCES</span><h2>School knowledge library</h2><div className="knowledgeLibrary">{docs.map(doc=><article className="knowledgeDoc" key={doc.id}><div><span className="stageBadge">{doc.category}</span><h3>{doc.title}</h3><p>{doc.summary||doc.content.slice(0,220)}</p><div className="knowledgeTags">{(doc.tags||[]).map(tag=><span key={tag}>{tag}</span>)}</div><small>{doc.source_name||"Pasted text"} · updated {new Date(doc.updated_at).toLocaleDateString("en-GB")}</small></div><div className="phaseActions">{doc.storage_path&&<button className="secondary" onClick={()=>openSource(doc)}>Open source</button>}{leader&&<button className="secondary" onClick={()=>archive(doc)}>Archive</button>}</div></article>)}{!docs.length&&<div className="emptyCompact">No school knowledge has been added yet.</div>}</div></section>
  </main>;
}
