"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { courses } from "@/lib/catalogue";
import { suggestForImprovementPriority } from "@/lib/developmentIntelligence";
import { pathways } from "@/lib/pathways";
import { getSupabaseBrowserClient } from "@/lib/supabase";

type Profile={id:string;role:string;organisation_id:string|null;site_id:string|null};
type Priority={id:string;title:string;description:string;scope:string;department:string|null;active:boolean};
type Programme={id:string;priority_id:string;title:string;audience:string;course_ids:string[];pathway_ids:string[];facilitator_minutes:number;review_days:number[];success_measure:string;active:boolean;created_at:string};

export default function ImprovementProgrammesPage(){
  const [profile,setProfile]=useState<Profile|null>(null);const [priorities,setPriorities]=useState<Priority[]>([]);const [programmes,setProgrammes]=useState<Programme[]>([]);const [selectedPriority,setSelectedPriority]=useState("");const [message,setMessage]=useState("");const [loading,setLoading]=useState(true);
  const courseMap=useMemo(()=>new Map(courses.map(c=>[c.id,c])),[]);const priorityMap=useMemo(()=>new Map(priorities.map(p=>[p.id,p])),[priorities]);
  useEffect(()=>{const supabase=getSupabaseBrowserClient();(async()=>{const {data:auth}=await supabase.auth.getUser();if(!auth.user){window.location.href="/auth?next=/improvement/programmes";return;}const {data:p,error:pe}=await supabase.from("staff_profiles").select("id,role,organisation_id,site_id").eq("id",auth.user.id).single();if(pe||!p){setMessage(pe?.message||"Unable to load profile.");setLoading(false);return;}const me=p as Profile;setProfile(me);const [pr,pg]=await Promise.all([supabase.from("improvement_priorities").select("id,title,description,scope,department,active").eq("active",true).order("title"),supabase.from("improvement_cpd_programmes").select("id,priority_id,title,audience,course_ids,pathway_ids,facilitator_minutes,review_days,success_measure,active,created_at").order("created_at",{ascending:false})]);if(pr.error)setMessage(pr.error.message);if(pg.error)setMessage(pg.error.message);setPriorities((pr.data||[]) as Priority[]);setProgrammes((pg.data||[]) as Programme[]);setSelectedPriority((pr.data?.[0] as Priority|undefined)?.id||"");setLoading(false);})();},[]);
  const canManage=Boolean(profile&&["CPD Lead","Admin"].includes(profile.role));const selected=priorityMap.get(selectedPriority);const suggestions=selected?suggestForImprovementPriority(selected.title,selected.description):[];
  async function createProgramme(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!profile?.organisation_id||!selected)return;const formEl=e.currentTarget;const form=new FormData(formEl);const selectedCourses=suggestions.filter(s=>form.get(`course-${s.course.id}`)==="on").map(s=>s.course.id);const selectedPathways=pathways.filter(p=>form.get(`pathway-${p.id}`)==="on").map(p=>p.id);const payload={organisation_id:profile.organisation_id,site_id:profile.site_id,priority_id:selected.id,title:String(form.get("title")||`${selected.title} CPD programme`),audience:String(form.get("audience")||"All staff"),course_ids:selectedCourses.length?selectedCourses:suggestions.slice(0,3).map(s=>s.course.id),pathway_ids:selectedPathways,facilitator_minutes:Number(form.get("facilitator_minutes")||60),review_days:[7,30,90],success_measure:String(form.get("success_measure")||""),created_by:profile.id,active:true};const supabase=getSupabaseBrowserClient();const {data,error}=await supabase.from("improvement_cpd_programmes").insert(payload).select("id,priority_id,title,audience,course_ids,pathway_ids,facilitator_minutes,review_days,success_measure,active,created_at").single();if(error){setMessage(error.message);return;}setProgrammes(prev=>[data as Programme,...prev]);setMessage("CPD programme created and linked to the improvement priority.");formEl.reset();}
  if(loading)return <main className="stagePage"><div className="stageCard">Loading improvement programmes…</div></main>;
  return <main className="stagePage"><section className="stageHero"><span className="eyebrow">SCHOOL IMPROVEMENT → CPD</span><h1>Turn a priority into a complete professional-development programme.</h1><p>Select a school priority and the platform suggests relevant courses, facilitator delivery, pathways and the 7/30/90-day follow-through cycle. Leaders choose the final programme rather than accepting an automatic recommendation blindly.</p><div className="stageHeroActions"><a className="secondary phaseLinkButton" href="/improvement">Improvement priorities</a><a className="secondary phaseLinkButton" href="/facilitator">Facilitator packs</a><a className="secondary phaseLinkButton" href="/impact">Impact hub</a></div></section>{message&&<div className="phaseNotice">{message}</div>}
    {canManage&&<section className="stageGrid"><div className="stageCard stageSpan4"><span className="eyebrow">1 · PRIORITY</span><h2>Select the focus</h2><label>Active improvement priority<select value={selectedPriority} onChange={e=>setSelectedPriority(e.target.value)}>{priorities.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label>{selected&&<p>{selected.description||"No description supplied."}</p>}</div><div className="stageCard stageSpan8"><span className="eyebrow">2 · BUILD PROGRAMME</span><h2>Suggested CPD sequence</h2><form className="stageForm" onSubmit={createProgramme}><div className="featureProgrammeCourses">{suggestions.map(s=><label key={s.course.id}><input type="checkbox" name={`course-${s.course.id}`} defaultChecked={s.score>0}/><div><strong>{s.course.title}</strong><span>{s.reason}</span><small>{s.course.duration} min · {s.course.category}</small></div></label>)}</div><div className="stageFormGrid"><label>Programme title<input name="title" defaultValue={selected?`${selected.title} CPD programme`:""}/></label><label>Audience<input name="audience" defaultValue={selected?.scope==="department"?(selected.department||"Department staff"):"All staff"}/></label><label>Live delivery route<select name="facilitator_minutes"><option value="15">15 minutes</option><option value="30">30 minutes</option><option value="60">60 minutes</option><option value="90">90 minutes</option></select></label><label className="full">Success measure<textarea required name="success_measure" rows={3} placeholder="What observable evidence would show that this priority is improving?"/></label><fieldset className="full featurePathwayChecks"><legend>Optional pathway links</legend>{pathways.slice(0,8).map(p=><label className="inlineCheck" key={p.id}><input type="checkbox" name={`pathway-${p.id}`}/>{p.title}</label>)}</fieldset></div><button className="primary">Create priority-linked CPD programme</button></form></div></section>}
    {!canManage&&<div className="phaseNotice">CPD Leads and Admins can create programmes. Staff can see the active programmes available to their organisation.</div>}
    <section className="stageCard"><span className="eyebrow">ACTIVE PROGRAMMES</span><h2>Improvement-linked professional development</h2><div className="stageList">{programmes.map(p=><div className="stageRow" key={p.id}><div className="stageRowMain"><strong>{p.title}</strong><span>{priorityMap.get(p.priority_id)?.title||"School priority"} · {p.audience} · {p.facilitator_minutes} min live route</span><small>{p.course_ids.map(id=>courseMap.get(id)?.title).filter(Boolean).join(" · ")}</small><small>Impact reviews: {(p.review_days||[7,30,90]).join(" / ")} days · {p.success_measure}</small></div><div className="featureProgrammeActions"><a className="smallButton" href={`/facilitator?course=${encodeURIComponent(p.course_ids[0]||"")}&route=${p.facilitator_minutes}`}>Facilitate</a><a className="smallButton" href="/impact">Review impact</a></div></div>)}{!programmes.length&&<div className="emptyCompact">No improvement-linked CPD programmes yet.</div>}</div></section>
  </main>;
}
